const id = "ಅಂತಕನ-ದೂತರಿಗೆ-ಕಿಂಚಿತ್ತು";
const collection = "bhajan";
const data = {kannada_title:"ಅಂತಕನ ದೂತರಿಗೆ ಕಿಂಚಿತ್ತು",english_title:"Antakana dutarige",kannada:"ಅಂತಕನ ದೂತರಿಗೆ ಕಿಂಚಿತ್ತು ದಯವಿಲ್ಲ\nಚಿಂತೆಯನು ಬಿಟ್ಟು ಶ್ರೀ ಹರಿಯ ನೆನೆ ಮನವೆ ||ಪ||\n\nದಿವ ರಾತ್ರಿಯೆನ್ನದೆ ವಿಷಯಲಂಪಟನಾಗಿ\nಸವಿಯೂಟಗಳನುಂಡು ಭ್ರಮಿಸ ಬೇಡ\nಅವನ ಕೊಂದಿವನ ಕೊಂದರ್ಥವನು ಗಳಿಸುವರೆ\nಜವನ ದೂತರು ಬರುವ ಹೊತ್ತ ನೀನರಿಯೆ ||\n\nಮೊನ್ನೆ ಮದುವೆಯಾದೆನೈ ಕರೆವುದೊಂದೆರಡೆಮ್ಮೆ\nನಿನ್ನೆ ಕೊಂಡೆನು ಕ್ಷೇತ್ರ ಫಲವು ಬಹುದು\nಹೊನ್ನು ಹಣವುಂಟೆನಗೆ ಸಾಯಲಾರೆನು ಎನಲು\nಬೆನ್ನ ಬಿಡುವಳೆ ಮೃತ್ಯು ವ್ಯರ್ಥ ಜೀವಾತ್ಮ ||\n\nಹೊಸ ಮನೆಯ ಕಟ್ಟಿದೆನು ಗೃಹ ಶಾಂತಿ ಮನೆಯೊಳಗೆ\nಬಸಿರಿ ಹೆಂಡತಿ ಮಗನ ಮದುವೆ ನಾಳೆ\nಹಸನಾಗಿ ಇದೆ ಬದುಕು ಸಾಯಲಾರೆನು ಎನಲು\nಕುಸುರಿದರಿಯದೆ ಬಿಡರು ಯಮನವರು ಆಗ ||\n\nಪುತ್ರ ಹುಟ್ಟಿದ ದಿವಸ ಹಾಲು ಊಟದ ಹಬ್ಬ\nಮತ್ತೊಬ್ಬ ಮಗನ ಉಪನಯನ ನಾಳೆ\nಅರ್ತಿಯಾಗಿದೆ ಬದುಕು ಸಾಯಲಾರೆನು ಎನಲು\nಮೃತ್ಯು ಹೆಡತಲೆಯಲ್ಲಿ ನಗುತಿರ್ಪುದರಿಯೆ ||\n\nಅಟ್ಟಡಿಗೆಯುಣಲಿಲ್ಲ ಇಷ್ಟ ದರುಶನವಿಲ್ಲ\nಕೊಟ್ಟ ಸಾಲವ ಕೇಳ್ವ ಹೊತ್ತನರಿಯೆ\nಕಟ್ಲೆ ತುಂಬಿದ ಮೇಲೆ ಕ್ಷಣಮಾತ್ರ ಇರಲಿಲ್ಲ\nಅಷ್ಟರೊಳು\nಪುರಂದರ ವಿಠಲ\nನೆನು ಮನವೆ ||\n\n",english:"Antakana dutarige kinchittu dayavilla\nchinteyanu bittu shri hariya nene manav\ne ||\nantakana||\n\nDiva ratri yennade vishaya lampatanagi\nsavi yutagala nundu bhramisa beda\nantakanaavana kondivana kondarttavanu galisuvare\njavana dutaru baruva hotta ninariye\n||\nantakana||\n\nM\nonne maduvyadenai karevudondherademme\nninna kondenu kshetra phalavu bahud\nu\nhonnu hanavuntenage sayalarenu enalu\nbenna biduvale mrityu vyartta jivatma\n||\nantakana||\n\nHosa maneya kattidenu gruha shantimaneyolge\nbasiri hendati magana maduve nale\nhasanagi ide baduku sayalarenu enalu\nkusuridariyade bidaru yamanavaru aga\n||\nantakana||\n\nPutra huttida divasa halinutada habba\nmattobba magana upanayana nale\nartiyagide baduku sayalarenu enalu\nmrityu hedataleyalli nagudirpalayya\n||\nantakana||\n\nAtta dugeyu nalilla ishta darushanavilla\nkotta sAlava kelva hotta nariy\ne\nkatle tumbida mele kshana matra  iralilla\nashtarolu\npurandara vittala\nnenu mana\nve||\nantakana||\n\nYou can listen to the song here\n:\nhttps://youtu.be/Zs-TmN4aJ2Q\nby  Bellur sisters\n\n",meta:"",tags:["narayana","dasara padagalu","kannada devotional song","narayana","purandara dasarau"],media:"https://www.youtube.com/watch?v=Zs-TmN4aJ2Q"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಅಂತಕನ-ದೂತರಿಗೆ-ಕಿಂಚಿತ್ತು.json",
	rawData: "",
};

export { _internal, collection, data, id };
