const id = "ಅಮ್ಮ-ನಿಮ್ಮ-ಮನೆಗಳಲ್ಲಿ";
const collection = "bhajan";
const data = {kannada_title:"ಅಮ್ಮ ನಿಮ್ಮ ಮನೆಗಳಲ್ಲಿ",english_title:"Amma nimma manegalalli",kannada:"ಅಮ್ಮ ನಿಮ್ಮ ಮನೆಗಳಲ್ಲಿ\nನಮ್ಮ ರಂಗನ ಕಂಡಿರೇನೆನಮ್ಮ |\nಬ್ರಹ್ಮ ಮೂರುತಿ ನಮ್ಮ ಕೃಷ್ಣನು\nನಿಮ್ಮ ಕೇರಿಯೋಳಿಲ್ಲವೇನಮ್ಮ||\n\nಕಾಶಿ ಪೀತಾಂಬರ ಕೈಯಲ್ಲಿ ಕೊಳಲು\nಪೂಸಿದ ಶ್ರೀಗಂಧ ಮೈಯೊಳಗಮ್ಮ\nಲೇಸಾಗಿ ತುಲಸಿಯ ಮಾಲೆಯ ಹಾಕಿದ\nವಾಸುದೇವನು ಬಂದ ಕಂಡಿರೇನೆ\n\nಕರದಲ್ಲಿ ಕಂಕಣ ಬೆರಳಲ್ಲಿ ಉಂಗುರ\nಕೊರಳಲ್ಲಿ ಹಾಕಿದ ಹುಲಿಯುಗುರಮ್ಮ\nಅರಳೆಲೆ ಕನಕದ ಕುಂಡಲ ಕಾಲಂದಿಗೆ\nಉರಗಶಯನ ಬಂದ ಕಂಡಿರೇನೆ\n\nಕಾಲಲಿ ಕಿರುಗೆಜ್ಜೆ ನೀಲದ ಬಾವುಲಿ\nನೀಲವರ್ಣನು ನಾಟ್ಯವಾಡುತಲಿ\nಮೇಲಾಗಿ ಬಾಯಲ್ಲಿ ಜಗವನು ತೋರಿದ\nಮೂರ್ಲೋಕದೊಡೆಯನ ಕಂಡಿರೇನೆ\n\nಕುಂಕುಮ ಕಸ್ತೂರಿ ಕುಡಿಕುಡಿ ನಾಮವು\nಶಂಕಚಕ್ರಂಗಳ ಧರಿಸಿಹನಮ್ಮ\nಬಿಂಕದಿಂದಲಿ ಕೊಳಲೂದುತ ಪಾಡುತ\nಪಂಕಜಾಕ್ಷನು ಬಂದ ಕಂಡಿರೇನೆ\n\nಹದಿನಾರು ಸಾವಿರ ಗೋಪಿಯರೊಡಗೂಡಿ\nಚದುರಂಗ ಪಗಡೆಯನಾಡುವನಮ್ಮ\nಮದನ ಮೋಹನರೂಪ ಎದೆಯಲಿ\nಪದುಮನಾಭಾನು  ಬಂದ ಕಂಡಿರೇನೆ\n\nನೊಸಲ ಸುತ್ತಿದ ಪಟ್ಟಿ ನಡುವಿನ ವಡ್ಯಾಣ\nಎಸೆವ ಕಸ್ತೂರಿ ಬಟ್ಟು ಮೈಯವನಮ್ಮ\nಪಸರಿಸಿ ಪಟ್ಟಿಯ ಹಾವಿಗೆ ಮೆಟ್ಟಿದ\nಅಸುರಾಂತಕ ಬಂದ ಕಂಡಿರೇನೆ\n\nತೆತ್ತೀಸಕೋಟಿ ದೇವರ್ಕಳ ಒಡಗೂಡಿ\nಹತ್ತವತಾರವನೆತ್ತಿದನೆ\nಭಕ್ತವತ್ಸಲ ನಮ್ಮ\nಪುರಂದರವಿಠಲ\nನಿತ್ಯೋತ್ಸವ ಬಂದ ಕಂಡಿರೇನೆ\n\n",english:"Amma nimma manegalalli\nnamma rangana kandirenamma ||\nBrahma muruti namma krishnanu\nnimma keryolillavenamma ||\n\nKashi pitambara kaiyalli kolalu\npusida shrigandha maiyolagamma|\nlesagi tulasiya maleya dharisida\nvasudevanu banda kanirene ||\n\nKaradalli kankana beralalli ungura\nkoralalli hakida huliyuguramma|\naralele kanaka kundala kalalanuge\nuraga shayana banda kandirrne ||\n\nKumkuma kasturi kari nama tiddi\nshankhachakragala dharisihanamma|\nbinkadindali kolaludutta padutta\npankajakaanu banda kanirene  ||\n\nMavana maduhida shakatana kedahida\ngovardhana giri ettidanamma|\nAva tayige irelu jaga torida\nkavanayya banda kanirene ||\n\nKalali kiru gejje nilada bavuli\nnila varnanu natyavadutali |\nmelagi bayalli jagavannu torida\nmukokadodeyana kandirene||\n\nHadinaru savira gopiyara kudi\nchaturanga pagadeyanaduvanamma|\nmadana mohana rupa edeyalli kaustubha\nmadhusudana banda kanirene ||\n\nTettesa koti devargala oda gudi\nhattavataravanettittadamma|\nsatyabhama priya\npurandara vittala\nnityotsava banda kanirene||\n\nBy Dr.M Balamurali Krishna\nhttps://youtu.be/veTbp7B_Jo0\n\n",meta:"",tags:["krishna","dasara padagalu","kannada devotional song","kannada lyrics","krishna song"],media:"https://www.youtube.com/watch?v=WbfPjs2EShw"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಅಮ್ಮ-ನಿಮ್ಮ-ಮನೆಗಳಲ್ಲಿ.json",
	rawData: "",
};

export { _internal, collection, data, id };
