const id = "ಅಂತರಂಗದಲಿ-ಹರಿಯ-ಕಾಣದವ";
const collection = "bhajan";
const data = {kannada_title:"ಅಂತರಂಗದಲಿ ಹರಿಯ ಕಾಣದವ",english_title:"Antarangadali hariya kaanadava",kannada:"ರಚನೆ : ವ್ಯಾಸರಾಯರು\n\nಅಂತರಂಗದಲ್ಲಿ ಹರಿಯ ಕಾಣದವ ಹುಟ್ಟು ಕುರುಡನೋ                               ||ಪ||\n\nಸಂತತ ಶ್ರೀ ಕೃಷ್ಣ ಚರಿತೆ ಕೇಳದವ ಜಡಮತಿ ಕಿವುಡನೋ ಎಂದೆಂದಿಗೂ         ||ಅ.ಪ||\n\nಹರುಷದಿಂದಲಿ ನರಹರಿಯ ಪೂಜೆ ಮಾಡದವನೆ ಕೈ ಮುರಿದವನೊ\nಕುರುವರಸೂತನ ಮುಂದೆ ಕೃಷ್ಣಾಯೆಂದು ಕುಣಿಯದವನೆ ಕುಂಟನೊ ||\n\nನರಹರಿ ಚರಣೋದಕವ ಧರಿಸದ ಶಿರ ನಾಯುಂಡ ಹೆಂಚು ಕಾಣೊ\nಸುರವರ ಕೃಷ್ಣ ಪ್ರಸಾದವಿಲ್ಲದ ಊಟ ಸೂಕರ ಭೋಜನವೊ ಎಂದೆಂದಿಗೂ       ||\n\nಅಮರೇಶ ಕೃಷ್ಣಗರ್ಪಿತವಲ್ಲದ ಕರ್ಮ ಆಸತಿಯ ವ್ರತನೇಮವೊ\nರಮಯರಸಗೆ ಪ್ರೀತಿಯಿಲ್ಲದ ವಿತರಣೆ ರಂಡೆಕೊರಳ ಸೂತ್ರವೊ ||\n\nಕಮಲನಾಭನ ಪಾಡಿ ಪೊಗಳದ ಸಂಗೀತ ಗಾರ್ಧಭರೋಧನವೋ\nಮಮತೆ ಇಂದಲಿ ಕೇಶವಗೆ ನಮಸ್ಕಾರ ಮಾಡದವನೆ ಮೃಗವೊ ಎಂದೆಂದಿಗೂ ||\n\nಜರೆ ಪುಟ್ಟು ಮರಣವ ತೊಡೆವ ಸುಧೆಯ ಬಿಟ್ಟು ಸುರೆಯ ಸೇವಿಸಬೇಡವೊ\nಸುರಧೇನುವಿರಲಾಗಿ ಸೂಕರ ಮೊಲೆಹಾಲು ಕರೆದು ಕುಡಿಯಬೇಡವೊ||\n\nಕರಿ ರಥ ತುರಗವಿರಲು ಬಿಟ್ಟು ಕೆಡಹುವ ಕತ್ತೆಯೇರಲು ಬೇಡವೊ\nಪರಮಪದವನೀವ ಸಿರಿಕೃಷ್ಣನಿರಲಾಗಿ ನರರ ಸೇವಿಸಬೇಡವೊ ಎಂದೆಂದಿಗೂ   ||\n\n",english:"Antarangadali hariya kanadava\nhuttu kurudano||pa||\n\nSantata shri krishna charita keledava\njadamati kirudano endendigu||a.pa|\n\nHarushadindali narahariya pujeya\nmadadava kai muridavano\nkuruvara sutana munde krishna\nendu kuniyadava kuntano endendigu ||\n\nNarahari charanodhakava dharisada\nshura naayunda henchu kaano |\nsuravara krishna prasadavillada\nota sookara bhojanavo endendigu ||\n\nAmaresha krishnagarpitavallada\nkarma asatiya vrata nemavo |\nramayarasage preetiyillada\nvitarane randekorala sootravo ||\n\nKamalanabhana padi pogalada\nsangita gardhabha rodhanavo|\nmamate indali keshavage namaskara\nmadadava mragava, endendigu||\n\nJare puttu maranava todeva sudheya\nbittu sureya sevisabedavo |\nsuradhenuviralaagi sookara\nmolehaalu karedu kudiyabedavo ||\n\nKari ratha turagaviralu bittu\nkedahuva katte erali bedavo\nparama padava niva siri\nkrishaniralagi sevisa bedavo endendigu ||\n\nYoutube link:\n\n",meta:"",tags:["narayana","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=8lT8zkgd280"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಅಂತರಂಗದಲಿ-ಹರಿಯ-ಕಾಣದವ.json",
	rawData: "",
};

export { _internal, collection, data, id };
