const id = "ಅಪಮೃತ್ಯು-ಪರಿಹರಿಸೊ";
const collection = "bhajan";
const data = {kannada_title:"ಅಪಮೃತ್ಯು ಪರಿಹರಿಸೊ",english_title:"Apamrutyu parihariso",kannada:"ಅಪಮೃತ್ಯು ಪರಿಹರಿಸೊ ಅನಿಲದೇವ\nಕೃಪಣ ವತ್ಸಲನೆ ಕಾವರ ಕಾಣೆ ಜಗದೊಳಗೆ ||ಪ||\n\nನಿನಗಿನ್ನು ಸಮರಾದ ಅನಿಮಿತ್ತ ಬಾಂಧವರು\nಎನಗಿಲ್ಲ ಆವಾವ ಜನುಮದಲ್ಲಿ\nಅನುದಿನವು ಎಮ್ಮನುದಾಸೀನ ಮಾಡುವುದು\nಅನುಚಿತವು ನಿನಗೆ ಸಜ್ಜನ ಶಿಖಾಮಣಿಯೆ ||೧||\n\nಕರಣಾಭಿಮಾನಿಗಳು ಕಿಂಕರರು ಮೂರ್ಲೋಕ\nದೊರೆ ನಿನ್ನೊಳಗಿಪ್ಪ ಪರ್ವಕಾಲ\nಪರಿಸರನೆ ಈ ಭಾಗ್ಯ ದೊರೆತನಕೆ ಸರಿಯುಂಟೆ\nಗುರುವರನೆ ನೀ ದಯಾಕರನೆಂದು ಬಿನ್ನೈಪೆ ||೨|\n\nಭವರೋಗಮೋಚಕನೆ ಪವಮಾನರಾಯ ನಿ-\nನ್ನವರವನು ನಾನು ಮಾಧವಪ್ರಿಯನೆ\nಜವನ ಬಾಧೆಯ ಬಿಡಿಸು ಅವನಿಯೊಳು ಸುಜನರಿಗೆ\nದಿವಿಜಗಣ ಮಧ್ಯದೊಳು ಪ್ರವರ ನೀನಹುದೋ ||೩||\n\nಜ್ಞಾನಾಯು ರೂಪಕನು ನೀನಹುದೊ, ವಾಣಿ ಪಂ-\nಚಾನನಾದ್ಯಮರರಿಗೆ ಪ್ರಾಣದೇವ\nದೀನವತ್ಸಲನೆಂದು ನಾನಿನ್ನ ಮೊರೆಹೊಕ್ಕೆ\nದಾನವಾರಣ್ಯ ಕೃಶಾನು ಸರ್ವದಾ ಎಮ್ಮ ||೪||\n\nಸಾಧನ ಶರೀರವಿದು ನೀ ದಯದಿ ಕೊಟ್ಟದ್ದು\nಸಾಧಾರಣವಲ್ಲ ಸಾಧುಪ್ರಿಯನೆ\nವೇದವಾದೋದಿತ ಜಗನ್ನಾಥ ವಿಠಲನ\nಪಾದಭಜನೆಯನಿತ್ತು ಮೋದಕೊಡು ಸತತ ||೫||\n\n",english:"Apamrutyu parihariso aniladeva\nKrupanavatsalane kavara kane ninnulidu ||pa||\n\nNinaginnu samarada animitta bandhugalu\nEnagilla avava janumadalli\nAnudinadalennudasina maduvudu\nNinage anuchitavu sajjanasikamaniye ||1||\n\nKaranabimanigalu kinkararu murlokadarasu\nHariyu ninnolagippa sarvakala\nParisarane I bagya doretanake sariyunte\nGuruvarya ni dayakaranemdu prarthisuve ||2||\n\nBavaroga mochakane pavamanaraya ni\nNnavaravanu nanu madhavapriyane\nJavana badheya bidiso avaniyolu sujanarige\nDivijagana madhyadali pravara ninahudo ||3||\n\nJnaanavayurupakane ninahudo vani pancha\nNanadyamararige pranadeva\nDinavatsalanemdu na ninna marehokke\nDanavaranyakrusanu sarvada enna ||4||\n\nSadhana sariravidu ni dayadikottaddu\nSadharanavalla sadhupriya\nVedavadodita jagannathavithalana\nPadabakutiya kottu modavanu kodu satata ||5||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=Jg4A6Bej7_A"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಅಪಮೃತ್ಯು-ಪರಿಹರಿಸೊ.json",
	rawData: "",
};

export { _internal, collection, data, id };
