const id = "ಅವತಾರಿ-ನೀನಯ್ಯ-ಭವದಿ";
const collection = "bhajan";
const data = {kannada_title:"ಅವತಾರಿ ನೀನಯ್ಯ ಭವದಿ",english_title:" Olitu kedukugala madhye",kannada:"ಹರೇಕೃಷ್ಣ ಹರೇಕೃಷ್ಣ  ಕೃಷ್ಣ ಕೃಷ್ಣ ಹರೇ ಹರೇ\nಹರೇರಾಮ ಹರೇರಾಮ  ರಾಮ ರಾಮ ಹರೇ ಹರೇ|| ಹರೇ||\n\nಅವತಾರಿ ನೀನಯ್ಯ ಭವದಿ ಬಂದೆ ನಾನು\nಭುವಿ ನಿನ್ನ ಸೃಷ್ಠಿಯ ಲೀಲೆ\nಸವಿ ಆದರ ನಾನು ಬಲ್ಲೆ  |\nಕಷ್ಟ ಕಾರ್ಪಣ್ಯಗಳೇ ಬರಲಿ ದಿನ …. ದಿನಾ….\nಇಷ್ಟದಿ ನೆನೆವೆ ಹರಿನಾಮ ಅನುದಿನ |\nಹರಿನಿನ್ನ ಕೃಪೆಯಿಂದ ಸಾರ್ಥಕವಾಯಿತಿ ಜನ್ಮ\n||ಅವತಾರಿ||\n\nಹರೇಕೃಷ್ಣ ಹರೇಕೃಷ್ಣ ಕೃಷ್ಣ ಕೃಷ್ಣ ಹರೇ ಹರೇ\nಹರೇರಾಮ ಹರೇರಾಮ ರಾಮ ರಾಮ ಹರೇ ಹರೇ\nಒಳಿತು ಕೆಡುಕುಗಳ ಮಧ್ಯೆ\nಮೂರು ದಿನದ ಬಾಳು |\nಇರುಳು ಹಗಲ ಸಂಕೋಲೆ ಕೊನೆಯಲ್ಲಿ ಹೇಳು\nದುಃಖ ದುಮಾನಗಳೇ ಬರಲಿ ದಿನ…ದಿನಾ …\nಇಷ್ಟದಿ ನೆನೆವೆ ಹರಿನಾಮ ಅನುದಿನಾ |\nಹರಿನಿನ್ನ ಕೃಪೆಯಿಂದ ಸಾರ್ಥಕವಾಯಿತಿ ಜನುಮ\n|| ಅವತಾರಿ||\n\nಹರೇಕೃಷ್ಣ ಹರೇಕೃಷ್ಣ  ಕೃಷ್ಣ ಕೃಷ್ಣ ಹರೇ ಹರೇ\nಹರೇರಾಮ ಹರೇರಾಮ ರಾಮ ರಾಮ ಹರೇ ಹರೇ\n\nಪಾಪ ಪುಣ್ಯದ ಕಂತೆ\nಬದುಕು ಅದರ ಸಂತೆ |\nನೀ ನಮ್ಮ ಜೊತೆಯಿರಲು ನಮಗ್ಯಾಕೆ ಚಿಂತೆ\nಹಸಿವು ದಾರಿದ್ರ್ಯವೇ ಇರಲಿ ದಿನ …ದಿನಾ…\nಇಷ್ಟದಿ ನೆನೆವೆ ಹರಿನಾಮ ಅನುದಿನಾ |\nಹರಿ ನಿನ್ನ ಕೃಪೆಯಿಂದ\nಸಾರ್ಥಕವಾಯಿತಿ ಜನುಮ …. ಪ್ರಭುವೇ\n|| ಅವತಾರಿ ||\n\n",english:"Hare Krishna hare Krishna Krishna Krishna hare hare|\nhare rama hare rama rama rama hare hare||\n\nOlitu kedukugala madhye mooru dinada baalu |\nerulu hagala sankole koneyalli helu |\ndukha dumanagale barali dina …. dinaa….\nEshtadi neneve harinama anudina |\nhari ninna krupeyinda sartakavayiti janma ||Avatari||\n\nHare Krishna hare Krishna Krishna Krishna hare hare|\nhare rama hare rama rama rama hare hare||\n\nAvatari ninayya bhavadi bande nanu |\nbhuvi ninna srushtiya leele | savi adara nanu balle |\nkashta karpanyagale barali dina ….. dinaa …\nEshtadi neneve harinama anudina |\nhari ninna krupeyinda sartakavayiti janma ||Avatari||\n\nHare Krishna hare Krishna Krishna Krishna hare hare|\nhare rama hare rama rama rama hare hare||\n\nPapa punyada kante baduku adara Sante |\nnee namma joteyiralu namagyake chinte |\nhasivu daridryave erali dina ….. dinaa …..\nEshtadi neneve harinama anudina |\nhari ninna krupeyinda sartakavayiti janma ||Avatari||\n\nHare Krishna hare Krishna Krishna Krishna hare hare|\nhare rama hare rama rama rama hare hare||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=ZGvl2XjGrss"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಅವತಾರಿ-ನೀನಯ್ಯ-ಭವದಿ.json",
	rawData: "",
};

export { _internal, collection, data, id };
