const id = "ಅಧರಂ-ಮಧುರಂ-ವದನಂ";
const collection = "bhajan";
const data = {kannada_title:"ಅಧರಂ ಮಧುರಂ ವದನಂ",english_title:"Adharam Madhuram Vadanam",kannada:"ಅಧರಂ ಮಧುರಂ ವದನಂ ಮಧುರಂ ।\nನಯನಂ ಮಧುರಂ ಹಸಿತಂ ಮಧುರಂ ।\nಹೃದಯಂ ಮಧುರಂ ಗಮನಂ ಮಧುರಂ\nಮಧುರಾಧಿಪತೇರಖಿಲಂ  ಮಧುರಂ ।।೧।।\n\nವಚನಂ ಮಧುರಂ ಚರಿತಂ ಮಧುರಂ\nವಸನಂ  ಮಧುರಂ  ವಲಿತಂ  ಮಧುರಂ ।\nಚಲಿತಂ ಮಧುರಂ  ಭ್ರಮಿತಂ ಮಧುರಂ\nಮಧುರಾಧಿಪತೇರಖಿಲಂ  ಮಧುರಂ ।।೨।।\n\nವೇಣು-ರ್ಮಧುರೋ  ರೇಣು-ರ್ಮಧುರಃ\nಪಾಣಿ-ರ್ಮಧುರಃ  ಪಾದೌ  ಮಧುರೌ ।\nನೃತ್ಯಂ ಮಧುರಂ ಸಖ್ಯಂ ಮಧುರಂ\nಮಧುರಾಧಿಪತೇರಖಿಲಂ  ಮಧುರಂ ।।೩।।\n\nಗೀತಂ ಮಧುರಂ ಪೀತಂ  ಮಧುರಂ\nಭುಕ್ತಂ ಮಧುರಂ ಸುಪ್ತಂ ಮಧುರಂ ।\nರೂಪಂ ಮಧುರಂ ತಿಲಕಂ ಮಧುರಂ\nಮಧುರಾಧಿಪತೇರಖಿಲಂ  ಮಧುರಂ।।೪।।\n\nಕರಣಂ ಮಧುರಂ ತರಣಂ ಮಧುರಂ\nಹರಣಂ ಮಧುರಂ ಸ್ಮರಣಂ ಮಧುರಂ ।\nವಮಿತಂ ಮಧುರಂ ಶಮಿತಂ ಮಧುರಂ\nಮಧುರಾಧಿಪತೇರಖಿಲಂ  ಮಧುರಂ।।೫।।\n\nಗುಂಜಾ ಮಧುರಾ  ಮಾಲ ಮಧುರಾ\nಯಮುನಾ ಮಧುರಾ ವೀಚೀ  ಮಧುರಾ ।\nಸಲಿಲಂ ಮಧುರಂ ಕಮಲಂ ಮಧುರಂ\nಮಧುರಾಧಿಪತೇರಖಿಲಂ  ಮಧುರಂ।।೬।।\n\nಗೋಪಿ ಮಧುರಾ ಲೀಲಾ ಮಧುರಾ\nಯುಕ್ತಂ ಮಧುರಂ ಮುಕ್ತಂ ಮಧುರಂ ।\nದೃಷ್ಟಂ  ಮಧುರಂ ಶಿಷ್ತಂ ಮಧುರಂ\nಮಧುರಾಧಿಪತೇರಖಿಲಂ  ಮಧುರಂ।।೭।।\n\nಗೋಪಾ ಮಧುರಾ ಗಾವೋ ಮಧುರಾ\nಯಷ್ಟಿ-ರ್ಮಧುರಾ  ಸೃಷ್ಟಿ-ರ್ಮಧುರಾ ।\nದಲಿತಂ ಮಧುರಂ ಫಲಿತಂ  ಮಧುರಂ\nಮಧುರಾಧಿಪತೇರಖಿಲಂ  ಮಧುರಂ।।೮।।\n\n।। ಇತಿ ಶ್ರೀಮದ್ ವಲ್ಲಭಾಚಾರ್ಯ ವಿರಚಿತ ಮಧುರಾಷ್ಟಕಂ  ಸಂಪೂರ್ಣಂ ।।\n\n",english:"Adharam Madhuram Vadanam Madhuram\nNayanam Madhuram, Hasitham Maduram,\nHrudhayam Madhuram, Gamanam Maduram,\nMadhuradhipather Akhilam Madhuram ||1||\n\nVachanam Madhuram, Charitham Madhuram,\nVasanam Madhuram, Valitham Madhuram,\nChalitham Madhuram, Bramitham Maduram,\nMadhurathipather Akhilam Madhuram ||2||\n\nVenur Madhuro, Renur Madhuraha,\nPanir Madhuraha, Padhou Madhuram,\nNrithyam Madhuram, Sakhyam Madhuram,\nMadurathipather Akhilam Madhuram ||3||\n\nGeetham Madhuram, Peetham Madhuram,\nBhuktham Madhuram,Suptham Madhuram,\nRoopam Madhuram, Thilakam Madhuram\nMadhurathipather Akhilam Madhuram ||4||\n\nKaranam Madhuram, Tharanam Madhuram,\nHaranam Madhuram, Smaranam Madhuram,\nVamitham Madhuram, Samitham Maduram,\nMadhurathipather Akhilam Madhuram ||5||\n\nGunja Madhura, Mala Madhura,\nYamuna Madhura, Veechi Madhura,\nSalilam Madhuram, Kamalam Madhuram,\nMadhurathipather Akhilam Madhuram ||6||\n\nGopi Madhura, Leela Madhura,\nYuktham Madhuram, Muktham Madhuram,\nDrishtam Madhuram,Sishtam Madhram,\nMadhurathipather Akhilam Madhuram ||7||\n\nGopa Madhura, Gavo Madhura,\nYashtir Madhura, Srushtir Madhra,\nDhalitham Madhram, Phalitham Madhuram,\nMadhurathipather Akhilam Madhuram ||8||\n\nIti sri mad vallabhaacharya virachita madhuraashtakam sampoornam\n\n",meta:"",tags:["madhrashtakam"],media:"https://www.youtube.com/watch?v=V00tRswnayc"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಅಧರಂ-ಮಧುರಂ-ವದನಂ.json",
	rawData: "",
};

export { _internal, collection, data, id };
