const id = "ಆಡಿದನೊ-ರಂಗ-ಅದ್ಭುತದಿಂದಲಿ";
const collection = "bhajan";
const data = {kannada_title:"ಆಡಿದನೊ ರಂಗ ಅದ್ಭುತದಿಂದಲಿ",english_title:"Adidano ranga adbhutadindali",kannada:"ಆಡಿದನೊ ರಂಗ ಅದ್ಭುತದಿಂದಲಿ ಕಾಳಿಂಗನ ಫಣೆಯಲಿ\n\nಪಾಡಿದವರಿಗೆ ಬೇಡಿದ ವರಗಳ\nನೀಡುತಲಿ ದಯಮಾಡುತಲಿ ನಲಿ-\nದಾಡುತಲಿ ಬೆಣ್ಣೆ ಬೇಡುತಲಿ ಕೃಷ್ಣ\n\nಅಂಬುರುಹೋದ್ಭವ ಅಖಿಲ ಸುರರು ಕೂಡಿ\nಅಂಬರದಲಿ ನಿಂತವರು ಸ್ತುತಿಸೆ\nರಂಭೆ ಊರ್ವಶಿ ರಮಣಿಯರೆಲ್ಲರು\nಚಂದದಿಂ ಭರತನಾಟ್ಯವ ನಟಿಸೆ\nಝಂತಟ ತಕಧಿಮಿ ತಧಿಗಣಿ ತೋಂ ಎಂದು\n\nಝಂಪೆತಾಳದಿ ತುಂಬುರನೊಪ್ಪಿಸೆ\nಧಾಮಪಪದಸರೀ ಎಂದು ಧ್ವನಿಯಿಂದ\nನಾರದ ತುಂಬುರರ್ಗಾನವ ಮಾಡಲು\nನಂದಿಯು ಚಂದದಿ ಮದ್ದಲೆ ಹಾಕಲು\n\nಫಣಿಯ ಮೆಟ್ಟಿ ಬಾಲವ ಕೈಯಲಿ ಪಿಡಿದು\nಘಣಘಣಿಸುತ ನಾಟ್ಯವನಾಡೆ\nಚಂದ್ರಮಂಡಲದಂತೆ ಪೊಳೆಯುವ ಮುಖದೊಳು\nಚಲಿಸುವ ನೀಲಕೇಶಗಳಾಡೆ\nಕಾಲಲಂದಿಗೆ ಗೆಜ್ಜೆ ಘಲು ಘಲು\nಘಲುರೆನುತ ಉಡುಗೆಜ್ಜೆ ಘಂಟೆಗಳಾಡೆ\n\nದುಷ್ಟ ಕಾಳಿಂಗನ ಮೆಟ್ಟಿ ಭರದಿಂದ\nಪುಟ್ಟ ಪಾದವ ಇಟ್ಟು ಶ್ರೀಕೃಷ್ಣನು\nಮೆಟ್ಟಿದ ತದ್ಧಿಮಿ ತಧಿಗಣತೋಂ ಎಂದು\n\nಸುರರು ಪುಷ್ಪದ ವೃಷ್ಟಿಯ ಕರೆಯಲು\nಸುದತಿಯರೆಲ್ಲರು ಪಾಡಲು\nನಾಗಕನ್ನಿಕೆಯರು ನಾಥನ ಬೇಡಲು\nನಾನಾ ವಿಧದಿ ಸ್ತುತಿಮಾಡಲು\nರಕ್ಕಸರೆಲ್ಲರು ಕಕ್ಕಸವನೆ ಕಂಡು\nದಿಕ್ಕು ದಿಕ್ಕುಗಳಿಗೆ ಓಡಲು\n\nಚಿಕ್ಕವನಿವನಲ್ಲ\nಪುರಂದರವಿಠಲ\nವೆಂಕಟರಮಣನ ಬೇಗ ಯಶೋದೆ\nಬಿಂಕದೊಳೆತ್ತಿ ಮುದ್ದಾಡೆ ಶ್ರೀಕೃಷ್ಣನ\n\n",english:"Adidano ranga adbhutadindali kalingana phaneyali||pa||\n\nPadidavarige bedida varagala nidutali daya madutali\nnalidadutali benne bedutali krishna ||a.pa.||\n\nAmburuhodbhava akhila suraru kudi|\nambaradali nindu stutise | rambe urvashi ramaniyarellaru |\nchendadim bharata natyava natise|\njhamtata takadhimi tadhigini tom endu|\njhampe taladi tumburanoppise|\ndha ma pa dha sa ri endu dhvaniyinda |\nnarada tumburar gana madalu\nnandiyu maddale chendadi hakalu ||1||\nPhaniya metti balava kaiyali pididu|\nghana ghanisutta natyavanade chandra\nmandaladante poleyuva mukhadolu |\nchalisuva nila keshagalade |\nkalalanduge gejje ghalu ghalu  |\nghalurenuta udi gejje kantegalade |\ndushta kalingana metti bharadinda putta |\npadava ittu shri krishnanu mettidanu taka dhimi tadhikenuta ||2||\nSuraru pushpada vrustiya kareyalu|\nsuddiyarellaru padalu naga kannikeyaru |\nnathana bedalu nana vidhadi stuti madalu |\nrakkasarellaru kakkasavane kandu|\ndikku dikkugalige odalu chikkavanivanalla\npurandara vittala\nvenkataramana beka\nyashode binkadoletti muttade shri krishnana||3||\n\nYoutube link :\nhttps://youtu.be/kO2SeL5vC9c\nby Sri T.V.Ramprasad\n\nThis song from the film Sri Purandara daasaru. The song is rendered by M.L.Vasanthakumari :\nhttps://youtu.be/pHp3gFtcdyA\n\n",meta:"",tags:["krishna","dasara padagalu","kannada devotional song","kannada lyrics","krishna song"],media:"https://www.youtube.com/watch?v=kO2SeL5vC9c"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಆಡಿದನೊ-ರಂಗ-ಅದ್ಭುತದಿಂದಲಿ.json",
	rawData: "",
};

export { _internal, collection, data, id };
