const id = "ಆರೇನು-ಮಾಡುವರು-ಅವನಿಯೊಳಗೆ";
const collection = "bhajan";
const data = {kannada_title:"ಆರೇನು ಮಾಡುವರು ಅವನಿಯೊಳಗೆ",english_title:" Arenu maduvaru avaniyolage",kannada:"ಆರೇನು ಮಾಡುವರು ಅವನಿಯೊಳಗೆ  ||pa||\n\nಪೂರ್ವಜನ್ಮದ ಕರ್ಮ ಹಣೆಯಲ್ಲಿ ಬರೆದುದಕೆ ||a.pa||\n\nಮಾಡಿದಡುಗೆಯು ಕೆಡಲು ಮನೆಯ ಗಂಡನು ಬಿಡಲು\nಕೂಡಿದ್ದ ಸತಿ ತಾನು ಕುಣಿಸ್ಯಾಡಲು\nಗೋಡೆಗೆ ಬರೆದ ಹುಲಿ ಘುಡಿಘುಡಿಸಿ ತಿನಬರಲು\nಆಡದಾ ಮಾತುಗಳ ಅಖಿಳರೂ ನಿಜವೆನಲು ||1||\n\nಹೊಲ ಬೇಲಿ ಮೆದ್ದರೆ ಮೊಲವೆದ್ದು ಇರಿದರೆ\nತಲೆಗೆ ತನ್ ಕೈಪೆಟ್ಟು ತಾಕಿದರೆ\nಹೆಳಲು ಹಾವಾದರೆ ಗೆಳೆಯ ರಿಪುವಾದರೆ\nಕಲಸಿಟ್ಟ ಅವಲಕ್ಕಿ ಕಲಪರಟಿ ನುಂಗಿದರೆ ||2||\n\nಹೆತ್ತಾಯಿ ಮಕ್ಕಳಿಗೆ ಹಿಡಿದು ವಿಷ ಹಾಕಿದರೆ\nಮತ್ತೆ ತಂದೆಯು ಹೊರಗೆ ಮಾರಿದರೆ\nತೊತ್ತು ಅರಸಿಗೆ ಪ್ರತಿ ಉತ್ತರವನಾಡಿದರೆ\nಕತ್ತಲೆಯು ಬೆನ್ನಟ್ಟಿ ಕರಡ್ಯಾಗಿ ಕಚ್ಚಿದರೆ ||3||\n\nಕಣ್ಣಿನೊಳಗಿನ ಬೊಂಬೆ ಕಚ್ಚಾಡ ಬಂದರೆ\nಹೆಣ್ಣಿನ ಹೋರಾಟ ಹೆಚ್ಚಾದರೆ\nಅನ್ನ ಉಣ್ಣದೆ ಬಹಳ ಅಜೀರ್ಣವಾದರೆ\nಪುಣ್ಯ ತೀರ್ಥಗಳಲ್ಲಿ ಪಾಪ ಘಟಿಸಿದರೆ ||4||\n\nಏರಿ ಕುಳಿತ ಕೊಂಬೆ ಎರಡಾಗಿ ಮುರಿದರೆ\nಮೇರೆ ತಪ್ಪಿ ಉದಧಿ ಮೆರೆದರೆ\nಆರಿದ್ದ ಇದ್ದಲಿಯು ಅಗ್ನಿಯಾಗುರಿದರೆ\nಧೀರ ಪುರಂದರವಿಠಲ ನಿನ್ನ ದಯ ತಪ್ಪಿದರೆ ||5||\n\n",english:"Arenu maduvaru avaniyolage ||pa||\n\nPurvajanmada karma haneyalli baredudake ||a.pa||\n\nMadidadugeyu kedalu maneya gandanu bidalu\nkudidda sati tanu kunisyadalu\ngodege bareda huli gudigudisi tinabaralu\nadada matugala akilaru nijavenalu ||1||\n\nHola beli meddare molaveddu iridare\ntalege tan kaipettu takidare\nhelalu havadare geleya ripuvadare\nkalasitta avalakki kalaparati nungidare ||2||\n\nHettayi makkalige hididu visha hakidarem                                                                                                                      matte tandeyu horage maridare\ntottu arasige prati uttaravanadidare\nkattaleyu bennatti karadyagi kaccidare||3||\n\nKanninolagina bombe kaccada bandare\nhennina horata heccadare\nanna unnade bahala ajirnavadare\npunya tirthagalalli papa gatisidare||4||\n\nEri kulita kombe eradagi muridare\nmere tappi udadhi meredare\naridda iddaliyu agniyaguridare\ndhira purandaravithala ninna daya tappidare||5||\n\n",meta:"",tags:["english lyrics","kannada devotional song","kannada lyrics"],media:"https://www.youtube.com/watch?v=Yb6HW7hGYW8"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಆರೇನು-ಮಾಡುವರು-ಅವನಿಯೊಳಗೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
