const id = "ಆರೇನ-ಮಾಡುವರು-ಆರಿಂದಲೇನಹುದು";
const collection = "bhajan";
const data = {kannada_title:"ಆರೇನ ಮಾಡುವರು ಆರಿಂದಲೇನಹುದು",english_title:" Arena maduvaru arindalenahudu",kannada:"ಆರೇನ ಮಾಡುವರು ಆರಿಂದಲೇನಹುದು\nಪೂರ್ವಜನ್ಮದ ಕರ್ಮವಿಧಿ ಬೆನ್ನಬಿಡದು || ಪ ||\n\nಐದು ವರುಷದ ತರಳ ತಾನೆತ್ತ ತಪವೆತ್ತ |\nಬೈದು ಮಲತಾಯಿ ಅಡವಿಗೆ ನೂಕಲು ||\nಸುಯ್ದು ಕೋಪಾಗ್ನಿಯಲಿ ಪೊರಮಟ್ಟು ಪೋಪಾಗ |\nಐದೆ ಬಂಧುಗಳಿದ್ದು ಏನ ಮಾಡಿದರು  || 1 ||\n\nನೃಪರೊಳಗೆ ಅತಿ ಶ್ರೇಷ್ಠ ಬಲವಂತ ರಘುರಾಮ |\nಅಪರಿಮಿತ ಶೂರ ಲಕ್ಷ್ಮಣದೇವರು |\nಚಪಲಾಕ್ಷಿ ಸೀತೆಯನು ಖಳನು ಕದ್ದೊಯ್ವಾಗ |\nವಿಪರೀತ ವೀರರಿದ್ದೇನ ಮಾಡಿದರು || 2 ||\n\nಪಾಪಿ ದುಶ್ಯಾಸ ದ್ರೌಪದಿಯ ಸೀರೆಯ ಸೆಳೆದು |\nಕೋಪದಿಂ ಮಾನಭಂಗವ ಮಾಡಲು ||\nಆಪತ್ತು ಬೆನ್ನಟ್ಟಿ ಹಾ ಕೃಷ್ಣ | – ಎನುವಾಗ |\nಭೂಪತಿಗಳೈವರಿದ್ದೇನ ಮಾಡಿದರು || 3 ||\n\nರಣದೊಳಗೆ ಅಭಿಮನ್ಯು ಚಕ್ರವ್ಯೂಹವ ಪೊಕ್ಕು |\nಸೆಣಸಿ ಷಡುರಥದೊಡನೆ ಹೊಯ್ದಾಡಲು ||\nಅಣಕವಿಲ್ಲದೆ ಕಾದಿ ಅಸುವಳಿದು ಪೋಪಾಗ |\nತ್ರಿಣಯಸಖಿ ಪಾರ್ಥರಿದ್ದೇನ ಮಾಡಿದರು  || 4 ||\n\nಬ್ರಹ್ಮಶಿರ ಕರಕಟ್ಟಿ ಶಿವನ ಪೀಡಿಸುತಿರಲು |\nಸುಮ್ಮನೇ ಜಗವನೆಲ್ಲವ ತಿರುಗಿದ ||\nಬೊಮ್ಮಮೂರುತಿಯಾದ\nಪುರಂದರವಿಠಲ\nನೇ\nನಮ್ಮ ಅಳವಲ್ಲ ವಿಧಿಮೀರಿ ಬಾಳುವರೆ  || 5 ||\n\n",english:"Arena māḍuvaru ārindalēnahudu\npūrvajanmada karmavidhi bennabiḍadu ||\n\nAidu varuṣhada taraḷa tānetta tapavetta |\nbaidu malatāyi aḍavige nūkalu ||\nsuydu kōpāgniyali poramaṭṭu pōpāga |\naide bandhugaḷiddu ēna māḍidaru ||\n\nNr̥uparoḷage ati śrēṣhṭha balavanta raghurāma |\naparimita śūra lakṣhmaṇadēvaru |\nchapalākṣi sīteyanu khaḷanu kaddoyvāga |\nviparīta vīrariddēna māḍidaru ||\n\nPāpi duśhyāsa draupadiya sīreya seḷedu |\nkōpadiṁ mānabhaṅgava māḍalu ||\nāpattu bennaṭṭi hā kr̥iṣhṇa | – enuvāga |\nbhūpatigaḷaivariddēna māḍidaru ||\n\nRaṇadoḷage abhimanyu chakravyūhava pokku |\nseṇasi ṣhaḍurathadoḍane hoydāḍalu ||\naṇakavillade kādi asuvaḷidu pōpāga |\ntriṇayasakhi pārthariddēna māḍidaru ||\n\nBrahmaśhira karakaṭṭi śhivana pīḍisutiralu |\nsummanē jagavanellava tirugida ||\nbommamūrutiyāda\npurandaraviṭhala\nnē\nnamma aḷavalla vidhimīri bāḷuvare ||\n\n",meta:"",tags:["narayana","dasara padagalu","kannada devotional song","narayana"],media:"https://www.youtube.com/watch?v=7AJqmw_Thnc"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಆರೇನ-ಮಾಡುವರು-ಆರಿಂದಲೇನಹುದು.json",
	rawData: "",
};

export { _internal, collection, data, id };
