const id = "ಇಂಥ-ಪ್ರಭುವ-ಕಾಣೆನೋ";
const collection = "bhajan";
const data = {kannada_title:"ಇಂಥ ಪ್ರಭುವ ಕಾಣೆನೋ",english_title:"Intha prabhuva kaaneno",kannada:"ಇಂಥ ಪ್ರಭುವ ಕಾಣೆನೋ\nಈ ಜಗದೊಳಗಿಂಥ ಪ್ರಭುವ ಕಾಣೆನೋ||ಪ||\n\nಇಂಥ ಪ್ರಭುವ ಕಾಣೆ ಶಾಂತ ಮೂರುತಿ ಜಗದಂತರಂಗನು |\nಲಕ್ಷ್ಮಿಕಾಂತ ಸರ್ವಂತರ್ಯಾಮಿ || ಅ ಪ||\n\nಬೇಡಿದ ವರ ಕೊಡುವ ಭಕ್ತರ ತಪ್ಪು ನೋಡದೆ ಬಂದು ಪೊರೆವ |\nಗಾಡಿಕಾರನು ಗರುಡಾರೂಢ ಗುಣವಂತ ಮಹ ಪ್ರೌಢ ಪ್ರತಾಪ ಜಗದಿ ಗೂಢದಿಂ ಸಂಚರಿಪ|\nಹಾಡಿ ಪೊಗಳಿ ಕೊಂಡಾಡುವವರ ಮುಂದಾದುತಲಿರ್ಪನು ಕಾಡೊಳಗಿದ್ದರು\nಕೇಡಿಗನೆ ನಾಡಾದಿಗಳಂದದಿ ಈಡುಂಟೇನೋ ಈ ವೇಂಕಟನಿಗೆ ||1||\n\nಭಾರ್ಗವಿ ಭುವಿ ವಲ್ಲಭ ಭವದೂರ ಭಕ್ತ ವರ್ಗಕೆ ಸುಲಭ |\nನಿರ್ಗುಣ ನಿರ್ವಿಕಾರ ಸ್ವರ್ಗದೈಶ್ವರ್ಯ ಕಿಂತಾನರ್ಗ ಸಂಪದವೀವ ಧೀರ್ಘಾಯುವಂತನಾದ |\nಭಾರ್ಗವರಾಮ ನೃಪಾರ್ಗಳನೆಲ್ಲ ರಣಾರ್ಗದಿ ಜಯಿಸಿದ ಉಗ್ರಪ್ರತಾಪಿ\nಸುರಾಗ್ರಗಣ್ಯ ಸದ್ವಿಗ್ರಹ ಶ್ರೀಮದನುಗ್ರಹಮಾಣ್ಯನ ದುರ್ಗವ ಕಡಿವ ||2||\n\nಸರಸೀಜಾಸನ ಮನ್ಮಥ ಈರ್ವರು ಸುತರು ಸುರತರಂಗಿಣಿ ತನುಜೆ\nಪುರವೇ ವೈಕುಂಟ ಇಂದ್ರಾಧ್ಯಮರರೇ ಕಿಂಕರರು\nಗರುಡನೆ ತುರಗ ಉರಗ ಪರಿಯಂತ ನಿಷ್ಕಳಂಕ |\nಸರಿದೊರೆಗಳನಾನರಿಯೆನು ವೇಂಕಟ ಗಿರಿಯಲಿ ಮೆರೆಯುವ ಕರುಣಿಗಳರಸನೆ\nಮರೆಯದೆ ಸಲಹುವ ಶರಣಾಗತರನು ಮರುತಾಂತರ್ಗತ\nವಿಜಯವಿಠಲ\n||3||\n\n",english:"Intha prabhuva kaaneno\nee jagadolagintha prabhuva kaaneno || pa ||\n\nInthaa prabhuva kaane shaanta mooruti jagadanta ranganu\nLakshmi kaanta sarvaantaryaami || a.pa ||\n\nBedida vara koduva bhaktara tappu nodade bandu poreva\ngaadi kaaranu garudaarooda gunavanta prauda prataapi jagadi goodadim sancharipa\npaadi pogali kondaaduvavara mundaadutalippanu naadolagiddaru\nkedidane naadaadi galandadi eedunteno ee Venkatage || 1 ||\n\nNigama tatigala ariyada neeraja bhavaadyaganita suraru kaanada\njagadodeyane bhaktaadigaligolidu tristhaanagala tyajisi Kaliyugadi bhoomige bandu |\naganita sugunaarnava Shree Hariye jagadolu sevaadigalanu kolutiha\naghahara mokshaadigalane needuta\nnagu mogadali channiga nintihano || 2 ||\n\nSarasijaasana manmatha eervaru sutaru sura tarangini tanuje |\npurave Vaikunta Indraadyamarare kinkararu |\nGarudane turaga uraga pariyanka nishkalanka |\nsaridoregala naanariyenu Venkata giriyali | irutiha karunegalarasane\nmareyade salaho sharanaagataranu\nMarutaantargata\nVijaya Vittala\n|| 3 ||\n\nYou can listen to the song here\n:\nhttps://youtu.be/rbHJFaDES3I\nby Putturu\nNarasimha Nayak\n\n",meta:"",tags:["venkateshwara srinivasa","dasara padagalu","kannada devotional song","kannada lyrics"],media:"https://www.youtube.com/watch?v=rbHJFaDES3I"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಇಂಥ-ಪ್ರಭುವ-ಕಾಣೆನೋ.json",
	rawData: "",
};

export { _internal, collection, data, id };
