const id = "ಇಂದಿರಾರಮಣ-ಗೋವಿಂದ-ನಾರಾಯಣ";
const collection = "bhajan";
const data = {kannada_title:"ಇಂದಿರಾರಮಣ ಗೋವಿಂದ ನಾರಾಯಣ",english_title:" Indiraramana govinda narayana",kannada:"ಇಂದಿರಾರಮಣ ಗೋವಿಂದ ನಾರಾಯಣ |\nವಂದಿಸುವೆ ತವಪಾದ ಪಂಕಜಕೆ ಹರಸೆನ್ನ ||\nಮಂದರಾಚಲವೆತ್ತಿ ಗೋವುಗಳ ಪೊರೆದಾತ |\nವಂದನೆಯು ನಿನ್ನಡಿಗೆ ಪೊರೆಯೆನ್ನ ||\nಪೊರೆಯೆನ್ನ ಕ್ರಷ್ಣಾ….ಕ್ರಷ್ಣಾ….\n\nಹರಿಗೋವಿಂದಂ ಹರಿಗೋವಿಂದಂ\nಗೋವಿಂದಂ ಹರಿ ಗೋಪಾಲಂ ||\nಓಂ ನಮೋ ನಾರಾಯಣಂ ಶ್ರೀ ಜಯ ನಾರಾಯಣಂ\nಶ್ರೀ ಹರಿ ನಾರಾಯಣಂ ನಮೋ ನಮೋ ನಾರಾಯಣಂ  ||ಹರಿ ಗೋವಿಂದಂ||\n\nಮಂಗಳಂ ಭಗವಾನ್ ವಿಷ್ಣು ಮಂಗಳಂ ಮಧುಸೂದನಂ\nಮಂಗಳಂ ದೇವಕಿ ಪುತ್ರೋ ಮಂಗಳಂ ಗರುಡಧ್ವಜ\nಕ್ರಷ್ಣಾಯ ವಾಸುದೇವಾಯ ದೇವಕಿನಂದನಾಯಚ\nನಂದಗೋಪ ಕುಮಾರಾಯ ಗೋವಿಂದಾಯ ನಮೋ ನಮ:\n\nಮತ್ಸ್ಯಾವತಾರವ ತಾಳಿದನೆ\nಮಂದರಾಚಲ ಬೆನ್ನೊಳು ಪೊತ್ತವನೆ ||\nಹಚ್ಚಸೂಕರನಾಗಿ ಬಾಳಿದನೆ|\nಮದಮೆಟ್ಟಿ ಹಿರಣ್ಯನ ಸೀಳಿದನೆ ||\n\nಓಂ ನಮೋ ನಾರಾಯಣಂ ಶ್ರೀ ಜಯ ನಾರಾಯಣಂ\nಶ್ರೀ ಹರಿ ನಾರಾಯಣಂ ನಮೋ ನಮೋ ನಾರಾಯಣಂ ||ಹರಿಗೋವಿಂದಂ||\n\nಕುಂಭಿನಿ ದಾನವ ಬೇಡಿದನೆ\nಕ್ಷಾತ್ರರೆಂಬವರನು ಹತ ಮಾಡಿದನೆ ||\nಅಂಬುಧಿಗೆ ಶರ ಹೂಡಿದನೆ |\nಕಮಲಾಂಬಕ ಗೊಲ್ಲರೊಳಾಡಿದನೆ ||\n\nಓಂ ನಮೋ ನಾರಾಯಣಂ ಶ್ರೀ ಜಯ ನಾರಾಯಣಂ\nಶ್ರೀ ಹರಿ ನಾರಾಯಣಂ ನಮೋ ನಮೋ ನಾರಾಯಣಂ ||ಹರಿಗೋವಿಂದಂ||\n\nಸಾಧಿಸಿ ತ್ರಿಪುರರ ಗೆಲಿದವನೆ\nವ್ಲೇಂಚರ ಛೇಧಿಸಿ ಮೆರೆದವನೆ ||\nಸಾಧಿಸಿ ಸಕಲವ ತಿಳಿದವನೆ   |\nಬಾಡದಾದಿ ಕೇಶವನಿಗೆ ಒಲಿದವನೆ ಆದಿಕೇಶವನಿಗೆ ಒಲಿದವನೆ\n\nಓಂ ನಮೋ ನಾರಾಯಣಂ ಶ್ರೀ ಜಯ ನಾರಾಯಣಂ\nಶ್ರೀ ಹರಿ ನಾರಾಯಣಂ ನಮೋ ನಮೋ ನಾರಾಯಣಂ ||ಹರಿಗೋವಿಂದಂ||\n\n",english:"Indiraramana govinda narayana | vandisuve tavapada pankajake harasenna || mandarachalavetti govugala poredata | vandaneyu ninnadige poreyenna || poreyenna krishnaa …. krishnaa ….\n\nHari govindam harigovindam govindam hari gopalam || om namo narayanam sri jaya narayanam | sri hari narayanam namo namo narayanam || hari govindam ||\n\nMangalam bhagavan vishnu mangalam madhusudanam | mangalam devaki putro mangalam garudadhwaja | krishnaya vasudevaya devakinandanayacha | nandagopa kumaraya govindaya namo namh ||\n\nMatsyavatarava talidane mandarachala bennolu pottavane | hacchasookaranagi balidane | madametti hiranyana seelidane ||\n\nOm namo narayanam sri jaya narayanam | sri hari narayanam namo namo narayanam || hari govindam ||\n\nKumbhini danava bedidane kshtraremvaranu hata madidane | ambudhige shara hoodidane | kamalaambaka gollarolaadidane ||\n\nOm namo narayanam sri jaya narayanam | sri hari narayanam namo namo narayanam || hari govindam ||\n\nSadhisi tripurara gelidavane vlenchara chedhisi meredavane | sadhisi sakalava tilidavane | baadadaadi keshavanige olidavane aadikeshavanige olidavane ||\n\nOm namo narayanam sri jaya narayanam | sri hari narayanam namo namo narayanam || hari govindam ||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=GRcJ2eY5EUc"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಇಂದಿರಾರಮಣ-ಗೋವಿಂದ-ನಾರಾಯಣ.json",
	rawData: "",
};

export { _internal, collection, data, id };
