const id = "ಇಂದು-ನಾನೇನು-ಸುಕ್ರತವ-ಮಾಡಿದೆನೂ";
const collection = "bhajan";
const data = {kannada_title:"ಇಂದು ನಾನೇನು ಸುಕ್ರತವ ಮಾಡಿದೆನೂ",english_title:" Indu nanenu sukrutava madideno",kannada:"ರಚನೆ : ಶ್ರೀ ಪುರಂದರ ದಾಸರು\n\nಇಂದು ನಾನೇನು ಸುಕ್ರತವ ಮಾಡಿದೆನೂ ||2||\nಮಂಗಳ ಮಹಿಮ ವೆಂಕಟ ಬಂದ ಮನೆಗೆ  ||ಇಂದು||\n\nಹಾರ ಕೇಯೂರ ಹೊಣ್ಣುಂಗುರ ಬೆರಳು\nಹಾರದ ನಡುವೆ ಹಾಕಿದವು ಏಳು ಪದಕ ||\nತೋರ ಮುತ್ತಿನ ಕಂಠ ಮಾಲೆಯು ಸರಿಗೆಯು ||2||\nಕೋನೇರಿವಾಸ ವೆಂಕಟ ಬಂದ ಮನೆಗೆ ||2||\nವೆಂಕಟ ಬಂದ ಮನೆಗೆ ||2|| ಇಂದು||\n\nಕಾಲ ಪೆಂಡಿಗೆಯು ರಕ್ಕಸರ ಹಾವಿಗೆಯು\nಮೇಲಾದ ವಜ್ರ ನವರತ್ನದ ಮುಕುಟ  ||\nವೀಳ್ಯದ ಬಾಯಿ ಕರ್ಪೂರದ ಕರಡಿಗೆಯು| |2||\nಮೇಲು ಗಿರಿವಾಸ ವೆಂಕಟ ಬಂದ ಮನೆಗೆ ||2||\nವೆಂಕಟ ಬಂದ ಮನೆಗೆ ||2|| ಇಂದು||\n\nಬಿಗಿದು ಸುತ್ತಿದ ವಳ್ಳಿ , ಬಿಡಿ ಮುತ್ತಿನ ಕಂಠಿ\nಬಿಗಿ ಮುಗುಳು ನಗೆದಂತ ಎಸೆವಂತ ಪಂಕ್ತಿ ||\nತೆಗೆದುಟ್ಟ ಪೀತಾಂಬರ ಉಡುಗೆ ಕಠಾರಿ ||2||\nಯದುಗಿರಿ ವಾಸ  ವೆಂಕಟ ಬಂದ ಮನೆಗೆ ||2||\nವೆಂಕಟ ಬಂದ ಮನೆಗೆ ||2||  ಇಂದು||\n\nನೊಸಲ ಸುತ್ತಿದ ಪಟ್ಟಿ , ಎಸೆವ ಕಸ್ತೂರಿಯು\nವಸವಾದ ಅಮ್ರತದ  ರಸ  ಸವಿಮಾತು ||\nಎಸಲು ಕಂಗಳ ನೋಟ, ಹೊಸ ಪಂಚ ಬಾಣ ||2||\nಸುಕುಮಾರ ಸೊಬಗು ವೆಂಕಟ ಬಂದ ಮನೆಗೆ ||2||\nವೆಂಕಟ ಬಂದ ಮನೆಗೆ ||2||ಇಂದು||\n\nಕಲಿಯುಗದಲಿ ಶಂಖಚಕ್ರವ ಧರಿಸಿ\nಹದಿನಾಲ್ಕು ಲೋಕ ತನ್ನುದರದಲ್ಲಿಟ್ಟು ||\nಗರುಡನ ಏರಿ ಮೂರ್ಜಗವ ಮೋಹಿಸುವ ||2||\nಪುರಂದರವಿಠ್ಠಲ\nವೆಂಕಟ ಬಂದ ಮನೆಗೆ ||2||\nವೆಂಕಟ ಬಂದ ಮನೆಗೆ|| 2|| ಇಂದು||\n\n",english:"Composer : Sri Purandara dasaru\n\nIndu nanenu sukrutava madideno |\nmangala mahima banda manege || Indu ||\n\nHaara keyura honnungura beralu\nhaarada naduve haakidavu elu padaka ||\ntora muttina kanta maleyu sarigeyu\nkonerivasa venkata banda manege ||\nvenkata banda manege || Indu ||\n\nKaala pendigeyu rakkasara haavigeyu\nmelaada vajra navaratnada mukuta ||\nveelyada baayi karpoorada karadogeyu\nmelu girivasa venkata banda manege ||\nvenkata banda manege || Indu ||\n\nBigidu suttida valli, bidi muttina kanti\nbigi mugulu nagedanta esevanta pankti ||\ntegedutta peetaambara uduge kataari\nyadugiri vasa venkata banda manege  ||\nvenkata banda manege || Indu ||\n\nNosala suttida patti, eseva kasturiyu\nvasavaada amrutada rasa savimaatu ||\nesalu kangala nota hosa pancha bana\nsukumara sobagu venkata banda manege ||\nvenkata banda manege || Indu ||\n\nKaliyugadali shankha chakrava dharisi\nhadinalku loka tannudaradallittu ||\ngarudana eri murjagava mohisuva\npurandaravittala\nvenkata banda manege ||\nvenkata banda manege || Indu ||\n\n************************\n\n",meta:"",tags:["venkateshwara srinivasa","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=dJ1DcAdLGu8"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಇಂದು-ನಾನೇನು-ಸುಕ್ರತವ-ಮಾಡಿದೆನೂ.json",
	rawData: "",
};

export { _internal, collection, data, id };
