const id = "ಈ-ಪಾದ-ಪುಣ್ಯ-ಪಾದ";
const collection = "bhajan";
const data = {kannada_title:"ಈ ಪಾದ ಪುಣ್ಯ ಪಾದ",english_title:"Ee Paada Punya Paada",kannada:"ಈ ಪಾದ ಪುಣ್ಯ ಪಾದ\nಈ ಪಾದ ದಿವ್ಯ ಪಾದ..\n\nಈ ಪಾದ ಪುಣ್ಯ ಪಾದ\nಈ ಪಾದ ದಿವ್ಯ ಪಾದ..\nಮನೆಗೆ ಬಂದು ಹೋದ ಪ್ರಥಮ ಲೋಕ ಪಾದ\nಮುಗಿಯದೇ ಹೋದ ನನ್ನ ಈ ಕರವೇಕೆ ಈ ಕರವೇಕೆ ||ಈ ಪಾದ ಪುಣ್ಯ ಪಾದ||\n\nಮಾರ್ಕಂಡೇಯ ಕಂಡ ಪಾದ | ಪ್ರಾಣ ಪಾದ ||2||\nಬೇಡರ ಕಣ್ಣ ಕಂಡ ಪರಮ ಪಾದ ಭಕ್ತ ಪಾದ |2|\nಬೇಡರ ಕಣ್ಣ ಕಂಡ ಪರಮ ಪಾದ ಭಕ್ತ ಪಾದ\nಆತ್ಮ ಲಿಂಗ ಸ್ವಯಂಪೂರ್ಣ..\nಆತ್ಮ ಲಿಂಗ ಸ್ವಯಂಪೂರ್ಣ  ತಾನಾಗಿ ಬಂದರು\nದಾಸೋಹಿ ಅಂದರು, ಅಯ್ಯೋ.. ಕಾಣದ ನಾಥನಾದೆ ಮಂಜುನಾಥ\n\nಈ ಪಾದ ಪುಣ್ಯ ಪಾದ\nಧರೆಯಾಳೋ ಧರ್ಮ ಪಾದ\nಮದವ ಮೆಟ್ಟಿ ಹೋದ ಪ್ರಳಯ ನಾಟ್ಯ ಪಾದ\nಮಣಿಯದೆ ಹೋದ ನನ್ನ ಈ ಶಿರವೇಕೆ.. ಈ ಶಿರವೇಕೆ?\n\nಈ ಪಾದ ಪುಣ್ಯ ಪಾದ\nಧರೆಯಾಳೋ ಧರ್ಮ ಪಾದ\n\nಭಕ್ತ ಶಿರಿಯಾಳ ಕಂಡ ಪ್ರೇಮಪಾದ\nಭಕ್ತ ಶಿರಿಯಾಳ ಕಂಡ ಪ್ರೇಮಪಾದ\nಬ್ರಹ್ಮ ವಿಷ್ಣುವೇ ಮುಗಿದ ಆದಿ ಪಾದ ನಾದಿ ಪಾದ\nಬ್ರಹ್ಮ ವಿಷ್ಣುವೇ ಮುಗಿದ ಆದಿ ಪಾದ ನಾದಿ ಪಾದ\nಅನ್ನದಾತ ವಿಶ್ವನಾಥ..\nಅನ್ನದಾತ ವಿಶ್ವನಾಥ ಲೀಲಾವಿನೋದಕೆ\nತನ್ನ ಲೀಲಾವಿನೋದಕೆ, ಅಯ್ಯೋ.. ಎನ್ನ ಸಿಂಧು ಮಾಡಿದರು ಅಸಿಂಧುವಾದೆ\n\nಈ ಪಾದ ಪುಣ್ಯ ಪಾದ\nಈ ಪಾದ ದಿವ್ಯ ಪಾದ\nಹರಸ ಬಂದ ಪಾದ\nಮೆರೆಸಾ ಬಂದ ಪಾದ\nಅರಿಯದೆ ಹೋದ ನನ್ನ ಈ ಅರಿವೇಕೆ.. ಈ ಅರಿವೇಕೆ ||ಈ ಪಾದ||\n\nಈ ಪಾದ ಪುಣ್ಯ ಪಾದ\nಈ ಪಾದ ದಿವ್ಯ ಪಾದ..\n\n",english:"Ee Paada Punya Paada\nEe Paada Divya Paada..\n\nEe Paada Punya Paada\nEe Paada Divya Paada..\nManege Bandu Hoda Prathama Loka Paada\nMugiyade Hoda Nanna Ee Karaveke Ee Karaveke ||Ee pada||\n\nMaarkhandeya Kanda Paada, Praana Paada..\nMaarkhandeya Kanda Paada, Praana Paada\nBedara Kanna Kanda Parama Paada Bhakta Paada..\nBedara Kanna Kanda Parama Paada Bhakta Paada\nAatma Linga Swayampoorna..\nAatma Linga Swayampoorna Thaanagi Bandaru\nDaasohi Andaru, Ayyo.. Kaanada Naathanaade Manjunatha\n\nEe Paada Punya Paada\nDhareyaalo Dharma Paada\nMadava Metti Hoda Pralaya Naatya Paada\nManiyade Hoda Nanna Ee Shiraveke.. Ee Shiraveke ||Ee pada||\n\nEe Paada Punya Paada\nDhareyaalo Dharma Paada\n\nBhakta Siriyaala Kanda Prema Paada..\nBhakta Siriyaala Kanda Prema Paada\nBarhma Vishnuve Mugida Aadi Paada Naadi Paada..\nBarhma Vishnuve Mugida Aadi Paada Naadi Paada\nAnna’daatha Vishvanaatha..\nAnna’daatha Vishvanaatha Leelaavinodake\nTanna Leelaavinodake, Ayyo.. Enna Sindhu Maadidaru Asindhuvaade\n\nEe Paada Punya Paada\nEe Paada Divya Paada..\nHarasi Banda Paada\nMeresa Banda Paada..\nAriyade Hoda Nanna Ee Ariveke.. Ee Ariveke ||Ee pada||\n\n",meta:"",tags:["kannada devotional song"],media:""};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಈ-ಪಾದ-ಪುಣ್ಯ-ಪಾದ.json",
	rawData: "",
};

export { _internal, collection, data, id };
