const id = "ಉಡುಪಿಯ-ಕಂಡಿರಾ…";
const collection = "bhajan";
const data = {kannada_title:"ಉಡುಪಿಯ ಕಂಡಿರಾ…",english_title:" Udupiya kandeera ….",kannada:"ಉಡುಪಿಯ ಕಂಡಿರಾ…ಅ\nಉಡುಪಿಯ ಕೃಷ್ಣನ  ಕಂಡಿರಾ…ಅ ll 2 ll\nಕೃಷ್ಣನ ಕಂಡಿರಾ…. ಅ ಕೃಷ್ಣನ ಕಂಡಿರಾ…. ಅ ಕೃಷ್ಣನ ಉಡುಪಿಯ ಕಂಡಿರಾ….ಅ         ಉಡುಪಿಯ ಕಂಡಿರಾ…\n\nಜಗದೊಡೆಯ ಬಂದ ಉಡುಪಿಯಲ್ಲಿ ನಿಂದ\nಪಡು ಗಡಲ ದಾರಿಯಿಂದ  ll 2 ll\nಮಿಗಿಲುಂಟೆ ಚಂದ ಕಣ್ಗಳಾನಂದ ಆನಂದ ಕಂದನಿಂದ….\nದ್ವಾರೆಕೆಯ ವಾಸ  ಓ ಋಷಿಕೇಶ ಸಾಕೆನಿಸಿತೇನು\nಈಶ…. ವಾರಿಯಲ್ಲಿ ಬಂದೆ ದಾರಿಯಲ್ಲಿ ನಿಂದೆ\nನೀ ದಾಟಿ ತೇಸಾ ತೇಸಾ…ಅ               |ಉಡುಪಿಯ ಕಂಡಿರಾ… ll\n\nಕಡೆಗೋಲು ಕೈಯ್ಯಯಾ…\nಕಡುನೀಲ ಮೈಯ್ಯಾಯಾ… ಈ ಬಾಲ ರೂಪ ಕಂಡು ll 2 ll\nಕೊಡಮಡದ ಶಿರವು ಜೋಡಿಸದ ಕರವೋ\nಬರೀ ಹುಲ್ಲು ಮಣ್ಣು ದೂಂಡೊಆ ಮುಗುಳು ನಗುಗೆ  ಆ ನಿಂತ ಬಗೆಗೆ\nಮರುಳಾದಳಂತೆ ಗೋಪಿ… ಇ…\nಶ್ರೀ ಮಧ್ವಗೊಳಿದ ಕೃಷ್ಣನಗೆಳಿದ\nಹೆಗ್ಗಲದ ನಾಡು ಉಡುಪಿ…       Il ಉಡುಪಿಯ ಕಂಡಿರಾ… ll\n\nಪಡುಗಡಲ ತೀರದಿಂದೆದ್ದು ಬಾರಾ ಕಡೆಗೋಲು  ಹಗ್ಗ ಹಿಡಿದು ll 2 llಬಿಡುಗಡೆಯ ದಾರಿ ಭಕ್ತರಿಗೆ ತೋರಿ\nನಮ್ಮೆದೆಯ ಬೆಣ್ಣೆ ಕಡಿದು ಆನಂದ ತಿರ್ಥಂಕರಿಗೆ\nಪಾರ್ಥ ಸಾರಥಿಯು ಕರಗಿ ಬಂದು\nಬಾನಿಂದ ಕಲ್ಲಿನೊಳಗಿಂದ ಇಲ್ಲಿ ವೈಕುಂಠವನ್ನೇ ತಂದು     Il ಉಡುಪಿಯ ಕಂಡಿರಾ… ll 2 ll    Il ಉಡುಪಿಯ ಕೃಷ್ಣನ ll 2 ll\n\n",english:"Udupiya kandeera Udupiya Krishnana kandeera (2)\nKrishnana kandeera…. Krishnana Udupiya kandeera\nUdupiya kandeera …….Udupiya Krishnana kandeera ||\n\nJagadhodeya bandha Udupiyali ninda padugadala dhari inda(2)\nMigilunte chanda kangalaananda ananda kandaninda\nDvarakeya vasa oh rishikesha sakenisitheno Esha\nVariali badhe dariali nindhe nee dati desha desha\n\nUdupiya kandeera Udupiya Krishnana kandeera (2)\n\nKadakolu kaiyya kaduneeli maiyya e bala roopa kandu (2)\nKodamadadha shiravo jodisadha karavu bari hullu mannu thumbhu\nAa mugulu nagege aa nintha bhagege maruladhalanthe gopi\nSrimadhwa golidha Krishnanani gelidha yaggalada nadu Udupi\n\nUdupiya kandeera Udupiya Krishnana kandeera (2)\n\nKadugadala theera nintheddhu bara kadegolu attha hididhu (2)\nBidugadeya dhari bhaktharige thori nammedheya benne kadedhu\nAnanda thirtha rirtharege parthasarathiyu karagi banthu\nKanindha kalli nolaginda illi vaikunta vanne thadhu\n\nUdupiya kandeera udupiya krishnana kandeera\nKrishnana kandeera(2) krishnana udupiya kandeera\nUdupiya kandeera, udupiya krishnana kandeera (3)\n\n",meta:"",tags:["kannada devotional song","kannada lyrics"],media:"https://www.youtube.com/watch?v=S5Z4PW5aw74"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಉಡುಪಿಯ-ಕಂಡಿರಾ….json",
	rawData: "",
};

export { _internal, collection, data, id };
