const id = "ಉಮಾ-ಕಾತ್ಯಾಯಿನೀ-ಗೌರೀ-ದಾಕ್ಷಾಯಿಣೀ";
const collection = "bhajan";
const data = {kannada_title:"ಉಮಾ ಕಾತ್ಯಾಯಿನೀ ಗೌರೀ ದಾಕ್ಷಾಯಿಣೀ",english_title:" Uma Kathyayani gowri",kannada:"ಉಮಾ ಕಾತ್ಯಾಯಿನೀ ಗೌರೀ ದಾಕ್ಷಾಯಿಣೀ ಹಿಮವಂತ ಗಿರಿಯ ಕುಮಾರಿ\nರಮೆಯರಸನ ಪದಕಮಲಮಧುಪೆ ನಿತ್ಯ ಅಮರ ವಂದಿಪೆ ಗಜಗಮನೆ ಭವಾನೀ\n\nಪನ್ನಗಧರನ ರಾಣಿ ಪರಮ ಪಾವನೀ ಪುಣ್ಯ ಫಲಪ್ರದಾಯಿನೀ\nಪನ್ನಗವೇಣೀ ಶರ್ವಾಣೀ ಕೋಕಿಲವಾಣಿ ಉನ್ನಂತ ಗುಣಗಣ ಶ್ರೇಣಿ |\nಎನ್ನ ಮನದ ಅಭಿಮಾನಿ ದೇವತೆಯೇ ಸ್ವರ್ಣಗಿರಿ ಸಂಪನ್ನೆ ಭಾಗ್ಯನಿಧಿ\nನಿನ್ನ ಮಹಿಮೆಯ ನಾ ಬಿನ್ನಾಣದಲ್ಲಿ ಬಣ್ಣಿಸಲಸಳವೇ ಪ್ರಸನ್ನವದನಳೇ ||\n\nಮುತ್ತಿನ ಪದಕ ಹಾರ ಮೋಹನ್ನಸರ ಉತ್ತಮಾಂಗದಲಂಕಾರ\nಜೊತ್ಯಾಗಿಟ್ಟ ಪಂಜರದೋಲೆ ಒಯ್ಯಾರ ರತ್ನಕಂಕಣದುಂಗುರ\nತೆತ್ತೀಸಕೋಟಿ ದೇವತೆಗಳು ಪೊಗಳುತ ಸತ್ತಿಗೆ ಚಾಮರವೆತ್ತಿ ಪಿಡಿಯುತಿರೇ\nಸುತ್ತಲೂ ಆಡುವ ನರ್ತನಸಂದಣಿ ಎತ್ತ ನೋಡಿದರತ್ತ ತತ್ಥೈವಾದ್ಯ ||\n\nಪೊಳೆವ ವಸನ ಕಂಚುಕ ಕಸ್ತೂರಿ ತಿಲಕ ಥಳಿಪ ಮೂಗುತಿ ನಾಸಿಕ\nತಳಿತ ಮಲ್ಲಿಗೆ ಗಂಧಿಕ ಮುಡಿದ ಸೂಸುಕ ಸಲೇ ಭುಜಕೀರ್ತಿಪಾಠಿಕ |\nಇಳೆಯೊಳು ಮಧುರಪೊಳಲೊಳುವಾಸಳೇ ಅಳಗಿರಿ ವಿಜಯವಿಟ್ಠಲನ ಕೊಂಡಾಡುವ\nಸುಲಭ ಜನರಿಗೆ ಒಲಿದು ಮತಿವ ಕೊಡುವ ಗಿಳಿಕರ ಶೋಭಿತೇ ಪರಮಮಂಗಳೇ ಹೇ ||\n\n",english:"Uma Kathyayani gowri dhakshayaani\nheemaavantha giriya kumaari|\n\nRamayerasa padha kamala madhupe nitya\namara vandhitha gaja gamane bavaani||\n\nPannagadharana raani parama paavani\npunya pala pradhayini\npannaga veni sarvaani kokila vaani\nunnatha gunadha shreni |\nenna manadha abhimani devateya\nsvarna giri sampanna baghya nidhi\nninna mahima yannu binnana dhali na\nbannisalalave prasanna vadhanale||1||\n\nMutthina padhaka haara mohanna sara\nuttamaangadha lankaara\njottheyagitta panjara dhole oyyara\nrathna kankana dhungura |\nthetthisa koti devathegalu pogalutha\nsatthige cgamara vetthi hidiyuthire\nsutthalu aduva narthana sandani\nettha nodidarathha thathai vaadhya||2||\n\nPoleva vasana kanjuka kasthuri tilaka\ndalipa mukuthi naasika\ndhalidammalige gandhiga mudida susuka\nsalebuja keerthi naasika\nilayolu madhuraapuradholu vaasane\nalagiri vijaya vittalana kondaduva\nsulapajanari gella olidhu madhiya neeve\ngilikara shobhithe parama mangale||3||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=jEu67bn_ZrA"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಉಮಾ-ಕಾತ್ಯಾಯಿನೀ-ಗೌರೀ-ದಾಕ್ಷಾಯಿಣೀ.json",
	rawData: "",
};

export { _internal, collection, data, id };
