const id = "ಎಲ್ಲರೂ-ಮಾಡುವುದು-ಹೊಟ್ಟೆಗಾಗಿ";
const collection = "bhajan";
const data = {kannada_title:"ಎಲ್ಲರೂ ಮಾಡುವುದು ಹೊಟ್ಟೆಗಾಗಿ",english_title:" Ellaru maduvudu hottegagi",kannada:"ಎಲ್ಲಾರು ಮಾಡುವುದು ಹೊಟ್ಟೆಗಾಗಿ ಗೇಣುಬಟ್ಟೆಗಾಗಿ   ।।ಪ ।।\n\nವೇದಶಾಸ್ತ್ರ ಪಂಚಾಂಗವ ಓದಿಕೊಂಡು ಅನ್ಯರಿಗೆ\nಬೋಧನೆಯ ಮಾಡುವುದು ಹೊಟ್ಟೆಗಾಗಿ ಗೇಣುಬಟ್ಟೆಗಾಗಿ         ||1||\n\nಚಂಡಭಟರಾಗಿ ನಡೆದು ಕತ್ತಿ ಡಾಲು ಕೈಲಿ ಹಿಡಿದು\nಖಂಡ ತುಂಡ ಮಾಡುವುದು ಹೊಟ್ಟೆಗಾಗಿ ಗೇಣುಬಟ್ಟೆಗಾಗಿ         ||2||\n\nಅಂಗಡಿ ಮುಂಗಟ್ಟನ್ನ ಹೂಡಿ ವ್ಯಂಗ ಮಾತುಗಳನ್ನ ಅಡಿ\nಭಂಗಬಿದ್ದು ಗಳಿಸಿವುದು ಹೊಟ್ಟೆಗಾಗಿ ಗೇಣುಬಟ್ಟೆಗಾಗಿ               ||3||\n\nಕುಂಟೆ ತುದಿಗೆ ಕೊರಡು ಹಾಕಿ ಹೆಂಟೆ ಮಣ್ಣು ಸಮನು ಮಾಡಿ\nರಂಟೆ ಹೊಡೆದು ಬೆಳೆಸುವುದು ಹೊಟ್ಟೆಗಾಗಿ ಗೇಣುಬಟ್ಟೆಗಾಗಿ      ||4||\n\nಬೆಲ್ಲದಂತೆ ಮಾತನಾಡಿ ಎಲ್ಲರನ್ನು ಮರುಳುಮಾಡಿ\nಸುಳ್ಳು ಬೊಗಳಿ ತಿಂಬುವುದು ಹೊಟ್ಟೆಗಾಗಿ ಗೇಣುಬಟ್ಟೆಗಾಗಿ       ||5||\n\nಕೊಟ್ಟ ಹಣವನು ಕುಟ್ಟಿಕೊಂಡು ಕಟ್ಟಿಗೆಯನು ಹೊತ್ತುಕೊಂಡು\nಕಷ್ಟ ಮಾಡಿ ಉಣ್ಣುವುದು  ಹೊಟ್ಟೆಗಾಗಿ ಗೇಣುಬಟ್ಟೆಗಾಗಿ          ||6||\n\nಸನ್ಯಾಸಿ ಜಂಗಮ ಜೋಗಿ ಜಟ್ಟಿ ಮೊಂಡ ಬೈರಾಗಿ\nನಾನ ವೇಷಗಳೆಲ್ಲ ಹೊಟ್ಟೆಗಾಗಿ ಗೇಣುಬಟ್ಟೆಗಾಗಿ                     ||7||\n\nಹಳ್ಳದಲಿ ಕುಳಿತುಕೊಂಡು ಕಲ್ಲು ದೊಣ್ಣೆ ಹಿಡಿದುಕೊಂಡು\nಕಳ್ಳತನವ ಮಾಡುವುದು ಹೊಟ್ಟೆಗಾಗಿ ಗೇಣುಬಟ್ಟೆಗಾಗಿ            ||8||\n\nಅಂದಣ  ಪಲ್ಲಕ್ಕಿ ಏರಿ ಮಂದಿ ಮಾರ್ಬಲ ಕೂಡಿ\nಚಂದದಿಂದ ಮೆರೆಯುವುದು ಹೊಟ್ಟೆಗಾಗಿ ಗೇಣುಬಟ್ಟೆಗಾಗಿ          ||9||\n\nಉನ್ನತ ಕಾಗಿನೆಲೆಯಾದಿಕೇಶವನಾ ದ್ಯಾನವನ್ನು\nಮನಮುಟ್ಟಿ ಮಾಡುವುದು ಮುಕ್ತಿಗಾಗಿ ಆನಂದಕಾಗಿ                  ||10||\n\n",english:"Ellaru maduvudu hottegagi genubattegagi ||pa||\n\nVedashastra panchangava odikonfu anyarige bodhaneya maduvudu hottegagi genubattegagi ||1||\n\nChandabataragi nadedu katti dalu kaili hididu\nKanda tunda maduvudu hottegagi genubattegagi ||2||\n\nAngadi mungattanna hudi vyanga matugalanna adi\nbangabiddu galisivudu hottegagi genubattegagi ||3||\n\nKunte tudige koradu haki hente mannu samanu madi\nrante hodedu belesuvudu hottegagi genubattegagi ||4||\n\nBelladante matanadi ellarannu marulumadi\nsullu bogali timbuvudu hottegagi genubattegagi ||5||\n\nKotta hanavanu kuttikondu kattigeyanu hottukondu\nkashta madi unnuvudu hottegagi genubattegagi ||6||\n\nSanyasi jangama jogi jatti monda bairagi\nnana veshagalella hottegagi genubattegagi ||7||\n\nHalladali kulitukondu kallu donne hididukondu\nkallatanava maduvudu hottegagi genubattegagi ||8||\n\nAndana pallakki eri mandi marbala kudi\nchandadinda mereyuvudu hottegagi genubatteggi ||9||\n\nUnnata kagineleyadikeshavana dyanavannu\nmanamutti maduvudu muktigagi anandakagi ||10||\n\nYoutube link :\nhttps://youtu.be/pmmqA0GE_2U\nby Dr.Rajkumar\n\n",meta:"",tags:["kannada devotional song","kannada lyrics"],media:""};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಎಲ್ಲರೂ-ಮಾಡುವುದು-ಹೊಟ್ಟೆಗಾಗಿ.json",
	rawData: "",
};

export { _internal, collection, data, id };
