const id = "ಎನ್ನ-ಬಿನ್ನಪ-ಕೇಳು-ಧನ್ವಂತ್ರಿ";
const collection = "bhajan";
const data = {kannada_title:"ಎನ್ನ ಬಿನ್ನಪ ಕೇಳು ಧನ್ವಂತ್ರಿ",english_title:" Enna binnapa kelu dhanvantri",kannada:"ಎನ್ನ ಬಿನ್ನಪ ಕೇಳು ಧನ್ವಂತ್ರಿ ದಯಮಾಡು | ಸಣ್ಣವನು ಇವ ಕೇವಲಾ ಬಣ್ಣ ಬಡಿಸುವ ರೋಗವನ್ನುಮೋಚನ\nಮಾಡಿ ಚೆನ್ನಾಗಿ ಪಾಲಿಸುವುದು ವಿಭುವೆ ಚೆನ್ನಾಗಿ ಪಾಲಿಸುವುದು ||\n\nಆರೋಗ್ಯ ಆಯುಷ್ಯ ಐಶ್ವರ್ಯವೆಂಬೊ ಈ ಮೂರು ವಿಧ ವಸ್ತುಗಳು ನಾರಾಯಣನ ಭಜಕರಾದವರ ಸಾಧನಕೆ ಪೂರ್ಣವಾಗಿಪ್ಪುವು ಘೋರ ವ್ಯಭಿಚಾರ ಪರನಿಂದೆ ಪರವಿತ್ತಾಪಹಾರ ಮಾಡಿದ ದೋಷದಿ ದರಿದ್ರರಾಗುವರು ಮೂರು ವಿಧದಿಂದಲಿ ಕಾರಣನು ನೀನೆ ದುಷ್ಕರ್ಮ ಪರಿಹರಿಸುವುದು ಹರಿಯೆ ||ಎನ್ನ||\n\nವಸುಮತಿಯ ಮೇಲಿನ್ನು\nಅಸುರ ಜನರೆ ಬಹಳ ವಶವಲ್ಲ ಕಲಿಯ ಬಾಧೆ\nಬಿಸಿಲಿಂದ ಪೀಡಿತವಾದ ಸಸಿಗಳಂತೆ\nಶಿಶುಗಳು ನಾವಿರ್ಪೆವೋ\nಅಸುರಾರಿ ನಿನ್ನ ಕರುಣಾಮ್ರತದ ಮಳೆಗರೆದು\nಕುಶಲದಲಿ ಪಾಲಿಪುವುದೋ\nಕೆಸರಿಂದ ಕೆಸರ ತೊಳೆದಂತೆ ಕರ್ಮದಪಥವು\nಅಸುನಾಥ ಹರಿಯೆ ಪೊರೆಯೋ ಸ್ವಾಮಿ ||ಎನ್ನ||\n\nಆದಿವ್ಯಾಧಿಗಳು ಉನ್ಮಾದ ವಿಭ್ರಮ\nನಾನಾ ಬಾಧೆಗೌಷದನು ನೀನೆ\nಹೇ ದೇವ ನಿನ್ನ ಕರಕಲಶ ಸುದೆಯನು\nಎರೆದು ಸಾಧುಗಳ ಸಂತೈಸುವೆ\nಮೋದ ಪಡಿಸುವಿ ನಿನ್ನ ಸಾಧಿಸುವರಿಗೆ\nಶುಭೋದಯಂಗಳನ್ನು ಮಾಡಿ\nಆದರಿಸಿ ಇವಗೆ ತವ ಪಾದ ಧ್ಯಾನವನಿತ್ತು\nಸಾಧುಗಳ ಒಳಗಿಟ್ಟು ಮೋದ ಕೊಡು ಸರ್ವದ ||ಎನ್ನ||\n\nಅನ್ಯರನು ಭಜಿಸದಲೆ ನಿನ್ನನೆ ಸ್ತುತಿಸುತ ನಿನ್ನ ಚಿಹ್ನೆಗಳ ಧರಿಸಿ ನಿನ್ನವರವನೆನಿಸಿ ನಿನ್ನ ನಾಮೋಚ್ಚರಿಸಿ ನಿನ್ನಿಂದ ಉಪಜೀವಿಸಿ ಅನ್ನ ಆರೋಗ್ಯಕ್ಕೆ ಅಲ್ಪಜೀವಿಗಳಿಗೆ ಇನ್ನು ಅಲ್ಲರಿಯಬೇಕೆ ನಿನ್ನ ಸಂಕಲ್ಪ ಭಕ್ತರಪೋಷಕನೆಂಬ ಘನ್ನ ಬಿರುದನ್ನು ಉಳುಹೊ ಸಲಹೊ  ||ಎನ್ನ||\n\nನಿನ್ನವರಲಿ ಇವಗೆ ಇನ್ನು ರತಿಯನು ಕಂಡು\nನಿನ್ನವನೆಂದು ಅರಿದೂ\nನಿನ್ನ ನಾ ಪ್ರಾರ್ಥಿಸಿದೆ ಅನ್ಯರಿಗೆ ಅಲ್ಪರಿಯೆ\nಎನ್ನ ಪಾಲಿಸುವ ದೊರೆಯೇ\nಎನ್ನ ಮಾತಲ್ಲವಿದು ಎನ್ನ ಹಿರಿಯರ ಮಾತು\nಮನ್ನಿಸಬೇಕು ಕರುಣಿ\nಅನಂತಗುಣಪೂರ್ಣಗೋಪಾಲವಿಠ್ಠಲನೇ\nಇನ್ನಿದನು ಪಾಲಿಸಯ್ಯಾ ಜೀಯ  ||ಎನ್ನ||\n\n",english:"Enna binnapa kelu dhanvantri dayamaadu | sannavanu eva kevala banna badisuva rogavanu mochana | maadi chennagi paalisuvudu | vibhuve chennagi paalisuvudu ||\n\nAarogya aayushya aishvaryavembo I ee muruvidhavastugalu\nNaarayanana bhajakaraadavara saadhanake purnavaagippuvu\nGhora vyabhichaara paraninde para vittaapahaaramaadida doshadi\nDaridraraaguvaru muru vidhadindali kaarananu nine dushkarma pariharisuvudu hariye ||\n\nVasumatiya melinnu asura janare bahala vashavalla kaliya baadhe | bisilinda peeditavaada sasigalante shishugalu naavirpevo | asuraari ninna karunaamrutada malegaredu \\ kushaladali paalipuvudo | kesarinda kesara toledante karmadapathavu | asunaatha hariye poreyo swami ||\n\nAdivyaadigalu unmaada vibhrama naana baadhegoushadanu neene | he deva ninna karakalasha sudeyanu | eredu saadhugala santaisuve | moda padisuvi ninna saadhisuvarige | shubhodayamgalannu maadi | adharisi evage tava paada dhanyavanittu | sadhugala olagittu moda kodu sarvada ||\n\nAnyaranu bhajisadale ninnane stutisuta ninna cihnegala dharisi\nNinnavaranenisi ninna naamoccarisi ninninda upajivisi\nAnna aarogyakke alpa jivigalige innu aalpariyabeke\nNinna sankalpa bhaktara poshakanemba ghanna birudinnu uluho salaho ||\n\nNinnavarali evage ennu ratiyanu kandu | ninnavanendu aridu | nnna naa prartiside anyarige alpariye | enna paalisuva doreye | enna maatallavidu enna hiriyara maatu | mannisabeku karune ananta gunapoorna gopaalavithalane | ennidanu paalisayya jeeya ||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=EzmRwoq7qIA"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಎನ್ನ-ಬಿನ್ನಪ-ಕೇಳು-ಧನ್ವಂತ್ರಿ.json",
	rawData: "",
};

export { _internal, collection, data, id };
