const id = "ಎಲ್ಲಿ-ಮರೆಯಾದೆ-ವಿಠ್ಠಲಾ";
const collection = "bhajan";
const data = {kannada_title:"ಎಲ್ಲಿ ಮರೆಯಾದೆ ವಿಠ್ಠಲಾ",english_title:"Elli Mareyade Vittalaa",kannada:"ರಂಗಾ…..ವಿಠ್ಠಲಾ….\nರಂಗಾ….ಪಾಂಡುರಂಗ ಎಲ್ಲಿ ಮರೆಯಾದೇ….\nಪಾಂಡುರಂಗಾ…ಆ…ಏಕೆ ದೂರಾದೆ\n\nಎಲ್ಲಿ ಮರೆಯಾದೆ ವಿಠ್ಠಲಾ, ಏಕೆ ದೂರಾದೆ\nರಂಗ ಏಕೆ ದೂರಾದೆ ಎಲ್ಲಿ ಮರೆಯಾದೆ. …\n\nದೇವರ ದೇವ ಎಂಬುದ ಮರೆತೆ ಸೇವಕನಂತೆ ನನ್ನೆಡೆ ನಿಂತೆ ||2||\nಮಾಧವ ನಿನ್ನ ಮಾಯಾಜಾಲ ||2||\nಮಾನವ ನಾನು ತಿಳಿಯಲಿಲ್ಲ ವಿಠ್ಠಲಾ….ರಂಗಾ…\n||ಎಲ್ಲಿ ಮರೆಯಾದೆ||\n\nಸಾಧಿಸಿ ಹರಿಯ ಪ್ರೀತಿಯ ಒಲವು ಪೂಜಿಸಿದಂತ ಪೂಜ್ಯರು ನೀವು ||2||\nಬಲ್ಲಿರಿ ಅವನ ಅಂತರಂಗ ||2||\nಎಲ್ಲಿಹ ಹೇಳಿ ಪಾಂಡುರಂಗ ವಿಠ್ಠಲಾ. …ರಂಗಾ…\n||ಎಲ್ಲಿ ಮರೆಯಾದೆ||\n\nಎತ್ತೆತ್ತಲೀಗ ಕಗ್ಗತ್ತಲಾಯಿತು ಗೊತ್ತಾಗದಾಯಿತೆ ವಿಠ್ಠಲಾ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\n\nಮುತ್ತಂತ ನಿನ್ನ ಕೈ ತುತ್ತ ತಿನ್ನೊ ಹೊತ್ತಾಯಿತು ಬಾರೊ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\n\nಬತ್ತಿರೊ ಬದುಕ , ಎತ್ತಿಸಿ ನಿ ಬೆಳಕ ,ಹತ್ತಿಸಿ ನೀ ಕಾಯೊ ವಿಠ್ಠಲಾ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\n\nಹೆತ್ತವಳಂತೆ ನೀನೆತ್ತಿಕೊಂಡು, ನನ್ನತ್ತ ನೋಡೊ ವಿಠ್ಠಲಾ. ..\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\n\nನೀ ಎನ್ನ ಧನ, ನೀ ಎನ್ನ ಮನ , ನೀ ಪ್ರಾಣ ವಿಠ್ಠಲ\nಎನ್ನಾತ್ಮ ನಿಧಿಯೇ ಮುಖ ತೋರೊ ದೊರೆಯೆ||2||\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈ ಜೈ ವಿಠ್ಠಲ………..\n\nರಂಗಾ….ವಿಠ್ಠಲಾ. …..ರಂಗಾ….\n\n",english:"Ranga..      Vittalaa..      Ranga..\nPaanduranga..\nElli Mareyade Paanduranga..a..\nEke Dooraade\n\nElli Mareyade Vittalaa\nYeke Dooraade\nRanga Yeke Dooraade\nElli Mareyade ||\n\nDevara deva embuda marethe\nsevakananthe nannede ninthe ||2||\nMaadhava ninna maayaajaala ||2||\nMaanava naanu thiliyalilla\nVittalaa.. Ranga.. ||Elli Mareyade||\n\nSaadisi hariya preethiya ilavu\npoojisidantha poojyaru neevu||2||\nBalliri avana antharanga ||2||\nElliha heli paanduranga\nVittala.. Ranga.. ||Elli Mareyade||\n\nEttettaleega kaggatthalaaytu gottaagadaayte vittalaa\nVittalaa Vittalaajai Jai Vittalaa\n\nMuttantha ninnakaitutta thinno\nhotaaytu baaro vittalaa\nVittalaa Vittalaajai Jai Vittalaa\n\nBattiro badukaetti nee belaka\nhattisi kaayo vittalaa\nVittalaa Vittalaa Jai Jai Vittalaa\n\nHettavalante neenettikondu\nnannattanodo vittalaa\nVittalaa Vittalaajai Jai Vittalaa\n\nNee enna dhana nee enna mana nee praana vittalaa\nennatma nidhiye mukha thoro doreye\nennatma nidhiye mukha thoro doreye\nVittalaa Vittalaajai Jai Vittalaa |3|\nVittalaa Vittalaajai Jai Vittalaa |3|\nVittalaa Vittalaajai Jai Vittalaa…\n\nRanga.. Vittala.. Ranga..\nVittalaa Vittalaajai Jai Vittalaa..\n\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=qJo3ecB_abY"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಎಲ್ಲಿ-ಮರೆಯಾದೆ-ವಿಠ್ಠಲಾ.json",
	rawData: "",
};

export { _internal, collection, data, id };
