const id = "ಎದುರಾರೊ-ಗುರುವೆ-ಸಮರಾರೊ";
const collection = "bhajan";
const data = {kannada_title:"ಎದುರಾರೊ ಗುರುವೆ ಸಮರಾರೊ",english_title:"Eduraro guruve samanaro",kannada:"ಎದುರಾರೊ ಗುರುವೆ ಸಮರಾರೊ ||pa||\n\nಮದನ ಗೋಪಾಲನ ಪ್ರಿಯ ಜಯರಾಯ ||a.pa||\n\nಕಡು ಗರ್ಜಿಸುವ ಕೇಸರಿಯಂತೆ ನಿಮ್ಮ ವಾದ\nಗಡಣೆಯ ಕೇಳುತ ನುಡಿ ಮುಂದೋಡದೆ\nಗಡ ಗಡ ನಡಗುತ ಮಾಯ್ಗೋಮಾಯ್ಗಳು\nಅಡವಿಯೊಳಡಗೋರು ನಿಮ್ಮ ಭೀತಿಯಲಿ||1||\n\nಕುಟಿಲ ಮತಗಳೆಂಬೋ ಚಟುಲಂಧಕಾರಕ್ಕೆ\nಪಟುತರ ತತ್ತ್ವಪ್ರಕಾಶಿಕೆಯೆಂತೆಂಬ\nಚಟುಲಾತಪದಿಂದ ಖಂಡಿಸಿ ತೇಜೋ\nತ್ಕಟದಿ ಮೆರೆದೆ ಬುಧಕಟಕಾಬ್ಜ ಮಿತ್ರ ||2||\n\nಅಮಿತ ದ್ವಿಜಾವಳಿ ಕುಮುದಗಳರಳಿಸಿ\nವಿಮತರ ಮುಖ ಕಮಲಂಗಳ ಬಾಡಿಸಿ\nಸ್ವಮತರ ಹೃತ್ಸಂತಾಪಗಳೋಡಿಸಿ\nವಿಮಲ ಸುಕೀರ್ತಿಯ ಪಡೆದೆಯೋ ಚಂದ್ರ ||3||\n\nವೇದಶಾಸ್ತ್ರಗಳೆಂಬೊ ಶೃಂಗಗಳಿಂದ ಸು\nಧಾದಿ ಗ್ರಂಥಗಳೆಂಬೊ ಸ್ತನದಿಂದೊಪ್ಪುತ ತತ್ತ್ವ\nಬೋಧನೆಯೆಂಬ ದುಗ್ದ ಶಿಷ್ಯವತ್ಸಂಗಳಿಗೆ\nಆದರದಲಿ ಕೊಟ್ಟ ಯತಿಸುರಧೇನು ||4||\n\nವ್ಯಾಸಸೂತ್ರಗಳೆಂಬ ಮಂದರವನು ವೇದ\nರಾಶಿಯೆಂಬ ವಾರಾಶಿಯೊಳಿಟ್ಟು\nಶ್ರೀ ಸರ್ವಜ್ನರ ವಾಕ್ಯಪಾಶದಿ ಸುತ್ತಿ\nಭಾಸುರ ನ್ಯಾ ಸುಧಾ ಪಡೆದೆ ಯತೀಂದ್ರ||5||\n\nವನಜನಾಭನ ಗುಣಮಣಿಗಳ ಸರ್ವಜ್ನ-\nಮುನಿಕೃತ ಗ್ರಂಥಗಳವನಿಯೊಳಡಗೆ ಸ-\nಜ್ಜನರಿಗೆ ಟೀಕಾಂಜನದಿಂದ ತೋರಿಸಿ\nಘನ ಸುಖಸಾಧನ ಮಾಡಿದ್ಯೋ ಧೀರ||6||\n\nಅರ್ಥಿಮಂದಾರ ವೇದಾರ್ಥವಿಚಾರ ಸ-\nಮರ್ಥ ಶ್ರೀ ಕೃಷ್ಣ ಪಾದಾಂಬುಜಲೋಲ ಪ್ರ-\nತ್ಯರ್ಥಿ ಮತ್ತೇಭಕಂಠೀರವ ಕ್ಷೋಭ್ಯ-\nತೀರ್ಥ ಕರಜ ಜಯತೀರ್ಥ ಯತೀಂದ್ರ ||7||\n\n",english:"Lyrics  in English\n\nEduraro guruve samanaro || pa ||\nMadanagopalana priya jayaraya || a.pa |\n\nKadugarjisuva kesariyamte nimma vada\nGadaneya keluta nudi mundodade\nGada gada naduguta maygo maygalu\nAdaviyo ladagoru nimma bitiyali || 1 ||\n\nKutilamatagalembo chatulandhakarakke\nPatutara tattvaprakasi kentemba\nChatula tapadinda kandisi tejot\nKatadi merede budhakatakabjamitra || 2 ||\n\nAmitad vijavalikumuda galarasi\nVimatara mukakamalangala badisi\nSvamatara hrutsantapagalodisi\nVimalasukirtiya padedeyo chandra || 3 ||\n\nVedasastragalembo srumgagalimda su\nDhadigramthagalembo stanadimdopputa tattva\nBodheyemba dugdha sishyavatsamgalige\nAdaradali kotta yatisuradhenu || 4 ||\n\nVyasasutragalemba mandaravanu veda\nRasiyemba varasiyolagittu |\nSrisarvaj~jara vakyapasadi sutti\nBasuranyayasudha padeda yatindra || 5 ||\n\nVanajanabana gunamanigalu sarvaj~ja\nMunikruta granthagal avaniyoladagire sa\nJjanarige tikanjanadinda torisi\nGanasukasadhana madidyo dhira || 6 ||\n\nArthimandara vedarthavicara sa\nMartha srikrushna padambujalola pra\nTyarthi mattebakanthirav akshobya\nTirthakaraja jayatirthayatimndra || 7 ||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=KNI5MzsXA6c"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಎದುರಾರೊ-ಗುರುವೆ-ಸಮರಾರೊ.json",
	rawData: "",
};

export { _internal, collection, data, id };
