const id = "ಎದ್ದೇಳು-ಮಂಜುನಾಥ";
const collection = "bhajan";
const data = {kannada_title:"ಎದ್ದೇಳು ಮಂಜುನಾಥ",english_title:" Eddelu manjunatha",kannada:"ಎದ್ದೇಳು……\nಎದ್ದೇಳು ಮಂಜುನಾಥ ಏಳು ಬೆಳಗಾಯಿತು…\nಧರ್ಮ ದೇವತೆಗಳು ನಿನ್ನ ದರುಶನಕೆ ಕಾದಿಹರು..\nಧರ್ಮ ದೇವತೆಗಳು ನಿನ್ನ ದರುಶನಕೆ ಕಾದಿಹರು..\nಅಣ್ಣಪ್ಪ ಸ್ವಾಮಿಯೂ ನಿನ್ನ ಆಜ್ಞೆಗೆ ನಿಂತಿಹನು\nಎದ್ದೇಳು ಮಂಜುನಾಥ ಎದ್ದೇಳು…||\n\nಮುನಿಗಣಂಗಳು ಸ್ತೋತ್ರ ಮಾಡುತಿಹರು…………\nದೇವಾದಿದೇವತೆಗಳೂ ನಿನ್ನ ದರುಶನಕೇ ಕಾದಿಹರು …\nಎದ್ದೇಳು ಮಂಜುನಾಥ ಎದ್ದೇಳು…||\n\nಮೃಗರಾಜನೂ ನಿನ್ನ ದರುಶನಕೇ ಬಂದಿಹನು…\nಮೃಗರಾಜನೂ ನಿನ್ನ ದರುಶನಕೇ ಬಂದಿಹನು…\nಗಜರಾಜನು ನಿನಗೇ ಚಾಮರವ ಬೀಸುತಿಹನು….\nಗಜರಾಜನು ನಿನಗೇ ಚಾಮರವ ಬೀಸುತಿಹನು….\nನಿನ್ನ ಆಭರಣಗಳಿಗಾಗಿ ಆದಿಶೇಷನೂ……..\nನಿನ್ನ ಆಭರಣಗಳಿಗಾಗಿ ಆದಿಶೇಷನೂ…… ನಿನ್ನ ಸೇರಲೂ ಕಾತರಿಸುತಿಹನು\nಎದ್ದೇಳು ಮಂಜುನಾಥ ಎದ್ದೇಳು……||\n\nಕೋಗಿಲೆಗಳೂ, ಕೋಗಿಲೆಗಳೂ, ಸುಸ್ವರದಿ ಗಾನಮೊಳಗುತಿಹವೂ…………\nಸರಿಗಪದ… ಸದಪಗಪ…. ದಪಗಸರಿ… ಗರಿಸದಸ…..\nಕೋಗಿಲೆಗಳು ಸುಸ್ವರದಿ ಗಾನ ಮೊಳಗುತಿಹವು….\nಸವಿಮಾತಿನ ಅರಗಿಳಿಯೂ ನಿನ್ನ ಧ್ಯಾನದಲಿಹುದೂ …….\nಪಾರಿವಾಳಗಳು ನಿನ್ನ ದರುಶನಕೆ ಕಾದಿಹವೂ………\nಹೆಗ್ಗಡೆಯ ದಂಪತಿಗಳು ನಿನ್ನಯ ಸೇವೆಗೆ ಕಾತರಿಸುತಿಹರು………..\nತಡವು ಏತಕೆ ಪ್ರಭುವೇ ದರುಶನವ ನೀಡೇಳು\nಎದ್ದೇಳು ಮಂಜುನಾಥ ಎದ್ದೇಳು……||\n\nನೇತ್ರಾವತಿಯಲ್ಲಿ ಮಿಂದು ಜನರೂ ವಿಧವಿಧದೀ ಸೇವೆಗಳ ಗೈಯುತಿಹರೂ…….\nನೇತ್ರಾವತಿಯಲ್ಲಿ ಮಿಂದು ಜನರೂ ವಿಧವಿಧದೀ ಸೇವೆಗಳ ಗೈಯುತಿಹರೂ…….\nಸರ್ವರಕ್ಷಕ… ಸರ್ವರಕ್ಷಕನು ನೀನು ದರುಶನವಾ ನೀಡೇಳೂ ……….\nವಿಪ್ರರೆಲ್ಲರೂ ಕೂಡಿ ವೇದಘೋಷಿಸುತಿಹರೂ………..\nವಿಪ್ರರೆಲ್ಲರೂ ಕೂಡಿ ವೇದಘೋಷಿಸುತಿಹರೂ………..\nಮೋಕ್ಷವನು ನೀಡೇಳು….\nರವಿಯ ಕಿರಣವೂ ನಿನ್ನ ಮಹಾದ್ವಾರವನು ಬೆಳಗುತಿಹುದೂ…\nದರುಶನವ ನೀಡೇಳೂ…… ಏಳೂ ಬೆಳಗಾಯಿತು ….ಏಳು ಬೆಳಗಾಯಿತು …….\nಎದ್ದೇಳು ಮಂಜುನಾಥಾ ಎದ್ದೇಳು……….. ಎದ್ದೇಳು ||\n\n",english:"lyrics of an evergreen melodious devotional song by Shri P B Sreenivas , dedicated to Lord Manjunatha\n\nEddelu Manjunatha Yelu Belagaayithu\nEddelu Manjunatha Yelu Belagaayithu\nDharma Devathegalu Ninna Darushanake Kaadiharu |\nAnnappa Swamiyu Ninna Aagnege Ninthihanu ||\nEddelu Manjunatha Eddelu..\n\nMuniganangalu Sthothra Maaduthiharu |2|\nDevaadi Devathegalu Ninna Darushanke Kaadiharu\nEddelu Manjunatha.. Eddelu..||\n\nMruga Rajanu Ninna Darushanke Bandihanu |2|\nGaja Rajanu Ninage Chaamarava Beesuthihanu |2|\nGaj\nNinna Abharanagaligaagi Aadhi Sheshanu..\nNinna Abharanagaligaagi Aadhi Sheshanu..\nNinna Seralu Kaatharisuthihanu..\nEddelu Manjunatha Eddelu..||\n\nKogilegalu.. Kogilegalu..\nSuswaradi.. Gaana Molaguthihavu\nSarigapada.. Sadapagapa.. Dapagasari.. Garisadasa..\nKogilegalu Suswaradi Gaana Molaguthihavu\nSavi Maathina Aragiliyu Ninna Dhyanadalihudu\nPaarivaalagalu Ninna Darushanake Kaadihavu\nHeggadeya Dampathigalu Ninnaya Sevege Kaatharisuthiharu\nTadavu Yethake Prabhuve\nTadavu Yethake Prabhuve Darushanva Needelu\nEddelu Manjunatha Eddelu..||\n\nNethravathiyalli Mindu Janaru..\nVidha Vidhadi Sevegala Gayyuthiharu\nNethravathiyalli Mindu Janaru\nVidha Vidhadi Sevegala Gayyuthiharu\nSarva Rakshaka.. Sarva Rakshakanu Neenu |\nDarushanava Needelu..\nViprarellaru Koodi Veda Ghoshisuthiharu\nViprarellaru Koodi Veda Ghoshisuthiharu\nMokshavanu Needelu\nRaviya Kiranavu Ninna Mahadwaravanu Belaguthihudu\nDarushanva Needelu.. Yelu Belagaayithu.. Yelu Belagaayithu..\nEddelu Manjunatha.. Eddelu..\nEddelu..||\n\n",meta:"",tags:[],media:"https://www.youtube.com/watch?v=GsprYdmUhoU"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಎದ್ದೇಳು-ಮಂಜುನಾಥ.json",
	rawData: "",
};

export { _internal, collection, data, id };
