const id = "ಎನ್ನಂಥ-ಭಕ್ತರು-ಅನಂತ";
const collection = "bhajan";
const data = {kannada_title:"ಎನ್ನಂಥ ಭಕ್ತರು ಅನಂತ",english_title:" Enanta bhaktaru anantha",kannada:"ಎನ್ನಂಥ ಭಕ್ತರು ಅನಂತ ನಿನಗಿಹರು ನಿನ್ನಂಥ ಸ್ವಾಮಿ ಎನಗಿಲ್ಲ\nನಿನ್ನಂಥ ಸ್ವಾಮಿ ಎನಗಿಲ್ಲ ಅದರಿಂದ ಭಿನ್ನೈಪೆ ನಿನ್ನ ಸಲಹೆಂದು || ಪ ||\n\nಪತಿತ ನಾನಾದರೂ ಪತಿತ ಪಾವನ ನೀನು ರತಿನಾಥ ಜನಕ ನಗಪಾಣಿ\nರತಿನಾಥ ಜನಕ ನಗಪಾಣಿ ನೀನಿರಲು ಇತರ ಚಿಂತ್ಯಾಕೊ ಎನಗಿನ್ನು || 1 ||\n\nಮನಗೊಳಗೆ ನೀನಿದ್ದು ಮನವೆಂದೆನಿಸಿಕೊಂಡು ಮನದ ವೃತಿಗಳನ್ನ ಸೃಜಿಸುವಿ\nಮನದ ವೃತ್ತಿಗಳನ್ನ ಸೃಜಿಸುವಿ ಸಂಕರ್ಷಣನೆ ನಿನ್ನ ಕರುಣಕ್ಕೆ ಎಣೆಗಾಣೆ || 2 ||\n\nನಾನಾ ಪದಾರ್ಥದೊಳು ನಾನಾ ಪ್ರಕಾರದಲ್ಲಿ ನೀನಿದ್ದು ಜಗವ ನಡೆಸುವಿ\nನೀನಿದ್ದು ಜಗವ ನಡೆಸುವಿ ಹರಿ ನೀನೆ ನಾನೆಂಬೋ ನನಗೆ ಗತಿಯುಂಟೆ || 3 ||\n\nಎನ್ನಪ್ಪ ಎನ್ನಮ್ಮ ಎನ್ನಯ್ಯ ಎನ್ನಣ್ಣ ಎನ್ನರಸ ಎನ್ನ ಕುಲದೈವ\nಎನ್ನರಸ ಎನ್ನ ಕುಲದೈವ ಇಹಪರದಿ ಎನ್ನ ಬಿಟ್ಟಗಲದೇ ಇರು ಕಂಡ್ಯ || 4 ||\n\nಏಸೇಸು ಜನ್ಮದಲಿ ದಾಸನಾ ನಿನಗಯ್ಯ ಈಶ ನೀನೆಂಬೋ ನುಡಿಸಿದ್ಧ\nಈಶ ನೀನೆಂಬೋ ನುಡಿಸಿದ್ಧ ವಾಗಿರಲುದಾಸೀನ ಮಾಡಲುಚಿತಲ್ಲ || 5 ||\n\nಆಶೆಯೊಂದುಂಟು ಸರ್ವೇಶಾ ವಿಜ್ಞಾಪಿಸುವೆ ವಿಶ್ವಂಭರಾಭಾಗ್ಯ ಸತಿಮೋಹ\nವಿಶ್ವಂಭರಾಭಾಗ್ಯ ಸತಿಮೋಹ ತಪ್ಪಿಸಿ ನೀ ಸಲಹಬೇಕೋ ದಯದಿಂದ || 6 ||\n\nಅನಾಥ ಬಂಧು\nಜಗನ್ನಾಥ ವಿಠ್ಠಲ\nಪ್ರಪನ್ನ ಪರಿಪಾಲ ಮಾಲೋಲ\nಪ್ರಪನ್ನ ಪರಿಪಾಲ ಮಾಲೋಲ ಅರಿ ಪಾಂಚಜನ್ಯ ಧೃತಪಾಣಿ ಸಲಹೆಮ್ಮ || 7 ||\n\n",english:"Ennantha bhaktaru ananta ninagiharu ninna swaami enagilla\nninnantha swaami enagilla adarinda bhinnaipe ninna salahendu || pa ||\n\nPatita naanaadaru patita paavana neenu ratinaatha janaka nagapaani\nRatinaatha janaka nagapaani neeniralu itara chintyaako enaginnu || 1 ||\n\nManadolage neeniddu manavendenisikondu manada vruttigalanna srujisuvi\nManada vruttigalanna srujisuvi Sankarshanane ninna karunakke enegaane || 2 ||\n\nNaanaa padaarthadolu naanaa prakadalli neenidu jagava nadesuvi\nNeeniddu jagava nadesuvi Hari neene naanembo nanage gatiyunte || 3 ||\n\nEnnappa ennamma ennayya ennanna ennarasa enna kuladaiva\nEnnarasa enna kuladaiva ihaparadi enna bittagalade iru kandya || 4 ||\n\nYesesu janmadali daasanaa ninagayya eesha neenembo nudisiddha\nEesha neenembo nudisiddha vaagiraludaaseena maadaluchitalla || 5 ||\n\nAasheyonduntu sarveshaa vijnaapisuve vishwambharaabhaagya satimoha\nVishwambharaabhaagya satimoha tappisi nee salahabeko dayadinda || 6 ||\n\nAnaatha bandhu\nJagannatha Vittala\nprapanna paripaala maalola\nPrapanna paripaala maalola ari paanchajanya dhrutapaani salahemma || 7 ||\n\nYou can listen to the song here\n\n",meta:"",tags:["krishna","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=nz5eD5e3T6Y"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಎನ್ನಂಥ-ಭಕ್ತರು-ಅನಂತ.json",
	rawData: "",
};

export { _internal, collection, data, id };
