const id = "ಎಂಥ-ಅಂದ-ಎಂಥ-ಚಂದ";
const collection = "bhajan";
const data = {kannada_title:"ಎಂಥ ಅಂದ ಎಂಥ ಚಂದ",english_title:" Entha anda entha chanda",kannada:"ಗಾಯಕರು : ಡಾ. ರಾಜ್ ಕುಮಾರ್.                         ಸಾಹಿತ್ಯ : ಚಿ. ಉದಯ್ ಶಂಕರ್\n\nಎಂಥ ಅಂದ ಎಂಥ ಚಂದ ಶಾರದಮ್ಮ ನೀನು\nಎಂಥ ಅಂದ ಎಂಥ ಚಂದ ಶಾರದಮ್ಮ ನಿನ್ನ\nನೋಡಲೆರಡು ಕಣ್ಣು ನನಗೆ ಸಾಲದಮ್ಮ ||\n\nಎಂಥ ಅಂದ ಎಂಥ ಚಂದ ಶಾರದಮ್ಮ ನಿನ್ನ\nನೋಡಲೆರಡು ಕಣ್ಣು ನನಗೆ ಸಾಲದಮ್ಮ ||\n\nಇನ್ನು ಇನ್ನು ನೋಡುವಾಸೆ ತುಂಬಿತಮ್ಮ\nಇನ್ನು ಕೋಟಿ ಜನುಮ ಬರಲಿ ನನಗೆ ಸಾಲದಮ್ಮ||ಇನ್ನು||\nಅಭಯ ಹಸ್ತ ನೋಡಿ ಜೀವ ಕುಣಿಯಿತಮ್ಮ\nಅಭಯ ಹಸ್ತ ನೋಡಿ ಜೀವ ಕುಣಿಯಿತಮ್ಮ\nನಿನ್ನ ಪಾದಕಮಲದಲ್ಲಿ ಶಿರವು ಬಾಗಿತಮ್ಮ\nನಿನ್ನ ಪಾದಕಮಲದಲ್ಲಿ ಶಿರವು ಬಾಗಿತಮ್ಮ ||\n\nಎಂಥ ಶಕ್ತಿ ನಿನ್ನಲಿದೆಯೋ ಶಾರದಮ್ಮ\nನಿನ್ನ ನೋಡಿ ಹಾಡೋ ಆಸೆ ಬಂದಿತಮ್ಮ\nಎಂಥ ಶಕ್ತಿ ನಿನ್ನಲಿದೆಯೋ ಶಾರದಮ್ಮ ||\nನಿನ್ನ ನೋಡಿ ಹಾಡೋ ಆಸೆ ಬಂದಿತಮ್ಮ\nರತ್ನದಂಥ ಮಾತುಗಳನೆ ಆಡಿಸಮ್ಮ\nಒಳ್ಳೆ ರತ್ನದಂಥ ಮಾತುಗಳನೆ ಆಡಿಸಮ್ಮ ||\nರಾಗ ಭಾವ ಭಕ್ತಿ ತುಂಬಿ ಹಾಡಿಸಮ್ಮ\nಒಳ್ಳೆ ರಾಗ ಭಾವ ಭಕ್ತಿ ತುಂಬಿ ಹಾಡಿಸಮ್ಮ ||\n\nಅಲ್ಲಿ ಇಲ್ಲಿ ಓಡೋ ಮನಸು ನನ್ನದಮ್ಮಾ\nಬೇಗ ಬಂದು ನೆಲೆಸು ಅಲ್ಲಿ ಶಾರದಮ್ಮ || ಅಲ್ಲಿ ||\nಬೇರೆ ಏನು ಬೇಕು ಎಂದು ಕೇಳೇನಮ್ಮ ನಿನ್ನ\nಬೇರೆ ಏನು ಬೇಕು ಎಂದು ಕೇಳೆನಮ್ಮ ನಿನ್ನ\nವೀಣೆ ತಂತಿ ಮಾಡಿ ನುಡಿಸು ಶಾರದಮ್ಮ\nನನ್ನ ವೀಣೆ ತಂತಿ ಮಾಡಿ ನುಡಿಸು ಶಾರದಮ್ಮ ||ನನ್ನ ||\n\n",english:"This song is dedicated to Goddess Sharadamba sung by the veteran, Karnataka rathna Dr. Rajkumar, lyrics is by Shri.Chi Udayashankar… This song describes the beauty of Goddess Sharadamba, who is the goddess of wisdom and knowledge in Hinduism..\n\nEntha anda entha chanda Sharadamma neenu\nEntha anda entha chanda Sharadamma ninna\nninna nodaleradu kannu nanage saaladamma||\n\nEntha anda entha chanda Sharadamma ninna\nninna nodaleradu kannu nanage saaladamma||\n\nInnu innu noduvaase tumbithamma\ninnu koti januma barali nanage saaladamma||Innu||\nAbhaya hasta nodi jeeva kuniyitamma\nAbhaya hasta nodi jeeva kuniyitamma\nninna paadakamaladalli shiravu baagitamma\nninna paadakamaladalli shiravu baagitamma\n\nEntha anda entha chanda sharadamma neenu\nEntha anda entha chanda Sharadamma ninna\nninna nodaleradu kannu nanage saaladamma\n\nEntha shakti ninnalideyo Shaaradamma\nninna nodi haado aase banditamma\nEntha shakti ninnalideyo Shaaradamma ||\nninna nodi haado aase banditamma\nrathnadanta maatugalane aadisamma\nolle rathnadanta maatugalane aadisamma ||\nraaga bhaava bhakti tumbi haadisamma\nolle raaga bhaava bhakti tumbi haadisamma||\n\nAlli illi vodo manasu nannadamma\nbega bandu nelesu alli sharadamma|| Alli ||\nbere yenu beku endu kelenamma ninna\nbere yenu beku endu kelenamma ninna\nveene tanti maadi nudisu Sharadamma\nnanna veene tanti maadi nudisu Sharadamma||nanna||\n\n",meta:"",tags:["saraswati","kannada devotional song"],media:"https://www.youtube.com/watch?v=I0japj6Irfk"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಎಂಥ-ಅಂದ-ಎಂಥ-ಚಂದ.json",
	rawData: "",
};

export { _internal, collection, data, id };
