const id = "ಏಳೇಳು-ಶರಧಿಯು-ಏಕವಾಗಿದೆ-ಕಣ್ಡ್ಯ-ಹೇಗೆ";
const collection = "bhajan";
const data = {kannada_title:"ಏಳೇಳು ಶರಧಿಯು ಏಕವಾಗಿದೆ ಕಣ್ಡ್ಯ ಹೇಗೆ",english_title:" Elellu sharadhiyu ekavaagide kandya",kannada:"ಏಳೇಳು ಶರಧಿಯು ಏಕವಾಗಿದೆ ಕಣ್ಡ್ಯ ಹೇಗೆ ಬಂದೆ ಹೇಳೋ ಕೋತಿ\nಏಳು ಶರಧಿಯು ಎನಗೆ ಏಳು ಕಾಲುವೆಯು ತುಳಿ ಲಂಘಿ ಸಿ ಬಂದೆ ಭೂತ ||\n\nಏಳು ಸಮುದ್ರದೊಳಿರುವ ಮಕಾರಿ ಮತ್ಸ್ಯವು ಹೇಗೆ ಬಿಟ್ಟರು ಹೇಳೋ ಕೋತಿ\nಏಳು ಸಮುದ್ರದ ಮಕಾರಿ ಮತ್ಸ್ಯದ ಕೂಡೆ ಮಾತಾಡಿ ಬಂದೆನೋ ಭೂತ ||1||\nಲಂಕಾ  ದ್ವಾರದೊಳೊಬ್ಬ ಲಂಕಿಣಿ ಇರುವಳು ಹೇಗೆ ಬಿಟ್ಟಳು ಹೇಳೋ ಕೋತಿ\nಲಂಕಿಣಿಯನು  ಕೊಂದು  ಶಂಕೆಯಿಲ್ಲದೆ ನಾನು ಬಿಂಕದಿಂದಲಿ ಬಂದೆ ಭೂತ ||2||\nಕೊಂಬೆ ಕೊಂಬೆಗೆ ಕೋಟಿ ಮಂದಿ ರಕ್ಶಸರಿರೆ ಹೇಗೆ ಬಿಟ್ಟರು ಪೇಳು ಹೇಳೋ ಕೋತಿ\nಕೊಂಬೆ ಕ್ಕೊಂಬೆಗೆ ಕೋಟಿ ಮಂದಿ ರಾಕ್ಷಷರನ್ನೂ  ಕೊಂದ  ಬಂದೆನೋ ಭೂತ ||3||\n\nಯಾವೂರೋ ಎಲೋ ನೀನು ಯಾವ ಭೂಮಿಯೋ ನಿಂದು ಯಾಕೆ ಬಂದೆ ಹೇಳೋ ಕೋತಿ\nಯಾವ ವನದೊಳಗೆ ಜಾನಕಿ ದೇವಿ ಇದ್ದಾಳೆ ಅವಳೇ ನೋಡ ಬಂದ ಭೂತ ||4||\n\nದಕ್ಶಿಣಪುರಿ  ಇಕ್ನ್ನಾವರಿಗಲ್ಲದೆ  ದ್ರಾಕ್ಶಾದ್ಯರಿಗಳವಲ್ಲ ಕೋತಿ\nಪಕ್ಶಿ ಧ್ವಜ ರಾಮನ ಅಪ್ಪಣೆಯೆನಗಿಲ್ಲ ಈ ಕ್ಶಣ ತಪ್ಪಿಸಿ ಕೊಂಡೆ  ಭೂತ  ||5||\nದೂತನಗಿಹೆ ಎನ್ನ ಕೈಯೊಳು ಸಿಕ್ಕಿಹೆ ಕೋಪವಿನೇತಕ್ಕೊ ಕೋತಿ\nನಾ ತಾಳಿ ಕೊಂಡಿಹನು  ಈ ಕ್ಷಣದಿ  ಲಂಕೆ ನಿರ್ಧೂಮವನು ಮಲ್ಪೆ ಭೂತ ||6||\nನಿಮ್ಮಂದ ದಾಸರು ನಿಮ್ಮರಸನ ಬಳಿ ಎಶ್ಟು ಮನ್ದಿದ್ದಾರೋ ಕೋತಿ\nನನ್ನಂಥ ದಾಸರು ನಿನ್ನಂಥ ಹೇಡಿಗಳು ಕೋಟ್ಯಾನು ಕೋಟಿಯೊ ಭೂತ ||7||\n\nಎಲ್ಲಿಂದ ನೀ ಬಂದೆ ಏತಕ್ಕೆಲ್ಳರ ಕೊಂದೆ ಯವರಸಿನ ಬಂಟ  ಕೋತಿ\nಎಲ್ವಯೋ-ಧ್ಯಾಪುರದರಾಸು ಜಾನಕೀಪತಿ ರಾಮಚಂದ್ರನ ಬಂಟ  ಭೂತ ||8||\n\nಸಿರಿ ರಾಮಚಂದ್ರನು  ನಿನ್ನರಸನಾದರೆ ಆತ ಮುನ್ನಾರು  ಹೇಳೋ ಕೋತಿ\nಹಿರಣ್ಯಕನನು ಸಿರಿ  ಪ್ರಹ್ಲಾದ ಗೋಲಿದ ಶ್ರೀ\nಪುರಂದರ ವಿಠ್ಠಲ\nನು  ಭೂತ ||9||\n\n",english:"Elellu sharadhiyu ekavaagide kandya hege bande helo koti |\nelu sharadhiyu enage elu kaluveyu tuli langhisi bande bhuta ||\n\nElu samudradoliruva makari matsyavu hege bittaru helo koti |\nelu samudrada makari matsyada koode maatadi bandeno bhuta ||1||\n\nLanka dwaradolobba lankini iruvalu hege bittalu helo koti |\nlankiniyanu kondu shankeyillade naanu binkadindali bande bhuta ||2||\n\nKombe kombege koti Mandi rakkasarire hege bittaru pelu helu koti |\nkombe kombege koti Mandi rakshasarannu kondu bandeno bhuta ||3||\n\nYavuro elo neenu yava bhumiyo nindu yaake bande helo koti |\nyaava vanadolage janaki devi eddaale avale noda bande bhuta ||4||\n\nDakshinapuri iknaavarigallade draakshyaadyarigalavalla koti |\npakshi dhwaja Ramana appane yenagilla ee kshana tappisikonde bhuta ||5||\n\nDootanagihe enna kaiyolu sikkihe kopavinnetako koti |\nNaa taali kondihenu ee kshanadi lanke nirdhumavanu maalpe bhuta ||6||\n\nNimmanta dasaru nimmarasana Bali eshtu Mandi eddaro koti |\nnannanta dasaru ninnanta hedigalu kotyanu kotiyo bhuta ||7||\n\nEllinda nee bande ettakke ellara konde yuvarasana Banta koti |\nelliya ayodhyapuradarasu janakipati ramachandrana Banta bhuta ||8||\n\nSiri ramachandranu ninnarasanadare aata munnaru helo koti |\nhiranyakananu Siri prahladagolida Sri\npurandara vittala\nnu bhuta ||9||\n\n",meta:"",tags:["anjaneya hanuma","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=O1Oj_gWK2E0"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಏಳೇಳು-ಶರಧಿಯು-ಏಕವಾಗಿದೆ-ಕಣ್ಡ್ಯ-ಹೇಗೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
