const id = "ಏಸು-ಕಾಯಂಗಳ-ಕಳೆದು";
const collection = "bhajan";
const data = {kannada_title:"ಏಸು ಕಾಯಂಗಳ ಕಳೆದು",english_title:" Esu kayangala kaledu",kannada:"ಏಸು ಕಾಯಂಗಳ ಕಳೆದು ಎಂಬತ್ನಾಲ್ಕು ಲಕ್ಷ ಜೀವರಾಶಿಯನ್ನು ದಾಟಿ ಬಂದ ಈ ಶರೀರ |\nತಾನಲ್ಲ ತನ್ನದಲ್ಲ ಆಸೆ ಥರವಲ್ಲ ಮುಂದೆ ಬಾಹೋದಲ್ಲ\nದಾಸನಾಗು ವಿಶೇಷನಾಗು ದಾಸನಾಗು ಭವಪಾಶ ನೀಗು || ಪ ||\n\nಆಶ ಕ್ಲೇಶ ದೋಷವೆಂಬ ಅಬ್ಧಿಯೊಳು ಮುಳುಗಿ\nಯಮನ ಪಾಶಕ್ಕೊಳಗಾಗದೆ ನಿರ್ದೋಷಿಯಾಗು ಸಂತೋಷಿಯಾಗು |\n\nಕಾಶಿ ವಾರಣಾಸಿ ಕಂಚಿ ಕಾಳಹಸ್ತಿ ರಾಮೇಶ್ವರ\nಏಸು ದೇಶ ತಿರುಗಿದರೆ ಬಾಹೋದೇನೋ ಅಲ್ಲಿ ಹೋದೇನೋ |\nದೋಷ ನಾಶಿ ಕೃಷ್ಣೆ ಗಂಗೆ ಗೋದಾವರಿ ಭವನಾಶಿ |\nತುಂಗಭದ್ರೆ ಯಮುನೆ ವಾಸದಲ್ಲಿ ಉಪವಾಸದಲ್ಲಿ |\nಮೀಸಲಾಗಿ ಮಿಂದು ಜಪ ತಪ ಹೋಮ ನೇಮಗಳ |\nಏಸು ಬಾರಿ ಮಾಡಿದರು ಫಲವೇನು ಈ ಛಲವೇನು || 1 ||\nದಾಸನಾಗು ವಿಶೇಷನಾಗು ದಾಸನಾಗು ಭವಪಾಶ ನೀಗು\n\nಅಂದಿಗೋ ಇಂದಿಗೋ ಒಮ್ಮೆ ಸಿರಿಕಮಲೇಶನನ್ನು\nಒಂದು ಬಾರಿ ಯಾರೂ ಹಿಂದ ನೆನೆಯಲಿಲ್ಲ ಮನದಣಿಯಲಿಲ್ಲ |\nಬಂದು ಬಂದು ಭ್ರಮೆಗೊಂಡು ಮಾಯಾಮೋಹಕ್ಕೆ ಸಿಕ್ಕಿ\nನೊಂದು ಬೆಂದು ಒಂದರಿಂದ ಉಳಿಯಲಿಲ್ಲ ಬಂಧ ಕಳೆಯಲಿಲ್ಲ |\nಸಂದೇಹವ ಮಾಡದಿರು ಅರಿವು ಎಂಬ ದೀಪವಿಟ್ಟು\nಇಂದು ಕಂಡ್ಯ ದೇಹದಲ್ಲಿ ಪಿಂಡಾಂಡ ಹಾಗೆ ಬ್ರಹ್ಮಾಂಡ |\nಇಂದು ಹರಿಯ ಧ್ಯಾನವನ್ನು ಮಾಡಿ ವಿವೇಕದಿ\nಮುಕುಂದನಿಂದ ಮುಕ್ತಿ ಬೇಡು ಕಂಡ್ಯ ನೀ ನೋಡು ಕಂಡ್ಯ || 2 ||\nದಾಸನಾಗು ವಿಶೇಷನಾಗು ದಾಸನಾಗು ಭವಪಾಶ ನೀಗು\n\nನೂರು ಬಾರಿ ಶರಣು ಮಾಡಿ ನೀರ ಮುಳುಗಲ್ಯಾಕೆ\nಪರ ನಾರಿಯರ ನೋಟಕೆ ಗುರಿಯ ಮಾಡಿದಿ ಮನ ಸೆರೆಯ ಮಾಡಿದಿ |\nಸೂರೆಯೊಳು ಸೂರೆ ತುಂಬಿ ಮೇಲೆ ಹೂವಿನ ಹಾರ\nಗೀರು ಗಂಧ ಅಕ್ಷತೆಯ ಧರಿಸಿದಂತೆ ನೀ ಮೆರೆಸಿದಂತೆ |\nಗಾರುಢಿಯ ಮಾತ ಬಿಟ್ಟು ನಾದಬ್ರಹ್ಮನ ಪಿಡಿದು\nಸಾರಿ ಸೂರಿ ಮುಕ್ತಿಯನ್ನು ಶಮನದಿಂದ ಮತ್ತೆ ಸುಮನದಿಂದ |\nನಾರಾಯಣ ಅಚ್ಯುತ\nಅನಂತಾದಿ ಕೇಶವನ\nಸಾರಾಮೃತವನ್ನುಂಡು ಸುಖಿಸೋ ಲಂಡ ಜೀವವೇ ಎಲೇ ಭಂಡ ಜೀವವೇ || 3 ||\nದಾಸನಾಗು ವಿಶೇಷನಾಗು ದಾಸನಾಗು ಭವಪಾಶ ನೀಗು\n\n",english:"Composer : Sri Kanakadasaru\n\nEsu kayangala kaledu embhatnalku laksha jiva rashiyannu dati banda ee sharira ||\nTanalla tannadalla ase taravalla, munde bahodalla dasanagu visheshanagu ||\n\nAsha klesha doshavembha arthiyolu mulugi\nyamana pashakkolagagade nirdoshiyagu santoshiyagu ||\n\nKashi varanasi kan̄chi kalahasti rameshvara |\nesu desha tirugidaru bahudenu allig hodenu ||\nDosha nashi  krishna gange godavari bhava nashi |\ntungabhadre yamune vasadalli upavasadalli ||\nMisalagi mindu japa tapa homa nemagala |\nesu bari madidare phalavenu ee chalavenu  ||dasanag||\n\nAndigu indigu omme siri kamaleshanannu\nondu bari yaru hinda nenayalilla mana daniyalilla |\nBandu bandu bhramegondu maya mohakke sikki\nnondu bendu ondarinda uliyalilla dvandva kaliyallilla ||\nSandehava madidaru arivu embha deepavittu\nindu kandya dehadalli pindanda hage brahmanda ||\nIndu hariya dhyanavannu madi vivekadi\nmukundhaninda mukti bedukandya ni nodukandya || daasanaagu ||\n\nMurubari sharanu madi nera mulugallyake\npara nariyara notakke guriya madidi mana seleya madidi |\nSureyolu sure tumbi mele hoovina hara\ngiru gandha aksateya dharisidante ni maresidante ||\nGarudiya mata bittu nada brahmana pididu\nsari suri muktiyannu shamanadante matte samanadinda ||\nNarayana achyuta\nanantadi keshavana\nsaramrathavannu undu sukhiso landa jivave ele bhanda jivave ||daasanaagu ||\n\n………………………………….. by Putturu Narasimha Nayak\n\n",meta:"",tags:["krishna","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=8RXI7X5_Dik"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಏಸು-ಕಾಯಂಗಳ-ಕಳೆದು.json",
	rawData: "",
};

export { _internal, collection, data, id };
