const id = "ಏಕದಂತಂ-ಮಹಾಕಾಯಂ";
const collection = "bhajan";
const data = {kannada_title:"ಏಕದಂತಂ ಮಹಾಕಾಯಂ",english_title:"Ekadantam mahaakaayam",kannada:"ಏಕದಂತಂ ಮಹಾಕಾಯಂ ತಪ್ತಕಾಂಚನಸನ್ನಿಭಮ್ ।\nಲಂಬೋದರಂ ವಿಶಾಲಾಕ್ಷಮ್   ವಂದೇಹಂ   ಗಣನಾಯಕಮ್  ।।೧।।\n\nಮೌಂಜೀಕೃಷ್ಣಾಜಿನಧರಂ ನಾಗಯಜ್ಞೋಪವೀತಿನಮ್ ।\nಬಾಲೇಂದುವಿಲಸನ್ಮೌಲೀಂ ವಂದೇಹಂ ಗಣನಾಯಕಮ್।।೨।।\n\nಅಂಬಿಕಾಹೃದಯಾನಂದಮ್ ಮಾತೃಭಿಃ ಪರಿಪಾಲಿತಮ್ ।\nಭಕ್ತಪ್ರಿಯಂ  ಮದೋನ್ಮತ್ತಮ್   ವಂದೇಹಂ ಗಣನಾಯಕಮ್ ।।೩।।\n\nಚಿತ್ರರತ್ನವಿಚಿತ್ರಾಂಗಮ್  ಚಿತ್ರಮಾಲಾವಿಭೂಷಿತಮ್ ।\nಚಿತ್ರರೂಪಧರಮ್ ದೇವಂ ವಂದೇಹಂ ಗಣನಾಯಕಮ್ ।।೪।।\n\nಗಜವಕ್ತ್ರಂ  ಸುರಶ್ರೇಷ್ಠಂ ಕರ್ಣಚಾಮರಭೂಷಿತಮ್ ।\nಪಾಶಾಂಕುಶಧರಮ್ ದೇವಂ ವಂದೇಹಂ ಗಣನಾಯಕಮ್ ।।೫।।\n\nಮೂಷೀಕೋತ್ತಮಮಾರುಹ್ಯ  ದೇವಾಸುರಮಹಾಹವೇ ।\nಯೋದ್ಧುಕಾಮಂ  ಮಹಾವೀರ್ಯಮ್ ವಂದೇಹಂ ಗಣನಾಯಕಮ್ ।।೬।।\n\nಯಕ್ಷಕಿನ್ನರಗಂಧರ್ವ ಸಿದ್ಧವಿದ್ಯಾಧರೈಸ್ಸದಾ ।\nಸ್ತೂಯಮಾನಂ ಮಹಾತ್ಮಾನಂ ವಂದೇಹಂ ಗಣನಾಯಕಮ್ ।।೭।।\n\nಸರ್ವವಿಘ್ನಕರಂ  ದೇವಂ ಸರ್ವವಿಘ್ನವಿವರ್ಜಿತಮ್ ।\nಸರ್ವಸಿದ್ಧಿಪ್ರದಾತಾರಂ  ವಂದೇಹಂ ಗಣನಾಯಕಮ್ ।।೮।।\n\nಗಣಾಷ್ಟಕಮಿದಂ ಪುಣ್ಯಂ  ಭಕ್ತಿತೋ ಯಃ ಪಠೇನ್ನರ: ।\nವಿಮುಕ್ತಸ್ಸರ್ವಪಾಪೇಭ್ಯೋ ರುದ್ರಲೋಕಂ  ಸ ಗಚ್ಛತಿ  ।।೯।।\n\n",english:"Lyrics In English\n\nEkadantam mahaakaayam taptakaanchanasannibham |\nLambodaram vishaalaaksham vandeham gananaayakam ||1||\n\nMaunjikrushnaajinadharam naagayagnopaveetinam |\nbaalenduvilasanmouleem vandeham gananaayakam ||2||\n\nAmbikahrudayaanandam maatrubhih paripaalitam |\nbhaktapriyam madonmattam vandeham gananaayakam ||3||\n\nChitraratnavichitraangam chitramaalavibhooshitam |\nchitraroopadharam devam vandeham gananaayakam ||4||\n\nGajavaktram surashreshtam karnachaamarabhooshitam |\npaashankushadharam devam vandeham gananaayakam| |5||\n\nMooshikottamamaaruhya devaasuramahaahave |\nyoddhakaamam mahaaveeryam vandeham gananaayakam ||6||\n\nYakshakinnaragandharva siddhavidyaadharaissadaa |\nstooyamaanam mahaatmaanam vandeham gananaayakam ||7||\n\nSarvavighnakaram devam sarvavighnavivarjitam |\nsarvasiddhipradaataaram vandeham gananaayakam ||8||\n\nGanashtakamidam punyam bhaktito yah pathennarah |\nvimuktassarvapaapebhyo rudralokam sa gachchati ||9||\n\n",meta:"",tags:["saskrit devoional song lyrics in kanada"],media:"https://www.youtube.com/watch?v=6Ut3GGL8EJI"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಏಕದಂತಂ-ಮಹಾಕಾಯಂ.json",
	rawData: "",
};

export { _internal, collection, data, id };
