const id = "ಒಟ್ಟುಗೂಡಿ-ಬಂದೆವು-ಪಂಪೆ";
const collection = "bhajan";
const data = {kannada_title:"ಒಟ್ಟುಗೂಡಿ ಬಂದೆವು ಪಂಪೆ",english_title:"Ottugoodi bandevu, pampe",kannada:"ಸ್ವಾಮಿಯೇ ಅಯ್ಯಪ್ಪೋ, ಅಯ್ಯಪ್ಪೋ ಸ್ವಾಮಿಯೇ\nಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪ ಶರಣಂ\nಅಯ್ಯಪ್ಪ ಶರಣಂ ಸ್ವಾಮಿ ಶರಣಂ\nಕಲ್ಲುಂ ಮುಳ್ಳುಂ ಕಾಲಿಗೆ ಮೆತ್ತೇ,  ಸ್ವಾಮಿಯ ಕಂಡಾಲ್ ಮೋಕ್ಷಂ ಗಿಟ್ಟು, ಸ್ವಾಮಿಯೇ ಅಯ್ಯಪ್ಪೋ\nಅಯ್ಯಪ್ಪೋ ಸ್ವಾಮಿಯೇ\n\nಒಟ್ಟುಗೂಡಿ ಬಂದೆವು, ಪಂಪೆ ಮಡಿಲಲಿ ಮಿಂದೆವು\nಹಾಡು ಹಾಡುತ ಸ್ವಾಮಿ ಮಹಿಮೆ ಹೊಗಳುತಾ\nಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪ ಶರಣಂ ||2||\nಬಂದೆವೂ…ಅಯ್ಯಪ್ಪಾ.. ಸ್ವಾಮಿ ಅಯ್ಯಪ್ಪಾ….ಸ್ವಾಮಿಯೇ…..\n||ಒಟ್ಟುಗೂಡಿ||\n\nಶರವಣ ಶಾಸ್ತನೆ ನಮೋ ನಮೋ…\nಧರ್ಮಕೆ ಮುಡಿಪಾಗಿ ಬಂದೆವು\nಸ್ವಾಮಿಯೇ…. ಶರಣಂ ಅಯ್ಯಪ್ಪ |\nಧರೆ ಮೇಲೆ ಅವನ ಕೀರ್ತಿ ಹಾಡುವ\nಭೂಲೋಕದಲ್ಲು ಅವನ ಕೊಂಡಾಡುವ\nಅಂದದ ಚೆಂದದ ಮಂಗಳಮೂರುತಿ ಶಾಸ್ತನ ಸ್ತುತಿಸುವ\nಆನಂದ ತುಂಬಿದ ಇ ಭಕ್ತವೃಂದದ ವಂದನೆ ಸಲ್ಲಿಸುವ\n||ಒಟ್ಟುಗೂಡಿ||\n\nತಂಪಾದ ತೆಂಕಣದ ಗಾಳಿ ಬೀಸಲು\nಬಾನೆಲ್ಲ ಕೆಂಪಾಗಿ ರಂಗೇರಲು |\nಸ್ವಾಮಿಯೇ ಶರಣಂ ಅಯ್ಯಪ್ಪ ||\nನೆನೆದಾಗ ಧರ್ಮಶಾಸ್ತ ಬಂದಿರಲು\nಸಂತಸವೆ ಉಕ್ಕಿ ಉಕ್ಕಿ ಬಂದಿರಲು\nಪಂದಳರಾಜನ ಮುದ್ದಿನ ಕಂದನ\nಎಂದೆಂದು ಭಜಿಸುವ ಕಾಂತಿ ಚೆಲ್ಲುವ ಚೆಲುವನಿವನ‌\nಕೀರ್ತಿ ಹೊಗಳುವ ||ಒಟ್ಟುಗೂಡಿ||\n\n",english:"Swamiye ayyappo, ayyappo swamiye |swami sharanam ayyappa sharanam | ayyappa sharanam swami sharanam | kallum mullum kaalige mette, swamiya kandaal moksham gittu, swamiye ayyappo, ayyappo swamiye ||\n\nOttugoodi bandevu, pampe madilali mindevu, haadu haduta swami mahime hogaluta| swami sharanam ayyappa sharanam ||2|| bandevoo …. Ayyappa … Swami ayyappaa ….. Swamiye …… ||Ottugoodi||\n\nSharavana shaastane namo namo ….. Dharmake mudipaagi bandevu| swamiye …… Sharanam ayyappa | dhare mele avana keerti haaduva | bhulokadallu avana kondaaduva andada chendada mangalamooruti shaastana stutisuva | ananda tumbida e bhaktavrundada vandane sallisuva ||ottugoodi||\n\nTampaada tenkanada gaali beesalu | baanella kempaagi rangeralu | swamiye sharanam ayyappa|| nenedaaga dharmashaasta bandiralu, santasave ukki ukki bandiralu, pandalaraajana muddina kandana, endendu bhajisuva kaanti chelluva cheluvanivana keerti hogaluva||ottugoodi||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=Uvm1GewLo_Y"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಒಟ್ಟುಗೂಡಿ-ಬಂದೆವು-ಪಂಪೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
