const id = "ಕಂದಾ-ಬೇಡವೊ-ಮಣ್ಣು";
const collection = "bhajan";
const data = {kannada_title:"ಕಂದಾ ಬೇಡವೊ ಮಣ್ಣು",english_title:" Kanda bedavo mannu",kannada:"ಕಂದಾ ಬೇಡವೊ ಮಣ್ಣು ತಿನ್ನ ಬೇಡವೊ ||ಪ||\nಕಂದಾ ಬೇಡವೊ ಮಣ್ಣು ತಿನ್ನಲಿ ಬೇಡವೊ\nಸುಂದರಾಂಗನೆ ನಿನಗೆ ಹೊಟ್ಟೆ ನೋಯುವುದಯ್ಯ ||ಅ||\n\nಬೇಗನೆ ಏಳಯ್ಯ , ಮಣ್ಣಾಟ ಬಿಡೊ ನೀನು\nಜೋಗಿ ಬರುತಾನಲ್ಲಿ ಅಂಜಿಸುವುದಕೀಗ ||\n\nತಾಯಿ ಮಾತನು ಒತ್ತಿ ಕರದಲಿ ಮಣ್ಣೊತ್ತಿ\nಬಾಯಲಿ ಇಟ್ಟನು ಬಾಲಕೃಷ್ಣಯ್ಯನು ||\n\nಪೆಟ್ಟು ಕೊಡುವೆ ನಿನಗೆ, ಸಿಟ್ಟು ಬಹಳ ಇದೆ\nಮುಟ್ಟಬೇಡೊ ಮಣ್ಣು , ಬೆಣ್ಣೆ ತರುವೆನಯ್ಯ ||\n\nಅಮ್ಮಯ್ಯ ಕೇಳೆಲೆ, ಬಾಯಲಿ ಮಣ್ಣಿಲ್ಲ\nಗುಮ್ಮನ ಕರೆಬೇಡ, ಸುಮ್ಮನೆ ಇರುತೇನೆ ||\n\nಮಗುವೆ ಬಾ ಬಾ ಎಂದು ಬಣ್ಣಿಸಿ ಕರೆದಳು\nಮಗುವಿನ ಬಾಯ ಶೋಧಿಸಿದಳು ಬೇಗನೆ ||\n\nಬಾಯಲಿ ಕಂಡಳು ಹದಿನಾಲ್ಕು ಲೋಕವ\nಕಾಯ ಮರೆತಳಯ್ಯ ಮರುಳಿಗೆ ವಶವಾಗಿ ||\n\nಮತ್ತು ಕಂಡಳು ಅವಳು ಗೋಕುಲವೆಲ್ಲವ\nಅತ್ತ ಕಂಡಳು ತನ್ನ ಕೃಷ್ಣನ ಬಗಲಲಿ ||\n\nಗೋಪ್ಯೇರ ಮನೆಗಳಲಿ ಗೋಪಾಲಕೃಷ್ಣನು\nಗೋಪ್ಯೇರ ಮನೆಗಳಂತೆ ದುಡುಕು ಮಾಡುತಲಿರ್ದ ||\n\nಬಾಲನು ಬೀದಿಯ ಮಣ್ಣೆತ್ತಿ ಉಣುತಿರ್ದ\nಬಾಲೆ ಗೋಪ್ಯಮ್ಮನು ಮಣ್ಣ ತೆಗೆತಿರ್ದಳು ||\n\nಕಂದನು ನೀನಲ್ಲ ಕಂದರ್ಪ ಜನಕನೆ\nಕಂದನೆ ನಿನ್ನ ಬಾಯ ಮುಚ್ಚಿಕೊಳ್ಳಯ್ಯ ಈಗ ||\n\nದೇವದಿದೇವನೆ ದೇವಕಿತನಯನೆ\nಭಾವಜನಯ್ಯನೆ ಬಾರಯ್ಯ ದೊರೆಯೆ ||\n\nಜಯಗಳಾಗಲಿ ನಮ್ಮ ಕೃಷ್ಣರಾಯಗೆ ಬಹಳ\nಜಯಗಳಾಗಲಿ ಅವನ ಭಕ್ತರ ವೃಂದಕೆ ||\n\nಲೀಲಾ ವಿನೋದನು ರುಕ್ಮಿಣೀ ಲೋಲನು\nಲೀಲೆ ತೋರಿದನಂದು ತಂದೆ ಪುರಂದರವಿಠಲ ||\n\n",english:"Kanda bedavo mannu tinna bedavo ||pa||\n\nKanda bedavo mannu tinnali bedavo\nSundarangane ninage hotte noyuvudayya ||a||\n\nBegane elayya, mannata bido ninu\nJogi barutanalli anjisuvudakiga ||\n\nTayi matanu otti karadali mannotti\nBayali ittanu balakrishnayyanu ||\n\nPettu koduve ninage, sittu bahala ide\nMuttabeda mannu, benne taruvenayya ||\n\nAmmayya kelele,  bayali mannilla\nGummana karebeda, summane irutene ||\n\nMaguve ba ba endu bannisi karedalu\nMaguvina baya shodhisidalu begane ||\n\nBayali kandalu hadinalku lokava\nKaya maretalayya marulige vashavagi ||\n\nMattu kandalu avalu gokulavellava\nAtta kandalu tanna krishnana bagalali ||\n\nGopyera manegalali gopalakrishnanu\nGopyera manegalante duduku madutalirda ||\n\nBalanu bidiya mannetti unutirda\nBale gopyammanu manna tegetirdalu ||\n\nKandanu ninalla kandarpa janakane\nKandane ninna baya mucchikollayya Iga ||\n\nDevadidevane devakitanayane\nBavajanayyane barayya doreye ||\n\nJayagalagali namma krishnarayage bahala\nJayagalagali avana Bhaktara vrundake ||\n\nLilavinodanu rukminilolanu\nLile toridanandu tande purandaravithala ||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=PvTJp812Cpw"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಕಂದಾ-ಬೇಡವೊ-ಮಣ್ಣು.json",
	rawData: "",
};

export { _internal, collection, data, id };
