const id = "ಕಾಪಾಡು-ಶ್ರೀಸತ್ಯನಾರಾಯಣ";
const collection = "bhajan";
const data = {kannada_title:"ಕಾಪಾಡು ಶ್ರೀಸತ್ಯನಾರಾಯಣ",english_title:"  Kaapaadu Sri Satyanarayana",kannada:"ಸತ್ಯಾತ್ಮ ಸತ್ಯ ಕಾಮ ಸತ್ಯ ರೂಪ ಸತ್ಯ ಸಂಕಲ್ಪ\nಸತ್ಯ ದೇವ ಸತ್ಯ ಪೂರ್ಣ ಸತ್ಯಾನಂದ\n\nಕಾಪಾಡು ಶ್ರೀ ಸತ್ಯನಾರಾಯಣ\nಪನ್ನಗ ಶಯನ ಪಾವನ ಚರಣ\nನಂಬಿಹೆ ನಿನ್ನ\n\nನಾರಾಯಣ ಲಕ್ಷ್ಮಿನಾರಾಯಣ\nನಾರಾಯಣ ಸತ್ಯನಾರಾಯಣ\n\nಮನವೆಂಬ ಮಂಟಪ ಬೆಳಕಾಗಿದೆ\nಹರಿನಾಮದಾ ಮಂತ್ರವೇ ತುಂಬಿದೆ\nಎಂದೆಂದು ಸ್ತಿರವಾಗಿ ನೀನಿಲ್ಲಿರು\nನನ್ನಲ್ಲಿ ಒಂದಾಗಿ ಉಸಿರಾಗಿರು\n\nನನಗಾಗಿ ಏನನ್ನು ನಾ ಬೇಡೆನು\nಧನಕನಕ ಬೇಕೆಂದು ನಾ ಕೇಳೆನು\nಈ ಮನೆಯು ನೀನಿಇರುವ ಗುಡಿಯಾಗಲಿ\nಸುಖ ಶಾಂತಿ ನೆಮ್ಮದಿಯ ನೆಲೆಯಾಗಲಿ\n\nಕಣ್ಣೀರ ಅಭಿಷೇಕ ನಾ ಮಾಡಿದೆ\nಕರುನಾಳು ನೀ ನನ್ನ ಕಾಪಾಡಿದೆ\nಬರಿದಾದ ಮಡಿಲನ್ನು ನೀ ತುಂಬಿದೆ\nನಾ ಕಾಣದಾನಂದ ನೀ ನೀಡಿದೆ.\n\n",english:"Sathyaathma Sathya Kaama Sathya Roopa\nSathya Sankalpa Sathya Dhevaa Sathya Poorna\nSthyaanadha\n\nKaapaadu Shree Sathya Narayana\nKaapaadu Shree Sathya Narayana\nPannaga Shayana Paavana Charana\nPannaga Shayana Paavana Charana\nNambihe Ninna\n\nKaapaadu Shree Sathya Narayana\nNaaraayana Lakshminaaraayana\nNaaraayana Sathynaaraayna\nNaaraayana Lakshminaaraayana\nNaaraayana Sathynaaraayna\n\nManavemba Mantapa Belakaagidhe\nHarinaamdhaa Manthravae Thumbidhe ||2 times ||\nEndhendhu Sthirvaagi Neenilliru\nNannalli Ondhaagi Usiraagiru || Kaapadu||\nNanagaagi Yenannu Naa Baedenu\nDhanakanaka Baekendhu Naa Kaelaenu ||2 times||\nEe Maneyu Neeniiruva Gudiyaagli\nSukha Shaanthi Nemmadhiya Neleyaagli || Kaapadu||\n\nKanneera Abhishaeka Naa Maadidhe\nKarunaalu Nee Nanna Kaapaadidhe || 2 times||\nBaridhaadha Madilannu Nee Thumbidhe\nNaa Kaandhaanandha Nee Needidhe || Kaapadu||\n\nKaapaadu Shree Sathynaaraayana\nPannaga Shayana Paavana Charana\nPannaga Shayana Paavana Charana\nNambihe Ninna\nKaapaadu Shree Sathynaaraayana\nNaaraayana Lakshminaaraayana Naaraayana Sathynaaraayna |4|\n\nThis beautiful song from the film Daari tappida maga, sung by P.B.Srinivas and A.P.Komala. This is an evergreen song which is sung on the occasion of Griha pravesham even today. Click the link to listen the song\n\n",meta:"",tags:[],media:"https://www.youtube.com/watch?v=3VQ7tDBVDlA"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಕಾಪಾಡು-ಶ್ರೀಸತ್ಯನಾರಾಯಣ.json",
	rawData: "",
};

export { _internal, collection, data, id };
