const id = "ಕಮಲಮುಖಿಯೆ-ಕಮಲಾಲಯೆ";
const collection = "bhajan";
const data = {kannada_title:"ಕಮಲಮುಖಿಯೆ ಕಮಲಾಲಯೆ",english_title:" Kamalamukiye kamalalaye",kannada:"ಕಮಲಮುಖಿಯೆ ಕಮಲಾಲಯೆ ಕಮಲೆಕಮಾಲಾಕ್ಷಿಯೆ ಕೋಮಲೆ ||\n\nಕಮಲನಾಭನ ಪಾದಕಮಲಯುಗಳ ಮಧುಪೆಕಮಲಜ ಜನನಿಯೆ ಕಮಲಮಿತ್ರೆ ಸುಪ್ರಭೆ ||ಅ.ಪ.||\n\nಅರುಣನ ಪೋಲುವ ಚರಣವು ಬಾಲಚಂದಿರನ ಸೋಲಿಪ ನಖವು ಬೆರಳಲ್ಲಿ ಪಿಲ್ಲಿ ಕಾಲುಂಗುರ ಮೆಂಟಿಕೆ ಕಿರುಗೆಜ್ಜ್ಯಂದಿಗೆ ಪೆಂಡೆಯುಕರಿಯ ದಂತದಂತೆ ಜಾನುದರ್ಪಣ ಜಂಘೆ ಉಟ್ಟ ದಟ್ಟಿಯು ನೆರಿಗೆಯು ಹರಿನಡು ಕಿಂಕಿಣಿ ಭರದಿ ಒಡ್ಯಾಣವು ಉದರ ತ್ರಿವಳಿರೇಖೆ ವರ ಕಂಚುಕಧಾರಿ||\n\nಕರಿಯ ಸೊಂಡಲಿನಂತೆ ಕರಯುಗದೊಳಗೊಪ್ಪುವ ಬೆರಳು ಮಾಣಿಕ್ಯದುಂಗುರಹರಡಿ ಕಂಕಣ ವಂಕಿ ಬಿರುದಿನ ತೋಳ್ಬಂದಿ ಶಿರಿಭುಜದಲ್ಲಿ ಕೇಯೂರ ಕೊರಳ ಒಪ್ಪುವ ಸರಗಳು | ಪದಕವು ಉರೆ ವೈಜಯಂತೀ ಮಂದಾರ ಮೆರೆವ ಚುಬುಕ ಬಿಂಬಾಧರ ಕೂರ್ಮಕದಪು ಕಿರಿದಂತ ರತುನದ ಕರಡಿಗೆ ವದನೆ ||\n\nಸುರಭಿ ಚಂಪಕನಾಸಿಕ ಮೂಗುತಿ ಶಾಂತ ಪರಮ ಕರುಣ ನೋಟದ ಹರಿಣನಯನೆ ಪುಬ್ಬುಸ್ಮರನ ಚಾಪದಂತೆ ಕರ್ಣಾಭರಣಲಂಕಾರ ಸಿರಿಕುಂಕುಮ ಕಸ್ತೂರಿ ತಿಲಕದ ಮೇಲೆ ಅರಳೆಲೆ ಬೈತಲೆಯ ಸರ ಕುರುಳುಸುಳಿಯು ಪರಿಪರಿ ರತ್ನ ಖಚಿತದ ವರ ಮಕುಟವು ಕೋಟಿ ತರಣಿಯಂತೊಪ್ಪುವ ||\n\nತೆತ್ತೀಸಕೋಟಿ ದೇವತೆಗಳು ವಾಣಿ ಭಾರತಿ ಪಾರ್ವತಿ ಮೊದಲಾದ ಉತ್ತಮ ಸ್ತ್ರೀಯರು ಛತ್ರಚಾಮರನೆತ್ತಿ ಬೀಸುವಲಂಕಾರಸುತ್ತಗಂಧರ್ವರು ತುಂಬುರ ನಾರದರು ಸ್ವರವೆತ್ತಿ ಪಾಡುವ ಝೇಂಕಾರ ತತ್ತರಿತರಿಘಟ್ಟ ಝಣುತ ಝಣುತ ಎಂದು ಎತ್ತ ನೋಡಿದರತ್ತ ತಥೈ ಎಂಬೊ ಶಬ್ದ ||\n\nಪಕ್ಷಿವಾಹನನಾದ ಪಾವನಮೂರ್ತಿಯ ವಕ್ಷಸ್ಥಳದಿ ಶೋಭಿತೆಲಕ್ಷ್ಮೀದೇವಿಯೆ ಸಲಕ್ಷಣೆ ಅಜ ಫಾಲಾಕ್ಷ ಸುರವಿನುತೆ ಮೋಕ್ಷದಾಯಕಿ ಲೋಕರಕ್ಷಕಿ ರಮಾದೇವಿ ಇಕ್ಷುಧನ್ವನ ಜನನಿ ಅಕ್ಷಯಫಲದ ಗೋಪಾಲವಿಠಲನ ಪ್ರತ್ಯಕ್ಷ ತೋರಿಸೆನ್ನಪೇಕ್ಷೆ ಪೂರೈಸೆ ತಾಯೆ ||\n\n",english:"Kamalamukiye kamalalaye kamalekamalakshiye komale ||\n\nKamalanabana padakamalayugala madhupekamalaja jananiye kamalamitre suprabe a||\n\nArunana poluva caranavu balachandirana solipa nakavuberalalli pilli kalungura mentike kirugejjyamdige pendeyukariya dantadante janudarpana jange utta dattiyu nerigeyuharinadu kimkini Baradi odyanavu udara trivalireke vara kancukadhari||\n\nKariya sondalinante karayugadolagoppuva beralu manikyadumguraharadi kankana vanki birudina tallbandi siribujadalli keyurakorala oppuva saragalu padakavu ure vaijayanti mandaramereva cubuka bimbadhara kurmakadapu kiridanta ratunada karadige vadane ||\n\nSurabi champakanasika muguti santa parama karuna notadaharinanayane pubbusmarana capadante karnabaranalamkara siri kumkuma kasturi tilakada mele aralele baitaleya sara kurulusuliyu paripari ratna Kacitada vara makutavu koti taraniyantoppuva ||\n\nTettisakoti devategalu vani barati parvati modalada^^uttamastriyaru chatrachamaranetti bisuvalankarasuttagandharvaru tumbura naradaru svaravetti paduva jenkaratattaritarigatta januta januta endu etta nodidaratta tathai embo Sabda ||\n\nPakshivahananada pavanamurtiya vakshasthaladi sobitelakshmideviye salakshane aja palaksha suravinutemokshadayaki lokarakshaki ramadevi ikshudhanvana janani^^akshayapalada gopalavithalana pratyaksha torisennapekshe puraise taye ||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=eC3DWht-qBo"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಕಮಲಮುಖಿಯೆ-ಕಮಲಾಲಯೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
