const id = "ಕೈಯ-ತೋರೋ-ಕರುಣಿಗಳರಸಾ";
const collection = "bhajan";
const data = {kannada_title:"ಕೈಯ ತೋರೋ ಕರುಣಿಗಳರಸಾ",english_title:" Kaiya toro karunigalarasa",kannada:"ಕೈಯ ತೋರೋ ಕರುಣಿಗಳರಸಾ-ಕೈಯ ತೋರೊ |ಕೈಯಲಿ ಬೆಣ್ಣೆಯ ಮುದ್ದೆಯ ನೀಡುವೆ-ಕೈಯ||pa||\n\nಗುಲಿಯೊಳು ಪೊನ್ನುಂಗುರವೊಪ್ಪುವ ಕೈಯ ತೋರೊ | ಶೃಂಗಾರದಿ ಶಂಖಚಕ್ರವ ಧರಿಸಿದ ಕೈಯ ತೋರೊ ಅಂಗೈಯಲಿ ಧ್ವಜಪಧ್ಮವಿರಾಜಿಪ ಕೈಯ ತೋರೊ | ಅಂಗನೆಯರಉತ್ತುಂಗಕುಚದಲಿಟ್ಟ ಕೈಯ ತೋರೊ||1||\n\nಬಡಬ್ರಾಹ್ಮಣನವಲಕ್ಕಿಯ ಬೇಡಿದ ಕೈಯ ತೋರೊ | ಕೊಡೆ ಮಾಡಿ ಗಿರಿಯೆತ್ತಿ ಗೋಗಳ ಕಾಯ್ದ-ಕೈಯ ತೋರೊ ಕಡುಹಿರಣ್ಯಾಖ್ಯನ ಒಡಲನು ಬಗೆದ-ಕೈಯ ತೋರೊ | ಧೃಡ ಪ್ರಹ್ಲಾದನ ಮಂಡೆಯೊಳಿಟ್ಟ ಕೈಯ ತೋರೊ||2||\n\nಅಲ್ಲಿ ಪೂತನಿಯ ಅಸುವನೆ ಹೀರಿದ ಕೈಯ ತೋರೊ | ಬಲ್ಲಿದಮಲ್ಲರ ಮರ್ದಿಸಿ ಬಂದ-ಕೈಯ ತೋರೊ\nಮೆಲ್ಲನೆ ಕುಬುಜೆಯ ಡೊಂಕನೆ ತಿದ್ದಿದ ಕೈಯ ತೋರೊ | ಬಿಲ್ಲನು ಎಡಗೈಯಲಿ ಮುರಿದಿಟ್ಟ ಕೈಯ ತೋರೊ||3||\n\nಬಲಿಯನು ವಂಚಿಸಿ ದಾನವ ಬೇಡಿದ ಕೈಯ ತೋರೊ | ಫಲಪುಷ್ಪ ಪಾರಿಜಾತವ ತಂದ ಕೈಯ ತೋರೊ\nಒಲಿದು ಪಾರ್ಥಗೆ ರಥವನು ನಡೆಸಿದ ಕೈಯ ತೋರೊ | ಮಲ್ಲಿಗೆ ಜಾಜಿಯ ತುರುಬಿಗೆ ಮುಡಿಸಿದ ಕೈಯ ತೋರೊ ||4||\n\nಆಕಾಶದ ಚಂದ್ರಮನನು ಕರೆದ-ಕೈಯ ತೋರೊ | ನಾಕಪತಿಗೆ ಅಭಯವನಿತ್ತ-ಕೈಯ ತೋರೊ |\nನೇಕ ಬಗೆಯಲಿ ಕೊಳಲನೂದುವ-ಕೈಯ ತೋರೊ | ಶ್ರೀಕಾಂತ ನಮ್ಮ ಪುರಂದರವಿಠಲ-ಕೈಯ ತೋರೊ ||5||\n\n",english:"Kaiya toro karunigalarasa-kaiya toro |kaiyali benneya muddeya niduve-kaiya||pa||\n\nGuliyolu ponnunguravoppuva kaiya toro | shrungaradi shankhachakrava dharisida kaiya toro angaiyali dhvajapadhmavirajipa kaiya toro |anganeyara uttungakuchadalitta kaiya toro||1||\n\nBadabrahmananavalakkiya bedida kaiya toro | kode madi giriyetti gogala kayda-kaiya toro kaduhiranyakyana odalanu bageda-kaiya toro | dhruda prahladana mandeyolitta kaiya toro||2||\n\nAlli putaniya asuvane hirida kaiya toro | ballidamallara mardisi banda-kaiya toro\nMellane kubujeya Donkane tiddida kaiya toro  | billanu edagaiyali muriditta kaiya toro||3||\n\nBaliyanu vancisi danava bedida kaiya toro | palapushpa parijatava tanda kaiya toro\nOlidu parthage rathavanu nadesida kaiya toro | mallige jajiya turubige mudisida kaiya toro ||4||\n\nAkasada candramananu kareda-kaiya toro | nakapatige abayavanitta-kaiya toro |\nNeka bageyali kolalanuduva-kaiya toro | srikanta namma purandaravithala-kaiya toro ||5||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=dY662cKYEZM"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಕೈಯ-ತೋರೋ-ಕರುಣಿಗಳರಸಾ.json",
	rawData: "",
};

export { _internal, collection, data, id };
