const id = "ಕಂಡೆ-ಕಂಡೆ-ಸ್ವಾಮಿಯ";
const collection = "bhajan";
const data = {kannada_title:"ಕಂಡೆ ಕಂಡೆ ಸ್ವಾಮಿಯ",english_title:" Kande kande swamiya",kannada:"ಕಂಡೆ ಕಂಡೆ ಸ್ವಾಮಿಯ ,ಬೇಡಿ ಕೊಂಡೆ||2||\nಕಂಡೆ ಕಂಡೆ ಸ್ವಾಮಿಯಾ…\n\nಕಂಡೆ ತಿರುಪತಿ ವೆಂಟೇಶನ ಕಾರಣಾತ್ಮಕ ಸಾರ್ವಭೌಮನ ಕಾಮಿತಾರ್ಥಗಳೀವ ದೇವನ\nಕರುಣನಿಧಿ ಎಂದೆನಿಸಿ ಮೆರೆವನ. ||ಕಂಡೆ ಕಂಡೆ||\n\nಕೋಟಿ ಸೂರ್ಯ ಪ್ರಕಾಶವೆನಿಪ ಕಿರೀಟವನು ಮಸ್ತಕದಿ ಕಂಡೆನು  |ನೋಟಕಾಶ್ಚರ್ಯವಾದ ನಗೆಮುಖ ನೊಸಲಿನಲಿ ತಿರುಮಣಿಯ ಕಂಡೆನು|\nಸಾಟಿ ಇಲ್ಲದೆ ಚತುರ ಹಸ್ತದಿ ಶಂಖಚಕ್ರಗದಾಬ್ಜ ಕಂಡೆನು| ಬೂಟಕದ ಮಾತಲ್ಲ ಕಾಣಿರೊ, ಬೂರಿ ದೈವರ ಗಂಡನಂಘ್ರಿಯ.           ||ಕಂಡೆ ಕಂಡೆ||\n\nತಪ್ಪು ಕಾಣಿಕೆ , ಕಪ್ಪಗಳನು ಸಪ್ತ ದ್ವೀಪಗಳಿಂದ ತರಿಸುವ | ಉಪ್ಪು ಓಗರೆಗಳನೆ ಮಾರಿಸಿ\nಉಚಿತದಿಂದಲೆ ಹಣವಗಳಿಸುವ ಇಪ್ಪತ್ತು ದುಡ್ಡಿಗೆ ಸೇರು ತೀರ್ಥವ |ಒಪ್ಪದಲಿ ಕ್ರಯ ಮಾಡಿ ಕೊಡಿಸುವ ಸರ್ಪಶಯನನ ಸಾರ್ವಭೌಮನ\nಅಪ್ಪ ವೆಂಕಟರಮಣನಂಘ್ರಿಯ ||ಕಂಡೆ ಕಂಡೆ||\n\nಪುರದಿ ಸಿರಿದೇವಿ ಇರಲು ಕಂಡೆನು ಉನ್ನತದಿ ಕೌಸ್ತುಭವ ಕಂಡೆನು | ಗರುಡ ಕಿನ್ನರ ನಾರದಾದಿ\nಗಂಧರ್ವರೆಡಬಲದಿ ಕಂಡೆನು | ತೆರತೆರದಿ ಭಕ್ತರಿಗೆ ವರಗಳ ಕರೆದು ಕೊಡುವುದ ನಾನು ಕಂಡೆನು |\nಶರದಿ ಶಯನನ ಸಾರ್ವಭೌಮನ ವರದ ಪುರಂದರವಿಠ್ಠಲನಂಘ್ರಿಯ ||ಕಂಡೆ ಕಂಡೆ||\n\n",english:"Kande kande swamiya bedikonde ||2times|| kande kande||\n\nKande tirupati venkateshana kaaranaatmaka sarvabhoumana kaamitaarthagaliva devana karunanidhi endenisi merevana ||kande kande||\n\nKoti soorya prakashvenipa kireetavanu mastakadi kandenu| notakaashcharyavaada nagemukha nosalinali tirumaniya kandenu | saati ellade chatura hastadi shankhachakragadaabja kandenu |bootakada maatalla kaaniro, boori daivara gandanamghriya||kande kande||\n\nTappu kaanike kappagalannu sapta dweepagalinda tarisuva | uppu ogaregalane maarisi uchitadindale hanavagalisuva eppattu duddige seru theerthava| oppadali kraya maadi kodisuva sarpashayanana saarvabhoumana appa venkataramananghriya ||kande kande||\n\nPuradi siridevi eralu kandenu unnatadi koustubhava kandenu| garuda kinnara naaradaadi gandharvaredabaladi kandenu| terateradi bhaktarige varagala karedu koduvudu naanu kandenu| sharadi shayanana saarvabhoumana varada purandaravithalananghriya ||kande kande||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=Q-fEOFvPfgQ"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಕಂಡೆ-ಕಂಡೆ-ಸ್ವಾಮಿಯ.json",
	rawData: "",
};

export { _internal, collection, data, id };
