const id = "ಕ್ಷೀರ-ವಾರಿಧಿ-ಕನ್ನಿಕೆ-ಮಾರಜನಕೆ";
const collection = "bhajan";
const data = {kannada_title:"ಕ್ಷೀರ ವಾರಿಧಿ ಕನ್ನಿಕೆ ಮಾರಜನಕೆ",english_title:"Kshira varidhi kannike",kannada:"ಕ್ಷೀರ ವಾರಿಧಿ ಕನ್ನಿಕೆ ಮಾರಜನಕೆ\nಈರೇಳು ಲೋಕನಾಯಿಕೆ |pa||\n\nವಾರವಾರಕೆ ಆರಾಧಿಪುದಕೆ ಚಾರುಮತಿಯ ಕೊಡು\nದೂರ ನೋಡದಲೆ ||ಅ.ಪ||\n\nಶ್ರೀಧರಾ ದುರ್ಗಿ ಆಂಭ್ರಣಿ ನಿತ್ಯ ಕಲ್ಯಾಣಿ\nವೇದವತಿಯೆ ರುಕ್ಮಿಣಿ |\nವೇದ ವೇದಾಂತದಭಿಮಾನಿ ವಾರಿಜ ಪಾಣಿ\nಆದಿ ಮಧ್ಯಾಂತ ಗುಣಮಣಿ |\nಸಾಧು ಜನರ ಹೃನ್ಮಂದಿರ ವಾಸಿನಿ\nಭೇದಗೊಳಿಪ ಕಾಮಕ್ರೋಧಗಳೋಡಿಸಿ|\nನೀ ದಯದಿಂದಲೆ ಮುಂದೆ ಗತಿಗೆ ಪಂಚ\nಭೇದಮತಿಯ ಕೊಡು ಮಾಧವ ಪ್ರಿಯಳೆ ||1||\n\nಶ್ರೀ ಮಾಯಾ ಜಯಾ ಕೃತಿ ಶಾಂತಿದೇವಿ ಜಯಂತೆ\nನಾಮದೊಳಪ್ಪ ಗುಣವಂತೆ |\nಕೋಮಲವಾದ ವೈಜಯಂತೆ ಧರಿಸಿದ ಶಾಂತೆ\nಸೋಮಾರ್ಕ ಕೋಟಿ ಮಿಗೆ ಕಾಂತೆ |\nತಾಮರಸಾಂಬಕೆ ರಮೆ ಲಕುಮಿ ಸತ್ಯ\nಭಾಮೆ ಭವಾರಣ್ಯ ಧೂಮಕೇತಳೆ |\nಯಾಮ ಯಾಮಕೆ ಹರಿ\nನಾಮವ ನುಡಿಸಿ ಉತ್ತಮರೊಡನೆ ಪರಿ\nಣಾಮವನೀಯುತ ||2||\n\nಅನೇಕಾಭರಣ ಭೂಷಿತೆ ಧರಣಿಜಾತೆ\nಸುಜ್ಞಾನಿ ಗಳ ಮನೋಪ್ರೀತೆ |\nಆನಂದಲೀಲೆ ವಿಖ್ಯಾತೆ ಆದಿದೇವತೆ\nಗಾನವಿಲೋಲೆ ಸುರನುತೆ ನೀನೇ ಗತಿ ಎನಗಾರನ |\nಕಾಣೆನೆ ದಾನಿ ಇಂದಿರಾದೇವಿ\nನಾನಾ ಪರಿಯಲಿ ಶ್ರೀನಿಧಿ ವಿಜಯವಿಠ್ಠಲನ ಮೂರುತಿಯ ಧ್ಯಾನದೊಳಿಡುವಂಥ ಸುಜ್ಞಾನ ಭಕುತಿ ಕೊಡು||3||\n\n",english:"Kshira varidhi kannike marajanake\nIrelu lokanayike |pa||\n\nVaaravarake aradhipudake charumatiya kodu | doora nodadale ||a.pa||\n\nSridhara durgi ambrani nitya kalyani\nvedavatiye rukmini|\nVeda vedantadabimaani varija paani\nAdi madhyanta gunamani|\nSadhu janara hrunmandira vaasini\nBedagolipa kamakrodhagalodisi|\nNi dayadindale munde gatige pancha\nBedamatiya kodu madhava priyale ||1||\n\nSri maya jaya kruti shantidevi jayante\nNamadolappa gunavante|\nKomalavaada vaijayante dharisida shante\nSomarka koti mige kante|\nTamarasambake rame lakumi satyabhame bavaranya dhumaketale|\nYaama yaamake hari\nnamava nudisi uttamarodane pari\nnaamavaniyuta ||2||\n\nAnekabharana bushite dharanijate\nSujnanigala manoprite|\nAnandalile vikyate adidevate\ngaanavilole suranute nine gati enagarana|\nkaanene daani indiradevi\nnaana pariyali srinidhi vijayaviththalana muruti |yadhyanadoliduvantha sujnana Bakuti kodu||3||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=hwkZkMf6gBM"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಕ್ಷೀರ-ವಾರಿಧಿ-ಕನ್ನಿಕೆ-ಮಾರಜನಕೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
