const id = "ಕೋಲು-ಕೃಷ್ಣ-ಸಾಗರ-ಶಯನ";
const collection = "bhajan";
const data = {kannada_title:"ಕೋಲು ಕೃಷ್ಣ ಸಾಗರ ಶಯನ",english_title:" kolu Krishna sagara shayana",kannada:"ಕೋಲು ಕೃಷ್ಣ ಸಾಗರ ಶಯನ ಕೋಲಣ್ಣ ಕೋಲ\nಸಾಲಿಗ್ರಾಮಕೆ ಹಾಲಭಿಷೇಕ\nಕೋಲಣ್ಣ ಕೋಲ, ಕೋಲಣ್ಣ ಕೋಲ\n||ಕೋಲು||\n\nಅಟ್ಟದ ಮೇಲಿನ ನೆಲವಲ್ಲಾಡಿಸಿ ಸಕ್ಕರೆಗಳ ಸವಿದಾ\nಕೃಷ್ಣಾ ಕೃಷ್ಣೆಂದರೆ ನಾನಲ್ಲ ಬೆಕ್ಕೇನೊ ಎಂದಾ ||\n\nಬೆಕ್ಕೆಂದೋಡುತ ಊರೊಳಗಿದ್ದ ಹಕ್ಕಿಗಳೋಡಿಸಿದ\nಮಕ್ಕಳು ಮಲಗ್ಯಾರೆಬ್ಬಿಸಬೇಡೆನೆ ಬಟ್ಟಲು ಬಾರಿಸಿದಾ ||\n||ಕೋಲು||\n\nಹಪ್ಪಳ ಸಂಡಿಗೆ ಹರವಿದ ಮನೆಯಲಿ\nತಪ್ಪದೆ ತಾ ಪೋದ ಮುಚ್ಚಿಡಬ್ಯಾಡಿ ಮುಟ್ಟುವನಲ್ಲ ಅಪ್ಪಂತವನಲ್ಲ ||\n\nಸಾರಿದ ಮನೆಯಲಿ ಸುಣ್ಣವ ಚೆಲ್ಲಿ ಧೂಳನು ಹರವಿದಾ\nಕಾಲಲಿ ರಂಗೋಲಿ ಹಾಕಿದೆ ಯಶೋದೆ\nನೋಡು ಬಾ ಎಂದು ಕರೆದಾ ||2||\n||ಕೋಲು||\n\nಅಭಿಷೇಕಕೆಂದು ಅಘ್ರ್ಯೋದಕ ತಂದರೆ\nಅಚಮನ ಮಾಡಿದಾ\nಪ್ರೀತಿಯಿಂದ ಗಂಧಾಕ್ಷತೆ ಇಟ್ಟರೆ ಶ್ರೀತುಳಸಿಯ ತಾ ಮುಡಿದ ||\n\nನೈವೇದ್ಯಕೆಂದು ಅಮ್ರತಾನ್ನ‌ಮಾಡಲು ಬಾಯ್ತೆರೆದೆ ಎಂದಾ\nನೈವೇದ್ಯಕೆಲ್ಲಣಿಯಾಗಿದೆ ಯಶೋದೆ\nನೋಡು ಬಾ ಎಂದು ಕರೆದ ||\n||ಕೋಲು||\n\nಕಜ್ಜಾಯ ಮಾಡುವ ಅಲ್ಲಿಗೆ ಹೋಗಿ ಒಬ್ಬಂತೆ ತಾ ನಿಂತ\nಜಜ್ಜಿಡೆರೆ ತಿಂದು ದೂರ ಹೋಗಿ ನಿಂತು ಹಬ್ಬವು ಏನೆಂದ ||\n\nಒಬ್ಬನೆ ತಿಂದು ಒಳಗಿದ್ದವರಿಗೆ ಜಿಬ್ಬನು ತೋರಿಸಿದ\nಮಜ್ಜಿಗೆ ಕಳ್ಳನು ಹಿಡಿಹಿಡಿ ಎಂದರೆ\nಅಜ್ಜನ ಮಗನೆಂದಾ ||\n||ಕೋಲು||\n\nಉಪ್ಪು ಸಾಕು ಸಾಲದು ನೋಡೆನೆ ಅಪ್ಪಟವನೆ ಮೆದ್ದ\nತುಪ್ಪದ ಕಳ್ಳನ ಹಿಡಿಹಿಡಿ ಎಂದರೆ\nನಿಮ್ಮಪ್ಪನ ಮಗನೆಂದಾ ||\n\nಧಿಮಿ ಧಿಮಿ ಮಳ್ಳಿಗೆ ,ಧಿಮಾಕು ಜಾಜಿಗೆ ಕೋಲಣ್ಣಾ ಕೋಲ\nರಾಮನ‌ ನೆಂಟ\nಭೀಮೇಶ ಕ್ರಷ್ಣ\nಕೋಲಣ್ಣ ಕೋಲ ಕೋಲಣ್ಣ ಕೋಲ\n‌ ||ಕೋಲು||\n\n",english:"Composer : Harapanahalli Bhimavva\n\nKolu Krishna saagara shayana kolanna kola |\nsaaligramake haalabhisheka kolanna kola kollanna kola || kolu ||\n\nAttada melina nelavallaadisi sakkaregala savida |\nkrishna krishna nanendare bekkeno endaa\n\nBekkendoduta orolagidda hakkigalodisida,\nmakkalu malagyarebisabedene battalu baarisida ||kolu||\n\nHappala sandige haravida maneyali tappade taa poda |\nmuchidabyadi muttuvanalla appantavanalla ||\n\nSaarida maneyali sunnava chelli dhulanu haravida |\nkaalali rangoli haakide yashode not nodu baa endu kareda ||kolu ||\n\nAbhishekakenda arghyodaka tandare aachamana maadida |\npreetiyinda mantraakshyate ettare, shri tulasiya taa mudida |\n\nNyvedhyakendu amritanna msadalu baayterede endaa,\nnyvedhyakellaniyaagide yashode nodu baa endu karedaa || kolu||\n\nKajjaya maaduva allige hogi obbante taa ninta |\njajjirede tindu doora hogi nintu habbavu enenda ||\n\nObbane tindu olagiddavari jibbanu torisida |\nmajjige kallana hidi hidi endare ajjana maganenda || kolu||\n\nUppu saaku saaladu nodene appatavane medda |\ntuppada kallana hiding hidi endare, nimappana maganendaa |\n\nDhimi dhimi mallige, dhimaaku jaajige kolanna kola |\nramana nenta\nbhimesha krishna\nna kolanna kola kolanna kola || kolu ||\n\nClick the link to listen the song by Ramakrishna katukukke\n\n",meta:"",tags:["krishna","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=h3O4-YwK-PM"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಕೋಲು-ಕೃಷ್ಣ-ಸಾಗರ-ಶಯನ.json",
	rawData: "",
};

export { _internal, collection, data, id };
