const id = "ಗೋವಿಂದ-ಸಲಹೆನ್ನನು-ಸದಾನಂದ";
const collection = "bhajan";
const data = {kannada_title:"ಗೋವಿಂದ ಸಲಹೆನ್ನನು ಸದಾನಂದ",english_title:" Govinda salahennanu sadananda",kannada:"ಗೋವಿಂದ ಸಲಹೆನ್ನನು\nಸದಾನಂದಾ  ಗೋವಿಂದ ಸಲಹೆನ್ನನು ।।ಪ॥\n\nಗೋವಿಂದ ಸಲಹೆನ್ನ  ಕುಮುದ ಲೋಚನ\nನಿನ್ನ  ಸೇವಕರಡಿಯ  ಸೇವಕನಯ್ಯ  ಹರಿಯೇ ।।ಅ.ಪ ।।\n\nತಮನ ಸಂಹರಿಸಿ  ವೇದವ  ತಂದೆ ಗೋವಿಂದ\nಅಮರರಿಗೆ  ಒಲಿದು  ಅಮೃತವನಿತ್ತೆ  ಗೋವಿಂದ\nರಮಣಿಯ  ತಂದೆ ವರಹ  ರೂಪಿ ಗೋವಿಂದ\nಭ್ರಮಿಸಿ ಕಂಭದೊಳು  ಉದ್ಭವಿಸಿದೆ ಗೋವಿಂದ\nಕ್ಷಮೆಯನೆಳೆಯ  ಬ್ರಹ್ಮಚಾರಿ  ಆದೆ ಗೋವಿಂದ\nಸಮರದಲ್  ಅಖಿಲ ರಾಜರ  ಕೊಂದೆ  ಗೋವಿಂದ\nಕಮಲಾಕ್ಷ  ಕಡಲ ಕಟ್ಟಿದ  ದಿಟ್ಟ ಗೋವಿಂದ\nಮಮತೆಯೊಳ್  ಇಳೆಯ  ಗೋಗಳ  ಕಾಯ್ದೆ  ಗೋವಿಂದ\nರಮಣಿಯರಿಗೆ  ಒಲಿದು  ಬತ್ತಲೆ  ನಿಂತೆ  ಗೋವಿಂದ\nಅಮಿತ ವಾಹನ ಗೋವಿಂದ\nನಿಂದಿಪರಿಗೆ  ಶಮನನಂತಿಹ ಗೋವಿಂದ\nಇಂಗಡಲೊಳು  ರಮಿಸಿ ನಿದ್ರಿಪ ಗೋವಿಂದ\nಅರಿಯದಂತೆ  ವಿಮಲ ಜ್ಯೋತಿ ಗೋವಿಂದ\nಅಚ್ಯುತ ಸರ್ವೋತ್ತಮನೇ  ಚಿನ್ಮಯ ಗೋವಿಂದ\nಅಚಲ ಮುಕ್ತಿ  ಕ್ರಮವ ಭೋದಿಪ  ಗೋವಿಂದ\nಸತತ ಕಾಯೋ  ಕಮಲಾಲಿಂಗಿತ  ಗೋವಿಂದ\nಭಕುತಿಯಿಂದ ನಮೋಯೆಂಬೇ  ದಶಾವತಾರದ  ಗೋವಿಂದ ।।೧।।\n\nನರ  ಬೊಂಬೆಗಳ ಮಾಡಿ ಕುಣಿಸುವೆ ಗೋವಿಂದ\nನರರ  ನೋಡಿ  ನೋಡಿ ನಗುತಿಪ್ಪೆ ಗೋವಿಂದ\nಅರಿಯದಂತಖಿಳದೊಳಗಿಪ್ಪೆ ನೀ ಗೋವಿಂದ\nಪರಮ ಪಾವನನೆಂಬ ಬಿರುದುಳ್ಳ  ಗೋವಿಂದ\nಪರಮಾತ್ಮ  ಕರಿಯ ಮೇಘವ ಪೋಲ್ವ  ಗೋವಿಂದ\nಪರಮ ಪುರುಷೋತ್ತಮ  ನೀನೇ  ಗೋವಿಂದ\nಕರಿರಾಜ ಕರಿಯಲದಹಿ  ಬಂದೆ ಗೋವಿಂದ\nಮೊರೆ   ಹೊಕ್ಕ  ಭಕುತರ ಸಲಹೋದೆ  ಗೋವಿಂದ\nಅರಿಯನು ನಾನು  ನಿನ್ನವನೈಯ್ಯ ಗೋವಿಂದ\nಗರುಡ ವಾಹನ ಗೋವಿಂದ\nನಿನ್ನರಸಿಯು  ಅರಿಯದಂತಿಹೆ  ಗೋವಿಂದ\nಸತತ ನಿನ್ನ  ಸ್ಮರಣೆಗೈವೆನೋ  ಗೋವಿಂದ\nಸಾಸಿರ ಕೋಟಿ  ಸುರರ ಪೊರೆವ ಗೋವಿಂದ\nಗಂಗೆಯ ಪಡೆದ  ಚರಣ ನಿರ್ಗುಣ  ಗೋವಿಂದ\nಮುಕ್ತಿಯು ನಿನ್ನ ಚರಣವಲ್ಲವೇ  ಗೋವಿಂದ\nಶ್ರೀ ವೈಕುಂಠ  ಪುರದಲ್ಲಿರುವ ಗೋವಿಂದ\nಶರಣು ಸಿರಿ  ವರ\nಕಾಗಿನೆಲೆ  ಆದಿಕೇಶವ\nಶ್ರೀ ಕೃಷ್ಣ ।।೨।।\n\n",english:"Composer : Sri Kanaka dasaru\n\nGovinda salahennanu\nsadananda govinda salahennanu ||pa||\n\nGovinda salahenna kumuda lochana\nninna sevakaradiya sevakanayya hariye ||a.pa||\n\nTamana samharisi vedava tande govinda\namararige olidu amrutavanitte govinda\nramaniya tande varaha roopi govinda\nbhramisi kambhadolu govinda\nkshameyaneleya brahmachari ade govinda\nsamaradol akhila rajara konde govinda\nkamalaksha kadala kattida ditta govinda\nmamteyol eleya gogala kayda govinda\nramaniyarige olidu battale ninte govinda\namita vahana govinda\nnindiparige shamananantiha govinda\ningadalolu ramisi nidripa govinda\nariyadante vimala jyoti govinda\nachyuta sarvottamane chinmaya govinda\nachala mukti kramava bhodipa govinda\nsatata kayo kamalalingita govinda\nbhakutiyinda namoyembe dashavatarada govinda ||1||\n\nNara bombegala madi kunisuve govinda\nnarara nodi nodi nagutippe nee govinda\nariyadantakhiladolagippe nee govinda\nparama pavananemba birudulla govinda\nparamatma kariya meghava polva govinda\nparama puroshottama nene govinda\nkariraja kariyaladahi bande govinda\nmore hokka bhakutara salahode govinda\nariyanu nanu ninnavanaiyya  govinda\ngaruda vahana govinda\nninnarasiyu ariyadantihe govinda\nsatata ninna smaranegaiveno govinda\nsasira koti surara poreva govinda\ngangeya padeda charana nirguna govinda\nmuktiyu ninna charanavallave govinda\nsri vaikunta puradalliruva govinda\nsharanu siri vara\nkaginele adikeshava\nsri krishna ||2||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=Pc4AwjDXCg4"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಗೋವಿಂದ-ಸಲಹೆನ್ನನು-ಸದಾನಂದ.json",
	rawData: "",
};

export { _internal, collection, data, id };
