const id = "ಗರುಡ-ಗಮನ-ತವ";
const collection = "bhajan";
const data = {kannada_title:"ಗರುಡ ಗಮನ ತವ",english_title:" Garuda gamana tava",kannada:"ಗರುಡ ಗಮನ ತವ\nಚರಣ ಕಮಲ ಮಿಹ..\nಮನಸಿ ಲಸತು ಮಮ ನಿತ್ಯಂ..\nಮನಸಿ ಲಸತು ಮಮ ನಿತ್ಯಂ..\nಮಮ ತಾಪಮಪಾಕುರು ದೇವಾ ||\nಮಮ ಪಾಪಮಪಾಕುರು ದೇವಾ ||\n\nಜಲಜ ನಯನ ವಿಧಿ..\nನಮುಚಿ ಹರಣ ಮುಖ..\nವಿಭುದ ವಿನುತ ಪದಪದ್ಮ..\nಮಮ ತಾಪಮಪಾಕುರು ದೇವಾ\nಮಮ ಪಾಪಮಪಾಕುರು ದೇವಾ ||\n\nಭುಜಗ ಶಯನ ಭವ ಮದನ ಜನಕ ಮಮ\nಜನನ ಮರಣ ಭಯಹಾರಿ..\nಜನನ ಮರಣ ಭಯಹಾರಿ..\nಮಮ ತಾಪಮಪಾಕುರು ದೇವಾ\nಮಮ ಪಾಪಮಪಾಕುರು ದೇವಾ ||\n\nಶಂಖ ಚಕ್ರಧರ, ದುಷ್ಟ ದೈತ್ಯ ಹರ\nಸರ್ವಲೋಕ ಶರಣಾ..\nಸರ್ವಲೋಕ ಶರಣಾ..\nಮಮ ತಾಪಮಪಾಕುರು ದೇವಾ\nಮಮ ಪಾಪಮಪಾಕುರು ದೇವಾ ||\n\nಅಗಣಿತ ಗುಣಗಣ ಅಶರಣ ಶರಣದ\nವಿದಳಿತ ಸುರರಿಪುಜಾಲ..\nವಿದಳಿತ ಸುರರಿಪುಜಾಲ..\nಮಮ ತಾಪಮಪಾಕುರು ದೇವಾ\nಮಮ ಪಾಪಮಪಾಕುರು ದೇವಾ ||\n\nಭಕ್ತ ವರ್ಯ ಮಿಹ ಭೂರಿ ಕರುಣಯಾ\nಪಾಹಿ ಭಾರತೀ ತೀರ್ಥಂ..\nಪಾಹಿ ಭಾರತೀ ತೀರ್ಥಂ..\nಮಮ ತಾಪಮಪಾಕುರು ದೇವಾ\nಮಮ ಪಾಪಮಪಾಕುರು ದೇವಾ ||\n\n",english:"Below have provided lyrics of Shri Vishnu Stotra by His Holiness Shri Bharathi Teertha Mahaswamiji of Sringeri…..\n\nGaruda gamana tava\nCharana kamala miha\nManasila sathu mama nithyam\nManasila sathu mama nithyam II\nMama taapamapaakuru deva\nMama paapamapaakuru deva II\nJalaja nayana vidhi\nNamuchi harana mukha\nVibudhavinutha padapadma\nVibudhavinutha padapadma\nMama taapamapaakuru deva\nMama paapamapaakuru deva II\n\nBhujaga sayana bhava\nMadana janaka mama\nJanana marana bhaya haari\nJanana marana bhaya haari\nMama taapamapaakuru deva\nMama paapamapaakuru deva II\nShankachakradhara\nDushta daitya hara\nSarva loka sarana\nSarva loka sarana\n\nMama taapamapaakuru deva\nMama paapamapaakuru deva II\n\nAganita gunagana\nAsarana saranada\nVidalita suraripujaala jaala\nVidalita suraripujaala jaala\n\nMama taapamapaakuru deva\nMama paapamapaakuru deva II\n\nBhaktavarya miha\nBhoori karuna yaa\nPaahi bharathi teertham\nPaahi bharathi teertham\n\nGaruda gamana tava\nCharana kamala miha\nManasi lasathu mama nithyam\nManasi lasathu mama nithyam II\n\nMama taapamapaakuru deva\nMama paapamapaakuru deva II\n\nMama taapamapaakuru deva\nMama paapamapaakuru deva II\n\nYoutube link\n:\nhttps://youtu.be/8JvjBsYbkrY\nby Kuruvada sisters\n\n",meta:"",tags:["shankaracharyaru","kannada devotional song","kannada lyrics"],media:"https://www.youtube.com/watch?v=8JvjBsYbkrY"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಗರುಡ-ಗಮನ-ತವ.json",
	rawData: "",
};

export { _internal, collection, data, id };
