const id = "ಗುಮ್ಮನ-ಕರೆಯದಿರೆ-ಅಮ್ಮ-ನೀನು";
const collection = "bhajan";
const data = {kannada_title:"ಗುಮ್ಮನ ಕರೆಯದಿರೆ ಅಮ್ಮ ನೀನು",english_title:" gummana kareyadire amma neenu",kannada:"ಹರಿದಾಸರಿಗೆ ಭಗವಂತನನ್ನು ಎಷ್ಟು ಪರಿಪರಿಯಾಗಿ ಬಣ್ಣಿಸಿದರೂ ಸಾಲದು.ಅದರಲ್ಲೂ ಕೃಷ್ಣನ ಬಾಲ್ಯದ ಆಟೋಟ,ತುಂಟಾಟ, ರಂಪಾಟಗಳನ್ನು ಸಾವಿರಾರು ಕೃತಿ ಕೀರ್ತನೆಗಳಲ್ಲಿ ಬಣ್ಣಿಸಿದ್ದಾರೆ.ಅಂತಹ ಪುರಂದರದಾಸರ ಸುಪ್ರಸಿದ್ದ ರಚನೆ…\n\n“ಗುಮ್ಮನ ಕರೆಯದಿರೆ|ಅಮ್ಮ ನೀನು ಗುಮ್ಮನ ಕರೆಯದಿರೆ…..”.\n\nಗುಮ್ಮನ ಕರೆಯದಿರೆ| ಅಮ್ಮ ನೀನು\nಗುಮ್ಮನ ಕರೆಯದಿರೆ ||ಪ||\n\nಸುಮ್ಮನೆ ಇದ್ದೇನು| ಅಮ್ಮಿಯ ಬೇಡೆನು|\nಮಮ್ಮು ಉಣುತೇನೆ ಅಮ್ಮ ಅಳುವುದಿಲ್ಲ ||ಅ||\n\nಹೆಣ್ಣುಗಳಿರುವಲ್ಲಿಗೆ ಹೋಗಿ ಅವರ\nಕಣ್ಣು ಮುಚ್ಚುವುದಿಲ್ಲವೆ|\nಚಿಣ್ಣರ ಬಡಿಯೆನು|\nಅಣ್ಣನ ಬೈಯೆನು ಬೆಣ್ಣೆಯ ಬೇಡೆನು|\nಮಣ್ಣು ತಿನ್ನುವುದಿಲ್ಲ ||೧||\n\nಬಾವಿಗೆ ಹೋಗೆ ಕಾಣೆ| ಅಮ್ಮ ನಾನು ಹಾವಿನೊಳಾಡೆ ಕಾಣೆ|ಆವಿನ\nಮೊಲೆಯೂಡೆ| ಕರುಗಳ ಬಿಡೆ ನೋಡೆ|\nದೇವರಂತೆ ಒಂದು ಠಾವಿಗೆ ಕೂಡುವೆ ||೨||\n\nಮಗನ ಮಾತನು ಕೇಳುತ ಗೋಪೀದೇವಿ|\nಮುಗುಳುನಗೆಯ ನಗುತ ಜಗದೊಡೆಯ\nಶ್ರೀ ಪುರಂದರವಿಠಲ\nನ ಬಿಗಿದಪ್ಪಿಕೊಂಡಳು ಮೋಹದಿಂದಾಗ ||೩|\n\n",english:"Composer : Purandaradasaru\n\nGummana kareyadhire amma ninu\ngummana kareyadhire\ngummana kareyadhire amma ninu\ngummana kareyadhire\n\nsummane idhenu ammiya bedenu\nmammu unuthene amma aluvudhilla\ngummana kareyadhire amma ninu\ngummana kareyadhire\n\nhenugaliruvallige hogi\navara kanu muchuvudhillave\nhenugaliruvallige hogi\navara kannu muchuvudhillave\nchinara badiyenu anana baiyenu\nbeneya bedenu manu thinnuvudhilla\ngummana kareyadhire amma ninu\ngummana kareyadhire\n\nbaavige hoge kaane amma naanu\nhaavinolade kaane\nbaavige hoge kaane amma naanu\nhaavinolade kaane\nAvina moleyude karugala bide node\ndhevaramthe ondhu taavige kuruve\ngummana kareyadhire amma ninu\ngummana kareyadhire\n\nmagana maathanu  kelutha gopidhevi\nmugulu naguvu naguthaa\njagadhodeya shri puramdharavitalana\njagadhodeya shri puramdharavitalana\nbigidhappikomdalu mohadhidhaaga\ngummana kareyadhire amma ninu\ngummana kareyadhire\n\n*********************\n\nSung By Smt. S. Janaki and Sri Vidyabhushanaru\n\n",meta:"",tags:["krishna","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=gzNF6sl54K8"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಗುಮ್ಮನ-ಕರೆಯದಿರೆ-ಅಮ್ಮ-ನೀನು.json",
	rawData: "",
};

export { _internal, collection, data, id };
