const id = "ಚಂದ್ರಚೂಡ-ಶಿವಶಂಕರ-ಪಾರ್ವತಿ";
const collection = "bhajan";
const data = {kannada_title:"ಚಂದ್ರಚೂಡ ಶಿವಶಂಕರ ಪಾರ್ವತಿ",english_title:" Chandrachooda shivashankara parvati",kannada:"ರಚನೆ : ಪುರಂದರದಾಸರು\n\nಚಂದ್ರಚೂಡ ಶಿವಶಂಕರ ಪಾರ್ವತಿ ರಮಣನೆ ನಿನಗೆ ನಮೋ ನಮೋ || ಪ ||\n\nಸುಂದರ ಮೃಗಧರ ಪಿನಾಕ ಧನುಕರ ಗಂಗಾ ಶಿರ\nಗಜಚರ್ಮಾಂಬರಧರ ನಮೋ ನಮೋ || ಅ ಪ ||\n\nನಂದಿವಾಹನಾನಂದದಿಂದ ಮೂಜಗದಿ ಮೆರವೆ ನೀನೇ\nಅಂದು ಅಮೃತ ಘಟದಿಂದುದಿಸಿದ ವಿಷ ತಂದು ಭುಜಿಸಿದವ ನೀನೇ\nಕಂದರ್ಪನ ಕ್ರೋಧದಿಂದ ಕಣ್ತೆರೆದು ಕೊಂದ ಉಗ್ರನು ನೀನೇ\nಇಂದಿರೇಶ ಶ್ರೀ ರಾಮನ ಪಾದವ ಚಂದದಿ ಪೊಗಳುವ ನೀನೇ || ೧ ||\n\nಬಾಲಮೃಕಂಡಜನ ಕಾಲನು ಎಳೆವಾಗ ಪಾಲಿಸಿದವ ನೀನೇ\nವಾಲಯದಿ ಕಪಾಲ ಪಿಡಿದು ಭಿಕ್ಷೆ ಬೇಡೋ ದಿಗಂಬರ ನೀನೇ\nಕಾಲಕೂಟವ ಪಾನಮಾಡಿದ ನೀಲಕಂಠನು ನೀನೇ\nಜಾಲ ಮಾಡಿದ ಗೋಪಾಲನೆಂಬ ಹೆಣ್ಣಿಗೆ ಮರುಳಾದವ ನೀನೇ || ೨ ||\n\nಧರೆಗೆ ದಕ್ಷಿಣ ಕಾವೇರಿತೀರ ಕುಂಭಪುರವಾಸನು ನೀನೇ\nಕೊರಳೋಳು ಭಸ್ಮ ರುದ್ರಾಕ್ಷಿಯ ಧರಿಸಿದ ಪರಮ ವೈಷ್ಣವ ನೀನೆ\nಕರದಲಿ ವೀಣೆಯ ನುಡಿಸುವ ನಮ್ಮ ಉರಗಭೂಷಣನು ನೀನೇ\nಗರುಡಗಮನ\nಶ್ರೀ ಪುರಂದರವಿಠಲ\nಗೆ ಪ್ರಾಣಪ್ರಿಯನು ನೀನೆ || ೩||\n\n",english:"Composed by – Sree Purandara Dasaru\n\nChandrachuda Sivasankara parvati ramanane ninage namo namo || pa ||\n\nsundara mrugadhara pinaaka dhanukara ganga sira\ngajacharmambaradhara namo namo || a pa ||\n\nnandivahana nandadinda mujagadi merave nine\nandu amruta ghatadindudisida visha tandu bhujisidava nine\nkandarpana krodhadinda kanteredu konda ugranu nine\nindiresa sree ramana paadava chandadi pogaluva neene || 1 ||\n\nbalamrukandajana kaalanu elevaaga paalisidava nine\nvalayadi kapala pididu bhikshe bedo digambara nine\nkalakutava paanamadida nilakamthanu nine\njala madida gopalanemba hennige maruladava nine || 2 ||\n\ndharege dakshina kaveri teera kumbhapuravasanu nine\nkoralolu bhasma rudrakshiya dharisida parama vaishnava nine\nkaradali veeneya nudisuva namma uragabhushananu neene\ngarudagamana\nshree purandara vithala\nge pranapriyanu neene || 3||\n\n*********************\n\n",meta:"",tags:["shiva","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=WvKN39ZAJaw"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಚಂದ್ರಚೂಡ-ಶಿವಶಂಕರ-ಪಾರ್ವತಿ.json",
	rawData: "",
};

export { _internal, collection, data, id };
