const id = "ಜನ್ಮ-ಸಫಲವಾಯಿತು";
const collection = "bhajan";
const data = {kannada_title:"ಜನ್ಮ ಸಫಲವಾಯಿತು",english_title:" Janma saphalavayitu",kannada:"ಜನ್ಮ ಸಫಲವಾಯಿತು || ಪ ||\nಆದಿ ಅನಂತ ಜನಾರ್ದನನ ಕಂಡು\nಎನ್ನ ಜನ್ಮ ಸಫಲವಾಯಿತು || ಅ ಪ ||\nಬ್ರಹ್ಮಾನಂದ ಸುಗುಣ ನಿಮ್ಮ ಮಹಿಮೆ ಅ-\nಗಮ್ಯ ಗೋಚರನೆಂದು ಸ್ತುತಿಸುತಿರೆ\nಬ್ರಹ್ಮ ರುದ್ರಾದಿಗಳು ಇಂದ್ರ ಚಂದ್ರಾದಿಗಳು\nನಿರ್ಮಲಮೂರುತಿ ನಿಮ್ಮ ನಿಜವ ತೋರಿದ ಮ್ಯಾಲೆ || 1 ||\nಚತುರಮುಖನು ಬಂದು ಪೃಥಿವಿ ಒಳಗೆ ನಿಂದು\nಕ್ರತುಗಳ ಮಾಡಿ ಆಹುತಿ ಕೊಡಲು\nಅತಿಗ್ರಾಸವಾಯಿತೆಂದು ಅನಲ ಬಂದು ಮೊರೆಯಿಡಲು\nದ್ವಿತೀಯ ಗ್ರಾಸಕೆ ಕೈಯ ಒಡ್ಡಿ ನಿಂತದ್ದು ಕಂಡು || 2 ||\nಮೊದಲ ಬಾಗಿಲಲಿ ನಿಮ್ಮ ಮುಖಕಮಲವ ಕಂಡೆ\nಮುದದಿಂದ ಮಕರ ಕುಂಡಲ ಕಿರೀಟವ ಕಂಡೆ\nಭುಜದ್ವಯವನು ಕಂಡೆ ಶ್ರೀವತ್ಸ ಕೌಸ್ತುಭ ಕೊರಳ\nವೈಜಯಂತೀ ಮಾಲಿಕೆಗಳ  ಕಂಡು ಎನ್ನ || 3 ||\nನಡುವಿನ ಬಾಗಿಲಲಿ ನಾಭಿಕಮಲ ಕಂಡೆ\nಉದ್ಭವಿಸಿ ಮೆರೆವ ವಿರಿಂಚಿಯ ಕಂಡೆ\nಜಡಿವೊ ಪೀತಾಂಬರ ನಡುವಿನೊಡ್ಯಾಣವ\nಉಡಿಗೆಜ್ಜೆ ಮೇಲಿನ ಕಿರುಗೆಜ್ಜೆಗಳ ಕಂಡು || 4 ||\nಮೂರನೆ ಬಾಗಿಲಲಿ ಮುದ್ದು ಶ್ರೀ ಚರಣವು\nಶ್ರೀದೇವಿ ಭೂದೇವಿ ಸೇವೆ ಮಾಳ್ಪುದ ಕಂಡೆ\nಸುರರು ಮಾನವರ ಕಂಡೆ ಸ್ತೋತ್ರಮಾಳ್ಪದ ಕಂಡೆ\nಉರಗಶಯನ ಮ್ಯಾಲೆ\nಹಯವದನ\nನ ಕಂಡು ಎನ್ನ || 5 ||\n\n",english:"Composer : Sri Vadirajaru\n\nJanma saphalavayitu ||pa||\n\nAdi ananta janardhanana kandu\nenna janma saphalavayitu ||a.pa||\n\nBrahmananda suguna nimma mahime\nagamya gocharanendu stutisutire\nbrahma rudradigalu indra chandradigalu\nnirmala mooruti nimma nijava torida myale ||1||\n\nChatura mukhanu bandu prithvi olage nindu\nkrutugala madi aahuti kodalu\natigrasavayitendu anala bandu moreyidalu\ndwiteeya grasake kaiyya oddi nintaddu kandu ||2||\n\nmodala bagilali nimma mukhakamalava kande\nmudadinda makara kundala kireetava kande\nbhujadwayavanu kande srivatsa koustubha korala\nvaijayanti malikegala kandu enna ||3||\n\nnaduvina bagilali nabhikamala kande\nudhbhavisi mereva virinchiya kande\njadiva pitambhara naduvinodyanava\nudigejje melina kirugejjegala kandu ||4||\n\nMoorane bagilali muddu sri charanavu\nsridevi bhudevi seve malpuda kande\nsuraru manavara kande stotra malpuda kande\nuragashayana myale\nhayavadana\nna kandu enna ||\n\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=7JLVIJpzx8k"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಜನ್ಮ-ಸಫಲವಾಯಿತು.json",
	rawData: "",
};

export { _internal, collection, data, id };
