const id = "ಜಯ-ಜನಾರ್ಧನ-ಕೃಷ್ಣ";
const collection = "bhajan";
const data = {kannada_title:"ಜಯ ಜನಾರ್ಧನ ಕೃಷ್ಣ",english_title:"Jaya janardhana krishna",kannada:"ಜಯ ಜನಾರ್ಧನ ಕೃಷ್ಣ ರಾಧಿಕಾಪತೇ\nಜನ ವಿಮೋಚನ ಕೃಷ್ಣ ಜನ್ಮ ಮೋಚನ\nಗರುಡ ವಾಹನ ಕೃಷ್ಣ ಗೋಪಿಕಾ ಪತೇ\nನಯನ ಮೋಹನ ಕೃಷ್ಣ ನೀರಜೇಕ್ಷಣ\n\nಸುಜನ ಬಾಂಧವ ಕೃಷ್ಣ ಸುಂದರ ಕೃತೆ\nಮದನ ಕೋಮಲ ಕೃಷ್ಣ ಮಾಧವ ಹರೇ\nವಸುಮತಿ ಪತೇ ಕೃಷ್ಣ ವಾಸವಾನುಜ\nವರಗುಣಾಕರ ಕೃಷ್ಣ ವೈಷ್ಣವಾಕೃತೆ\n\nಸುರಚಿರಾನನ ಕೃಷ್ಣ ಶೌರ್ಯವಾರಿಧೆ\nಮುರಹರ ವಿಭೋ ಕೃಷ್ಣ ಮುಕ್ತಿದಾಯಕ\nವಿಮಲಪಾಲಕ ಕೃಷ್ಣ ವಲ್ಲಭಿಪತೆ\nಕಮಲಲೋಚನಾ ಕೃಷ್ಣ ಕಾಮ್ಯದಾಯಕ\n\nವಿಮಾಲಗಾತ್ರನೇ ಕೃಷ್ಣ ಭಕ್ತವತ್ಸಲ\nಚರಣ ಪಲ್ಲವಂ ಕೃಷ್ಣ ಕರುಣ ಕೋಮಲಮ್\nಕುವಲೈಕ್ಷಣ ಕೃಷ್ಣ ಕೋಮಲಾಕೃತೆ\nತವ ಪದಾಮ್ಬುಜಂ ಕೃಷ್ಣ ಶರಣಾಮಾಶ್ರಯೆ\n\nಭುವನ ನಾಯಕ ಕೃಷ್ಣ ಪಾವನಾಕೃತೆ\nಗುಣಗಣೋಜ್ವಲಾ ಕೃಷ್ಣ ನಳಿನಲೋಚನ\nಪ್ರಣಯವಾರಿಧೆ ಕೃಷ್ಣ ಗುಣಗಣಾಕರ\nದಾಮಸೋದರ ಕೃಷ್ಣ ದೀನ ವತ್ಸಲ\n\nಕಾಮಸುಂದರ ಕೃಷ್ಣ ಪಾಹಿ ಸರ್ವಾದಾ\nನರಕನಾಶನ ಕೃಷ್ಣ ನರಸಹಾಯಕ\nದೇವಕಿಸುತ ಕೃಷ್ಣ ಕಾರುಣ್ಯಾಂಭುದೇ\nಕಂಸಾನಾಶನ ಕೃಷ್ಣ ದ್ವಾರಕಾಸ್ಥಿತ\n\nಪಾವನಾತ್ಮಕ ಕೃಷ್ಣ ದೇಹಿ ಮಂಗಳಂ\nತ್ವತ್ ಪದಾಮ್ಬುಜಂ ಕೃಷ್ಣ ಶ್ಯಾಮ ಕೋಮಲಮ್\nಭಕ್ತವತ್ಸಲ ಕೃಷ್ಣ ಕಾಮ್ಯದಾಯಕ\nಪಾಲಿಸೆನ್ನನೂ ಕೃಷ್ಣ ಶ್ರೀಹರಿ ನಮೋ\n\nಭಕ್ತದಾಸ ನಾ ಕೃಷ್ಣ ಹರಸು ನೀ ಸದಾ\nಕಾದು ನಿಂತೇನಾ ಕೃಷ್ಣ ಸಲಹೆಯಾ ವಿಭೋ\nಗರುಡ ವಾಹನ ಕೃಷ್ಣ ಗೋಪಿಕಾ ಪತೇ\nನಯನ ಮೋಹನ ಕೃಷ್ಣ ನೀರಜೇಕ್ಷಣ\n\n",english:"Jaya janardhana krishna radhika pathe |Jana vimochana krishna janma mochana |Garuda vahana krishna gopika pathe |Nayana mohana krishna neerajekshana ||\n\nSujana bandhava krishna sundarakruthe |Madana komala krishna madhava hare | Vasumati pathe krishna vasavanuja Varagunakara krishna vaishnavakruthe |Suruchiranana krishna shouryavaridhe |Murahara vibho krishna mukthidayaka | Vimalapalaka krishna vallabhipathe |\nKamalalochana krishna kamyadayaka ||\n\nVimalagatrane krishna bhaktavatsala| Charana pallavam krishna karuna komalam | kuvalaikshana krishna komalakruthe tava padambujam krishna sharanamashraye | bhuvana nayaka krishna pavanakruthe |\nGunaganojwala krishna nalinalochana |pranayavaridhe krishna gunaganakara damasodara krishna deena vatsala ||\n\nKamasundara krishna pahi sarvadan narakanashana krishna narasahayaka | Devaki sutha krishna karunyambhude |kamsanashana krishna dwaraksthitha pavanatmaka krishna dehi mangalam |\nTvatpadambujam krishna shyama komalam |\nBhaktavatsala krishna kamyadayaka palisennanu krishna srihari namo ||\n\nBhaktadasa naa krishna harasu nee sada |kadu ninthena krishna salaheya vibho | Garuda vahana krishna gopika pathe |Nayana mohana Krishna neerajekshana ||\n\n\n",meta:"",tags:["kannada devotional song","kannada lyrics"],media:"https://www.youtube.com/watch?v=YltMEcUufK0"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಜಯ-ಜನಾರ್ಧನ-ಕೃಷ್ಣ.json",
	rawData: "",
};

export { _internal, collection, data, id };
