const id = "ಜೈ-ಜೈ-ಹನುಮಾನ್-ಜೈ-ಗುರು";
const collection = "bhajan";
const data = {kannada_title:"ಜೈ ಜೈ ಹನುಮಾನ್ ಜೈ ಗುರು",english_title:" Jai jai hanuman jai guru jai",kannada:"ಮನೋಜವಂ ಮಾರುತ ತುಲ್ಯ ವೇಗಂ | ಜಿತೇಂದ್ರಿಯಂ ಬುಧ್ಧಿಮತಾಂ ವರಿಷ್ಠಂ\nವಾತಾತ್ಮಜಂ ವಾನರ ಯೂಥ ಮುಖ್ಯಂ | ಶ್ರೀ ರಾಮ ಧೂತಂ ಶಿರಸಾ ನಮಾಮಿ\nಬುಧ್ಧಿರ್ಬಲಂ ಯಶೋಧೈರ್ಯಂ | ನಿರ್ಭಯತ್ವಂ ಅರೋಗತ\nಅಜಾಡ್ಯಂ ವಾಕ್ಪಟುತ್ವಂಚ | ಹನುಮತ್ ಸ್ಮರಣಾತ್ ಭವೇತ್ ||\n\nಜೈ ಜೈ ಹನುಮಾನ್ ಜೈ ಗುರು ಜೈ ಜೈ ಪವಮಾನ್ ||4 times||\nಪವನ್ ಪುತ್ರ ಹನುಮಾನ್ ಕೀ ಜೈ\n\nಆಂಜನೇಯ ಜೈ, ಬಲಭೀಮ ಜೈ, ಭಕ್ತರ ಅತುಲಿಥ ಬಲಧಾಮ ಜೈ\nಹನುಮಂತ ಜೈ, ಎಮ್ಮ ರಕ್ಷಿಸೊ ನೀ, ರಾಮ ವಿರೋಧಿಗಳನ್ನು ಶಿಕ್ಷಿಸೋ ||\n|| ಆಂಜನೇಯ||\n\nಜೈ ಹನುಮಾನ್…. ಜೈ ಪವಮಾನ್…\n\nಬುಧ್ಧಿರ್ ಬಲ ಧೈರ್ಯಗಳ ಕರುಣಿಸೊ ,ಜೈ ಜೈ ಹನುಮಾನ್ ಜೈ ಗುರು ಜೈ ಜೈ ಪವಮಾನ್\nನಿರ್ಭಯತ್ವ ಆರೋಗ್ಯ ಕರುಣಿಸೊ, ಜೈ ಜೈ ಹನುಮಾನ್ ಜೈ ಗುರು ಜೈ ಜೈ ಪವಮಾನ್\nವಾಕ್ಪಟುತ್ವ ಹರಿ ಸ್ಮರಣೆ ಕರುಣಿಸೊ, ಜೈ ಜೈ ಹನುಮಾನ್ ಜೈ ಗುರು ಜೈ ಜೈ ಪವಮಾನ್\nಶ್ರೀರಾಮ ದರುಶನ ಭಾಗ್ಯ ಕರುಣಿಸೊ, ಜೈ ಜೈ ಹನುಮಾನ್ ಜೈ ಗುರು ಜೈ ಜೈ ಪವಮಾನ್ಭ ||\n||ಆಂಜನೇಯ||\nಜೈ ಶ್ರೀ ರಾಮ್. ..ಜೈ ಶ್ರೀ ರಾಮ್\n\nರಾಮ ಸ್ಮರಣೆ ಕೊಡು, ಶ್ರೀರಾಮ್ ಜೈ ರಾಮ್ ಜೈ ಜೈ ರಾಮ್\nರಾಮ ಸೇವೆಯ ಕೊಡು, ಶ್ರೀರಾಮ್ ಜೈ ರಾಮ್ ಜೈ ಜೈ ರಾಮ್\nರಾಮಾಯಣದ ಕಥೆಯೊಳು ಬಂದು ಕೂಡು, ಜೈ ಜೈ ಹನುಮಾನ್\nಜೈ ಗುರು ಜೈ ಜೈ ಪವಮಾನ್ ||ರಾಮ ಸ್ಮರಣೆ||\n\nದಾಸ ಕೇಶವ ಸುತ ಮಾರುತಿ ಹನುಮ | ಹನುಮಂತ ಗುಣವಂತ\nಮಾರುತಿರಾಯ ಬಲವಂತ | ದಾಸಕೇಶವ ಸುತ ಮಾರುತಿ ಹನುಮ\nದಾಸಗ್ರೇಶರ ಜೈ ಬಲಭೀಮ, ಜೈ ಜೈ ಹನುಮಾನ್\nಜೈ ಗುರು ಜೈ ಜೈ ಪವಮಾನ್, ಪವನ್ ಪುತ್ರ್ ಹನುಮಾನ್ ಕೀ ಜೈ\n||ಜೈ ಹನುಮಾನ್||\n\n",english:"Manojavam marutatulya vegam | jitendriyam budhimataam varishtam | vaataatmajam vanarayutha mukhyam | srirama dhutam shirasa namaami | budhirbalam yashodhairyam | nirbhayatvam arogatam ajaadayam vaakpatutvam cha | hanumat smaranat bhavet ||\n\nJai jai hanuman jai guru jai jai pavamaan || 4 times || pavanaputra hanuman ki jai ||\n\nAnjaneya jai, balabheema jai, bhaktara atulitha phaladhamaa jai | hanumanta jai, emma rakshiso nee, rama virodhigala shikshiso || anjaneya ||\n\nJai hanumaan …… jai pavamaan …..\n\nBudhirbala dhairyagala karuniso, jai jai hanuman jai guru jai jai pavamaan | nirbhayatva arogya karuniso  jai jai hanuman jai guru jai jai pavamaan | vaakpatutva hari smarane karuniso,  jai jai hanuman jai guru jai jai pavamaan | srrama darushana bhagya karuniso,  jai jai hanuman jai guru jai jai pavamaan || Anjaneya || jai sri ram …. jai sri ram\n\nRaama smarane kodo, sri ram jai ram jai jai ram | rama seveya kodo, sri ram jai ram jai jai ram | ramayanada katheyolu bandu kodo, jai jai hanuman | jai guru jai jai pavaman || rama smarane ||\n\nDaasa keshava suta maruti hanuma | hanumanta gunavanta marutiraya bhalavanta | dasakeshava suta maruti hanuma | dasagreshara jai bhalabheema, jai jai hanuman | jai guru jai jai pavaman | pavana putra hanuman ki jai || jai hanuman ||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=Q42FDw3W-L4"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಜೈ-ಜೈ-ಹನುಮಾನ್-ಜೈ-ಗುರು.json",
	rawData: "",
};

export { _internal, collection, data, id };
