const id = "ಜಯ-ಕೋಲ್ಹಾಪುರ-ನಿಲಯೇ";
const collection = "bhajan";
const data = {kannada_title:"ಜಯ ಕೋಲ್ಹಾಪುರ ನಿಲಯೇ",english_title:" jaya kolhapura nilaye",kannada:"ಜಯ ಕೊಲ್ಹಾಪುರ ನಿಲಯೇ ಭಜದಿಷ್ಟೇತರವಿಲಯೇ\nತವಪಾದೌ ಹೃದಿಕಲಯೇ ರತ್ನ ರಚಿತ ವಲಯೇ ।।ಪ ।।\n\nಜಯ ಜಯ ಸಾಗರಜಾತೇ ಕುರು ಕರುಣಾಮಯಿಭೀತೆ\nಜಗದಂಬಾಭಿದಯಾತೆ ಜೀವತಿ ತವ ಪೋತೆ ।।೧।।\n\nಜಯ ಜಯ ಸಾಗರ ಸದನ ಜಯ ಕಾಂತ್ಯಾಜಿತ ಮದನಾ\nಜಯ ದುಷ್ಟಾಂತಕ ಕದನ ಕುಂದಮುಕುಲರದನ ।।೨।।\n\nಸುರರಮಣಿ ನುತಚರಣೇ ಸುಮನಃ ಸಂಕಟ ಹರಣೇ\nಸುಸ್ವರ ರಂಜಿತವೀಣೇ ಸುಂದರ ನಿಜ ಕಿರಣೇ।।೩।।\n\nಭಜದಿಂದೀವರ ಸೋಮಾ ಭವ ಮುಖ್ಯಾಮರಕಾಮಾ\nಭಯ ಮೂಲಾಳಿವಿರಾಮಾ ಭಂಜಿಕ ಮುನಿಭೀಮಾ ।।೪।।\n\nಕುಂಕುಮ ರಂಜಿತಘಾಲೇ ಕುಂಜರ ಬಾಂಧವಲೋಲೆ\nಕಲಧೌತೌಮಲಚೈಲೇ ಕೃನ್ತಕುಜನಜಾಲೆ ।।೫।।\n\nಧ್ರಿತ ಕರುಣಾರಸಪೂರೇ ಧನದಾನೋತ್ಸವ ಧೀರೇ\nಧ್ವನಿಲವನಿಂದಿತಕೀರೆ ಧೀರೆದನುಜಧಾರೇ।।೬।।\n\nಸುರ ಹೃತ್ಪಂಜರಕೀರಾ ಸುಮಗೇ ಹಾರ್ಪಿತ ಹಾರ\nಸುಂದರ ಕುಂಜ ವಿಹಾರ ಸುರವರ ಪರಿವಾರ ।।೭।।\n\nವರ ಕಬರಿ ಧ್ರಿತ ಕುಸುಮೆ ವಾರಕನಕಾಧಿಕಸುಶುಮೇ\nವನನಿಲಯಾ ದಯಭೀಮೇ ವದನ ವಿಜಿತ ಸೋಮೇ।।೮।।\n\nಮದಲಕ ಭಾಲಸಗಮನೆ ಮಧು ಮಥನಾಲಸ ನಯನೇ\nಮೃದುಲೋಲಾಲಕ ರಚನೇ ಮಧುರ ಸರಸ ಗಾನೇ।।೯।।\n\nವ್ಯಾಘ್ರ ಪುರೀ ವರ ನಿಲಯೇ ವ್ಯಾಸಪದಾರ್ಪಿತ ಹೃದಯೇ\nಕುರು ಕರುಣಾಮಹಿಸದಯೇ ವಿವಿಧ ನಿಗಮ ಗೆಯೇ।।೧೦ ||\n\n",english:"Jaya kolhapura nilaye bajadhishtetaravilaye\ntavapadau hridikalaye ratna rachita valeye || pa||\n\njaya jaya sagarajate kuru karunamayibhite\njagadambabhidhyate jivati tavapote || 1||\n\njaya jaya sagarasadana jaya kantyajita madana\njaya dushtantaka kadana kundamukularadana ||2||\n\nsuraramani nutacharane sumanah sankataharane\nsuswara ranjitaveene sundara nijakirane || 3||\n\nbhajadindivara soma bhava mukhyamarakama\nbhaya muialivirama bhanjika munibhima ||4||\n\nkumkuma ranjitafale kunjara bandavalole\nkaladhautaumalachaile krintakujanajale ||5||\n\ndhrita karunarasapure dhanadanotsava dhire\ndhvanilavaninditakire dhiredanujadare ||6||\n\nsura hrutpanjarakira sumageharpita hara\nsundara kunjavihara sura parivara ||7||\n\nvara kabari dhrita kusume varakanakadhikasushume\nvana nilaya dayabhime vadana vijita some ||8||\n\nmadalaka bhalasagamane madhu mathanalasa nayane\nmrudulolalaka rachane madhura sarasagane ||9||\n\nvyagrapurivaranilaye vyasapadarpitahrudaye\nkurukarunamahisadaye vividanigamageye ||10||\n\nClick the link to listen song\n\n",meta:"",tags:["lakshmi"],media:"https://www.youtube.com/watch?v=WEgRmR0pyD0"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಜಯ-ಕೋಲ್ಹಾಪುರ-ನಿಲಯೇ.json",
	rawData: "",
};

export { _internal, collection, data, id };
