const id = "ಜಗದ-ಶಕ್ತಿಗಳೆಲ್ಲ-ಒಂದಾಗಿ";
const collection = "bhajan";
const data = {kannada_title:"ಜಗದ ಶಕ್ತಿಗಳೆಲ್ಲ ಒಂದಾಗಿ",english_title:"Jagada shaktigalella ondagi",kannada:"ಜಗದ ಶಕ್ತಿಗಳೆಲ್ಲ ಒಂದಾಗಿ ನಿಂತಿತೋ…\nಜಗವೆಲ್ಲಾ ಆಕ್ರಮಿಸಿ ಈ ಆಕಾರ ಬಂದಿತೋ\nಕರಿಮುಗಿಲೆ ಕೇಶವೊ…\nಸೂರ್ಯ-ಚಂದ್ರರೇ ನಯನಗಳೊ..\nಸುಳಿವ ಮಿಂಚಿಗಳೆ ನಗೆಯೊ…\nಸಿಡಿಲಿಗುಡುಗಳೆಲ್ಲ ನೀನಾಡುವ ನುಡಿಯೊ..\nಮೇರುಪರ್ವತವೇ ನೀ ಹಿಡಿದ ಗದೆಯೊ..\nಪಾದಕಮಲಗಳೆರಡು ಪಾತಾಳದಲ್ಲಿದೆಯೊ\nಅಂಜನಾ ತನಯ.. ವೀರಾಂಜನೇಯ.. ಮಾರುತಿರಾಯ ||\n\nಆಕಾಶ ಭೂಮಿಗಳ ಒಂದು ಮಾಡಿ ನಿಂತ ನಿನ್ನ ಈ ಆಕಾರವೇನು |\nಕಣ್ಣುಗಳೆಲ್ಲ ಕೋರೈಸುವ ಕಾಂತಿ ಚೆಲ್ಲುವ ಈ ಭವ್ಯ ರೂಪವೇನು |\nನೋಡುವ ಬಗೆ ಹೇಗೆ ನಿನ್ನ ಬೇಡುವ ಬಗೆ ನಿನ್ನ\nಪಾದ ಹುಡುಕಲಾರೆ ಹನುಮ ಮೊಗವ ಕಾಣಲಾರೆ ||ನೋ||\nಕೋಟಿ ಕಣ್ಣು ಸಾಲದಯ್ಯ ನಿನ್ನ ರೂಪ ತುಂಬಿಕೊಳಲು\nಹೇಗೆ ನಿನ್ನ ಕಾಣಲಯ್ಯ ಹೀಗೆ ನಿಲ್ಲಲು |\nನಿಂತ ರೀತಿಯೋ ತನುವ ಕಾಂತಿಯೋ |\nಉರಿವ ಸೂರ್ಯ ಹಣತೆ ದೀಪದಂತೆ ಕಾಣುತಿರಲು ಹೀಗೆ….|\nಆಕಾಶ ಭೂಮಿಗಳ ಒಂದು ಮಾಡಿ ನಿಂತ ನಿನ್ನ ಈ ಆಕಾರವೇನೋ\n….||\n\nನಿನ್ನ ಉಸಿರ ಬಿಸಿಗೆ ಹೆದರಿ ನದಿಗಳಾವಿಯಾಗುತಿರಲು\nದಿವ್ಯ ರೂಪ ಕಂಡ ಗಿರಿಗಳೆಲ್ಲ ನಡುಗುತಿರಲು|\nನಿನ್ನ ಭಾರ ತಾಳೆನೆಂದು ಭೂಮಿ ಕುಸಿದು ಹೋಗುತಿರಲು|\nಎಲ್ಲಿ ನಾನು ನಿಲ್ಲಲಯ್ಯ ನಿನ್ನ ನೋಡಲು|\nರೋಮ ರೋಮದಿ ರಾಮನಾಮವು…\nರೋಮ ರೋಮದಿ ರಾಮನಾಮವು  ||\n\nಶಂಖನಾದ ತಾಳವಾದ್ಯ\nಶಂಖನಾದ ತಾಳವಾದ್ಯ ದಶದಿಕ್ಕಲು ಮೊಳಗುತಿರಲು…\n\nಆಕಾಶ ಭೂಮಿಗಳ ಒಂದು ಮಾಡಿ ನಿಂತ ನಿನ್ನ ಈ ಆಕಾರವೇನು…\nಕಣ್ಣುಗಳೆಲ್ಲ ಕೋರೈಸುವ ಕಾಂತಿ ಚೆಲ್ಲುವ ಈ ಭವ್ಯ ರೂಪವೇನು…..\n\nಆಕಾಶ ಭೂಮಿಗಳ ಒಂದು ಮಾಡಿ ನಿಂತ ನಿನ್ನ ಈ ಆಕಾರವೇನು\nನಿನ್ನ ಈ ಆಕಾರವೇನು….  ನಿನ್ನ ಈ ಆಕಾರವೇನು……..||\n\n",english:"Singer : Dr. Raj kumar\nComposition : chi Udayashankar\nMusic : Upendra kumar\n\nJagada shaktigalella ondagi nintito\njagavella akramisi ee akara bandito\nkarimugile keshavo surya chandrare nayanagalo |\nsuliva minchugale nageyo\nsidilu gudugugalella ninado nudiyo\nmeru parvatave ni hidida gadeyo\npadakamalagaleradu pataladalliveyo\nanjana tanaya viranjaneya\nmarutiraya….\n\nAkasha bhumigala ondu madi ninta ninna ee akaraveno|\nkannugala koraisuva kanti chelluva ee bhavya rupaveno ||Akasha||\n\nNoduva bage hege ninna beduva bage hege ninna|\npada hudukalare hanuma mogava kanalare..\n\nKoti kannu saladayya ninna rupa tumbikolalu\nhege ninna kanalayya hige nillalu\nninta ritiyu tanuva kantiyu\nuriva surya hanate dipadante kanutiralu hige ||AkAsha||\n\nNinna usira bisige hedari nadigalaviyagutiralu\ndivya rupa kanda girigalella nadugutiralu..\nninna bhara talenendu bhumi kusidu hogutiralu\nelli nanu nillalayya ninna nodalu\nroma romadi rama namavu..\nshankanada talavadya….dasha dikkanu molagutiralu |Akasha||\n\n………………………………………………………………………………………………………..\n\n",meta:"",tags:["anjaneya hanuma","kannada devotional song"],media:"https://www.youtube.com/watch?v=CGl-toxPZZQ"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಜಗದ-ಶಕ್ತಿಗಳೆಲ್ಲ-ಒಂದಾಗಿ.json",
	rawData: "",
};

export { _internal, collection, data, id };
