const id = "ಡಿಂಬದಲ್ಲಿರುವ-ಜೀವ-ಕಂಬಸೂತ್ರ";
const collection = "bhajan";
const data = {kannada_title:"ಡಿಂಬದಲ್ಲಿರುವ ಜೀವ ಕಂಬಸೂತ್ರ",english_title:" Dimbadalliruva jeeva kambasutra",kannada:"ಡಿಂಬದಲ್ಲಿರುವ ಜೀವ ಕಂಬಸೂತ್ರ ಗೊಂಬೆಯಂತೆ|\nಎಂದಿಗಾದರೊಂದು ದಿನ ಸಾವು ತಪ್ಪದೂ…||ಎಂದಿ||\nಸಾವು ತಪ್ಪದು….ಸಾವು ತಪ್ಪದೂ\n\nಹುಟ್ಟುತೇನು ತರಲಿಲ್ಲ ಸಾಯುತೇನು ಒಯ್ಯಲಿಲ್ಲ|\nಸುಟ್ಟು ಸುಟ್ಟು ಸುಣ್ಣದ ಹರಳಾಯಿತೀ ದೇಹ|\nಹೊಟ್ಟೆ ಬಲುಕೆಟ್ಟದೆಂದು ಎಷ್ಟು ಕಷ್ಟ ಮಾಡಿದರು |\nಬಿಟ್ಟು ಹೋಗುವಾಗ ಗೇಣು ಬಟ್ಟೆ ಕಾಣದು|\n||ಡಿಂಬದಲ್ಲಿರುವ||\n\nಹತ್ತು ಎಂಟು ಲಕ್ಷ ಗಳಿಸಿ ಮತ್ತೆ ಸಾಲದೆಂದು ಪರರ|\nಅರ್ಥಕ್ಕಾಗಿ ಆಸೆಪಟ್ಟು ಸುಳ್ಳು ನ್ಯಾಯ ಮಾಡ್ವರು|\nಬಿತ್ತಿ ಬೆಳೆದು ತನ್ನದೆಂಬ ವ್ಯರ್ಥಚಿಂತೆಯನ್ನು ಮಾಡೆ|\nಸತ್ತು ಹೋದ ಮೇಲೆ ಅರ್ಥ ಯಾರಿಗಾಹುದೊ|\n||ಡಿಂಬದಲ್ಲಿರುವ||\n\nಹೊನ್ನು ಹೆಣ್ಣು ಮಣ್ಣು ಮೂರು ತನ್ನಲಿದ್ದು ಉಣ್ಣಲಿಲ್ಲ|\nಅಣ್ಣತಮ್ಮ ತಾಯಿ ತಂದೆ ಬಯಸಲಾಗದು|\nಅನ್ನ ವಸ್ತ್ರ ಭೋಗಕ್ಕಾಗಿ ತನ್ನ ಸುಖವ ಕಾಣಲಿಲ್ಲ|\nಮಣ್ಣುಪಾಲು ಆದಮೇಲೆ ಯಾರಿಗಾಹುದೊ|\n||ಡಿಂಬದಲ್ಲಿರುವ||\n\nಬೆಳ್ಳಿ ಬಂಗರಿಟ್ಟುಕೊಂಡು ಒಳ್ಳೆ ವಸ್ತ್ರ ಹೊದ್ದುಕೊಂಡು|\nಚಳ್ಳಪಿಳ್ಳ ಗೊಂಬೆಯಂತೆ ಆಡಿ ಹೋದೆನೆ|\nಹಳ್ಳ ಹರಿದು ಹೋಗುವಾಗ ಗುಳ್ಳೆ ಒಂದು ಒಡೆಯುವಂತೆ|\nಗುಳ್ಳೆ ಪೊರೆಯಂತೆ ಕಾಣೊ ಸಂಸಾರದಾಟ|\n||ಡಿಂಬದಲ್ಲಿರುವ||\n\nವಾರ್ತೆ ಕೀರ್ತಿಯೆಂಬುವೆರಡು ಸತ್ತ ಮೇಲೆ ಬಂದವಯ್ಯ|\nವಸ್ತು ಪ್ರಾಣನಾಯಕನು ಎಲ್ಲಿ ದೊರಕ್ಯಾನು|\nಕರ್ತೃ ಕಾಗಿನೆಲೆಯಾದಿ ಕೇಶವನ ಚರಣಕಮಲ|\nನಿತ್ಯದಲ್ಲಿ ಭಜಿಸಿ ಸುಖಿಯಾಗಿ ಬಾಳೆಲೊ |\n||ಡಿಂಬದಲ್ಲಿರುವ||\n\n",english:"Dimbadalliruva jeeva kambasutra gombeyante | endigaadarondu dina saavu tappadu .. ||endigadaru|| saavu tappadu ….saavu tappadu……\n\nHuttutenu taralilla saayutenu oyyalilla | suttu suttu sunnada haralaayitee deha | hotte balu kettadendu eshtu kashta maadidaru | bittu hoguvaaga genu batte kaanadu || dimbadalliruva ||\n\nHattu entu laksha galisi matte saaladendu parara | arthakkaagi aasepattu sullu nyaaya maadvaru | bitti beledu tannademba vyartha chinteyannu maade | sattu hoda mele artha yaarigaahudo ||dimbadalliruva||\n\nHonnu hennu mannu mooru tannaliddu unnalilla | anna tamma taayi tande bayasalaagadu | anna vastra bhogakkaagi tanna sukhava kaanalilla | mannu paalu aada mele yaarigaahudo ||dimbadalliruva||\n\nBelli bangarittukondu olle vastra hoddukondu | challapilla gombeyante aadi hodene | halla haridu hoguvaaga gulle ondu odeyuvante | gulle poreyante kaano samsaaradaata| dimbadalliruva||\n\nVaarte keertiyembuveradu satta mele bandavayya | vastu praananayakanu elli dorakyaanu | kartra kaagineleyaadi keshavana charana kamala | nityadalli bhajisi sukhiyaagi baalelo || dimbadalliruva||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=reszOu2vfNE"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಡಿಂಬದಲ್ಲಿರುವ-ಜೀವ-ಕಂಬಸೂತ್ರ.json",
	rawData: "",
};

export { _internal, collection, data, id };
