const id = "ತಪ್ಪುಗಳೆಲ್ಲವ-ಪರಿಹರಿಸುವ";
const collection = "bhajan";
const data = {kannada_title:"ತಪ್ಪುಗಳೆಲ್ಲವ ಪರಿಹರಿಸುವ",english_title:" Tappugalellava pariharisuva",kannada:"ತಪ್ಪುಗಳೆಲ್ಲವ ಪರಿಹರಿಸುವ ನಮ್ಮಪ್ಪನಲ್ಲವೆ ನೀನು ||ಪ||\nಅಷ್ಟಾದರು ಎನ್ನವಗುಣ ಎಣಿಸದೆ ಸತ್ಯ ಸಂಕಲ್ಪ ತಿಮ್ಮಪ್ಪ ನೀನು ||ಅ||\n\nಬೆಳಗಿನ ಝಾವದಿ ಹರಿಯ ಸ್ಮರಣೆಯ ಮಾಡದಿರುವುದು ತಪ್ಪು\nಮಲಮೂತ್ರ ವಿಸರ್ಜನೆ ಮೃತ್ತಿಕೆಯಲಿ ಮಲವ ತೊಳೆಯದಿರುವುದು ತಪ್ಪು\nತುಳಸಿ ವೃಂದಾವನ ಗೋಸೇವೆಗೆ ಆಲಸ್ಯ ಮಾಡುತಲಿರುವುದು ತಪ್ಪು\nನಳಿನ ಸಹೋದರನಿಗರ್ಘ್ಯವನೀಯದೆ ಕಲಿ ವ್ಯಾಸಂಗದಲಿರುವುದು ತಪ್ಪು ||\n\nದಿನದಿನ ಉದಯ ಸ್ನಾನ ಮಾಡದ ತನು ವಂಚನೆಯಾ ತಪ್ಪು\nಮುನಿಸುರ ಭೂಸುರರಾರಾಧಿಸದೆ ಧನ ವಂಚನೆಯ ತಪ್ಪು\nಕ್ಷಣ ಗುಣ ಜಿಜ್ಞಾಸಿಲ್ಲದೆ ದುರ್ಜನರ ಸಂಸರ್ಗದ ತಪ್ಪು\nವನಜಾಕ್ಷ ನಿನ್ನ ಧ್ಯಾನವ ಮಾಡದೆ ಮನ ವಂಚನೆಯ ತಪ್ಪು ||\n\nಕಣ್ಣಿಲಿ ಕೃಷ್ಣಾಕೃತಿಯ ನೋಡದೆ ಪರಹೆಣ್ಣಿನ ನೋಡಿದ ತಪ್ಪು\nಅನ್ನವನರ್ಪಿಸದೆ ಅಜ್ಞಾನದಿ ಉಣ್ಣುವ ನಾಲಿಗೆ ತಪ್ಪು\nನಿನ್ನ ಕಥಾಮೃತವಿಲ್ಲದೆ ಹರಟೆಯ ಮನ್ನಿಸುವ ಕಿವಿ ತಪ್ಪು\nಚಿನ್ಮಯ ಮೂರುತಿ ಚರಣೆಕ್ಕೆರಗದೆ ಉನ್ಮತ್ತೆಯ ತಪ್ಪು ||\n\nಆನಂದನ ಸಂಕೀರ್ತನೆ ಮಾಡದೆ ಹೀನ ವಿವಾದದ ತಪ್ಪು\nಶ್ರೀನಾಥಾರ್ಚನೆ ಇರಲೂಳಿಗವ ಮಾಡಿದ ಕೈಯ ತಪ್ಪು\nಶ್ರೀನಿರ್ಮಾಲ್ಯ ವಿರಹಿತ ಸುರಭಿಯ ಘ್ರಾಣದ ನಾಸಿಕ ತಪ್ಪು\nಶ್ರೀ ನಾರಾಯಣನ ವೇಷಗೆಯ್ಯದನ ನಟನೆ ಪಾದದ ತಪ್ಪು ||\n\nಯಜ್ಞಾತ್ಮಗೆ ಯಜ್ಞವರ್ಪಿಸದೆ ಕಾಮ್ಯ ಯಜ್ಞಮಾಡಿದ ತಪ್ಪು\nಅಜ್ಞಾನ ಜ್ಞಾನದಲಿ ಕ್ಷಣ ಕ್ಷಣ ಅಘಗಳ ಗಳಿಸುವ ತಪ್ಪು\nಆಗತ ಶೌಚದ ಕರ್ಮವ ಜರೆದು ಸಮಗ್ರ ಗುಹ್ಯದ ತಪ್ಪು\nಯಜ್ಞೇಶ ಮಧ್ವಪತಿ ಪುರಂದರವಿಠಲನ ವಿಸ್ಮರಣೆಯ ತಪ್ಪು ||\n\n",english:"Tappugalellava pariharisuva nammappanallave ninu ||pa||\nAshtadaru ennavaguna enisade satya sankalpa timmappa ninu ||a||\n\nBelagina javadi hariya smaraneya madadiruvudu tappu\nMalamutra visarjane mruttikeyali malava toleyadiruvudu tappu\nTulasi vrumdavana gosevege alasya madutaliruvudu tappu\nNalinasahodaranigarghyavaniyade kalivyasangadaliruvudu tappu ||\n\nDinadina udaya snana madada tanu vanchaneya tappu\nMunisura busurararadhisade dhana vanchaneya tappu\nKshana guna jijnasillade durjanara samsargada tappu\nVanajaksha ninna dhyanava madade mana vanchaneya tappu ||\n\nKannili krishnakrutiya nodade parahennina nodida tappu\nAnnavanarpisade ajnanadi unnuva nalige tappu\nNinna kathamrutavillade harateya mannisuva kivi tappu\nChinmayamuruti charanekkeragade unmatteya tappu ||\n\nAnandana sankirtane madade hinavivadada tappu\nSrinatharchane iraluligava madida kaiya tappu\nSrinirmalya virahita surabhiya granada nasika tappu\nSri narayanana veshageyyadana natane padada tappu ||\n\nYajnaatmage yajnavarpisade kamya yajnamadida tappu\nAjnana jnanadali kshana kshana agagala galisuva tappu\nAgata Sauchada karmava jaredu samagra guhyada tappu\nYajnesha madhvapati purandara vithalana vismaraneya tappu ||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=oNqALYRE55k"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ತಪ್ಪುಗಳೆಲ್ಲವ-ಪರಿಹರಿಸುವ.json",
	rawData: "",
};

export { _internal, collection, data, id };
