const id = "ತೋಳು-ತೋಳು-ತೋಳು-ರಂಗ";
const collection = "bhajan";
const data = {kannada_title:"ತೋಳು ತೋಳು ತೋಳು ರಂಗ",english_title:" Tolu tolu tolu ranga",kannada:"ತೋಳು ತೋಳು ತೋಳು ರಂಗ ತೋಳನ್ನಾಡೈ ಸ್ವಾಮಿ |\nನೀಲವರ್ಣದ ಬಾಲಕೃಷ್ಣನೆ ತೋಳನ್ನಾಡೈ ||ಪ||\n\nಹುಲಿಯುಗುರರಳೆಲೆ ಮಾಗಾಯಿಗಳನಿಟ್ಟ ತೋಳನ್ನಾಡೈ ಸ್ವಾಮಿ |\nಘಲಿರೆಂಬಂದುಗೆ ಗೆಜ್ಜೆಲಿ ನಲಿವುತ್ತ ತೋಳನ್ನಾಡೈ |\nನೆಲುವಿಗೆ ನಿಲುಕದೆ ಒರಳ ತಂದಿಟ್ಟ ತೋಳನ್ನಾಡೈ ಸ್ವಾಮಿ |\nಚೆಲುವ ಮಕ್ಕಳ ಮುದ್ದು ಮಾಣಿಕವೆ ತೋಳನ್ನಾಡೈ ||\n\nಮಾತೆಯ ಪಿತನ ಅಣುಗನ ಮಡುಹಿದ ತೋಳನ್ನಾಡೈ|\nಪೂತನಿಯೆಂಬವಳಸುವನೆ ಹೀರಿದ ತೋಳನ್ನಾಡೈ ಸ್ವಾಮಿ |\nಮಾತಿಗೆ ಶಿಶುಪಾಲನ ಶಿರತರಿದ ತೋಳನ್ನಾಡೈ ಸ್ವಾಮಿ |\nಶ್ರೀ ತುಲಸಿಯ ಪ್ರಿಯ ನಿತ್ಯವಿನೋದಿ ತೋಳನ್ನಾಡೈ ||\n\nದಟ್ಟಡಿಯಿಡುತಲೆ ಬೆಣ್ಣೆಯ ಮೆಲುವ ತೋಳನ್ನಾಡೈ ಸ್ವಾಮಿ |\nಕಟ್ಟಿದ ಕರಡಿಯ ಕರುವೆಂದೆಳೆದ ತೋಳನ್ನಾಡೈ |\nಬಟ್ಟಲ ಹಾಲ ಒಲ್ಲೆಂದು ಕಾಡಿದ ತೋಳನ್ನಾಡೈ ಸ್ವಾಮಿ |\nಬಟ್ಟಲೊಳುಣವಿಸೆ ನಗುವಾತನೆ ತೋಳನ್ನಾಡೈ ||\n\nಸಜ್ಜನ ಸತ್ಯಕೆ ಧರ್ಮವ ನಡೆಸಿದ ತೋಳನ್ನಾಡೈ ಸ್ವಾಮಿ |\nಅರ್ಜುನ ರಥಕೆ ಸಾರಥ್ಯ ಮಾಡಿದ ತೋಳನ್ನಾಡೈ |\nಲಜ್ಜೆಗೀಡಾದ ದ್ರೌಪದಿ ಕಾಯ್ದ ತೋಳನ್ನಾಡೈ ಸ್ವಾಮಿ |\nವಜ್ರಪಂಜರ ಪಾಂಡವಪ್ರಿಯ ತೋಳನ್ನಾಡೈ ||\n\nನಖದಿಂದ ಹಿರಣ್ಯಕನುದರ ಬಗಿದ ತೋಳನ್ನಾಡೈ ಸ್ವಾಮಿ |\nಸುಖದಿಂದಲಿ ಪ್ರಹ್ಲಾದನ ಕಾಯ್ದ ತೋಳನ್ನಾಡೈ |\nವಿಖಳಿತಗೆಡಿಸಿದ ಗೋಪಸ್ತ್ರೀಯರ ತೋಳನ್ನಾಡೈ |\nಸ್ವಾಮಿ ಸುಖತೀರ್ಥರ ಪತಿ\nಪುರಂದರವಿಠಲ\nತೋಳನ್ನಾಡೈ ||\n\n",english:"Tolu tolu tolu ranga tolannadai swami\nnilavarnada balakrishnane tolannadai ||pa||\n\nHuliyuguraralele magayigala nitta tolannadai\nsvami khalirembanduge gejjeli nalivutta tolannadai ||1||\n\nNeluvige nilukade orala tanditta tolannadai\nsvami chaluva makkala muddu manikave tolannadai ||2||\n\nPutaniyembavalasuvane hirida tolannadai svami\nmateya pitana anugala maduhida tolannadai ||3||\n\nMatige shishupAlana shira tarida tolannadai svami\nshri tulasiya priya nityavinodi tolanadai||4||\n\nDattadiyidutale benneya meluva tolannadai svami\nkattida karadiya karuvendeleda tolannadai||5||\n\nBattala hala ollendu kadida tolannadai svami\nbattalolunavise naguvadane tolannadai||6||\n\nSajjana satyake dharmava nadesida tolannadai svami\narjunaradake sarathya madida tolannadai||7||\n\nLajjegitada draupadi kaida tolannadai svami\nvajra panjara pandava priya tolannadai||8||\n\nNakhadinda hiranyakanudara bagida tolannadai svami\nsukhadindali prahladana kaida tolannadai||9||\n\nVikhalitagedisida gopa striyara tolannadai svami\nsukhatirttara pati\npurandara vittala\ntolannadai||10||\n\nYoutube link\n:\n\n",meta:"",tags:["krishna","dasara padagalu","kannada devotional lyrics","krishna song"],media:"https://www.youtube.com/watch?v=MaUHE7JIXGk"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ತೋಳು-ತೋಳು-ತೋಳು-ರಂಗ.json",
	rawData: "",
};

export { _internal, collection, data, id };
