const id = "ತಿಳಿಯದೋ-ನಿನ್ನಾಟ-ತಿರುಪತಿಯ";
const collection = "bhajan";
const data = {kannada_title:"ತಿಳಿಯದೋ ನಿನ್ನಾಟ ತಿರುಪತಿಯ",english_title:" Tiliyado ninnata tirupathiya",kannada:"ತಿಳಿಯದೋ ನಿನ್ನಾಟ ತಿರುಪತಿಯ ವೆಂಕಟ |ಪ|\nಪೊಳೆವ ನೀರೊಳು ಗೆಲುವ ಮೋರೆಯ\nನೆಲವ ನೋಡುವ ಸುಳಿವ ಕಂಬದಿ\nಇಳೆಯನಳೆಯುವ ಭಳಿರೆ ಭಾರ್ಗವ\nಖಳನ ಛೇಧಿಸಿ ಕೊಳಲಧ್ವನಿಗೆ\nನಳಿನಮುಖಿಯರ ನಾಚಿಸುವ ಬಲು\nಹಯದಳದ ಬಹು ಹವಣೆಗಾರನೆ||\nಆರು ಬಲ್ಲರು ನಿಮ್ಮ ಶ್ರೀ ಲಕುಮಿಯ ಮನಸಿಗೆ ತೋರುವಿಯೊ ಪರಬೊಮ್ಮ |\nಉಳಿದವರು ಬಲ್ಲರೆ ನೀರಜಾಸನ ಬೊಮ್ಮ ಇದು ನಿನ್ನ ಮರ್ಮ |\nನೀರೊಳಗೆ ಮನೆ ಭಾರ ಬೆನ್ನಿಲಿ ಕೋರದಾಡೆಯ ನಾರಸಿಂಹನೆ |\nಧರೆಯ ಬೇಡಿದ ಧೀರಪುರುಷನೆ ವಾರಿಬಂಧನ ಮಾರಜನಕನೆ |\nನಾರಿಯರ ವ್ರತವಳಿದು ಕುದುರೆಯನೇರಿ ಮೆರೆಯುವ ಸುಂದರಾಂಗನೆ||\nಸಕಲ ಮಾಯವಿದೇನು ವೃಕನ ವಾಯು ಸಖನ ಸಲಹಿದೆ ನೀನು |\nಭಕುತಿಯಿಂದಲಿ ತುತಿಪರಿಗೆ ಸುರಧೇನು ಸುರಕಾಮಧೇನು |\nನಿಖಿಳ ವೇದೋದ್ಧಾರ ಗಿರಿಧರ ಅಖಿಳ ಭೂಮಿಯ ತಂದ ನರಹರಿ |\nಯುಕುತಿಯಲಿ ನೆಲನಳೆದ ಭಾರ್ಗವ ಮುಕುತಿಗೋಸುಗ ಫಲವ ಸವಿದನೆ |\nರುಕುಮನನುಜೆಯ ರಮಣ ಬೌದ್ದನೆ ಲಕುಮಿರಮಣನೆ ಕಲ್ಕಿರೂಪಿಯೆ||\nನಿನ್ನ ರೂಪಿನ ಲೀಲಾ ನೋಡುವ ಜನಕೆ ಕಣ್ಣು ಸಾವಿರವಿಲ್ಲ |\nನಾ ಪಾಡಿ ಪೊಗಳಲು ಪನ್ನಗಾಧಿಪನಲ್ಲ ನೀನರಿಯದಿಲ್ಲ |\nಕಣ್ಣುಮುಚ್ಚಿದೆ ಬೆನ್ನು ತೋರುವಿ ಮಣ್ಣು ಕೆದರುವಿ ಚಿಣ್ಣಗೊಲಿದನೆ |\nಸಣ್ಣವಾಮನ ಅಣ್ಣರಾಮನೆ ಪುಣ್ಯಪುರುಷನೆ ಬನ್ನ ಬಡಕನೆ |\nಹೆಣ್ಣುಗಳ ವ್ರತಕೆಡಿಸಿ ತೇಜಿಯ ಬೆನ್ನನೇರಿದ ವ್ಯಾಸವಿಠಲ||\n\n",english:"Tiliyado ninnata tirupathiya venkata ||pa||\n\nPoleva nirolu geluva moreya nelevanoduva |Suliva kambadi ileyanaliyuva balire bhargava | khalana chedisi kolala dwanige nalinamukhiyara |nachisuva balu hayadalada bahu havanegarane  |1|\n\nAru ballaru nimma shri lakumiya manasige thoruviyo |parabomma ulidavaru ballare nirajasana bomma idu ninna marma |neerolage mane bara bennali koredadiya    narasimhane dareya bedida dheera purushane |varibhandana mara janakane nariyara vrata validu |kudureya eri mereyuva sundarangane      ||\n\nSakala mayavidenu vrikana vayu sakana salahide neenu |bhakuthi indali tutiparige suradhenu sura kama dhenu |nikhila vedodhara giridhara akila bumiya |tanda narahari yukuthiyali nelenalada bhargava |mukuthigosuga phalava savidane rukumananujeya ramana |boudhane lakumi ramanane kalki roopiye  ||\n\nNinna roopina leela noduvajanake kannu saviravilla |na padi pogalalu pannagadipa nalla neenariyadilla |kannu muchchade bennu toruvi mannu kedaruvi | chinna golidane sanna vamana anna ramane | punya purushane banna badakane hennugala vrata |kedisi tejiya bennanerida vyasa vittala ||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=hoPQFp0vvA0"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ತಿಳಿಯದೋ-ನಿನ್ನಾಟ-ತಿರುಪತಿಯ.json",
	rawData: "",
};

export { _internal, collection, data, id };
