const id = "ದಯವಿರಲಿ-ದಯವಿರಲಿ-ದಾಮೋದರ";
const collection = "bhajan";
const data = {kannada_title:"ದಯವಿರಲಿ ದಯವಿರಲಿ ದಾಮೋದರ",english_title:" Dayavirali dayavirali damodara",kannada:"ದಯವಿರಲಿ ದಯವಿರಲಿ ದಾಮೋದರ ।।ಪ॥\nಸಯವಾಗಿ ಬಿಡದೆನ್ನ ಸಾಕುವ ಶ್ರೀಕ್ರಷ್ಣ ।।ಅ.ಪ॥\n\nಹೋಗಿ ಬರುವೆನಯ್ಯ ಹೋದ ಹಾಂಗೆಲ್ಲ\nಸಾಗುವವನಲ್ಲನಾ ನಿನ್ನ ಬಿಟ್ಟು\nತೂಗಿ ತೊಟ್ಟಿಲು ಕೊನೆಗೆ ಸ್ಥಳದಲ್ಲೆ ನಿಲ್ಲುವುದು\nಹ್ಯಾಗೆ ನೀ ನಡೆದಂತೆ ಹಾಗೆ ನಾ ನಡಕೊಂಬೆ ।।೧।।\n\nಇದ್ದಲ್ಲೆ ಎನ್ನನುದ್ಧರಿಪ ಶಕ್ತಿ ಅ-\nಸಾಧ್ಯ ನಿನಗೆಂದು ನಾ ಬಂದವನಲ್ಲ\nನದ್ಯಾದಿ ಕ್ಷೇತ್ರಮೂರ್ತಿಗಳಲ್ಲ್ಲಿ ನಿಜ ಜ್ಞಾನ\nವೃದ್ಧ ಜನರ ಹುಡುಕಿ ನಿನ್ನ ತಿಳಿಯಲು ಬಂದೆ ।।೨।।\n\nಸತತ ಇದ್ದಲ್ಲೆ ಎನ್ನ ಸಲಹೊ ಅವರೊಳಗಾಗಿ\nಅತಿಶಯವು ಉಂಟು ವಿಭೂತಿಯಲ್ಲಿ\nಗತಿಯು ಸಾಧನಕೆ ಅಭಿವ್ಯಕ್ತ ಸಂದರ್ಶನದಿ\nಸ್ಮೃತಿಗೆ ವಿಶೇಷ ಮಾರುತಿರಮಣ ನಿನ್ನ ।।೩।।\n\nನೋಡಿದೆನೆ ನಾ ನಿನ್ನ ನೋಡದೆ ಎಂದೆಂದು\nಪಾಡಿದೆನೆ ಆರಾರು ಪಾಡದೊಂದು\nಮಾಡಿದೆನೆ ಅರ್ಚನೆಯ ಮೀಸಲಾದುದು ಒಂದು\nಮೂಢಮತಿಯಲಿ ಮುಂದೆ ನಿಂದೆ ಕೈಮುಗಿದು ।।೪।।\n\nಬಂದೆನೊ ನಾನಿಲ್ಲಿ ಬಹುಜನ್ಮದ ಸುಕೃತ-\nದಿಂದ ನಿನ್ನ ಬಳಿಗೆ ಇಂದಿರೇಶ\nಒಂದು ಮಾತ್ರವು ಇಟ್ಟು ಸಕಲವು ಅರ್ಪಿಸಿದೆ\nಬಂಧನ ಬಡಿವ ಭಕುತಿಯು ಜ್ಞಾನ ನೀಡುವುದು ।।೫।।\n\nಬಿನ್ನಪವ ಕೇಳು ಸ್ವಾಮಿ ಎನ್ನನೋಬ್ಬನ್ನೆ ಅಲ್ಲ\nಎನ್ನ ಹೊಂದಿ ನಡೆವ ವೈಷ್ಣವರನ\nಇನ್ನವರಿಗೆ ಬಾಹೊ ದುಷ್ಕರ್ಮಗಳ ಕೆಡಿಸಿ\nಘನಗತಿಗೈದಿಸುವ ಭಕುತಿ ಕೊಡು ಕರುನಾಡಿ ।।೬।।\n\nರಾಜರಾಜೇಶ್ವರ ರಾಜೀವದಳನಯನ\nಮೂಜಗದೊಡೆಯ ಮುಕುಂದಾನಂದ\nಈ ಜೀವಕೀ ದೇಹ ಬಂದದ್ದಕ್ಕು ಎನಗತಿ ನಿ\nರ್ವ್ಯಾಜದಿ ಸುರಗಂಗೆ ಸ್ನಾನವನು ಮಾಡಿಸೊ ।।೭।।\n\nಎನಗೆ ಆವುದು ಒಲ್ಲೆ ಎಲ್ಲೆಲ್ಲಿ ಪೋದರು\nಕ್ಷಣ ಬಿಡದೆ ನಿನ್ನ ನೋಳ್ಪ ಜ್ಞಾನವ ಕೊಡೊ\nಚಿನುಮಯ ಮೂರುತಿ ಗೋಪಾಲವಿಠಲ\nಘನಕರುಣಿ ಮಧ್ವಮುನಿ ಮನಮಂದಿರನಿವಾಸ ।।೮।।\n\n",english:"Dayavirali dayavirali damodara ||pa||\n\nSayavagi bidadenna sakuva srikrashna ||a.pa||\n\nHogi baruvenayya hoda hangella\nsaguvavanallana ninna bittu\ntoogi tottilu konege sthaladalle nilluvudu\nhyage ni nadedante hage na nadakombe ||1||\n\nIddalle ennanuddharipa Shakti a-\nSadhya ninagendu na bandavanalla\nNadyadi kshetramurtigalallli nija jnaana\nVruddha janara huduki ninna tiliyalu bande ||2||\n\nSatata iddalle enna salaho avarolagagi\natisayavu untu vibutiyalli\ngatiyu sadhanake abivyakta sandarsanadi\nsmrutige visesha marutiramana ninna ||3||\n\nNodidene na ninna nodade endendu\npadidene araru padadondu\nmadidene archaneya misaladudu ondu\nmudhamatiyali munde ninde kaimugidu ||4||\n\nBandeno nanilli bahujanmada sukruta-\ndinda ninna balige indiresha\nondu matravu ittu sakalavu arpiside\nbandhana badiva Bakutiyu jnana niduvudu ||5||\n\nBinnapava kelu svami ennanobbanne alla\nenna hondi nadeva vaishnavarana\ninnavarige baho dushkarmagala kedisi\nganagatigaidisuva Bakuti kodu karunadi ||6||\n\nRajarajeshvara rajivadalanayana\nmujagadodeya mukundananda\ni jivaki deha bandaddakku enagati ni\nrvyajadi suragange snanavanu madiso ||7||\n\nEnage avudu olle ellelli podaru\nkshana bidade ninna nolpa jnanava kodo\nChinmaya muruti gopalavithala\nganakaruni madhvamuni manamandiranivasa ||8||\n\n\n",meta:"",tags:["lyrics kannada devotional songs"],media:"https://www.youtube.com/watch?v=sK5kCrffFNU"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ದಯವಿರಲಿ-ದಯವಿರಲಿ-ದಾಮೋದರ.json",
	rawData: "",
};

export { _internal, collection, data, id };
