const id = "ನಗುವರಲೋ-ರಂಗಯ್ಯ";
const collection = "bhajan";
const data = {kannada_title:"ನಗುವರಲೋ ರಂಗಯ್ಯ",english_title:"Naguvarella rangayya ninnatava",kannada:"ನಗುವರಲೋ ರಂಗಯ್ಯ ನಿನ್ನಾಟವ ಕಂಡು ||\n\nಹಗರಣವಾಗಿದೆ ಎನಗೆ ನಿಗಮಗೋಚರನೆ||\n\nನಿಗಮವನ್ನು ತರಲು ಮತ್ಸ್ಯಾಕೃತಿಯ ತಾಳಿದೆ ನಗವನೆತ್ತಿ ಕೂರ್ಮನೆಂಬ ಹೆಸರ ಧರಿಸಿದೆ | ಜಗತಿಯನ್ನು ತರಲು ವರಾಹ ಮೂರ್ತಿಯೆನಿಸಿದೆ| ಮಗುವಿಗಾಗಿ ಘೋರಾಕೃತಿ ನರ ಮೃಗನೇಣಿಸಿದೆ||\n\nಹೆಡೆಮುರಿ ಕಟ್ಟಿ ದಾನವ ಕೊಟ್ಟ ಬಲಿಯ ಭಂಗಿಸಿದೆ ಪಡೆದ ತಾಯಿಯ ಶಿರವ ಕಡಿದು ನ್ಯಾಯವೆನಿಸಿದೆ | ಮಡದಿಗಾಗಿ  ಮರ್ಕಟರ ಹಿಂಡು ಕೂಡಿಸಿದೆ,  ಕಡಲ ಕಟ್ಟಿ ಕಪಿಗಳಿಂದ  ಪುರವ ಜಯಿಸಿದೆ  ||\n\nಅಷ್ಟಮಿಯೊಳರ್ಧರಾತ್ರಿ ಜನಿಸಿದೆ, ದುಷ್ಟ ಕಂಸನು ಹಾಕಿದ ಬಾಗಿಲ ತೆಗೆಸಿದೆ | ತಟ್ಟನೆ ಗೋಕುಲದಲ್ಲಿ ಬಂದು ನೆಲೆಸಿದೆ ಸೃಷ್ಟಿಸಿ ಚಂಡಿಕೆಯ ಖಳನ ಮುಂದೆ ನಿಲಿಸಿದೆ ||\n\nನಂದಗೋಪ ತನಗೆ ಕಂದನಾದನು ಎಂದು ಮಿಂದು ಕಾಲಿಂದಿಯೊಳು ಮಂದಿರಕೆ ಬಂದು ಚಂದದಿಂದ ಜಾತಕರ್ಮ ಮಾಡಿಸಿಕೊಂಡು ಬಂದ ಬ್ರಾಹ್ಮಣರಿಗೆ ದಕ್ಷಿಣಿ ಕೊಟ್ಟನು ಅಂದು ||\n\nಬಣ್ಣಿಸಿ ಮಕ್ಕಳ ಕರೆದು ಬೆಣ್ಣೆಯುಣಿಸಿದೆ ಚಿನ್ನಿಕೋಲು ಚೆಂಡು ಬುಗರಿ ಗಂಜುಗವಾಡಿದೆ || ಕಣ್ಣು ಸನ್ನೆ ಮಾಡಿ ಅವರ ಕಾಕು ಮಾಡಿದೆ, ಮಣ್ಣು ತಿಂದ ಬಾಯೊಳು ಬ್ರಹ್ಮಾಂಡ ತೋರಿದೆ ||\n\nಗೊಲ್ಲರ ಮನೆಗೆ ನೀನು ಮೆಲ್ಲನೆ ಪೋಗಿ ಚೆಲ್ಲಿ ಪಾಲು ಮೊಸರು ಬೆಣ್ಣೆ ಸೂರೆ ಮಾಡಿದೆ | ವಲ್ಲಭಯರ ಕೂಡೆ, ನೀನು ಸರಸವಾಡಿದೆ ಮುಲ್ಲೇ ಮಲ್ಲಿಗೆಯ ಅರಳ ಮುಡಿಗೆ ಮುಡಿಸಿದೆ ||\n\nಬಾಲಕರ ಕೂಡೆ ಮೊಸರ ಭಾಂಡ ಒಡೆಸಿದೆ ಹಾಲು ಮೊಸರು ಬೆಣ್ಣೆ ಕದ್ದು ಕಳ್ಳನೆನಿಸಿದೆ | ಬಾಲೆಯರ ವಸ್ತ್ರವ ಕೊಂಡು ಮರವನೇರಿದೆ ಮಾನಿನಿಯರೊಡಕೂಡಿ ರಮಿಸಿದೆ ||\n\nತರುಣಿಯರ ವ್ರತವ ಕೆಡಿಸಿ ಬತ್ತಲೆ ನಿಲ್ಲಿಸಿದೆ ತುರಗವೇರಿ ಕಲ್ಕಿಯಾಗಿ ಖಡ್ಗವ ಧರಿಸಿದೆ | ಗುರು ಮಧ್ವರಾಯರಿಗೊಲಿದು ಉಡುಪಿಲಿ ನೆಲಸಿದೆ, ವರದ ಪುರಂದರ ವಿಠ್ಠಲನೆ ನಮಗೆ ಗತಿಯಾದೆ ||\n\n",english:"Naguvarella rangayya ninnatava kandu||\n\nHagaranavagide enage nigamagocharane||\n\nNigamavannu taralu matsyakrtiya talide nagavanetti kurmanemba hesara dhariside |\njagatiyannu taralu varaha murtiyeniside maguvigagi ghorakrti nara mruganeniside||\n\nHedemudi katti danava kotta baliya bhangiside padeda tata shirava kadidu nyayaveniside |\nmadadigsgi markatara hindu kudiside kadala katti kapigalinda dhurava jayiside||\n\nAshtamiyolardha ratriyalli janiside dushta kamsanu hakida bagila tegeside |\ntattane gokuladalli bandu nelaside shrushtisi chandikeya khalana munde niliside ||\n\nNandagopa tanage kandanadanu endu mindu kalindiyolu mandirake bandu |\nchandadinda jatakarma madisi kondu banda brahmanarige dakshine kottanu andu ||\n\nBannisi makkala karedu benneyuniside chinnikolu chendu bugari ganjugavadide|\nkannu sanne madi avara kaku madide mannu tinda bayolu brahmanda toride ||\n\nGollara manege ninu mellane pogi chelli palu mosaru benne sure madide |\nvallabhayara kude ninu sarasavadide mulle malligeye arala mudige mudiside ||\n\nBalakara kude mosara bhanda odeside halu mosaru benne kaddu kallaneniside |\nbaleyara vastrava kondu maravaneride maaniniyaroda kudi ramiside ||\n\nTaruniyara vratava keisi battale niliside turagaveri kalkiyagi khadgava dhariside |\nguru madhvarayarigolidu udupili nelaside varada purandara vittalane namage gatiyade ||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=VLgpObkONak"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ನಗುವರಲೋ-ರಂಗಯ್ಯ.json",
	rawData: "",
};

export { _internal, collection, data, id };
