const id = "ನಿನ್ನ-ಒಲುಮೆಯಿಂದ-ನಿಖಿಳ-ಜನರು";
const collection = "bhajan";
const data = {kannada_title:"ನಿನ್ನ ಒಲುಮೆಯಿಂದ ನಿಖಿಳ ಜನರು",english_title:" Ninna olumeyinda nikhila janaru",kannada:"ರಚನೆ : ಶ್ರೀ ವಿಜಯ ದಾಸರು\n\nನಿನ್ನ ಒಲುಮೆಯಿಂದ ನಿಖಿಳ ಜನರು ಬಂದು\nಮನ್ನಿಸುವರೊ ಮಹರಾಯ\nಎನ್ನ ಪುಣ್ಯಗಳಿಂದ ಈ ಪರಿಯುಂಟೇನೊ\nನಿನ್ನದೆ ಸಕಲ ಸಂಪತ್ತು\n\nಒಬ್ಬ ಹೆಂಗಸಿನ ಹೊಟ್ಟೆಗೆ ಹಾಕುವುದಕಿನ್ನು\nತಬ್ಬಿಬ್ಬುಗೊಂಡನೊ ಹಿಂದೆ\nನಿಬ್ಬರದಿಂದಲಿ ಸರ್ವರ ಕೂಡುಂಬೊ\nಹಬ್ಬವನುಣಿಸುವಿ ಹರಿಯೆ ||1||\n\nಸಂಜೆತನಕವಿದ್ದು ಸಣ್ಣ ಸೌಟಿನ ತುಂಬ\nಗಂಜಿ ಕಾಣದೆ ಬಳಲಿದೆನೋ\nವ್ಯಂಜನ ಮೊದಲಾದ ನಾನಾ ರಸಂಗಳು\nಭುಂಜಿಸುವುದು ಮತ್ತೇನೊ ||2||\n\nಜೀರ್ಣ ಮಲಿನ ವಸ್ತ್ರ ಕಾಣದ ನರನಿಗೆ\nಊರ್ಣ ವಿಚಿತ್ರ ಸುವಸನ\nವರ್ಣವರ್ಣದಿಂದ ಬಾಹೋದದೇನೊ ಸಂ\nಪೂರ್ಣಗುಣಾರ್ಣವ ದೇವ  ||3||\n\nನೀಚೋಚ್ಚ ತಿಳಿಯದೆ ಸರ್ವರ ಚರಣಕ್ಕೆ\nಚಾಚಿದೆ ನೊಸಲ ಹಸ್ತಗಳ\nಯೋಚಿಸಿ ನೋಡಲು ಸೋಜಿಗವಾಗಿದೆ\nವಾಚಕ್ಕೆ ನಿಲುಕದು ಹರಿಯೆ  ||4||\n\nಮಧ್ಯಾಹ್ನ ಕಾಲಕ್ಕೆ ಅತಿಥಿಗಳಿಗೆ ಅನ್ನ\nಮೆದ್ದೆನೆಂದರೆ ಈಯಗಾಣೆ\nಈ ಧರೆಯೊಳಗೆ ಸತ್ಪಾತ್ರ ಕೂಡುಂಬೊ\nಪದ್ಧತಿ ನೋಡೊ ಪುಣ್ಯಾತ್ಮ ||5||\n\nಮನೆ ಮನೆ ತಿರಿದರು ಕಾಸು ಪುಟ್ಟದೆ ಸು\nಮ್ಮನೆ ಚಾಲ್ವರಿದು ಬಳಲಿದೆನೊ\nಹಣ ಹೊನ್ನು ದ್ರವ್ಯಂಗಳಿದ್ದಲ್ಲಿಗೆ ತನಗೆ\nತಾನೆ ಪ್ರಾಪ್ತಿ ನೋಡೊ ಜೀಯಾ ||6||\n\nವೈದಿಕ ಪದವಿಯನೀವಗೆ ಲೌಕಿಕ\nಐದಿಸುವುದು ಬಹು ಖ್ಯಾತೆ\nಮೈದುನಗೊಲಿದ\nಶ್ರೀ ವಿಜಯವಿಠ್ಠಲ\nನ ನಿನ್ನ\nಪಾದಸಾಕ್ಷಿಯನುಭವವೊ ||7||\n\n",english:"Composer : Sri Vijaya dasaru\n\nNinna olumeyinda nikhila janaru bandu\nmannisuvaro maharaaya\nenna punyagalinda ee pariyunteno\nninnade sakala sampattu ||\n\nObba hengasina hottege hakuvudakinnu\ntabbibbugondano hinde\nnibbaradindali sarvara kudumbo\nhabbavanunisuvi hariye ||1||\n\nSanjetanakaviddu sanna soutina tumba\nganji kanade balalideno\nvyanjana modalada naana rasamgalu\nbhunjisuvudu matteno ||2||\n\nJeerna malina vastra kaanada naranige\noorna vichitra suvasana\nvarnavarnadinda baahodadeno sampurna\ngunaarnava deva ||3||\n\nNeechoccha tiliyade sarvara charanakke\nchaachide nosala hastagala\nyochisi nodalu sojigavagide\nvachakke nilukadu hariye ||4||\n\nMadhyanna kaalakke atithigalige anna\nmeddenendare eeyagaane\nee dhareyolage satpaatra koodumbo\npaddati nodo punyatmma ||5||\n\nMane mane tiridaru kaasu puttade\nsummane chalvaridu balalideno\nhana honnu dravyagaliddallige tanage\ntaane prapti nodo jeeya ||6||\n\nVaidika padviyaneevage loukika\nidisuvudu bahu khyate\nmaidunagolida\nsri vijayavittala\nna ninna\npadasaakshiyanubhavavo ||7||\n\n",meta:"",tags:["narayana","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=0c7tNUlWchE"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ನಿನ್ನ-ಒಲುಮೆಯಿಂದ-ನಿಖಿಳ-ಜನರು.json",
	rawData: "",
};

export { _internal, collection, data, id };
