const id = "ನಡೆದು-ಬಾರಯ್ಯಾ-ಭವ";
const collection = "bhajan";
const data = {kannada_title:"ನಡೆದು ಬಾರಯ್ಯಾ ಭವ",english_title:"Nadedu barayya bhava",kannada:"ನಡೆದು ಬಾರಯ್ಯಾ |ಭವ ಕಡಲಿಗೇ ಕುಂಭಸಂಭವಾ…||2||\n\nಸಡಗರದಿಂದ ಮೆಲ್ಲಡಿಯನಿಡುತ ಬೇಗ\nಎಡಬಲದಲಿ ನಿನ್ನ ಮಡದಿಯರೊಡಗೂಡಿ\nತಡಮಾಡದೆ ಬಾ ಮೃಡಸಖ ವೆಂಕಟ … ನಡೆದು\n||ನಡೆದು||\n\nವಿಜಯದಶಮಿ ಆಶ್ವಿಜ ಶುಧ್ಧ ಮಾಸದಲ್ಲಿ\nನಿಜರಥಾರೂಢನಾಗಿ ಸುಜನರಿಂದೊಡಗೂಡಿ\nಗಜಸಿಂಹ,ಮಯೂರ,ಧ್ವಿಜಸಿಂಗ,ಸಾರಂಗ\nಮಜಬಾಪುರೆ ಎನಲು ತ್ರಿಜಗವು ತಲೆದೂಗೇ…ಏ…ಏ…\nಅಜನು ಸ್ತುತಿಯ ಮಾಡೆ ರುಜಗಣಾಧಿಪ ಪಡೆ\nಗಜಮುಖನಯ್ಯ ನಿಜಾನಂದದಲಾಡೆ\nಭುಜಗಶ್ರೇಷ್ಠ ಧ್ವಿಜರಾಜರು ಜಯವೆನ್ನೆ\nಕುಜನರೆದೆಯ ಮುಟ್ಟಿ ರಜತಮ ಕಲೆಯುತ ನಡೆದು….ನಡೆದು||ನಡೆದು ಬಾರಯ್ಯ||\n\nದಕ್ಷಿಣ ಧಿಕ್ಕಿನಲ್ಲಿ ,ರಾಕ್ಷಸ ಸಮೂಹ\nಒಂದಕ್ಷೋಹಿಣಿ ಬಲ\nನಿನ್ನೂಪೇಕ್ಷೆ ಮಾಡುತಲಿರೆ\nಪಕ್ಷಿವಾಹನಣೆ ಅ ಕ್ಷಣದಲ್ಲಿ ,ಖಳರ ಶಿಕ್ಷಿಸಿ\nಸುಜನರ ರಕ್ಷಿಸಿ ಮೆರೆದಯಾ…ಆ….\nತಕ್ಷಕ ನರನನು ಭಕ್ಷಿಸಬರುತಿರೆ ಈಕ್ಷಿಸಿ ತಕ್ಷಣ\nರಥನೆಲಕ್ಕೊತ್ತಿದೆ, ಲಕ್ಷೀಶನೆ ಅಕ್ಷಯ ಫಲದಾಯಕ\nಕುಕ್ಷಿಯೊಳಗೆ ಜಗರಕ್ಷಿಪ ವಿಶ್ವನೇ…..\n||ನಡೆದು ಬಾರಯ್ಯ||\n\nಪರಿಪರಿಯಿಂದಲಿ ಕರವ ಮುಗಿದು ಸ್ತುತಿಸಿ\nಕರೆದರೆ ಬಾರದೆ ಗರ್ವವು ಯಾಕೊ\nಕರಿರಾಜ ಮೊರೆಯಿಡೆ, ಸಿರಿಗೆ ಹೇಳದೆ ಬಂದೆ\nಕರಿರಾಜ ಅವನಿನ್ನ ಹಿರಿಯಪ್ಪನ ಮಗನೇನೊ…ಓ…ಓ..\nಶರಣಾಗತ ರಕ್ಷಕ ಮಣಿ ಎಂಬುವ\nಬಿರುದು ಬೇಕಾದರೆ ,ಸರಸರ ಬಾರಯ್ಯ,\nಗರುಡ ಗಮನ ಗೋಪಾಲ ವಿಠ್ಠಲರಾಯ\nಗೋಪಾಲ ವಿಠ್ಠಲರಾಯ. ..ಆ..||2||\n||ಗರುಡ||\nಕರುವಿನಮೊರೆಗಾವು ನೆರೆದಂತೆ ಪೊರೆಯೊ\n|| ನಡೆದು ಬಾರಯ್ಯ||\n\n",english:"Nadedu barayya bhava kadalige kumbhasambhava ||\n\nSadagaradinda  melladiyaniduta bega edabaladali ninna  madadiyarodagoodi tadamadade ba mrudasakha venkata … Nadedu||\n\nVijayadashami ashvija shuddha masadalli nija ratharudhanagi sujanarindarodagudi |\ngajasimha mayura dvija singa saranga\nmaja bhapure enalu trijagavu taleduge ….. ajanu stutiya made rujaganadipa pade\ngajamukhanayyanu nijanandadalade\nbhujagashreshtanu dvijaraja jayavenne kujanaredeya metti rajatama kaleyuta ||1||\n\ndakshina dikkinalli rakshasa samuha onda\ndakshohini bala ninnupekshe madutali\npakshivahananemi ninakshanadi khalara\nshikshisi sujanara rakshisi meredayya\ntakshaka naranannu bhakshisa barutire ikshisi\ntakshana nelakottide lakshmishane akshaya phaladayaka\nkukshiyolage jagarakshipa vishwa ||2||\n\nParipariyindali karava mugidu stutise\nkaredare barade garvatanavu yako\nkariraja more ide sirige helade bande\nkariraja ava ninna kiriyappana maganeno |\nsharanagata rakshamani ennuva\nbirudu bekadare sarasara barayya\ngarudagamana gopalavithalaraya…..\nKaruvina moregavu neredante poreyu ||3||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=VbPDfWVpNjQ"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ನಡೆದು-ಬಾರಯ್ಯಾ-ಭವ.json",
	rawData: "",
};

export { _internal, collection, data, id };
