const id = "ನಿನ್ನ-ದರ್ಶನಕೆ-ಸ್ವಾಮೀ-ನಿನ್ನ";
const collection = "bhajan";
const data = {kannada_title:"ನಿನ್ನ ದರ್ಶನಕೆ ಸ್ವಾಮೀ ನಿನ್ನ",english_title:" Ninna darushanake swami ninna",kannada:"ನಿನ್ನ ದರ್ಶನಕೆ ಸ್ವಾಮೀ ನಿನ್ನ ದರ್ಶನಕೆ\nಸ್ವರ್ಣಕ್ಷೇತ್ರ ಗುಡಿಯಲ್ಲಿರುವ ನಿನ್ನ ದರ್ಶನಕೆ\nಹಳ್ಳ ದಿಣ್ಣೆಗಳ  ಕಾಡು ಕಳ್ಳುಮುಳ್ಳುಗಳ\nದಾಟಿ  ಉಲ್ಲಾಸದಿ ಇಂದು\nನಾವು ಬರುವೆವಯ್ಯಪ್ಪ   ||ನಿನ್ನ ದರ್ಶನಕೆ||\n\nಮಂಡಲ ವ್ರತಮಾಡಿ ಮಾಲೆ ಹಾಕಿ ಕೊಂಡೆವು\nಇರುಮುಡಿ ಕಟ್ಟಿ ನಾವು ತಲೆಮೇಲಿಟ್ಟೆವು\nಪಂಪೆಯಲಿ ಮಿಂದು ನಾವು  ಪೂಜೆ ಮಾಡಿದೆವು\nಪಂಪಾಮೇಳ ಹಾಡಿ ಕೊಂಡು ಬರುವೆವಯ್ಯಪ್ಪ\nಏರುವುದು ಕಷ್ಟ ಮೇಲೆ ಏರುವುದು ಕಷ್ಟ\nನಿನ್ನ ಕೈಯ ನೀಡಿ ಮಲೆಗಳ ಮೇಲೆ\nಸೇರಿಸು ನನ್ನಯ್ಯ   ||ನಿನ್ನ ದರ್ಶನಕೆ||\n\nಹಂತ ಹಂತಕೆ ಕೈಯ ನಾವು  ಮುಗಿಯುವೆವಯ್ಯಪ್ಪ\nತೆಂಗಿನಕಾಯಿ ಅಡಿಗಡಿಗೆ ಹೊಡೆವೆವಯ್ಯಪ್ಪ\nಹಂತ ಹದಿನೆಂಟನ್ನು ಮುಟ್ಟಿ ಬರುವೆವಯ್ಯಪ್ಪ\nನಿನ್ನ ಮುಂದೆ ನಿಂತು ನಾವು ಬೇಡುವೆವಯ್ಯಪ್ಪ\nದೋಷ ತೀರಿಸು ಸ್ವಾಮಿ ಮೋಕ್ಷ ಕರುಣಿಸು\nಸ್ವಾಮಿ ಕಂಗಳ ತೆರೆದು ನಮ್ಮ ದುಃಖ ಹೋಗಲಾಡಿಸು ||ನಿನ್ನ ದರ್ಶನಕೆ||\n\nಸ್ವಾಮಿಯೇ ಶರಣು ಅಯ್ಯಪ್ಪ\nಹರಿಹರಸುತನೇ ಶರಣು ಅಯ್ಯಪ್ಪ\nಹರಿಹರಸುತನ್ ಆನಂದಚಿತ್ತನಯ್ಯನಯ್ಯಪ್ಪ\nಸ್ವಾಮಿಯೇ ಶರಣು ಅಯ್ಯಪ್ಪ\n\n",english:"Ninna darushanake swami ninna darushanake\nswarnakshetra gudiyalliruva ninna darushanake\nhalla dinnegala kadu kallumullugala\ndati ullasadi indu\nnavu baruvevayyappa || ninna darushanake||\n\nMandala vruta madi male haki kondevu\nerumudi katti navu talemelittevu\npapeyali mindu navu pooje madidevu\npampamela hadikondu baruvevayyappa\naruvudu kashta mele aruvudu kashta\nninna kaiyya needi malegala mele\nserisu nannayya || ninna darshanake ||\n\nHanta hantake kaiya navu mugivevayyappa\ntenginakayi adigadige hodevevayyappa\nhanta hadinentannu mutti baruvevayyappa\nninna munde nintu navu beduvevayyappa\ndosha teerisu swami moksha karunisu\nswami kangala teredu namma dukha hogaladisu || ninna darshanake||\n\nSwami sharanu ayyappa\nhariharasutane sharanu ayyappa\nhariharasutane anandachitaanayyappa\nswamiye sharanu ayyappa\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=UJuSYHLjdkQ"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ನಿನ್ನ-ದರ್ಶನಕೆ-ಸ್ವಾಮೀ-ನಿನ್ನ.json",
	rawData: "",
};

export { _internal, collection, data, id };
