const id = "ನಂಬಿದೆ-ನಿನ್ನ-ಪಾದ-ಗುರು-ಮುಖ್ಯಪ್ರಾಣ";
const collection = "bhajan";
const data = {kannada_title:"ನಂಬಿದೆ ನಿನ್ನ ಪಾದ ಗುರು ಮುಖ್ಯಪ್ರಾಣ",english_title:" Nambide ninna paada guru mukhyaprana",kannada:"ನಂಬಿದೆ ನಿನ್ನ ಪಾದ ಗುರು ಮುಖ್ಯಪ್ರಾಣ |\nನಂಬಿದೆ ನಿನ್ನ ಪಾದ ಡಂಭವ ತೊಲಗಿಸಿ ||\nಡಿಂಭದೊಳಗೆ ಹರಿಯ  ಬಿಂಬ ಪೊಳೆ ವಂತೆ ಮಾಡೋ\n||ನಂಬಿದೆ ||\n\nಅಂತರಂಗದ ಉಸುರ ಹೊರಗೆ ನೂಕಿ\nಅಂತರಂಗಕ್ಕೆ ಸೇರುವಾ |\nಪಂತದಾಳು ನೀನೇ ಕಂತು ಜನಕನಲ್ಲಿ ||\nಮಂತ್ರಿಯೆನಿಸಿ ಸರ್ವಾಂತರ್ಯಾಮಿಯಾಗಿ\nನಿಂತು ನಾನಾ ಬಗೆ ತಂತು ನಡೆಸುವ\nಹಂತಕಾರಿ ಗುಣವಂತ ಬಲಾಢ್ಯ  ||ನಂಬಿದೆ||\n\nಇಪ್ಪತ್ತು ಒಂದು ಸಾವಿರ ಐದೊಂದು ನೂರು\nಅಪ್ರತಿಮ ಹಂಸ ಮಂತರಾ |\nತಪ್ಪದೆ ದಿನ ದಿನ ಒಪ್ಪದಿಂದಲಿ ಜಪಿಸಿ ||\nತಪ್ಪಿಸಿ ಭವದ ಸಮೀಪದ ಜೀವರಿಗೆ\nಅಪ್ಪನಂದದಿ ಪುಣ್ಯ ಬಪ್ಪಂತೆ ಕರುಣಿಸು\nಕಪ್ಪು ವರ್ಣನ ಕೂಡೊಪ್ಪಿಸಿ ಪಾಲಿಸು\n||ನಂಬಿದೆ ||\n\nಹತ್ತೇಳು ಎರಡಾಯಿತು\nನಾಡಿಯೊಳು ಸುತ್ತಿ ಸುತ್ತುವ ಮಾರುತ  ||\nಉತ್ತರ ಲಾಲಿಸೊ ಉತ್ಕ್ರಮಣದಲ್ಲಿ |\nನೆತ್ತಿಯ ದ್ವಾರದಿಂದ ಎತ್ತ ಪೋಗಳಿಸದೆ\nತಪ್ಪು ಮರುಳು ಜೀವೋತ್ತಮನೆ\nಸಮಚಿತ್ತ  ಎನಗೆ ಕೊಡುತ್ತ ಉಧ್ಧರಿಸೋ\n||ನಂಬಿದೆ||\n\nಯೋಗಾಸನದೊಳಿಪ್ಪಾ\nಯಂತ್ರೋದ್ಧಾರಕ ಭಾಗವತ ಜನರಪ್ಪ ||\nಯೋಗಿಗಳಿಗೆ ಈಶಾ ವ್ಯಾಸ\nಯೋಗಿಗೊಲಿದ ನ್ಯಾಸ  ||\nಶ್ರೀ ತುಂಗಭದ್ರ ನಿವಾಸ  ಬಾಗುವೆ ಕೊಡು ಲೇಸಾ\nಶ್ರೀ ಗುರು\nವಿಜಯವಿಠ್ಠಲ\nಪಾದಕೆ\nಬಾಗಿದ ಭವದೂರ ಜಾಗರ ಮೂರುತಿ\n||ನಂಬಿದೆ ||\n\n",english:"Nambide ninna paada guru mukhyaprana |\nnambide ninna paada dambhava tolagisi ||\ndimbhadolage hariya bimba polevante maado || nambide ||\n\nAntarangada usura horage nooki\nantarangakke seruvaa |\npantadaalu neene kantu janakavalli ||\nmantriyenisi sarvvantaryaamiyaagi\nnintu naana bage tantu nadesuva\nhantakari gunavanta balaadya ||nambide ||\n\nIppattu ondu savira idondu nooru\napratima hamsa mantaraa|\ntappade dina oppadindali japisi ||\ntappisi bhavada sameepada jeevarige\nappanandadi punya bappante karunisu\nkappu varnada koodoppisi paalisu || nambide ||\n\nHattelu eradaayitu\nnaadiyolu sutti suttuva maaruta ||\nuttara laaliso utkramanadalli |\nnettiya dwaaradinda etta pogalisade\ntappu marulu jeevottamane\nsamachitta enage kodutta uddhariso || nambide ||\n\nYogaasanadolippa\nyantroddharaka bhaagavata janarappa ||\nyogigalige eeshavyaasa\nyogigolida nyaasa ||\nsri tungabhadra nivasa baaguve kodu lesa\nsri guru\nvijayavittala\npaadake\nbaagida bhavadoora jaagara mooruti || nambide ||\n\n",meta:"",tags:["anjaneya hanuma","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=rHV8ABQaKPM"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ನಂಬಿದೆ-ನಿನ್ನ-ಪಾದ-ಗುರು-ಮುಖ್ಯಪ್ರಾಣ.json",
	rawData: "",
};

export { _internal, collection, data, id };
