const id = "ನೀಲ-ಘನ-ನೀಲ-ಜೋ";
const collection = "bhajan";
const data = {kannada_title:"ನೀಲ ಘನ ನೀಲ ಜೋ",english_title:"Nila ghana nila jo jo",kannada:"ನೀಲ ಘನ ನೀಲ ಜೋ ಜೋ, ಕುರುಣಾಲವಾಲ ಶ್ರೀ ಕೃಷ್ಣ ಜೋ ಜೋ  | ಲೀಲಾವತಾರ ಜೋ ಜೋ, ಪರಮಾತ್ಮ ಬಾಲ ಗೋಪಾಲ ಜೋ ಜೋ ||ಪ||\n\nಇಂದುಧರ ಮಿತ್ರ ಜೋ ಜೋ, ಪರಮಾತ್ಮ, ಇಂದುರವಿ ನೇತ್ರ ಜೋ ಜೋ | ಇಂದುಕುಲ ರತ್ನ ಜೋ ಜೋ, ಪರಮಾತ್ಮ, ಇಂದಿರಾರಮಣ ಜೋ ಜೋ ||\n\nಆಶ್ಚರ್ಯ ಜನಕವಾಗಿ, ನಿರ್ಮಿಸಿದ, ಪಚ್ಚೆಯಾ ತೊಟ್ಟಿಲಲ್ಲಿ | ಅಚ್ಯುತಾನಂತನಿರಲು, ತೂಗಿದರು, ಮತ್ಸ್ಯಾವತಾರ ಹರಿಯ ||\n\nಧರ್ಮ ಸಂಸ್ಥಾಪನೆಂದು, ನಿರವಧಿಕ, ನಿರ್ಮಲಚರಿತನೆಂದು | ವರ್ಮ ಕರ್ಮಗಳ ತಿಳಿದು, ತೂಗಿದರು, ಕೂರ್ಮಾವತಾರ ಹರಿಯ ||\n\nಸರಸಿಜಾಕ್ಷಿಯರು ಎಲ್ಲ, ಜನವಶ್ಯಕರ ದಿವ್ಯ ರೂಪನೆಂದು | ಪರಮ ಹರ್ಷದಿ ಪಾಡುತ, ತೂಗಿದರು ವರಹಾವತಾರ ಹರಿಯ ||\n\nಕರಕುಂಭಗಳು ಪೋಲುವ ಕುಚದಮೇಲ್ ಹಾರ ಪದಕವು ಹೊಳೆಯಲು |ವರ ವರ್ಣಿನಿಯರು ಕೂಡಿ ತೂಗಿದರು, ನರಸಿಂಹ ರೂಪ ಹರಿಯ ||\n\nಭಾಮಾ ಮಣಿಯರೆಲ್ಲ, ಜಗದೊಳಗೆ ಸೋಮನಿವನೆಂದು ಹೊಗಳಿ |ನೇಮದಿಂದಲಿ ಪಾಡುತ ತೂಗಿದರು, ವಾಮನ ರೂಪ ಹರಿಯ ||\n\nಸಾಮಜವರದನೆಂದು ಅತುಳ ಭೃಗು ರಾಮಾವತಾರನೆಂದು |ಪ್ರೇಮದಿಂದಲಿ ಪಾಡುತ ತೂಗಿದರು, ಭಾರ್ಗವ ರೂಪ ಹರಿಯ ||\n\nಕಾಮಿನಿಯ ಕಾಮನೆಂದು, ಸುರಸಾರ್ವಭೌಮ ಗುಣಧಾಮನೆಂದು |ವಾಮ ನೇತ್ರಿಯರು ಪಾಡಿ ತೂಗಿದರು, ರಾಮಾವತಾರ ಹರಿಯ ||\n\nಸೃಷ್ಟಿಯಾ ಕರ್ತನೆಂದು ಜಗದೊಳಗೆ ದುಷ್ಟ ಸಂಹಾರನೆಂದು |ದೃಷ್ಟಾಂತರಹಿತನೆಂದು ತೂಗಿದರು, ಕೃಷ್ಣಾವತಾರ ಹರಿಯ ||\n\nವೃದ್ಧ ನಾರಿಯರು ಯೆಲ್ಲ ಜಗದೊಳ್ ಪ್ರಸಿದ್ಧನಿವನೆಂದು ಹೊಗಳಿ |ಬದ್ಧಾನುರಾಗದಿಂದ ತೂಗಿದರು, ಬೌದ್ಧಾವತಾರ ಹರಿಯ ||\n\nಝಣ ಝಣತ್ಕಾರದಿಂದ ರಂಜಿಸುವ ಮಲಯಜಾಲೇಪದಿಂದು |ಕುಸುಮ ಗಂಧಿಯರು ಕೂಡಿ ತೂಗಿದರು, ಕಲ್ಕ್ಯಾವತಾರ ಹರಿಯ ||\n\nತುಂಗ ಭವ ಭಂಗ ಜೋ ಜೋ, ಶ್ರೀ ಕೃಷ್ಣ, ಮಂಗಳಾಪಾಂಗ ಜೋ ಜೋ, |ರಂಗ ಶ್ರೀ ಪಾಂಗ ಜೋ ಜೋ, ಪರಮಾತ್ಮ ರಂಗ-ವಿಠ್ಠಲನೆ ಜೋ ಜೋ ||\n\n",english:"Nila ghana nila jo jo, kurunaalavaala shri krishna jo jo |\nlilaavataara jo jo, paramaatma baala gopaala jo jo ||\n\nIndudhara mitra jo jo, paramaatma, induravi netra jo jo |\nindukula ratna jo jo, paramaatma, indiraaramana jo jo ||\n\nAascharya janakavaagi, nirmisida, paccheyaa tottilalli\nachyutaanantaniralu, tugidaru, matsyaavataara hariya ||\n\nDharma samsthaapanendu, niravadhika, nirmalacharitanendu\nvarma karmagala tilidu, tugidaru, kurmaavataara hariya ||\n\nsarasijaakshiyaru ella, janavashyakara divya rupanendu\nparama harshadi paaduta, tugidaru varahaavataara hariya ||\n\nKarakumbhagalu poluva kuchadamel haara padakavu holeyalu\nvara varniniyaru kudi tugidaru, narasimha rupa hariya ||\n\nBhaamaa maniyarella, jagadolage somanivanendu hogali\nnemadindali paaduta tugidaru, vaamana rupa hariya ||\n\nSaamajavaradanendu atula bhrugu raamaavataaranendu\npremadindali paaduta tugidaru, bhaargava rupa hariya ||\n\nKaaminiya kaamanendu, surasaarvabhouma gunadhaamanendu\nvaama netriyaru paadi tugidaru, raamaavataara hariya ||\n\nSrushtiyaa kartanendu jagadolage dushta samhaaranendu\ndrushtaantarahitanendu tygidaru, krishnaavataara hariya ||\n\nVruddha naariyaru yella jagadol prasiddhanivanendu hogali\nbaddhaanuraagadinda tugidaru, bouddhaavataara hariya ||\n\nJhana jhanatkaaradinda ramjisuva malayajaalepadindu\nkusuma gandhiyaru kudi tugidaru, kalkyaavataara hariya ||\n\nTunga bhava bhanga jo jo, shri krishna, mangalaapaanga jo jo,\nranga shri paanga jo jo, paramaatma ranga-vithalane jo jo ||\n\n",meta:"",tags:["kannada devotional song"],media:""};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ನೀಲ-ಘನ-ನೀಲ-ಜೋ.json",
	rawData: "",
};

export { _internal, collection, data, id };
