const id = "ನರಸಿಂಹ-ಪಾಹಿ-ಲಕ್ಷ್ಮೀ-ನರಸಿಂಹ";
const collection = "bhajan";
const data = {kannada_title:"ನರಸಿಂಹ ಪಾಹಿ ಲಕ್ಷ್ಮೀ ನರಸಿಂಹ",english_title:" Narasimaha paahi lakshminarasimha",kannada:"ನರಸಿಂಹ ಪಾಹಿ ಲಕ್ಷ್ಮೀ ನರಸಿಂಹ ||pa||\n\nನರಸಿಂಹ ನಮಿಪೆ ನಾ ನಿನ್ನ\nಚಾರುಚರಣ ಕಮಲಕೆ ನೀ ಎನ್ನ\nಕರವ ಪಿಡಿದು ನಿಜ ಶರಣನೆಂದೆನಿಸೊ ಭಾಸುರ\nಕರಣಾಂಬುಧೆ ಗರುಡವಾಹನ ಲಕ್ಷ್ಮೀ ||a.pa||\n\nತರಳ ಪ್ರಹ್ಲಾದನ್ನ ನುಡಿಯಾ ಕೇಳಿ\nತ್ವರಿತದಿ ಬಂದ್ಯೊ ಎನ್ನೊಡೆಯ ನಾನು\nಕರುಣಾಳೊ ಭಕ್ತರ ಭಿಡೆಯ ಮೀರ-\nಲರಿಯೆ ಎಂದೆಂದು ಕೆಂಗಿಡಿಯ ಅಹ-\nಭರದಿಂದುಗುಳುತ ಬೊಬ್ಬಿರಿದು ಬೆಂಬತ್ತಿಕ-\nರ್ಬುರ ಕಶ್ಯಪುವಿನ ಹಿಂಗುರುಳ ಪಿಡಿದೆ ಲಕ್ಷ್ಮೀ ||1||\n\nಪ್ರಳಯಾಂಬುನಿಧಿ ಘನಘೋಷದಂತೆ\nಘುಳಿ ಘುಳಿಸುತಲಿ ಪ್ರದೋಷ ಕಾಲ\nತಿಳಿದು ದೈತ್ಯನ ಅತಿರೋಷದಿಂದ\nಪ್ಪಳಿಸಿ ಮೇದಿನಿಗೆ ನಿದೋಷ ಅಹ\nಸೆಳೆಸೆಳೆಯುತ ಚರ್ಮ ಸುಲಿದು ಕೆನ್ನೆತ್ತರೋ\nಕುಳಿಯನಾಡಿದೆ ದಿಶಾವಳಿಗಳೊಳಗೆ ಲಕ್ಷ್ಮೀ ||2||\n\nಕ್ರೂರ ದೈತ್ಯನ ತೋರಗರುಳಾ ತೆಗೆ\nದ್ಹಾರ ಮಾಡಿದೆ ನಿಜಕೊರಳ ಕಂಡು\nವಾರಿಜಾಸನ ಮುಖದಯರ್ಕಳ ಪುಷ್ಪ\nಧಾರಿಗೆರೆದು ವೇಗ ತರಳಾ ಆಹ\nಸೂರಿ ಪ್ರಹ್ಲಾದಗೆ ತೋರಿ ತವಾಂಘ್ರಿ ಸ\nರೋರುಹಾವನು ಕಾಯ್ದೆ ಕಾರಣ್ಯನಿಧಿ ||3||\n\nಜಯಜಯ ದೇವವರೇಣ್ಯ ಮಹ\nದ್ಭಯ ನಿವಾರಣನೆ ಅಗಣ್ಯ ಗುಣಾ\nಶ್ರಯ ಘೋರ ದುರಿತಾರಣ್ಯ ಧನಂ\nಜಯ ಜಗದೇಕ ಶರಣ್ಯ ಅಹ\nಲಯವಿವರ್ಜಿತ ಲೋಕ\nತ್ರಯ ವ್ಯಾಪ್ತ ನಿಜಭಕ್ತ\nಪ್ರಿಯ ಘೋರಮಯ ಹರ\nದಯ ಮಾಡೆನ್ನೊಳು ಲಕ್ಷ್ಮೀ ||4||\n\nಕುಟಲ ದ್ವೇಷದವನು ನೀನಲ್ಲ ನಿನ್ನಾ\nರ್ಭಟಕಂಜಿದರು ಸುರರೆಲ್ಲ ನರ\nನಟನೆ ತೋರಿದ್ಯೋ ಲಕ್ಷ್ಮೀನಲ್ಲ ನಾ ಪಾ\nಸಟಿ ಕಾಣೆನಪ್ರತಿಮಲ್ಲ ಅಹ\nವಟಪತ್ರಶಯನ ಧೂ\nರ್ಜಟಿವಂದ್ಯ\nಜಗನ್ನಾಥ\nವಿಠಲ\nಕೃತಾಂಜಲಿಪುಟದಿ ಬೇಡುವೆ ಲಕ್ಷ್ಮೀ||5||\n\n",english:"Narasimaha paahi lakshminarasimha || pa ||\n\nNarasimha namipe naa ninna\ncharucharana kamalake nee enna\nkarava pididu nija sharananendeniso bhasura\nkarunaambudhe garudavaahana lakshmi ||a.pa||\n\nTarala prahladanna nudiya keli\ntwaritadi bandyo ennodeya naanu\nkarunaalo bhaktara bhideya meeralariye\nendendu kengidiya aha-\nbharadinduguluta bobbiridu bembattika-\nrbura kashyapuvina hingurula pidide lakshmi ||1||\n\nPralayambunidhi ghanaghoshadante\nghali ghalisutali pradosha kaala\ntilidu daityana atiroshadinda\nppalisi medinige nidosha aha-\nseleseleyuta charma sulidu kennettaru\nkuliyanaadide dishavaligalolage lakshmi ||2||\n\nKroora daityana toragarulaa tege\ndhaara maadide nijakorala kandu\nvaarijasana mukhadayarkala pushpa\ndharigeredu vega taralaa aaha\nsoori prahlaadage tori tavaamghrisa\nroruhaavanu kaayde karunyanidhe ||3||\n\nJayajaya devavarenya maha\ndbhaya nivaaranane agraganya gunaa\nshraya ghora duritaaranya dhanam\njaya jagadeka sharanya aha\nlayavivarjita loka\ntraya vyaapta nijabhakta\npriya ghoramaya hara\ndaya maadennolu lakshmi ||4||\n\nKutila dweshadavanu neenalla nennaa\nrbhatakanjidaru surarella nara\nnatane toridyo lakshminalla naa paa\nsati kaanina pratimalla aha\nvatapatra shayana dhu\nrjativandya\njagannaatha\nvittala\nkrutaanjali putadi beduve lakshmi || 5||\n\n",meta:"ನರಸಿಂಹ ಪಾಹಿ ಲಕ್ಷ್ಮೀ ನರಸಿಂಹ ||pa||",tags:["narasimha","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=Ip8Zwww5-no"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ನರಸಿಂಹ-ಪಾಹಿ-ಲಕ್ಷ್ಮೀ-ನರಸಿಂಹ.json",
	rawData: "",
};

export { _internal, collection, data, id };
