const id = "ನಂಬಿದೆ-ನಿನ್ನ-ಪಾದ-ನರಸಿಂಹ";
const collection = "bhajan";
const data = {kannada_title:"ನಂಬಿದೆ ನಿನ್ನ ಪಾದ ನರಸಿಂಹ",english_title:" Nambide ninna paada narasimha",kannada:"ನಂಬಿದೆ ನಿನ್ನ ಪಾದ ನರಸಿಂಹ\nಎನ್ನ ಬೆಂಬಿಡದೆ ಸಲಹಯ್ಯ ನರಸಿಂಹ  || ನಂಬಿದೆ||\n\nಹಂಬಲಿಸುವೆನು ಬಲು ನರಸಿಂಹ\nಪಾದ ನಂಬಿದವರನು ಕಾಯೊ ನರಸಿಂಹ ||ನಂಬಿದೆ||\n\nತುಂಬುರು ನಾರದ ಪ್ರಿಯ ನರಸಿಂಹ\nಚೆಲ್ವ ಶಂಬರಾರಿಯ ಪಿತನೆ ನರಸಿಂಹ |\nಅಂಬರೀಶನ ಕಾಯ್ದೆ ನರಸಿಂಹ ||2||\nಜಗದಂಬಾ ರಮಣನೆ ಶ್ರೀ ನರಸಿಂಹ ||ನಂಬಿದೆ||\n\nಬಾಲ ಕರೆದಲ್ಲಿ ಬಂದೆ ನರಸಿಂಹ\nಭಕ್ತ ಪಾಲಿಪ ದಯಾಳು ಶ್ರೀ ನರಸಿಂಹ ||\nಲೀಲೆಯಿಂದ ಹಿರಣ್ಯಾನ ನರಸಿಂಹ || 2 ||\nಕೊಂದ ಲೋಲ ಸಿರಿ ಅರಸನೆ ನರಸಿಂಹ ||ನಂಬಿದೆ||\nಅಚ್ಯುತಾನಂತ ಗೋವಿಂದ ನರಸಿಂಹ\nಶ್ರೀ ಸಚ್ಚಿದಾನಂದ ಮುಕುಂದ ನರಸಿಂಹ |\nಕಿಚ್ಚಿನಂದದಿ ಬೆಂದೆ ನರಸಿಂಹ || 2 ||\nಭವ ಇಚ್ಛೆಯಿಂದ ಬಿಡಿಸಯ್ಯ ನರಸಿಂಹ ||ನಂಬಿದೆ||\n\nಕರಿ ಮೊರೆಯನು ಕೇಳಿ ನರಸಿಂಹ\nಬಲು ಭರದಿಂದೊದಗಿ ಬಂದೆ ನರಸಿಂಹ |\nಗರುಡವಾಹನನಾಗಿ ನರಸಿಂಹ || 2 ||\nಉದ್ಧರಿಸಿ ಕಾಯ್ದೆಯಲ್ಲೊ ನರಸಿಂಹ ||ನಂಬಿದೆ||\n\nದೇವರದೇವನು ನೀನೆ ನರಸಿಂಹ\nಬೇರೆ ಕಾವರನ್ನು ಕಾನೆನಯ್ಯ ನರಸಿಂಹ |\nಬಾವಜನಯ್ಯನೆ ಶ್ರೀ ನರಸಿಂಹ || 2 ||\nನಿನ್ನ ಸೇವೆಯ ಪಾಲಿಸಿ ಕಾಯೊ ನರಸಿಂಹ  ||ನಂಬಿದೆ||\n\nತಂದೆತಾಯಿ ಗುರು ದೈವ ನರಸಿಂಹ\nಎನ್ನ ಬಂಧುಬಳಗವು ನೀನೆ ನರಸಿಂಹ |\nಕುಂದು ಹೆಚ್ಚು ನೋಡ ಬೇಡ ನರಸಿಂಹ. || 2 ||\nಪುರಂದರ ವಿಠ್ಠಲ ಕಾಯೋ ನರಸಿಂಹ.||ನಂಬಿದೆ||\n\n",english:"Nambide ninna paada narasimha enna bembidade salahayya narasimha || Nambide ||\n\nHambalisuvenu balu narasimha | paada nambidavaranu kaayo narasimaha | nambide narasimha ||  laxminarasimha ||\n\nTumburu narada priya narasimha | chelva shambarariya pitane narasimha | ambarishana kaayde narasimha  || Nambide ||\n\nBala karedalli bande narasimha | bhakta palipa dayalu sri narasimha | leeleyinda hiranyana narasimha | konda lola siri arasane narasimha  || Nambide ||\n\nAchyutananta govinda narasimha | sri sacchidananda mukunda narasimha | kicchinandadi bende narasimha || Nambide ||\n\nKari moreyanu keli narasimha  | balu bharadindodagi bande narasimha | garudavahananagi narasimha | uddharisi kaaydeyello narasimha || Nambide ||\n\nDevara devanu neene narasimha | bere kaavarannu kanenayya narasimha | baavajanayyane sri narasimha || Nambide ||\n\nTande taayi guru daiva narasimha | enna bandubalagavu neene narasimha | kundu hecchu nodabeda narasimha | purandaravittala kaayo narasimha …. aa …. || Nambide ||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=vFPccld_dr8"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ನಂಬಿದೆ-ನಿನ್ನ-ಪಾದ-ನರಸಿಂಹ.json",
	rawData: "",
};

export { _internal, collection, data, id };
