const id = "ನಿನ್ನ-ನಾಮವೆ-ಎನಗೆ-ಅಮೃತಾನ್ನವು";
const collection = "bhajan";
const data = {kannada_title:"ನಿನ್ನ ನಾಮವೆ ಎನಗೆ ಅಮೃತಾನ್ನವು",english_title:" Ninna namave enage amrutaannavu",kannada:"ನಿನ್ನ ನಾಮವೆ ಎನಗೆ ಅಮೃತಾನ್ನವು |\nಇನ್ನು ಹಸಿದಿರಲೇಕೆ ಎನಗೆ ನೀನೊಲಿದಿರಲು ||ಪ||\n\nಓಂಕಾರವೆಂಬ ನಾಮ ಉಪ್ಪು – ಉಪ್ಪಿನಕಾಯಿ |\nಶಂಖಪಾಣಿಯ ನಾಮ ಪಾಕಾದಿ ಸೂಪ ||\nಸಂಕರ್ಷಣನ ನಾಮ ದಿವ್ಯ ಶಾಲ್ಯನ್ನವು |\nಪಂಕಜಾಕ್ಷನ ನಾಮ ಪಳಿದೆ ಬಗೆಬಗೆ ಸಾರು ||1||\n\nಕೇಶವನೆಂಬ ನಾಮ ಕರಿದ ಹೂರಣಗಡಬು |\nವಾಸುದೇವನ ನಾಮ ವಡೆ – ಸೇವಗೆ ||\nಸಾಸಿರದ ನಾಮಗಳು ಸವಿಸವಿಯ ಪರಮಾನ್ನ |\nದೋಷದೂರನ ನಾಮ ದೋಸೆ – ಸೂಸಲಗಡಬು ||2||\n\nನಾರಾಯಣನ ನಾಮ ನೊರೆಹಾಲು ಸಕ್ಕರೆ |\nಶ್ರೀರಾಮ ನಾಮ ಸರವಳಿ ಸಜ್ಜಿಗೆ ||\nಕಾರಣ್ಯನಿಧಿ ನಾಮ ಕರಿದ ಹಪ್ಪಳ – ಸಂಡಿಗೆ |\nಪಾರಾಯಣನ ನಾಮ ಪರಿಪರಿಯ ಪಕ್ವಾನ್ನ ||3||\n\nಯದುಪತಿಯೆಂಬ ನಾಮ ಎಣ್ಣೂರಿಗೆಯ ರಾಶಿ |\nಮಧುಸೂದನನ ನಾಮ ಮಧುರ ಮಂಡಿಗೆಯು ||\nಚದುರಗೋವಳ ನಾಮ ಚೆಲುವ ಬೀಸೂರಿಗೆ |\nಪದುಮನಾಭನ ನಾಮ ಪರಿಪರಿಯ ಭಕ್ಷ್ಯ ||4||\n\nದೇವಕಿಸುತನ ನಾಮ ವಧ್ಯನ್ನದಾ ಮುದ್ದೆ |\nಗೋವಿಂದನ ನಾಮ ಗುಳ್ಳೋರಿಗೆ ||\nಮಾವಮರ್ದನನ ನಾಮ ಕಲಸುಮೇಲೋಗರ |\nರಾವಣಾರಿಯ ನಾಮ ಇಡ್ಡಲಿಗೆ – ಸಖಯುಂಡೆ ||5||\n\nಗರುಡವಾಹನನ ನಾಮ ಘೃತಪಯೋದಧಿತಕ್ರ |\nಪರಮಪುರುಷನ ನಾಮ ಪನ್ನೀರ ಪಾನ ||\nಕರಿವರದ ನಿನ್ನ ನಾಮ ಕರ್ಪುರದ ವೀಳ್ಯವು |\nಶರಧಿಶಯನನ ನಾಮ ಶಯನಪರ್ಯಂಕ ||6||\n\nಈ ಪರಿಯ ನಾಮಾವಳಿಯನು ಸವಿದುಂಡು |\nಆಪತ್ತು ಬಿಡಿಸೆಕಿನ್ನ ಕ್ಷುಧೆಯ ನೂಕಿ ||\nಗೋಪಾಲ ಉರಗಾದ್ರಿ\nಪುರಂದರವಿಠಲ\nನ |\nಶ್ರೀಪಾದವನೆ ನಂಬಿ ಅಪವರ್ಗ ಸೇರುವ ||7||\n\n",english:"Ninna namave enage amrutaannavu |\nennu hasidiraleke enage neenolidiralu ||pa||\n\nOmkaravemba nama uppu- uppinakayi |\nshankhapaniya naama paakadi soopa ||\nsankarshanana naama divya shalyaannavu |\npankajakshana nama palide bagebage saaru ||1||\n\nKeshavanemba naama karida hooranakadubu| |\nvasudevana naama vade sevige ||\nsaasira naamagalu savisaviya paramaanna |\ndoshadoorana naama dose – soosalagadubu ||2||\n\nNarayanana naama norehaalu sakkare |\nsriraama naama saravali sajjige ||\nkaaruyanidhi naama karida happala – sandige |\nparayanana naama paripariya pakvaanna ||3||\n\nYadupatiyemba naama ennoorigeya raashi |\nmadhusudhannana naama madhura mandigeyu ||\nchaduragovala naama cheluva beesurige |\npadumanaabhana naama paripariya bhakshya ||4||\n\nDevakisutana naama vadhyannadaa mudde |\ngovindana naama gullorige ||\nmaavamardhanana naama kalasumelogara |\nraavanariya naama eddalige – sakhayunde ||5||\n\nGarudavaahanana naama ghrutapayodadhitakra |\nparamapurushana naama manneera paana |\nkarivarada ninna naama karpoorada veelyavu |\nsharadhi shayanana naama shayanaparyanka ||6||\n\nEe pariya naamaavaliyanu savidundu |\naapattu bidisekinna kshudheya nooki |\ngopaala uragadri\npurandaravittala\nna |\nsripaadavane nambi apavarga seruva ||\n\n",meta:"",tags:["narayana","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=Np0pid1hiyI"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ನಿನ್ನ-ನಾಮವೆ-ಎನಗೆ-ಅಮೃತಾನ್ನವು.json",
	rawData: "",
};

export { _internal, collection, data, id };
