const id = "ನಿನ್ನ-ಅಂಗಳದೊಳಗೆ-ಹಿಡಿ-ಅನ್ನ";
const collection = "bhajan";
const data = {kannada_title:"ನಿನ್ನ ಅಂಗಳದೊಳಗೆ ಹಿಡಿ ಅನ್ನ",english_title:"Ninna angaladolage hidi anna",kannada:"ನಿನ್ನ ಅಂಗಳದೊಳಗೆ ಹಿಡಿ ಅನ್ನ ಹಾಕೋ\nಘನ್ನ ಶ್ರೀ ಗುರುರಾಘವೇಂದ್ರ ಸಂಪನ್ನ ।।ಪ ।।\n\nವರುಷ ವರುಷಕೆ ನಿನ್ನ ದರುಶನವ ದಯಾ ಮಾಡೋ\nದುರಿತ ನಾಶನ ಗೈದು ಪರಿಶುದ್ಧಗೊಳಿಸೋ\nಅರಿತು ಅರಿಯದೆ ಗೈವ ಪಾಪ ಕರ್ಮವ ಕಳೆದು\nನಿರುತ ಶ್ರೀಹರಿ ಕೃಪೆಗೆ ಪಾತ್ರನಾಗಿರಿಸೋ ।।೧।।\n\nನಿನ್ನ ಭಕುತರ ಪಾದ ರಜದೊಳಿದಾಡಿಸೋ\nನಿನ್ನ ಗುಣ ಕೀರ್ತನೆಯ ಕಿವಿಗಳಲಿ ನಿಲಿಸೋ\nನಿನ್ನ ಪಾದೋದಕದಿ ಪಾವನ್ನ ಮಾಡೆನ್ನ\nನಿನ್ನ ರಘುಪತಿ ದಿವ್ಯ ದರುಶನವ ಕೊಡಿಸೋ ।।೨।।\n\nಮಂತ್ರ ಸದನದಿ ನಿನ್ನ ಸಂತಸ ಮಹೋತ್ಸವದಿ\nಶಾಂತಿ ಸುಖ ಸಂಭ್ರಮದಿ ಸನ್ನಿಧಿಯೊಳಿರಿಸೋ\nಸಂತ ಶರಣರ ಭಕುತಿ ನೃತ್ಯಗೀತಗಳ ನೋಡಿ\nನಲಿಯುವ ಭಾಗ್ಯ ಕೊಡು ಎನಗೆ ಪ್ರಭುವೇ ।।೩।।\n\nಪ್ರಲ್ಹಾದ ರಾಯನೀ ಬಲ್ಲಿದನು ಜಗದೊಳಗೆ\nಕಾಯ್ವ ನರಹರಿ ದೂತಾನಹುದೋ\nಎಲ್ಲ ರಾಜರ ರಾಜ ವ್ಯಾಸರಾಯನೇ ಸತ್ಯ\nಇಲ್ಲಿ ಶ್ರೀ ಪರಿಮಳರಾಯರ ಮಹಿಮೆಯೇ ಸ್ತುತ್ಯ ।।೪।।\n\nಏನು ಬೇಡಲಿ ನಾನು ದಾನ ಕರ್ಣನು ನೀನು\nಜ್ಞಾನಿ ಸದ್ಗುರು ಕಲ್ಪವೃಕ್ಷ ಸುರಧೇನು\nದೀನ ರಕ್ಷಕ ವಿಠಲೇಶ ಕರುಣಾಭರಣ\nಸಾನುರಾಗದಿ ನಿನ್ನ ಸೇವಕರೊಳಿರಿಸೋ।।೫।।\n\n",english:"Ninna angaladolage hidi anna haako\nghanna shree gururaaghavendra sampanna || pa ||\n\nVarusha varushake ninna darushanava daya maado |\ndurita naashanagaidu parishuddhagoliso|\nAritu ariyade gaiva paapa karmava kaledu |\nniruta shree harikrupege paatranaagiriso || 1 ||\n\nNinna bhakutara paada rajadolidaadiso |\nninna guna keertaneya kivigalali niliso |\nninna paadodakadi paavanna maadenna |\nninna raghupati divya darushanava kodiso || 2 ||\n\nMantra sadanadi ninna santasa mahotsavadi |\nshaanti sukha sambhramadi sannidhiyoliriso |\nsanta sharanara bhakuti nrutyageetegala |\nnodi naliyuva bhaagya kodu enage prabhuve || 3 ||\n\nPralhaadaraaya nee ballidanu jagadolage |\nnillade kayva narahari dootanahudo |\nella rajara raaja vyasaraayane satya |\nilli shree parimalaaryara mahime stutya || 4 ||\n\nEnu bedali naanu daani karnane neenu|\njnaani sadguru kalpavruksha suradhenu |\ndeena rakshaka viththalesha karunaabharana |\nsaanuraagadi ninna sevakaroliriso || 5 ||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=WAsnOjeq4t0"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ನಿನ್ನ-ಅಂಗಳದೊಳಗೆ-ಹಿಡಿ-ಅನ್ನ.json",
	rawData: "",
};

export { _internal, collection, data, id };
