const id = "ನಂಬಿ-ನೆಚ್ಚದಿರು-ನರಲೋಕ";
const collection = "bhajan";
const data = {kannada_title:"ನಂಬಿ ನೆಚ್ಚದಿರು ನರಲೋಕ",english_title:"Nambi necchadiru naraloka",kannada:"\nನಂಬಿ ನೆಚ್ಚದಿರು ನರಲೋಕ ಸುಖವೆಂಬೊ ಅಂಬಲಿ ಪರಮಾನ್ನ |\nಹಂಬಲಿಸುತಲಿರು ಹರಿಲೋಕಾನಂದವೆಂಬ ಪೀಯೂಷಪಾನ ||\n||ನಂಬಿ ನೆಚ್ಚದಿರು||\n\nದುರುಳಾಜನರ ಸಂಗವೆಂಬುದು ಎಂದಿಗೂ ನೊಣ ಬೆರಸಿದ ಊಟ\nಪರಮಭಾಗವತರ ಪದಸಂಗವೆಂಬುದು ಮಸ್ತಕ ಮಣಿ ಮುಕುಟಾ |\nಮರೆ ಮೋಸಗೊಳಿಸುವ ಸತಿಸುತರೆಂಬೋದೆ ಕೇವಲ ಯಮಕಾಟ |\nಪರತತ್ವನಾದ ಶ್ರೀಹರಿಯನ್ನು ಭಜಿಸುವುದೆ ವೈಕುಂಠಕೆ ಓಟಾ….\n||ನಂಬಿ ನೆಚ್ಚದಿರು||\n\nಬಿದ್ದ ಕಾಳಿಗೆ ಕಾಳು ಕೂಡಿ ಹಾಕುವುದೆಲ್ಲ ಹಾರಿ ಹೋಗುವ ಹೊಟ್ಟು\nಇದ್ದಾಗ ದಾನ ಧರ್ಮಂಗಳ ಮಾಡೋದು ಕೈವಲ್ಯಕೆ ಮೆಟ್ಟು ||\nಹೊದ್ದಿರುವರ ಕಂಡಾಸೆಯಪಟ್ಟರೆ ಹೋಗುವಿ ನೀ ಕೆಟ್ಟು |\nಬುದ್ಧಿಹೀನರಿಗೆ ಪೇಳದಿರೆಲೊ ತತ್ವಸಾರ ಸುಂದರ ಗುಟ್ಟೂ….\n||ನಂಬಿ ನೆಚ್ಚದಿರು||\n\nಅಲ್ಪಾವಕಾಶವು ಈ ಶರೀರವು ಗಾಳಿಗೊಡ್ಡಿದ ದೀಪ\nಅಲ್ಪ ಸಂತೋಷನಾಗು ಅದು ನಿನಗೆ ನೋಡು ,ಹಾಲುಸಕ್ಕರೆ ತುಪ್ಪ |\nಬಲ್ಪಂಥ ಮಾಡದಿರು ಜನುಮಜನ್ಮದಲಿ ಬಿಡದೆಲೊ ಸಂತಾಪ |\nಸ್ವಲ್ಪಕಾಲಾದರೂ ಮಧ್ವಮತವಪೊಂದು ಭವವೇ ನಿರ್ಲೇಪಾ….\n||ನಂಬಿ ನೆಚ್ಚದಿರು||\n\nಹರಿಗರ್ಪಿಸದ ಕರ್ಮ ಆವುದಾದರು ಸೂಳೆಗಿಕ್ಕಿದ ವಿತ್ತ\nಹರಿಗೆ ವಿಶ್ವಾಸದಿ ಅಣುಮಾತ್ರ ಅರ್ಪಿಸೆ ಅವನೆ ನಿರ್ಮಲ ಚಿತ್ತ |\nನಿರುತಗ್ರಾಸಕೆ ಚಿಂತೆಮಾಡಲು ಒದಗದು ಪುಣ್ಯವು ನಿನಗೆತ್ತ |\nಅರೆ ಮನವಿಲ್ಲದೆ ದೃಢಮನದಿಪ್ಪುದೆ ಸಂಪಾದನೆ ಭತ್ಯಾ….\n||ನಂಬಿ ನೆಚ್ಚದಿರು||\n\nಭಾವ ವಿರಕ್ತಿಯ ವಹಿಸದಿದ್ದರೆ ನಿನಗಾಗುವುದು ಖೇದ\nಸಾವಿರಕೊಂದೆ ಮಾತು ಹರಿದಾಸನೆನಿಸೋದು ಪರಿಪರಿಯಾಸ್ವಾದ |\nದೇವಕಿಸುತ ನಮ್ಮ ವಿಜಯವಿಠ್ಠಲನಂಘ್ರಿ ತೀರ್ಥ ಪ್ರಾಸಾದ |\nಸೇವಿಸದಾ ನರ ನಿತ್ಯ ನರಕವಾಸ ಎನ್ನುತಲಿದೆ ವೇದಾ….\n||ನಂಬಿ ನೆಚ್ಚದಿರು||\n\n",english:"Nambi necchadiru naraloka sukhavembo ambali paramaanna | hambalisutaliru  harilokaanandavemba peeyushapaana || nambi necchadiru ||\n\nDurulaajanara sangavembudu endigoo nona beresida oota | parama bhagavatara padasangavembudu mastaka mani mukutaa || mare mosagolisuva sati sutarembode kevala yamakaata | paratatvanaada srihariyannu bhajisuvude vaikuntake otaa …. || nambi necchadiru ||\n\nBidda kaalige koodi hakuvudella haari hoguva hottu | eddaaga daana dharmangala maadodu kaivalyake mettu || hoddiruvara kandaaseya pattare hoguvi nee kettu | buddhiheenarige peladirelo tatvasaara sundara guttu … || nambi necchadiru ||\n\nAlpavakaashavu ee shareeravu gaaligoddida deepa | alpa santoshanaagu adu ninage nodu halusakkare tuppa | balpantha maadadiru januma janmadali bidadelo santaapa | swalpa kaaladaru madhwamatavapondu bhavave nirlepaa …. ||nambi necchadiru ||\n\nHarigarpisada karma aavudaadaru soolegikkida vitta | harige vishwaasadi anumaatra arpise avane nirmala chitta || nirutagrasake chinte maadalu odagadu punyavu ninagetta | are manavillade drudamanadippude sampaadane bhatyaa…. ||nambi necchadiru ||\n\nBhaava viraktiya vahisadiddare ninagaaguvudu kheda | saavirakonde maatu haridaasanenisodu paripariyaa swaada | devakisuta namma vijayavittalananghri teertha prasaada | sevisadaa nara nitya narakavaasa ennutalide vedaa … || nambi necchadiru ||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=wreIUwmFths"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ನಂಬಿ-ನೆಚ್ಚದಿರು-ನರಲೋಕ.json",
	rawData: "",
};

export { _internal, collection, data, id };
