const id = "ನ್ಯಾಯ-ನೀತಿ-ಮೂರ್ತಿವೆತ್ತ";
const collection = "bhajan";
const data = {kannada_title:"ನ್ಯಾಯ ನೀತಿ ಮೂರ್ತಿವೆತ್ತ",english_title:" Nyaya neeti moortivetta",kannada:"ವಂದೇ ಶಂಭು ಉಮಾಪತಿಮ್ ಸುರಗುರುಮ್\nವಂದೇ ಜಗತ್ ಕಾರಣಂ\nವಂದೇ ಪನ್ನಗ ಭೂಷಣಮ್ ಮೃಗಧರಮ್\nವಂದೇ ಪಶುನಾಮ್ ಪತಿಮ್\nವಂದೇ ಸೂರ್ಯ ಶಶಂಕ್ ವನ್ನಿ ನಯನಮ್\nವಂದೇ ಮುಕುಂದಪ್ರಿಯಮ್\nವಂದೇ ಭಕ್ತ ಜನಾಶ್ರಯನ್ಚ ವರದಮ್\nವಂದೇ ಶಿವಮ್ ಶಂಕರಮ್\n\nನ್ಯಾಯ ನೀತಿ ಮೂರ್ತಿವೆತ್ತ ಸತ್ಯ ಧೈವವೇ\nಮಹಾಮಹಿಮ ಮಂಜುನಾಥ ನಮೋ ಎನುವೆ\nಭೂಮಿಗಿಳಿದ ಕೈಲಾಸ ನಿನ್ನ ಸನ್ನಿಧಿ\nನೇತ್ರಾವತಿ ನದಿ ಇದುವೆ ಆ ಸುರ ನದಿ ||\n\nಧರ್ಮಪಾಲಾ ದಯಶೀಲ ಮಂಜುನಾಥನೆ\nನಿನ್ನ ಚರಣ ಸೇವೆ ನಮ್ಮ ಗುರಿಯ ಸಾಧನೆ\nಕಾಳರಾತ್ರಿ ಕಾಳರಾಹು ಕುಮಾರಸ್ವಾಮಿಗೆ\nನೇಮದಿಂದ ನಮಿಸುವೆವು ಹೆಜ್ಜೆಹೆಜ್ಜೆಗೆ ||\n\nಅನ್ನಪ್ಪ ಗುರುವೆ ನಿನ್ನಗೆ ಶರಣು ಏನುವೆ\nನಿನ್ನ ರಕ್ಷೆ ಇರಲು ನಾನು ಎಲ್ಲ ಗೆಲುವೆ\nನ್ಯಾಯ ಮಾರ್ಗದಲ್ಲಿ ನೆಡೆದು ಧನ್ಯನಾಗುವೆ\nಧರ್ಮ ನನ್ನ ಕಾಯಲೆಂದು ಸದ ಬೇಡುವೆ ||\n\nಧರ್ಮವನು ರಕ್ಷಿಸುವ ಶಕ್ತಿ ನೀಡು\nನಿನ್ನ ನಂಬಿ ಬಾಳುವ ಭಕ್ತಿ ನೀಡು\nಸತ್ಯವೆ ಗೆಲುವ ನ್ಯಾಯ ನೀಡು\nನಮ್ಮ ಮನದ ಗುಡಿಯಲ್ಲಿ ವಾಸ ಮಾಡು ||\n\n",english:"Vandhe shambu umaapathim suragurum Vandhe jagath kaaranam Vandhe pannaga Bhushanam mrugadharam Vandhe pashunaam pathim Vandhe surya shashanka vanni nayanam Vandhe mukundhapriyam Vandhe Bhaktha janaashrayancha varadham Vandhe shivam shankaram\n\nNyaaya neethi moorthiveththa sathya daivave\nmahaamahima manjunaatha namo enuve\nBhumigilidha kailaasa ninna sannidhi\nnethraavathi nadhi idhuve aa suranadhi\n\nNyaaya neethi moorthiveththa sathya daivave\nmahaamahima manjunaayha namo enuve\n\nDharmapaalaa dhayasheela manjunaathane\nninna charana seve namma guriya saadhane\nKaalaraathri Kaalaraahu kumaaraswaamige\nnemadhindha namisuvevu hejjehejjege ||nyaya neeti ||\n\nAnnappa guruve ninnage sharanu enuve\nninna rakshe iralu naanu ella geluve\nnyaaya maargadhalli nededhu dhanyanaaguve\ndharma nanna kaayalendhu sadha beduve || nyaya neeti ||\n\nDharmavanu rakshisuva shakthi needu\nninna nambi baaluva bhakthi needu\nsathyave geluva nyaaya needu\nnamma manadha gudiyalli vaasa maadu || nyaya neeti||\n\n",meta:"",tags:["shiva","kannada devotional song"],media:"https://www.youtube.com/watch?v=s0Y62qSa_44"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ನ್ಯಾಯ-ನೀತಿ-ಮೂರ್ತಿವೆತ್ತ.json",
	rawData: "",
};

export { _internal, collection, data, id };
