const id = "ಪ್ರಾಣದೇವ-ನೀನಲ್ಲದೆ-ಕಾಯ್ವರ";
const collection = "bhajan";
const data = {kannada_title:"ಪ್ರಾಣದೇವ ನೀನಲ್ಲದೆ ಕಾಯ್ವರ",english_title:" Pranadeva neenallade kayvara",kannada:"ಪ್ರಾಣದೇವ ನೀನಲ್ಲದೆ ಕಾಯ್ವರ ಕಾಣೆನು ಜಗದೊಳಗೇ\n||ಪ್ರಾಣದೇವ||\n\nವಾಸವ ಕುಲಿಶದಿ ಘಾಶಿಸೆ ಜೀವರ ಶ್ವಾಸ ನಿರೋದಿಸಿದೆ |\nಅ ಸಮಯದಿ ಕಮಲಾಸನ ಪೇಳಲು | ನೀ ಸಲಹಿದೆ ಜಗವಾ…. ಮುಖ್ಯ\n||ಪ್ರಾಣದೇವ||\n\nಪರಿಸರ ನೀನಿರೆ ಹರಿ ತಾನಿಪ್ಪ ನೀ ಇರದಿರೆ ಹರಿ ಇರನೂ | ಕರಣ ನಿಯಾಮಕ ಸುರರ ಗುರುವೆ ನೀ ||\nಕರುಣಿಸೆ ಕರುಣಿಸುವಾ…. ಮುಖ್ಯ\n||ಪ್ರಾಣದೇವ||\n\nಅಂಗಧ ಪ್ರಮುಖ ಪ್ಲಭಂಗರು ರಾಮನ ಅಂಗನೆಯಳ ಹುಡುಕೇ |\nತಿಂಗಳು ಮೀರಲು ಕೆಂಗೆಡೆ ಕಪಿಗಳ | ಜಂಗುಳಿ ಪಾಲಿಸಿದೇ……ಮುಖ್ಯ\n||ಪ್ರಾಣದೇವ||\n\nಸಾವಿನ ಪಾಶದಿ ರಾವಣ ನೀಲ ಸುಗ್ರೀವನು ಕರ ಬಿಗಿಯೇ |\nಸಾವಿರ ದೈವಕ್ಕು ಗಾವದದಲ್ಲಿಹ | ಸಂಜೀವನ ಜವದಿ ತಂದಿತ್ತೇ……ಮುಖ್ಯ\n||ಪ್ರಾಣದೇವ||\n\nಭೂತೇಂದ್ರಿಯಂಗಳಿಗಧಿನಾಥ ನಿಯಾಮಕ ಆ ತೈಜಸ ಹರನಾ….. |\nತಾತನೆನಿಪ ಜಗನ್ನಾಥ ವಿಠ್ಠಲನಾ | ಪ್ರೀತಿಪಾತ್ರನಾದೇ…… ಮುಖ್ಯ\n||ಪ್ರಾಣದೇವ||\n\nಶ್ರೀ ಹನುಮಂತಂ ಏಕಾಂತಭಾಜಂ ರಾಘವ ಶ್ರೀಪಾದಂ ಭೋಜಭ್ರಂಗಂ |\nಮಾರುತೀಂ ಪ್ರಾಣಿನಾಂ ಪ್ರಾಣಭೂತಂ ನಂದಯಾಮೋ ವಯಂ ನಂದಿತೀರ್ಥಂ ||\n\n",english:"Pranadeva neenallade kayvara kaneno jagadolage || pranadeva ||\n\nVasava kulishadi ghashise jeevara shwasa nirodhiside | a samayadi kamalasana pelalu | nee salahide jagavaa … mukhya  ||pranadeva ||\n\nParisara neenire hari taa nippa nee eradire hari eranoo | karana niyamaka surara guruve nee | karunise karunisuvaa … mukhya ||pranadeva||\n\nAngadha pramukha plabhangaru ramana anganeyala huduke | tingalu meeralu kengede kapigala | janguli paliside …. mukhya ||pranadeva||\n\nSavina pashadi ravana neela sugreevanu kara bigiye | saavira daivakku gaavadadalliha | sanjeevana javadi tanditte ….. mukhya ||pranadeva ||\n\nBhutendriyangaligadhinaatha niyamak a taijasa harna …. | taatanenipa jagannaatha vittalanaa | preetipaatranade …. mukhya || pranadeva ||\n\nSri hanumantam ekaantabhaajam raghava sripaadambhojabhrangam | marutim praninam pranabhutam nandayamo vayam nanditeertham ||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=LdyiBa9GWVQ"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಪ್ರಾಣದೇವ-ನೀನಲ್ಲದೆ-ಕಾಯ್ವರ.json",
	rawData: "",
};

export { _internal, collection, data, id };
