const id = "ಪವಡಿಸು-ಪರಮಾತ್ಮ-ಶ್ರೀ";
const collection = "bhajan";
const data = {kannada_title:"ಪವಡಿಸು ಪರಮಾತ್ಮ ಶ್ರೀ",english_title:" Pavadisu paramathma",kannada:"ಶ್ರೀ ಎಸ್ ಪಿ ಬಾಲಸುಬ್ರಮಣ್ಯಂ ರವರು ಹಾಡಿರುವ ಸುಮಧುರ ಭಕ್ತಿ ಗೀತೆ\n\nಆ… ಆ .. ಆ.. ಆ..\nಪವಡಿಸು ಪರಮಾತ್ಮ ಶ್ರೀ ವೆಂಕಟೇಶ\nಮನವೆಂಬ ಮಲ್ಲಿಗೆಯ ಹೂವ ಹಾಸಿಗೆ ಮೇಲೆ ..\nಪವಡಿಸು ಪರಮಾತ್ಮ ಶ್ರೀ ವೆಂಕಟೇಶ ಸಪ್ತಗಿರಿವಾಸ ….\n\nರಾಮನಿಗೆ ಕೌಸಲ್ಯ ಲಾಲಿ ಹಾಡಿದ ರೀತಿ\nಅನಸೂಯೆ ಜೋಗುಳವ ಹಾಡಿ ನಲಿದ ರೀತಿ …\nರಾಮನಿಗೆ ಕೌಸಲ್ಯ ಲಾಲಿ ಹಾಡಿದ ರೀತಿ\nಅನಸೂಯೆ ಜೋಗುಳವ ಹಾಡಿ ನಲಿದ ರೀತಿ …\n\nನಿನ್ನ ಮಹಿಮೆಯ ಪಾಡಿ …… ಪಾದ ಸೇವೆಯ ಮಾಡಿ ….\nಆ .. ಆ.. ಆ.. ಆ.. ಆ..\nನಿನ್ನ ಮಹಿಮೆಯ ಪಾಡಿ …… ಪಾದ ಸೇವೆಯ ಮಾಡಿ ….\nಧನ್ಯನಾಗುವೆನಿಂದು ಕರುಣಿಸೋ ….ದಯಮಾಡಿ ..\n\nಪವಡಿಸು ಪರಮಾತ್ಮ ಶ್ರೀ ವೆಂಕಟೇಶ\nಮನವೆಂಬ ಮಲ್ಲಿಗೆಯ ಹೂವ ಹಾಸಿಗೆ ಮೇಲೆ ..\nಪವಡಿಸು ಪರಮಾತ್ಮ ಶ್ರೀ ವೆಂಕಟೇಶ ಸಪ್ತಗಿರಿವಾಸ ….\n\nಇರುಳು ಮುಗಿಯದೆ ಇರಲಿ .. ಹಗಲು ಮೂಡದೇ ಇರಲಿ ..\nಅನುಗಾಲ ಈ ಸೇವೆ ಸಾಗುತಲೇ ಇರಲಿ ..\nಇರುಳು ಮುಗಿಯದೆ ಇರಲಿ .. ಹಗಲು ಮೂಡದೇ ಇರಲಿ ..\nಭಕ್ತಿ ಅರಿತವನಲ್ಲ ಮುಕ್ತಿಯು ಬೇಕಿಲ್ಲ …\nಭಕ್ತಿ ಅರಿತವನಲ್ಲ ಮುಕ್ತಿಯು ಬೇಕಿಲ್ಲ …\nನಿನ್ನ ಕಾಣದೆ ಜೀವ ಕ್ಷಣಕಾಲ ನಿಲ್ಲದಯ್ಯ …\n\nಪವಡಿಸು ಪರಮಾತ್ಮ ಶ್ರೀ ವೆಂಕಟೇಶ\nಮನವೆಂಬ ಮಲ್ಲಿಗೆಯ ಹೂವ ಹಾಸಿಗೆ ಮೇಲೆ ..\nಪವಡಿಸು ಪರಮಾತ್ಮ ಶ್ರೀ ವೆಂಕಟೇಶ ಸಪ್ತಗಿರಿವಾಸ ….\nಶ್ರೀ ವೆಂಕಟೇಶ …. ಸಪ್ತ ಗಿರಿವಾಸ ….\n\n",english:"Aaaa.. aaaaaa.. aaaaa… aaa.. aa aa aaaaaa..\n\nPavadisu paramathma Shree Venkatesha\nManavemba malligeya hoova haasige mele..\n\nPavadisu paramathma Shree Venkatesha Sapthagirivaasa….\n\nRaamanige Kousalya laali haadida reeti\nAnasuye jogulava haadi nalida reeti…\nRaamanige Kousalya laali haadida reeti\nAnasuye jogulava haadi nalida reeti…\nNinna mahimeya paadi…… paada seveya maadi….\naa… aaa…. aaa…. aa… aaa… aaaaaa….\nNinna mahimeya paadi…… paada seveya maadi….\nDhanyanaaguvenindu karuniso ….dayamaadi..\n\nPavadisu paramathma Shree Venkatesha\nManavemba malligeya hoova haasige mele..\n\nPavadisu paramathma Shree Venkatesha Sapthagirivaasa….\n\nIrulu mugiyade Irali.. hagalu moodade Irali..\nanugaala ee seve saagutale irali..\nIrulu mugiyade Irali.. hagalu moodade Irali..\nBhakti aritavanalla muktiyu bekilla…\nBhakti aritavanalla muktiyu bekilla…\nninna kaaNade jeeva kshanakaala nilladayya…\n\nPavadisu paramathma Shree Venkatesha\nManavemba malligeya hoova haasige mele..\n\nPavadisu paramathma Shree Venkatesha Sapthagirivaasa….\nShree Venkatesha …. Saptha girivaasa….\n\n",meta:"",tags:["venkateshwara srinivasa","kannada devotional song"],media:""};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಪವಡಿಸು-ಪರಮಾತ್ಮ-ಶ್ರೀ.json",
	rawData: "",
};

export { _internal, collection, data, id };
