const id = "ಪವಮಾನ-ಜಗದ-ಪ್ರಾಣ";
const collection = "bhajan";
const data = {kannada_title:"ಪವಮಾನ ಜಗದ ಪ್ರಾಣ",english_title:" Pavamaana jagada praana",kannada:"ರಚನೆ : ವಿಜಯದಾಸರು\n\nಪವಮಾನ ಪವಮಾನ ಜಗದಾ ಪ್ರಾಣಾ\nಸಂಕರುಷಣ ಭವಭಯಾರಣ್ಯ ದಹನ |ಪ|\n\nಶ್ರವಣವೆ ಮೊದಲಾದ ನವವಿಧ ಭಕುತಿಯ\nತವಕದಿಂದಲಿ ಕೊಡು ಕವಿಗಳ ಪ್ರಿಯ ||\n\nಹೇಮ ಕಚ್ಚುಟ ಉಪವೀತ ಧರಿಪ ಮಾರುತ ಕಾಮಾದಿ ವರ್ಗ ರಹಿತ\nವ್ಯೋಮಾದಿ ಸರ್ವವ್ಯಾಪುತ ಸತತ ನಿರ್ಭೀತ ರಾಮಚಂದ್ರನ ನಿಜದೂತ\nಯಾಮ ಯಾಮಕೆ ನಿನ್ನಾರಾಧಿಪುದಕೆ ಕಾಮಿಪೆ ಎನಗಿದು ನೇಮಿಸಿ ಪ್ರತಿದಿನ\nಈ ಮನಸಿಗೆ ಸುಖಸ್ತೋಮವ ತೋರುತಪಾಮರ ಮತಿಯನು ನೀ ಮಾಣಿಪುದು |1|\n\nವಜ್ರ ಶರೀರ ಗಂಭೀರ ಮುಕುಟಧರ ದುರ್ಜನವನ ಕುಠಾರ\nನಿರ್ಜರ ಮಣಿದಯಾ ಪಾರ ವಾರ ಉದಾರ ಸಜ್ಜನರಘವ ಪರಿಹಾರ\nಅರ್ಜುನಗೊಲಿದಂದು ಧ್ವಜವಾನಿಸಿ ನಿಂದು ಮೂರ್ಜಗವರಿವಂತೆ ಗರ್ಜನೆ ಮಾಡಿದಿ\nಹೆಜ್ಜೆ ಹೆಜ್ಜೆಗೆ ನಿನ್ನ ಅಬ್ಜ ಪಾದದ ಧೂಳಿಮಾರ್ಜನದಲಿ ಭವ ವರ್ಜಿತನೆನಿಸೊ |2|\n\nಪ್ರಾಣ ಅಪಾನ ವ್ಯಾನೋದಾನ ಸಮಾನ ಆನಂದ ಭಾರತಿ ರಮಣ\nನೀನೆ ಶರ್ವಾದಿ ಗೀರ್ವಾಣಾದ್ಯಮರರಿಗೆ ಜ್ಞಾನಧನ ಪಾಲಿಪ ವರೇಣ್ಯ\nನಾನು ನಿರುತದಲಿ ಏನೇನೆಸಗಿದೆ ಮಾನಸಾದಿ ಕರ್ಮ ನಿನಗೊಪ್ಪಿಸಿದೆನೊ\nಪ್ರಾಣನಾಥ ಸಿರಿ\nವಿಜಯವಿಠಲ\nನ ಕಾಣಿಸಿ ಕೊಡುವದು ಭಾನು ಪ್ರಕಾಶ |3|\n\n",english:"Composer : Sri Vijaya dasaru\n\nPavamana Pavamana Pavamana Jagada Prana..aa..\nPavamana Jagada Prana Sankarushana\nBhava Bhayaaranya Dahana ||\n\nShravanave Modalaada Nava Vidha Bakuthiya\nThavakadindali Kodu Kavi Jana Priya ||\n\nHema Kacchuta Upaveetha Dharipa Maarutha Kaamadi Varga Rahitha\nVyomaadi Sarva Vyaaputha Sathatha Nirbeetha Rama Chandrana Nija Dhoota\nYaama Yamake Ninnaaradhipudake Kaamipe Enagidu Nemisi Prathi Dina\nEe Manasige Sukasthomava Thorutha Paamara Mathiyanu Nee Maanipudu\n\nVajra Shareera Gambheera Mukutadhara Durjana Vana Kutaara\nNirjara Mani Daya Paara Vaara Udara Sajjana Raga Parihaara\nArjunagolidandu Dhvajavanisi Nindu Moorjagavarivanthe Garjane Maadidi\nHejje Hejjege Ninabja Padadooli Maarjanadali Bhava Varjitha Neniso\n\nPraana apaana vyaanodaana samaana ananda bharati ramana\nneene sharvadi | geervanaadyamararige jnana dhana paalipa varenya\nnanu nirutadali enenesagidemanasadi karma ninagoppisideno\nprananatha siri\nvijayavitalan\na kaanisi koduvadu bhaanu prakasha |3|\n\n",meta:"",tags:["anjaneya hanuma","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=t1q7Opz5urg"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಪವಮಾನ-ಜಗದ-ಪ್ರಾಣ.json",
	rawData: "",
};

export { _internal, collection, data, id };
