const id = "ಪೂರ್ವಜನ್ಮದಲಿ-ನಾ-ಮಾಡಿದ";
const collection = "bhajan";
const data = {kannada_title:"ಪೂರ್ವಜನ್ಮದಲಿ ನಾ ಮಾಡಿದ",english_title:"Purva janmadali na",kannada:"ಪೂರ್ವ ಜನ್ಮದಲಿ ನಾ ಮಾಡಿದ ಪಾಪದಿಂ ದುರ್ವಿಯೊಳು ಜನಿಸಿದೆನು ಕೃಷ್ಣ ||2 times||\nಕಾರುಣ್ಯ ನಿಧಿ ಎನ್ನ ಕಾಯಬೇಕಯ್ಯ ಹರಿ ವಾರಿಜ ನಾಭ ಶ್ರೀ ಕೃಷ್ಣ||2 times||ಪೂರ್ವ ಜನ್ಮದಲಿ|\n\nಹುಟ್ಟಿದಂದಿಂದಿಗು ಸುಖವೆಂಬುದನು ಅರಿಯೆ ಕಷ್ಟ ಪಡುತಿಹೆನಯ್ಯ ಕೃಷ್ಣಾ |2 times||\nದಟ್ಟ ದಾರಿದ್ರ್ಯ ವನು ಪರಿಹರಿಸದಿರೆ ದೂರು ತಟ್ಟುವುದು ನಿನಗಯ್ಯ ಕೃಷ್ಣ||2 times||\n\nಕಾಸಿನ ಆಸೆಯನು ಮಾಡಿ ಬಹುದಿನದಿಂದ ಆಯಾಸದೊಳಗಿಹೆನು ಕೃಷ್ಣ|\nಆಸೆಯನು ಬಿಡಿಸೆಮಗೆ ದೋಷವನು ಪರಿಹರಿಸು ಸಾಸಿರ ನಾಮದ ಶ್ರೀ ಕೃಷ್ಣ ||2 times||ಪೂರ್ವ ಜನ್ಮದಲಿ||\n\nಮುಟ್ಟಲಂಜುವರು ಬಂದುಗಳು ಕಂಡರೆ ಎನ್ನ ಅಟ್ಟಿಕೊಳುತಿಹರಯ್ಯ ಕೃಷ್ಣ|| 2times||\nತೊಟ್ಟಿಲ ಶಿಶು ಬಾಯ ಬಿಡುವತೆರೆದಂತೆ ಕಂಗೆಟ್ಟು ಶೋಕಿಸುವೆನು ಕೃಷ್ಣ|| 2 times||\n\nಈ ಪರಿಯಿಂದ ನಾನಾಪಟ್ಟು ಪೇಳಿದರೆ ನಾಥನ್ನ ಕಾಯದಿದೆಕೋ ಕೃಷ್ಣ || 2 times||ಶಪಿಸುವೆನೆಂದರೆ ಸಾವು ಹುಟ್ಟು ನಿನಗಿಲ್ಲ ಏಸು ದೊರೆದನವಯ್ಯ ಕೃಷ್ಣ||2 times||\n\nತಂದೆ ತಾಯಿಯು ಇಲ್ಲ ಬಂಧು ಬಳಗವೂ ಇಲ್ಲ ಇಂದೆನಗೆ ಗತಿಯೇನು ಕೃಷ್ಣ|| 2times||\nಮಂದರಧರ ಶ್ರೀ ಪುರಂದರ ವಿಠ್ಠಲ ನೀ ಬಂದು ನೆಲೆಯಾಗಯ್ಯ ಕೃಷ್ಣ || 2 times||ಪೂರ್ವ ಜನ್ಮದಲಿ ||\n\nಪೂರ್ವ ಜನ್ಮದಲಿ ನಾ ಮಾಡಿದ ಪಾಪದಿಂ ದುರ್ವಿಯೊಳು ಜನಿಸಿದೆನು ಕೃಷ್ಣಕೃಷ್ಣಾ\nಕೃಷ್ಣಾ ಕೃಷ್ಣಾ ಕೃಷ್ಣಾ ಕೃಷ್ಣಾ\n\n",english:"Purva janmadali na madida aghadinda urviyolu janisideno krishna |karunya nidhiyenna kayabekayya hari varijanabha shri krishna||\n\nHuttidandindigu sukhavembudanu ariye kashtavsgirutihudu krishna|\ndatta daridaryavanu pariharisadire duru tattuvudu ninagayya krishna||\nKasina aseyanu madi bahu dinadinda ayasadolagirutiheno krishna|\nAseyanu bidisi mige doshavanu parihariso sasira nama shri krishna||\nMuttalanjuvaru bandhugalu kantare enna atti koludiharayya krishna|\ntottila shishu baya biduva teranante kangettu shokisuveno krishna||\n\nI pariyinda nanapattu pelidara nathanna kayadideko krishna|\nshapisuvenendare savu huttu ninagilla esu doredanavayya krishna|\nTande tayiyu illa bandhu balagavu illa indenu terahele krishna|\nmandaradhara shri purandara vittala ni bandu neleyagayya krishna ||\n\nYoutube link\n:\nhttps://youtu.be/PB5mKi7k_dk\n\n",meta:"",tags:["kannada devotional song","kannada lyrics"],media:""};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಪೂರ್ವಜನ್ಮದಲಿ-ನಾ-ಮಾಡಿದ.json",
	rawData: "",
};

export { _internal, collection, data, id };
