const id = "ಪೋಷಿಸು-ಎನ್ನಯ-ದೋಷಗಳೆಣಿಸದೆ-ದಾಸರಾಯ";
const collection = "bhajan";
const data = {kannada_title:"ಪೋಷಿಸು ಎನ್ನಯ ದೋಷಗಳೆಣಿಸದೆ ದಾಸರಾಯ",english_title:"poshishu yennanu doshagalenisade dasaraya",kannada:"ರಚನೆ : ಶ್ರೀ ಶ್ಯಾಮಸುಂದರ ದಾಸರು\n\nಪೋಷಿಸು ಎನ್ನಯ । ದೋಷಗಳೆಣಿಸದೆ ದಾಸರಾಯ ।\nಶೇಷ ನಾಮಕನೆ । ವಿಶೇಷ ಜ್ಞಾನವನೇಯೋ ದಾಸರಾಯ ।। ಪಲ್ಲವಿ ।।\n\nಸಂತತ ಕರಪಿಡಿ । ಸಂತರೊಡೆಯ ಗುರು ದಾಸರಾಯ ।\nಸಂತೋಷ ತೀರ್ಥರ । ಅಂತಃಕರುಣ ಪಾತ್ರ ದಾಸರಾಯ ।।\nಚಿಂತಿಪ ಜನರಿಗೆ । ಚಿಂತಾಮಣಿಯು ನೀನೆ ದಾಸರಾಯ ।\nಚಿಂತ ರಹಿತ ವರ । ಚಿಂತರವೇಲಿ ವಾಸ ದಾಸರಾಯ ।। ಚರಣ ।।\n\nಕುಂಭಿಣಿದೇವಕ । ದಂಬ ಸಂಸೇವಿತ ದಾಸರಾಯ ।\nಬೆಂಬಿಡದತಿ ಮನದ । ಹಂಬಲ ಪೂರೈಸು ದಾಸರಾಯ ।।\nನಂಬಿದ ದ್ವಿಜರಿಗೆ । ಶಂಭುಗಿರಿಯಲ್ಲಿ ದಾಸರಾಯ ।\nಬಾಂಬೋಳೆ ತೋರಿಸಿ । ಸಂಭ್ರಮಗೊಳಿಸಿದ ದಾಸರಾಯ ।। ಚರಣ ।।\n\nಹರಿಕೇತು ಹರಿಸುತ । ಹರಿಣಾಂಕ ಕುಲ ಜಾತ ದಾಸರಾಯ ।\nಹರಿಕೇತು ಹರುಸುತಾ । ದ್ಯರನ ಸಂಹರಿಸಿದ ದಾಸರಾಯ ।।\nಹರಿದಾಡುತಿಹ ಮನ । ಹರಿಯಲ್ಲಿ ನಿಲಿಸಯ್ಯ ದಾಸರಾಯ ।\nಹರಿವೈರಿಮತಕರಿ ಹರಿ । ಪರಿಹರಿಸಘ ದಾಸರಾಯ ।। ಚರಣ ।।\n\nಅರ್ಥ ಜನರ । ಇಷ್ಟಾರ್ಥವ ಜಗದೊಳು ದಾಸರಾಯ ।\nಪೂರ್ತಿಸುವ ನಿನ್ನ । ವಾರ್ತಿ ಕೇಳಿ ಬಂದೆ ದಾಸರಾಯ ।।\nಪಾರ್ಥಿವ ವರುಷದಿ । ಪಾರ್ಥಸಾರಥಿ ನಿನ್ನ ಭವ್ಯ ದಾಸರಾಯ ।\nಮೂರ್ತಿ ಸ್ಥಾಪಿಸಿ । ಕೀರ್ತಿಯ ಪಡೆದಿ ದಿವ್ಯ ದಾಸರಾಯ ।। ಚರಣ ।।\n\nನೇಮ ನಿಷ್ಠೆಯ ಬಿಟ್ಟು । ಪಾಮರನಾದೆನಗೆ ದಾಸರಾಯ ।\nಶ್ರೀಮಧ್ವ ನಿಗಮಾರ್ಥ । ಪ್ರೇಮದಿ ತಿಳಿಸಯ್ಯ ದಾಸರಾಯ ।।\nಕಾಮಾದಿಷಡ್ವೈರಿ । ಸ್ತೋಮಾದ್ರಿಕುಲಿಶನೆ ದಾಸರಾಯ ।\nಕಾಮಿತ ಫಲದಾತ ।\nಶ್ಯಾಮಸುಂದರ\nರ ದೂತ ದಾಸರಾಯ ।।\n\n",english:"Poshisu ennaya | doshagalenisade dasaraya |\nshesha namakane | vishesha jnanavaneyo dasaraya ||pa||\n\nSantata karapidi |santarodeya guru dasaraya |\nsanthosha teerthara | antahkaruna paatra dasaraya ||\nchintipa janarige | chintamaniyu neene dasaraya |\nchinta rahita vara chintaraveli vaasa dasaraya ||1||\n\nKumbhinidevaka | damba samsevita dasaraya |\nbembidadati ,manada | hambala pooraisu dasaraya ||\nnambida dwijarige | shambhugiriyalli dasaraya |\nbaambole torisi | sambhramagolisida dasaraya ||2||\n\nHariketu harisuta | harinaanka kula jaata dasaraya |\nhariketu harisuta | dyarana samharisida dasaraya ||\nharidadutiha mana | hariyalli nilisayya dasaraya |\nharivairimatakari hari | pariharisagha dasaraya ||3||\n\nArtha janara | ishtaarthava jagadolu dasaraya |\npoortisuva ninna | vaarti keli bande dasaraya ||\nparthiva varushadi | parthasarati ninna bhavya dasaraya |\nmurti stapisi | keertiya padeda divya dasaraya ||4||\n\nNema nishteya bittu | pamaranadenage dasaraya |\nsrimadhwa nigamartha | premadi tilisayya dasaraya ||\nkamadishadvairi | stomadrikulishane dasaraya |\nkamita phaladata |\nshyamasundara\nra doota dasaraya ||\n\n",meta:"",tags:["narayana","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=hCfhZ2VAqIs"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಪೋಷಿಸು-ಎನ್ನಯ-ದೋಷಗಳೆಣಿಸದೆ-ದಾಸರಾಯ.json",
	rawData: "",
};

export { _internal, collection, data, id };
