const id = "ಪಾಲಿಸೆ -ಪದುಮಾಲಯೇ -ನೀನೆ -ಗತಿ";
const collection = "bhajan";
const data = {kannada_title:"ಪಾಲಿಸೆ  ಪದುಮಾಲಯೇ  ನೀನೆ  ಗತಿ",english_title:"Palise padumalaye neene gati",kannada:"ಪಾಲಿಸೆ  ಪದುಮಾಲಯೇ  ನೀನೆ  ಗತಿ\n\nಪಾಲಕನು  ತಾನಾಗಿ  ಗೋಪಿಗೆ\nಲೀಲೆಯಿಂದಲಿ  ನಂದಗೋಕುಲ\nಬಾಲೆಯರ  ಮೋಹಿಸುತ  ಅಸುರರ\nಕಾಲನೆನಿಸಿದ  ಬಾಲಕನ  ಪ್ರಿಯೆ\n\nಅನ್ಯರ  ನೆನೆಯಲೊಲ್ಲೆ  – ನಿನ್ನಯಪಾದ\nವನ್ನು  ನಂಬಿದೆ  ನೀಬಲ್ಲೆ  – ತಡಮಾಡದಲೆ\nಚಿನ್ನ  ಕರೆಯಲು  ಘನ್ನ  ಮಹಿಮನು\nಉನ್ನತದ  ರೂಪಿನಲಿ  ಗುಣ  ಸಂಪನ್ನ\nರಕ್ಕಸರನ್ನು  ಸೀಳಿದ\nಪನ್ನಗಾದ್ರಿ  ನಿವಾಸ  ಹರಿಪ್ರಿಯೇ               (ಪಾಲಿಸೆ )\n\nಅರಿಯದ  ತರಳನೆಂದು  – ಶ್ರಿಪತಿಸತಿ\nಕರುಣದಿ  ಸಲಹೆ ಬಂದು  – ಕರುಣಾಸಿಂಧು\nಸರಸಿಜಾಸನ  ರುದ್ರರೀರ್ವರ\nಬರದಿ  ಮೂರ್ಖನು ಸುರರ ಬಾಧಿಸೆ\nಅರಿವರರ  ದಂಡೆತ್ತಿ  ಬಹುಮುಖ\nದುರುಳನಾಶಿರ ತರಿದ  ವನಪ್ರಿಯೇ          (ಪಾಲಿಸೆ )\n\nಅಜಮನಸಿಜ  ಜನನಿ  – ಅಂಬುಜಪಾಣಿ\nಭುಜಗ  ಸನ್ನಿಪ ವೇಣಿ – ನಿತ್ಯ  ಕಲ್ಯಾಣಿ\nಕುಜನ  ಮರ್ಧನ\nವಿಜಯವಿಠಲ\nನ\nಭಜಿಸಿ  ಪಾಡುವ  ಭಕ್ತ  ಕೂಟವ\nನಿಜದಿ  ಸಲಹುವೆ-ನೆಂಬ  ಬಿರುದುಳ್ಳ\nವಿಜಯ  ಸಾರಥಿ  ವಿಶ್ವಂಬರ  ಪ್ರಿಯೆ  (ಪಾಲಿಸೆ)\n\n",english:"Palise padumalaye neene gathi ||\n\nPalakanu thanagi gopige\nleele indhali nandha gokula\nbalayera mohisade asurara\nkalanenisida balakana priye ||\n\nAnyara neneyalolle ninnaya padavannu\nnambhide niballe thade madadhale\nchinna kareyalu ganna mahimanu unnatha\nruppinali guna sampanna rakkasaranna\nseelida pannagadri nivasa haripriye |palise|\n\nAriyadha tharalanendhu – shripathisathi\nkarunadi salahe  bandhu – karunasindhu\nsarasijasana rudrarirvara baradi murkhanu\nsurara badise | arivarara dandetthi bahuvida\ndurulana shira tharidu vanapriye  ||palise||\n\nAjamanasija janani – ambujapani\nbhujaga sannipa -veni, nithya kalyani\nkujana mardhana\nvijayavittala\nna\nbhajisi paduva bhaktha kutava\nnijadi salahuva – nemba birudulla vijaya sarathi vishvambara priye       ||palise||\n\n………………………………………………………………………………………………………………………….\n\nYoutube link :\nhttps://youtu.be/3_WHdtjJtrU\nby Sri Vidyabhushana Theertha Swamiji\n\n",meta:"",tags:["lakshmi","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=3_WHdtjJtrU"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಪಾಲಿಸೆ -ಪದುಮಾಲಯೇ -ನೀನೆ -ಗತಿ.json",
	rawData: "",
};

export { _internal, collection, data, id };
