const id = "ಬಾರೆ-ಸಖಿ-ಪೋಗುವ-ರಾಸ";
const collection = "bhajan";
const data = {kannada_title:"ಬಾರೆ ಸಖಿ ಪೋಗುವ ರಾಸ",english_title:" Baare sakhi poguva raasa",kannada:"ಬಾರೆ ಸಖಿ ಪೋಗುವ ರಾಸ ಕ್ರೀಡೆಯಾಡುವ\nಸಾರಸಾಕ್ಷ ಕೃಷ್ಣನು ತಾ ಕೊಳಲನೂದುವ |\nಕೊಳಲನೂದುವಾ ಕೃಷ್ಣ ಕೊಳಲನೂದುವ ||\n\nಜಾರನೆಂದು ಸಣ್ಣಮಾತನಾಡಿದ್ದಾಯಿತು ಚೋರನೆಂದು ಬಹಳ ದೂರು\nಮಾಡಿದ್ದಾಯಿತು | ಮೂರು ನಿಮಿಷ ಅವನ ಮರೆಯಲಾಗದಾಯಿತು |\nಬೀರುತಿರುವ ಮೋಹಜಾಲ ಸಡಲದಾಯಿತು ||\n||ಬಾರೆ ಸಖಿ||\n\nಯಾವನೀತನೆಂದು ಚಿಂತೆ ಮಾಡಿದ್ದಾಯಿತು ಗೋವಳನಿವನಲ್ಲವೆಂದು ನಿರ್ಧರಾಯಿತು |\nಯಾವನಾದರೇನು ಇವನ ಕ್ಷಣವು ಕಾಣದೆ | ಜೀವನ ಕಳೆಯುವುದೆ ದೊಡ್ಡ ಭಾರವಾಯಿತು ||\n||ಬಾರೆ ಸಖಿ||\n\nಮಂದಹಾಸದಿಂದ ಸಕಲ ಜಗವ ಬೆಳಗುವ ಚಂದ್ರನು ತಾನಿವನ ನೋಡಿ\nಬಹಳ ನಾಚುವ | ಸಾಂದ್ರವಾಯಿತಂತರಿಕ್ಷ ಮಧುರ ನಾದದಿ |\nಮಲಯ ಮಾರುತ ತಾ ತಲೆಯನಾಡುವ ||\n||ಬಾರೆ ಸಖಿ||\n\nನಾದದ ಸುಧೆ ಸಾಗರದಲಿ ತೇಲುವಂತಿದೆ ಮಾಧವ ತಾ ಸುಧೆಯ ರಸವನೆರಚುವಂತಿದೆ |\nಬಾಧಿಸುತಿಹ ಭವದ ತಾಪವಡಗಿದಂತಿದೆ | ಮಾದರಿಫಲ ರಾಸಕ್ರೀಡೆ ತೋರುವಂತಿದೆ ||\n|| ಬಾರೆ ಸಖಿ||\n\nಸಕಲ ಲೋಕನಾಥನೀತನೆಂದು ತಿಳಿಯಿತು. ಸಕಲವನರ್ಪಿಸುವುದೊಂದೆ\nಮಾರ್ಗ ಉಳಿಯಿತು | ಲಕುಮಿ ಮುರುಳಿ ರೂಪದಲ್ಲಿ\nಇಹುದು ಹೊಳೆಯಿತು | ಭಕುತಿ ಹರಿದು ಎನ್ನ ಮನ ಪ್ರಸನ್ನವಾಯಿತು ||\n‌ ||ಬಾರೆ ಸಖಿ||\n\n",english:"Baare sakhi poguva raasa kreedeyaduva | sarasaksha krishnanu taa kolalanooduva | kolalanooduva krishna kolalanooduva ||\n\nJaaranendu sanna matanaadiddaayitu, choranendu bahala dooru maadiddayitu | mooru nimisha avana mareyalaagadayitu | beerutiruva mohajaala sadaladaayitu || baare sakhi ||\n\nYaavaneetanendu chinte maadiddayitu, govalanivanallavendu nirdhaarayitu | yaavanadarenu evana kshanavu kaanade | jeevana kaleyuvude dodda bharavaayitu || baare sakhi ||\n\nMandahasadinda sakala jagava belaguva chandranu tanivana nodi | bahala nachuva | saandravayitantariksha madhura naadadi | malaya maruta taa taleyanaduva || baare sakhi ||\n\nNaadada sudhe sagaradali teluvantide, madhava taa sudheya rasavanerachuvantide | madariphala rasakreede toruvantide || baare sakhi ||\n\nSakala lokanathaneetanendu tiliyitu, sakalavanarpisuvudonde marga uliyitu |lakumi murali roopadalli ehudu holeyitu | bhakuti haridu enna mana prasanna vayitu || baare sakhi ||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=hbIVaZOw5a8"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಬಾರೆ-ಸಖಿ-ಪೋಗುವ-ರಾಸ.json",
	rawData: "",
};

export { _internal, collection, data, id };
