const id = "ಬಾರೋ-ಮನೆಗೆ-ಗೋವಿಂದ";
const collection = "bhajan";
const data = {kannada_title:"ಬಾರೋ ಮನೆಗೆ ಗೋವಿಂದ",english_title:" Baaro manege govinda",kannada:"ಬಾರೋ ಮನೆಗೆ ಗೋವಿಂದ -ನಿನ್ನಂಘ್ರಿಕಮಲವ\nತೋರೋ ಎನಗೆ ಮುಕುಂದ ನಲಿದಾಡು ಮನದಲಿ\nಮಾರಪಿತ ಆನಂದನಂದನ್ನ ಕಂದ ||ಪ||\n\nಚಾರುತರ ಶರೀರ ಕರುಣಾ-\nವಾರಿನಿಧಿ ಭವ ಘೋರನಾಶನ\nವಾರಿಜಾಸನ ವಂದ್ಯ ನಿರಜ\nಸಾರ ಸದ್ಗುಣ ಹೇ ರಮಾಪತೆ ||ಅ.ಪ||\n\nನೋಡೋ ದಯದಿಂದೆನ್ನ, ಕರಪದುಮ ಶಿರದಲಿ\nನೀಡೋ ಭಕ್ತಪ್ರಸನ್ನ , ನಲಿದಾಡೊ ಮನದಲಿ\nಬೇಡಿಕೊಂಬೆನೊ ನಿನ್ನ , ಆನಂದ ಘನ್ನ\nಮಾಡದಿರು ಅನುಮಾನವ , ಕೊಂ-\nಡಾಡುವೆನು ತವ ಪಾದಮಹಿಮೆಗಳನು\nಜೋಡಿಸುವೆ ಕರಗಳನು ಚರಣಕೆ\nಕೂಡಿಸೊ ತವ ದಾಸಜನರೊಳು ||೧||\n\nಹೇಸಿ ವಿಷಯಗಳಲ್ಲಿ ತೊಳಲಾಡಿ ನಾ ಬಲು\nಕ್ಲೇಶ ಪಡುವುದು ಬಲ್ಲಿ, ಘನ ಯುವತಿಯರ ಸುಖ\nಲೇಸು ಎಂಬುದನು ಕೊಲ್ಲಿ , ಆಸೆ ಬಿಡಿಸಿಲ್ಲಿ\nಏಸು ಜನುಮದ ದೋಷದಿಂದಲಿ\nಈಸುವೆನು ಇದರೊಳಗೆ, ಇಂದಿಗೆ\nಮೋಸವಾಯಿತು ಆದುದಾಗಲಿ\nಶ್ರೀಶ ನೀ ಕೈಪಿಡಿದು ರಕ್ಷಿಸು ||೨||\n\nನೀನೆ ಗತಿಯೆನಗಿಂದು ಉದ್ಧರಿಸೊ ಬ್ಯಾಗನೆ\nದೀನ ಜನರಿಗೆ ಬಂಧು ನಾ ನಿನ್ನ ಸೇವಕ\nಶ್ರೀನಿವಾಸ ಎಂದೆಂದು ಕಾರುಣ್ಯ ಸಿಂಧು\nಪ್ರಾಣಪತಿ ಹೃದಯಾಬ್ಜ ಮಂಟಪ –\nಸ್ಥಾನದೊಳಗಭಿವ್ಯಾಪ್ತ ಚಿನುಮಯ\nಧ್ಯಾನಗೋಚರನಾಗಿ ಕಣ್ಣಿಗೆ\nಕಾಣಿಸುವೆ ಶ್ರೀರಂಗವಿಠಲ ||೩||\n\n",english:"Baaro manege govinda | ninnanghri kamalava toro enage mukunda |\nnalidaado manadali maarapita aananda | aananda kanda || pa ||\n\nChaarutara shaareera karunaa vaarinidhi bhava ghora naashana |\nvaarijaasana vandya nirjara saara sadguna he ramaapate || a. Pa. ||\n\nNodo dayadinda enna karapaduma shiradali needu bhakta prasanna |\nnalidaadu manadali bedikombuvenu ninna aananda ghanna ||\nmaadadiru anumaanavanu kondaaduvenu tava mahimegalanu |\njodisuve karagalanu charanake | koodi sotava daasa janarolu || 1 ||\n\nHesi vishayagalalli | tolalaadi naa balu | kleshapaduvadu balli |\ndhana yuvatigala sukha leshavembuvadu kolli | aase bidisilli ||\nEsu janmada doshadindali eesuvenu idarolage indige | mosavaayitu aadudaagali |\nshreesha nee kaipididu rakshisu || 2 ||\n\nNeene gatiyo enagindu | uddhariso devane, deena janarige bandhu |\nnaa ninna sevaka shreenivaasaa endendu kaarunyasindhu ||\npraanapati hrudayaabja mantapa | sthaanadolagabhi vyaapta cinumaya |\ndhyaana gocaranaagu kannili | kaanuvenu shreerangaviththala || 3 ||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=hVpaFZ63ZSc"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಬಾರೋ-ಮನೆಗೆ-ಗೋವಿಂದ.json",
	rawData: "",
};

export { _internal, collection, data, id };
