const id = "ಬಾಗಿಲ-ತೆರೆದಿರುವೆ";
const collection = "bhajan";
const data = {kannada_title:"ಬಾಗಿಲ ತೆರೆದಿರುವೆ",english_title:" Baagila Terediruve",kannada:"ಬಾಗಿಲ ತೆರೆದಿರುವೆ ತಾಯೇ ಪೂಜೆಗೆ ಕಾದಿರುವೆ\nಸೇವೆಯ  ಸ್ವೀಕರಿಸು ಬಾ.ಽ… ಭಾಗ್ಯಲಕ್ಷ್ಮಿಯೇ..\nಬಾಗಿಲ ತೆರೆದಿರುವೆ ತಾಯೇ ಪೂಜೆಗೆ ಕಾದಿರುವೆ…\n\nಹೊಸಲಿನ ಪೂಜೆ ಮಾಡಿದೆಯಮ್ಮ..\nಹಸಿರು ತೋರಣ.ಽ.. ಕಟ್ಟಿದೆಯಮ್ಮ..\nತುಪ್ಪದ ದೀಪ ಬೆಳಗಿದೆಯಮ್ಮ\nಮಲ್ಲಿಗೆ ಮಾಲೆ ಕಾದಿದೆಯಮ್ಮ\nಕಮಲಾಕ್ಷಿ ಕಮಲಮುಖಿ ಕಮಲೋದ್ಭವೇ ಬಾರೆ..\n\nಬಾಗಿಲ ತೆರೆದಿರುವೆ ತಾಯೇ ಪೂಜೆಗೆ ಕಾದಿರುವೆ..\n\nನೀನು ಬರುವಾಗ ಹೊನ್ನಕಾಲ್ಗೆಜ್ಜೆ ನಾದ ನಾ ಕೇಳುವಂತೆ..\nನಿನ್ನ ನಗೆಯಿಂದ ನನ್ನ ಭಯವೆಲ್ಲಾ ಓಡಿ ಮರೆಯಾಗುವಂತೆ..\nಮನೆಯು ಬೆಳಕಾಗಿ, ಮನವು ಬೆಳಕಾಗಿ, ಬಾಳು ಬೆಳಕಾಗುವಂತೆ..\nದಯಮಾಡಿಸು…. ನಾರಾಯಣನ ಹೃದಯೇಶ್ವರಿಯೇ..\n\nಬಾಗಿಲ ತೆರೆದಿರುವೆ ತಾಯೇ ಪೂಜೆಗೆ ಕಾದಿರುವೆ..\n\nನಿನ್ನ ಮನೆಯಿಂದ ನಿನ್ನ ಗುಡಿಯಿಂದ ಬಂದು ಸ್ಥಿರವಾಗಿ ನೆಲೆಸು.\nಬಂದ ಕ್ಷಣದಿಂದ ತಂದ ಸುಖ-ಶಾಂತಿ ನಮ್ಮ ಬದುಕಲ್ಲಿ ಬೆರೆಸು..\nನಿತ್ಯ ಹರಿಪೂಜೆ ನಿತ್ಯ ಗುರುಸೇವೆ ಇಲ್ಲಿ ನಡೆವಂತೆ ಹರಸು..\nದಯೆ ತೋರಿಸು ಶರಣೆನ್ನುವೆ ಸೌಭಾಗ್ಯದ ನಿಧಿಯೇ..\n\nಬಾಗಿಲ ತೆರೆದಿರುವೆ ತಾಯೇ ಪೂಜೆಗೆ ಕಾದಿರುವೆ..\n\n",english:"Baagila terediruve taaye poojege kaadiruve||2||\nSeveya swikarisu baa bhagya lakshmiye||2||\nBaagila terediruve taaye poojege kaadiruve.\n\nHosalina pooje madideyamma |\nhasiru torana kattideyamma  |\ntuppada deepa belagideyamma |\nmallige maale kadideyamma |\nkamalakshi kamalamukhi kamalodbhavi baare ||\n\nBaagila Terediruve Taaye Poojege Kaadiruve.\n\nNinu baruvaga honna kaalgejje nada na keluvante|\nninna nadeyinda nanna bhayavella odi mareyaguvante|\nmaneyu belakagi manavu belakagi baalu belakaguvante|\ndayamadisu narayanana hrudeshwariye |\n\nBaagila Terediruve Taaye Poojege Kaadiruve.\n\nninna maneyandu ninna gudiyandu bandu stiravagi nelesu |\nbanda kshnadinda tanda sukha shanti namma badukalli beresu |\nnitya haripooje  nitya guru seve elli nadevante namma harasu ||\ndaye torisu sharannenuve soubhagyada nidhiye …\n\nbaagila terediruve taaye poojege kaadiruve||2||\nSeveya swikarisu baa bhagya lakshmiye||2||\n\nWatch The Song Here\n\n",meta:"",tags:[],media:"https://www.youtube.com/watch?v=rvE702G45rM"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಬಾಗಿಲ-ತೆರೆದಿರುವೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
