const id = "ಭಗವಾನ್-ಶರಣಂ-ಭಗವತಿ-ಶರಣಂ";
const collection = "bhajan";
const data = {kannada_title:"ಭಗವಾನ್ ಶರಣಂ ಭಗವತಿ ಶರಣಂ",english_title:"Bhagavan sharanam bhagavati",kannada:"ಭಗವಾನ್ ಶರಣಂ ಭಗವತಿ ಶರಣಂ\nಶರಣಂ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ….\nಭಗವತಿ ಶರಣಂ ಶಾಸ್ತ ಶರಣಂ\nಶರಣಂ ಶರಣಂ ನನ್ನಯ್ಯಪ್ಪಾ…\n\nಭಗವಾನ್ ಶರಣಂ ಭಗವತಿ ಶರಣಂ\nಭಗವಾನೇ ಭಗವತಿಯೇ\nದೇವಾ ಶರಣಂ ದೇವಿ ಶರಣಂ\nದೇವನೇ ದೇವಿಯೇ\n\nಭಗವಾನ್ ಶರಣಂ ಭಗವತಿ ಶರಣಂ\nಶರಣಂ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ||ಭಗವಾನ್||\nಭಗವತಿ ಶರಣಂ ಭಗವಾನ್ ಶರಣಂ\nಶರಣಂ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ||ಭಗವತಿ||\n\nಶಬರಿಯ ಗಿರಿಯ ಆಲಯ ನಿಲಯ\nಶರಣಂ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ\nಹಗಲು ಇರುಳು ಶ್ರೀ ನಾಮವ\nಸ್ಮರಿಸುವೆ ಸ್ವಾಮಿ ಅಯ್ಯಪ್ಪಾ\n\nಕರಿಮಲೆ ವಾಸ ಭಕ್ತ ಸಂಪೋಷ\nಶರಣಂ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ||ಕರಿಮಲೆ||\nಕಲಿಭಯ ಹರಣ ಕರುಣಾಭರಣ\nಶರಣಂ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ\n\nಮಹಿಷಿ ಸಂಹಾರ, ಮದಗಜ ವಾಹನ\nಶರಣಂ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ\nಪಾಪ ವಿನಾಸ ಪರಿಮಳ ಪ್ರೀತ\nಶರಣಂ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ…\n\nಆರು ವಾರಗಳ ವ್ರತ ಗೈದು\nಪಾದ ಯಾತ್ರೆಯ ಗೈಯುತ ಬಂದೇ…\nಅಯ್ಯಪ್ಪಾ…. ಅಯ್ಯಪ್ಪ ಅಯ್ಯಪ್ಪ ||ಆರು||\nಹಾಲಭಿಷೇಕ ನಿನಗಪ್ಪ\nನಿನ್ನ ದರುಶನ ಭಾಗ್ಯವ ನೀಡಪ್ಪ\n\nಇರುಮುಡಿ ತೆಂಗು ನಿನಗಪ್ಪ\nನಿನ್ನಯ ಒಲುಮೆ ನಮಗಪ್ಪ\nಕರ್ಪೂರ ದೀಪ ನಿನಗಪ್ಪ\nನಿನ್ನ ಕಮಲದ ಚರಣ ನಮಗಪ್ಪ\nತುಪ್ಪದಭಿಷೇಕ ನಿನಗಪ್ಪ\nದಿವ್ಯ ದರುಶನ ನಮಗಪ್ಪ\nಗಿರಿಯನು ಹತ್ತುವೆ ಅಯ್ಯಪ್ಪ\nನೀ ಪಾದ ಭಲವನು ನೀಡಪ್ಪ\n\nದೇವನ ಪಾದ ದೇವಿ ಪಾದ\nಶರಣಂ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ\nಶರಣಂ ಘೋಷವು ನಿನಗಪ್ಪ\nನಿತ್ಯ ಮಂಗಳ ಅಯ್ಯಪ್ಪಾ\n\nಭಗವಾನ್ ಶರಣಂ ಭಗವತಿ ಶರಣಂ\nಭಗವಾನೇ…. ಭಗವತಿಯೇ….\nದೇವಾ ಶರಣಂ ದೇವಿ ಶರಣಂ\nದೇವನೇ ದೇವಿಯೇ\n\nಭಗವಾನ್ ಶರಣಂ ಭಗವತಿ ಶರಣಂ\nಶರಣಂ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ\nಭಗವತಿ ಶರಣಂ ಭಗವಾನ್ ಶರಣಂ\nಶರಣಂ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ\n\nಶರಣಂ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ\nಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪಾ………\n\n",english:"Bhagavan sharanam bhagavati sharanam sharanam sharanam ayyappa | bhagavati sharanam shaasta sharanam | sharanam sharanam ayyappa ||\n\nBhagavan sharanam bhagavati sharanam bhagavaane bhagavatiye | devaa sharanam devi sharanam | devane deviye ||\n\nBhagavan sharanam bhagavati sharanam sharanam sharanam ayyappa | bhagavati sharanam shaasta sharanam | sharanam sharanam ayyappa ||\n\nShabariya giriya alaya nilaya | sharanam sharanam ayyappa | hagalu irulu sri naamava| smarisuve swami ayyappa ||\n\nKarimale vasa bhakta samposha | sharanam sharanam ayyappa ||karimale|| kalibhaya harana karunaabharana |sharanam sharanam ayyappa||\n\nMahishi samhaara, madagaja vaahana | | sharanam sharanam ayyappa | paapa vinaasha parimala preeta | sharanam sharanam ayyappa ||\n\nAru vaaragala vrutagaidu | paada yaatreya gaiyuta bande …. Ayyappaa …. Ayyappa ayyappa ||aru|| haalabhisheka ninagappa ninna darushana bhaagyava needappa ||\n\nIrumudi tengu ninagappa | ninnaya olume namagappa | karpura deepa ninagappa| ninna kamalada charana namagappa | tuppadabhisheka ninagappa |divya darushana namagappa |giriyanu hattuve ayyappa| nee paada  bhalavanu needappa ||\n\nDevana paada devi paada || sharanam sharanam ayyappa |sharanam ghoshavu ninagappa | nitya mangala ayyappa ||\n\nBhagavan sharanam bhagavati sharanam bhagavaane bhagavatiye | devaa sharanam devi sharanam | devane deviye ||\n\nBhagavan sharanam bhagavati sharanam sharanam sharanam ayyappa | bhagavati sharanam shaasta sharanam | sharanam sharanam ayyappa ||\n\nSharanam sharanam ayyappa | swami sharanam ayyappaa ……\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=1ZXsYSh7a_A"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಭಗವಾನ್-ಶರಣಂ-ಭಗವತಿ-ಶರಣಂ.json",
	rawData: "",
};

export { _internal, collection, data, id };
