const id = "ಭಾಗ್ಯದ-ಲಕ್ಷ್ಮಿ-ಬಾರಮ್ಮ";
const collection = "bhajan";
const data = {kannada_title:"ಭಾಗ್ಯದ ಲಕ್ಷ್ಮಿ ಬಾರಮ್ಮ",english_title:" Bhagyada laxmi baramma",kannada:"ರಚನೆ: ಶ್ರೀ ಪುರಂದರದಾಸರು\n\nಭಾಗ್ಯದ ಲಕ್ಷ್ಮೀ ಬಾರಮ್ಮ ನಮ್ಮಮ್ಮ ನೀ |\nಸೌಭಾಗ್ಯದ ಲಕ್ಷ್ಮೀ ಬಾರಮ್ಮ || ಪ ||\n\nಹೆಜ್ಜೆಯ ಮೇಲೆ ಹೆಜ್ಜೆಯನಿಕ್ಕುತ\nಗೆಜ್ಜೆ ಕಾಲ್ಗಳ ಧ್ವನಿಯ ತೋರುತ |\nಸಜ್ಜನ ಸಾಧು ಪೂಜೆಯ ವೇಳೆಗೆ\nಮಜ್ಜಿಗೆಯೊಳಗಿನ ಬೆಣ್ಣೆಯಂತೆ || ೧ ||\n\nಕನಕವೃಷ್ಟಿಯ ಕರೆಯುತ ಬಾರೆ\nಮನಕೆ ಮಾನವ ಸಿದ್ಧಿಯ ತೋರೆ |\nದಿನಕರ ಕೋಟಿ ತೇಜದಿ ಹೊಳೆಯುವ\nಜನಕರಾಯನ ಕುಮಾರಿ ಬೇಗ || ೨ ||\n\nಅತ್ತಿತ್ತಲಗದೆ ಭಕ್ತರ ಮನೆಯಲಿ\nನಿತ್ಯ ಮಹೋತ್ಸವ ನಿತ್ಯ ಸುಮಂಗಲಿ |\nಸತ್ಯವ ತೋರುವ ಸಾಧು ಸಜ್ಜನರ\nಚಿತ್ತದಿ ಹೊಳೆಯುವ ಪುತ್ಥಳಿ ಬೊಂಬೆ || ೩ ||\n\nಸಂಖ್ಯೆಯಿಲ್ಲದ ಭಾಗ್ಯವ ಕೊಟ್ಟು\nಕಂಕಣ ಕೈಯ ತಿರುವುತ ಬಾರೆ |\nಕುಂಕುಮಾಂಕಿತ ಪಂಕಜಲೋಚನೆ\nವೆಂಕಟರಮಣನ ಬಿಂಕದ ರಾಣಿ || ೪ ||\n\nಸಕ್ಕರೆ ತುಪ್ಪದ ಕಾಲುವೆ ಹರಿಸಿ\nಶುಕ್ರವಾರದ ಪೂಜೆಯ ವೇಳೆಗೆ |\nಅಕ್ಕರೆವುಳ್ಳ ಅಳಗಿರಿ ರಂಗನ\nಚೊಕ್ಕ\nಪುರಂದರ ವಿಠ್ಠಲ\nನ ರಾಣಿ || ೫ ||\n\n",english:"Bhagyada lakshmi baramma nammamma nee sau\nbhagyada lakshmi baramma\n\nhejjaya mele hejjeyanikkuta\ngejje kalgala dhvaniya madutha\nsajjana sadhu pujeya velege\nmajjigeyolagina bennee yante\n\nBhagyada lakshmi baramma nammamma nee sau\nbhagyada lakshmi baramma\n\nKanaka vrushtiya kareyuta bare\nmana kamanaya siddhiya thore\ndinakara koti tejadi holeva\njanakarayana kumari bega\n\nBhagyada lakshmi baramma nammamma nee sau\nbhagyada lakshmi baramma\n\nattittagalade bhaktara maneyali\nnitya mahotsava nitya sumangala\nsatyava toruva saadhu sajjanara\nchittadi holeva puttali bombe\n\nBhagyada lakshmi baramma nammamma nee sau\nbhagyada lakshmi baramma\n\nsankhye illada bhagyava kottu\nkankana kayya tiruvuta bare\nkunkumankithe pankaja lochane\nvenkataramanana binkada rani\n\nBhagyada lakshmi baramma nammamma nee sau\nbhagyada lakshmi baramma\n\nsakkare tuppada kaluve harisi\nshukravaradha pujaya velage\nakkareyulla alagiri rangana\nchokka purandara vithalana rani\n\nBhagyada lakshmi baramma nammamma nee sau\nbhagyada lakshmi baramma\n\n",meta:"",tags:["lakshmi","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=_tdYY6lUw9g"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಭಾಗ್ಯದ-ಲಕ್ಷ್ಮಿ-ಬಾರಮ್ಮ.json",
	rawData: "",
};

export { _internal, collection, data, id };
