const id = "ಭಳೀರೆ-ಭಳೀರೆ-ನರಸಿಂಹ";
const collection = "bhajan";
const data = {kannada_title:"ಭಳೀರೆ ಭಳೀರೆ ನರಸಿಂಹ",english_title:" Bhalire bhalire narasimha mahasimha",kannada:"ಭಳೀರೆ ಭಳೀರೆ ನರಸಿಂಹ ಮಹಾಸಿಂಹ ಮಲ ಮಲ ಮಲೆತವರ\nವೈರಿ ಉರಿ ಮಾರಿ | ಭಳೀರೆ ಭಳೀರೆ ನರಸಿಂಹ. …  ||2||\n\nನಗ ನಗ ನಗಗಳೆಲ್ಲಾಡೆ ಚತುರ್ದಶ ಜಗ ಜಗ ಜಗವೆಲ್ಲ ಕಂಪಿಸಿ ಕಂಬಾಗೆ |\nಹಗೆ ಹೊಗೆ ಹಗೆಬಲವ ದೆಶೆ ಕೆಡಿಸಿ ರೋಷಕಿಡಿ |\nಉಗು ಉಗು ಉಗುಳುತ್ತ ಬಂದ ನರಸಿಂಹ | ಬಂದ ನರಸಿಂಹ. …. ||ಭಳೀರೆ||\n\nಬಿಗಿ ಬಿಗಿ ಬಿಗಿ ಬಿಗಿದು ಉಬ್ಬುಗಂಟನೆ ಹಾಕಿ ಹೊಗೆ ಹೊಗೆ , ಹೊಗೆಸುತ್ತ ಸರ್ವರಂಜೆ |‌\nನೆಗೆ ನೆಗೆ  ನೆಗೆ ನೆಗೆದು ಕುಪ್ಪಳಿಸೆ ಅಸುರನ್ನ | ಮಗು ಮಗು ಮಗು ಬೇಡಿಕೊಂಡ ನರಸಿಂಹ |\nನನರಸಿಂಹಾ….. ||ಭಳೀರೆ||\n\nಉಗು ಉಗು , ಉಗುರಿಂದ ಕ್ರೂರನ ಹೇರೊಡಲ ಬಗೆ ಬಗೆ, ಬಗೆ ಬಗೆದು ರಕುತವನ್ನು |\nಉಗಿ ಉಗಿ ಉಗಿ ಉಗಿದು ಚೆಲ್ಲಿ ಕೊರಳಿಗೆ ಕರುಳ | ತೆಗೆ ತೆಗೆ, ತೆಗೆ ತೆಗೆದು ಇಟ್ಟ ನರಸಿಂಹ |\nಇಟ್ಟ ನರಸಿಂಹಾ….. ||ಭಳೀರೆ||\n\nಜಗ ಜಗ, ಜಗದೊಳಗೆ ಪ್ರಣತಾರ್ಥಿಹರನೆಂದು ಝಗ ಝಗ ,ಝಗ ಝಗಿಪ ಮುಕುಟ ತೂಗೆ ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌ನಗು ನಗು ನಗು ನಗುತ\nಸುರರು ಗಗನದಿ ಮೆರೆದು | ಮಿಗಿ ಮಿಗಿ, ಮಿಗಿ ಮಿಗಿಲೆನೆ ನರಸಿಂಹ | ನರಸಿಂಹ. ||ಭಳೀರೆ||\n\nಒಂದು ಒಂದು, ಒಂದೊಂದು ಒಂದೊಂದು ಮುನಿಗಳಿಗೆ ಅಂದಂದ್ ಅಂದಂದಿಗೆ ಆಯ ತಾ ಒಲಿದು ‌‌‌‌‌‌‌ ‌‌‌‌‌|\nಅಂದಂದ ಅಂದವರ ಕಾವ ಚೋಳಂಗಿರಿ ಮಂದಿರನೆ ವಿಜಯ ವಿಠ್ಠಲ ನರಸಿಂಹ |\nನರಸಿಂಹಾ…. ||ಭಳೀರೆ||\n\n",english:"Bhalire bhalire narasimha nahasimha | mala mala maletavara vairi uri maari | bhalire bhalire narasimha ||2||\n\nNaga naga nagagalellaade chaturdash jaga jaga jagavella kampisi kambaage | hage hoge hagebalava deshe kedisi roshakidi | ugu ugu ugulutta banda narasimha | banda narasimha ……. ||bhalire ||\n\nBigi bigi bigi bigidu ubbugantane haaki hoge hoge hogesutta sarvaranje | nege nege nnege negedu kuppalise asuranna | magu magu magu bedikonda narasimha …… ||bhalire||\n\nUgu ugu ugurinda kroorana herodala bage bage bage bagedu rakutavannu | ugi ugi ugi ugidu chelli koralige karula | tege tege tege tegedu itta narasimha | itta narasimha …… || bhalire ||\n\nJaga jaga jagadolage pranataarthiharanendu jaga jaga jaga jagipa mukuta tooge nagu nagu nagu naguta suraru gaganadi meredu | migi migi migi migilene narasimha | narasimha || bhalire ||\n\nOndu ondu ondondu ondondu munigalige andand andandige aaya taa olidu | andanda andavara kaava cholangiri mandirane vijaya vittala narasimha | narasimha …. || bhalire ||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=M7Q9NvhesZ0"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಭಳೀರೆ-ಭಳೀರೆ-ನರಸಿಂಹ.json",
	rawData: "",
};

export { _internal, collection, data, id };
