const id = "ಮುಳ್ಳು-ಕೊನೆಯ-ಮೇಲೆ";
const collection = "bhajan";
const data = {kannada_title:"ಮುಳ್ಳು ಕೊನೆಯ ಮೇಲೆ",english_title:"Mullu koneya mele",kannada:"ಮುಳ್ಳು ಕೊನೆಯ ಮೇಲೆ\nಮೂರು ಕೆರೆಯ ಕಟ್ಟಿ ,ಎರಡು ತುಂಬಲು\nಒಂದು ತುಂಬಲೇ ಇಲ್ಲ\n||ಮುಳ್ಳು||    ತುಂಬಲಿಲ್ಲದ ಕೆರೆಗೆ\nಬಂದರು ಮೂವರು ಒಡ್ಡರು\nಇಬ್ಬರು ಕುಂಟರು ಒಬ್ಬಗೆ ಕಾಲೇ ಇಲ್ಲ\n||ಮುಳ್ಳು||\n\nಕಾಲಿಲ್ಲದ ಒಡ್ಡಗೆ ಕೊಟ್ಟರು\nಮೂರು ಎಮ್ಮೆಗಳ ಎರಡು ಬರಡು\nಒಂದಕ್ಕೆ ಕರುವೇ ಇಲ್ಲ\n||ಕಾಲಿಲ್ಲದ||\nಕರುವಿಲ್ಲದ ಎಮ್ಮೆಗೆ ಕೊಟ್ಟರು\nಮೂರು ಹೊನ್ನುಗಳ\nಎರಡು ಸವಕಲು ,ಒಂದು ಸಲ್ಲಲೇ ಇಲ್ಲ||2||\n||ಮುಳ್ಳು||\n\nಸಲ್ಲದಿದ್ದ ಹೊಣ್ಣಿಗೆ ಬಂದರು\nಮೂವರು ನೋಟಗಾರರು ,ಇಬ್ಬರು ಕುರುಡರು\nಒಬ್ಬಗೆ ಕಣ್ಣೇ ಇಲ್ಲ\n||ಸಲ್ಲದಿದ್ದ||\nಕಣ್ಣಿಲ್ಲದ ನೋಟಗಾರಗೆ ಕೊಟ್ಟರು\nಮೂರು ಊರುಗಳ\nಎರಡು ಹಾಳು ,ಒಂದಕ್ಕೆ ಒಕ್ಕಲೇ ಇಲ್ಲ||3||\n||ಮುಳ್ಳು||\n\nಒಕ್ಕಲಿಲ್ಲದ ಊರಿಗೆ\nಬಂದರು ಮೂವರು ಕುಂಬಾರರು\nಇಬ್ಬರು ಚೊಂಚರು ,ಒಬ್ಬಗೆ ಕೈಯೇ ಇಲ್ಲ\n||ಒಕ್ಕಲಿಲ್ಲದ||\nಕೈಯಿಲ್ಲದ ಕುಂಬಾರನು\nಮಾಡಿದನು ಮೂರು ಮಡಕೆಗಳ\nಎರಡು ಒಡಕು ಒಂದಕ್ಕೆ ಬುಡವೇ ಇಲ್ಲ||4||\n||ಮುಳ್ಳು||\n\nಬುಡವಿಲ್ಲದ ಮಡಕೆಗೆ ಹಾಕಿದರು\nಮೂರು ಅಕ್ಕಿಕಾಳ\nಎರಡು ಬೇಯಲು ,ಒಂದು ಬೇಯಲೇ ಇಲ್ಲ\n||ಬುಡವಿಲ್ಲದ||\nಬೇಯಲಿಲ್ಲದ ಅಕ್ಕಿಗೆ\nಬಂದರು ಮೂವರು ನೆಂಟರು\nಇಬ್ಬರು ಉಣ್ಣರು ,ಒಬ್ಬಗೆ ಹಸಿವೇ ಇಲ್ಲ||5||\n||ಮುಳ್ಳು||\n\nಹಸಿವಿಲ್ಲದ ನೆಂಟಗೆ ಕೊಟ್ಟರು\nಮೂರು ಟೊಣೆಪೆಗಳ\nಎರಡು ತಾಕದು ,ಒಂದು ತಾಕಲೇ ಇಲ್ಲ\n||ಹಸಿವಿಲ್ಲದ||\nತಾಕಲಿಲ್ಲದ ಟೊಣೆಪೆಯ\nತಾಕಿಸಿ ಸದ್ಗತಿಯನು\nಈಯಬೇಕು ಪುರಂದರ ವಿಠ್ಠಲರಾಯ\n||ತಾಕಲಿಲ್ಲದ||\n||ಮುಳ್ಳು||\n\n",english:"Mullu koneya mele muru kereya katti\neradu tumbadu ondu tumbale illa |1|\n\nTumbalillada kerege bandaru muvaru oddaru\nibbaru kuntaru obbage kale illa |2|\n\nKalillada oddage kottaru muru emmegala\neradu baradu ondakke karuve illa |3|\n\nKaruvillada emmege kottaru muru honnugala\neradu savakalu ondu sallale illa |4|\n\nSalladidda honnige bandaru muvaru notagararu\nibaru kurudaru obbage kanne illa|5|\n\nKannillada notagarage kottaru muru urugala\neradu halu ondakke okkale illa |6|\n\nOkkalillada urige bandaru muvaru kumbararu\nibbaru choncharu obbage kaiye illa |7|\n\nKai illada kumbaranu madida muru madikegala\neradu odaku ondakke budave illa |8|\n\nBudavillada madikege hakidaru muru akkikala\neradu beyadu ondu beyale illa |9|\n\nBeyalillada akkige bandaru muvaru nentaru\nibbaru unnaru obbage hasive illa |10|\n\nhasive illada nentage kottaru muru tonapegala\neradu takadu ondu takale illa |11|\n\nTakalillada tonapeya takisi sadgatiya\nniyabeku purandaravithala ninu |12|\n\n",meta:"",tags:["kannada devotional song","kannada lyrics"],media:""};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಮುಳ್ಳು-ಕೊನೆಯ-ಮೇಲೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
