const id = "ಮೂರು-ನಾಮಗಳ-ಧರಿಸಿದ--ಕಾರಣವೇನು";
const collection = "bhajan";
const data = {kannada_title:"ಮೂರು ನಾಮಗಳ ಧರಿಸಿದ  ಕಾರಣವೇನು",english_title:" Mooru namagala dharisida karanavenu",kannada:"ಮೂರು ನಾಮಗಳ ಧರಿಸಿದ  ಕಾರಣವೇನು\nಸಾರಿ ಪೇಳಲೋ ಈಗಲೇ||pa||\nಶ್ರೀ ರಮಾಪತಿ ಶ್ರೀನಿವಾಸ ವೆಂಕಟರಮಣ\nಯಾರು ಇಟ್ಟರೊ ನಿನಗೆ ಮೂರು ನಾಮಗಳ |a.pa|\nಶುದ್ಧ ವೈಷ್ಣವರೆಲ್ಲ ಶುದ್ಧ ಮೂರುತಿ ಎಂದು |\nಶುದ್ಧ ಪಾದಕೆ ಎರಗಿ ಕರವ ಮುಗಿದು |\nಎದ್ದು ನೋಡಲು ನಿನ್ನ ಪಣೆಯೊಳೀ ಪರಿ ಇರಲು\nಮಧ್ವಮತದ ದೈವವೆಂದು ನಿನ್ನ ಕರೆಯುವರೆ ||1||\nಸಾಲದೆ ನಿನ್ನ ಸೌಂದರ್ಯಕ್ಕೆ ಒಂದು ತಿಲಕ |\nಪಾಲಸಾಗರಶಾಯಿ ಚೆಲುವಮೂರ್ತಿ |\nಕಾಲಕಾಲಕೆ ಬರುವ ಭಕುತ ಜನಗಳ ವೃಂದ |\nದೃಷ್ಟಿ ತಾಕುವುದೆಂಬ ತೋರುವ ಬಗೆಯೊ ||2||\nಮೂರು ಲೋಕಗಳಿಹವು ಮೂರು ರೂಪನ ನಾನು |\nಮೂರು ಮಾಳ್ಪೆನು ಜಗವ ಮೂರು ಗುಣದಿ |\nಮೂರು ತಾಪವಗೆದ್ದು ಮಾರ್ಗದಿ ಭಜಿಸೆ |\nಪಾರು ಮಾಡುವೆನೆಂದು ತೋರುವ ಬಗೆಯೊ ||3||\nಮೂರೆರಡು ಎರಡೊಂದು ಇಂದ್ರಿಯ ವರ್ಜಿಸಲು |\nತೋರುವನು ನಿಜ ರೂಪ ಭಕ್ತನೆಂದು |\nಸಾರುತ್ತಿದ್ದರು ವಾಯು ಅರಿಯದೆ ಭಜಿಸಿದಗೆ |\nಮೂರು ನಾಮಗಳೆ ಗತಿ ಎನುವ ಬಗೆಯೋ ||4||\nಶ್ರೀಲೋಲ ಕೃಷ್ಣ ಗೋಪಾಲವಿಠಲ ನಿನ್ನ\nಈ ಬಗೆಯ ಲೀಲೆಗಳ ಅರಿವರ್ಯಾರೊ |\nವಾಸಶಯನ ವೆಂಕಟೇಶನೆ ಎನ್ನ ಮನಕೆ |\nಕಾಲಕಾಲಕೆ ನಿನ್ನ ಲೀಲೆಗಳ ತೋರೋ ||5||\n\n",english:"Muru namagala dharisida karanavenu\nSari pelalo igale||\nSri ramapati srinivasa venkataramana\nYaru ittaro ninage muru namagala |\nShuddha vaishnavarella Shuddha muruti endu |\nShuddha padake eragi karava mugidu |\nEddu nodalu ninna paneyolipari iralu\nMadhvamatada daivavendu ninna kareyuvare ||\nSalade ninna saundaryakke ondu tilaka |\nPalasagarasayi celuvamurti |\nKalakalake baruva bakutajanagala vrunda |\nDrushtitakuvudemba toruva bageyo ||\nMuru lokagalihavu mururupana nanu |\nMuru malpenu jagava muru gunadi |\nMuru tapavageddu margadi Bajise |\nParu maduvenendu toruva bageyo ||\nMureradu eradondu indriya varjisalu |\nToruvanu nijarupa Baktanendu |\nSaruttiddaru vayu ariyade Bajisidage |\nMurunamagale gati enuva bageyo ||\nSrilola krishna\ngopalavithala\nninna\nI bageya lilegala arivaryaro |\nVasasayana venkatesane enna manake |\nKalakalake ninna lilegala toro ||\n\n",meta:"",tags:["venkateshwara srinivasa","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=QicQHBOSKwI"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಮೂರು-ನಾಮಗಳ-ಧರಿಸಿದ--ಕಾರಣವೇನು.json",
	rawData: "",
};

export { _internal, collection, data, id };
