const id = "ರಂಗ-ನಮ್ಮನೆಗೆ-ಬಂದ-ಮತ್ತೇನು";
const collection = "bhajan";
const data = {kannada_title:"ರಂಗ ನಮ್ಮನೆಗೆ ಬಂದ ಮತ್ತೇನು",english_title:" Ranga nammanege banda mattenu",kannada:"ರಂಗ ನಮ್ಮನೆಗೆ ಬಂದ ಮತ್ತೇನು ತಂದ                                     ।।ಪ॥\n\nಜಗದೋದ್ಧಾರನ ಸಭೆಗೆ ಬಂದ ನಗುವ ಪರಿಯ ಹೇಳಿದ್ದು ತಂದ\nಬಗೆ ಬಗೆ ವಸ್ತ್ರಕೊಳ್ಳಿರೆಂದ ಪಗಡಿ ಧರ್ಮಗೆ ತರಲಿಲ್ಲೆಂದ                 ।।೧।।\n\nವಾಣಿ ಮಾವ ಮನೆಗೆ ಬಂದ ಜಾಣತನವ ಹೇಳಿದ್ದು ತಂದ\nಮಾಣಿಕ ಮುತ್ತುಕೊಳ್ಳಿರೆಂದ ಕ್ವಾಣವ ಧರ್ಮಗೆ ತರಲಿಲ್ಲಂದ            ।।೨।।\n\nಕೃಷ್ಣರಾಯ ಸಭೆಗೆ ಬಂದ ಎಷ್ಟು ಜಂಬ ಹೇಳಿದ್ದು ತಂದ\nಪಟ್ಟಾವಳಿ ಕೊಳ್ಳಿರೆಂದ ಹುಟ್ಟು ಭೀಮಗೆ ತರಲಿಲ್ಲೆಂದ                     ।।೩।।\n\nನಳಿನಾಕ್ಷಸಭೆಯೊಳು ಬಂದ ಹೊಳೆವೊ ಎಷ್ಟು ಹೇಳಿದ್ದು ತಂದ\nಝಳಿಸೋ ವಸ್ತ್ರಕೊಳ್ಳಿರೆಂದ ಬಳೆ ಪಾರ್ಥಗೆ ತರಲಿಲ್ಲೆಂದ               ।।೪।।\n\nರಾಜ್ಯ ಲಕ್ಷ್ಮಣನಿಗಿಲ್ಲೆಂದ ಮಾಜುದಾ ಕುಲ ಧರ್ಮ ಕುಂದ\nತೇಜ ಮುಂದೆ ಓಡಿದ್ದು ಚೆಂದ ಸೋಜಿಗವಲ್ಲ ನಕುಲನೆಂದ              ।।೫।।\n\nಸುಮನಸರು ನಗುವೊರೆಂದ ಭ್ರಮೆಯ ಕಳೆದ್ಯೋ ಸಹದೇವ ಎಂದ\nಅಮಿತದನವ ಕಾಯ್ವೋಛಂದ  ರಮಿಯರಸು ನಗುವನೆಂದ            ।।೬।।\n\nಅಂದ ಮಾತಿಗೆ ಬಲರಾಮ ಹೀಗೆಂದ ಚಂದವಾಯಿತು ಕುಶಲವೆಂದ\nನಿಂದ್ಯವ ನೀ ಮಾಡಿಕೊ ಎಂದ ಇಂದಿರೇಶಗೆ ತಿಳಿಸಿರೆಂದ              ।।೭।।\n\n",english:"Ranga nammanege banda mattenu tanda ||pa||\n\nJagadoddharana sabhege banda naguva pariya heliddu tanda | bage bage vatsra kollirenda pagadi dharmage tarallillenda ||1||\n\nVani mava manege banda janatanava heliddu tanda | manika muttukollirenda kwanava dharmage tarallilenda ||2||\n\nKrishnaraya sabhege banda eshtu jamba heliddu tanda | pattaavali kollirenda huttu bhimage tarallilenda ||3||\n\nNalinaksha sabhege banda holevo eshtu helliddu tanda | jaliso vatsra kollirenda bale parthage tarallilenda ||4||\n\nRajya lakshmannigillenda majuda kula dharma kunda | teja munde odiddu chenda sojigavalla nakulanenda ||5||\n\nSumanasaru naguvarenda bhrameya kaledyo sahadeva enda | amitadanava kayvo chenda rameyarasa naguvanenda ||6||\n\nAnda maatige balarama higenda chandavayitu kushalavenda | nindyava nee madiko enda indireshage tilisirenda || 7||\n\n",meta:"ಕೀರ್ತನಕಾರರು : ಗಲಗಲಿ ಅವ್ವನವರು",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=BfVRoLdAIsg"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ರಂಗ-ನಮ್ಮನೆಗೆ-ಬಂದ-ಮತ್ತೇನು.json",
	rawData: "",
};

export { _internal, collection, data, id };
