const id = "ರಾಧೇ-ಶ್ಯಾಮ್-ರಾಧೇ-ಶ್ಯಾಮ್";
const collection = "bhajan";
const data = {kannada_title:"ರಾಧೇ ಶ್ಯಾಮ್ ರಾಧೇ ಶ್ಯಾಮ್",english_title:"Radhe shyaam radhe shyaam",kannada:"ರಾಧೇ  ಶ್ಯಾಮ್ ರಾಧೇ  ಶ್ಯಾಮ್ ।ರಾಧಾ ಮಾಧವ ಮೇಘ ಶ್ಯಾಮ್  ।।ರಾಧೇ।।\n\nಆದಿ ನಾರಾಯಣ ರಾಧೇ  ಶ್ಯಾಮ್ ।ಅನಾದಿ ಪುರುಷ ಮೇಘ ಶ್ಯಾಮ್ ।೨।\nವಾಸುದೇವ  ಹರಿ ರಾಧೇ  ಶ್ಯಾಮ್ ।ವಾಸುಕಿತನಯನೇ   ಮೇಘ ಶ್ಯಾಮ್ ।।ರಾಧೇ।।\n\nದೇವಕಿ ತನಯ ರಾಧೇ  ಶ್ಯಾಮ್ । ದೇವ ದೇವ ಹರಿ ಮೇಘ ಶ್ಯಾಮ್ ।೨।\nಸರಸಿಜ ನಯನ   ರಾಧೇ  ಶ್ಯಾಮ್ ।ಗೋವುಗಳ  ಪ್ರಿಯ ಹರಿ ಮೇಘ ಶ್ಯಾಮ್ ।।ರಾಧೇ।।\n\nಪೂತನಿ ಮರ್ಧನ ರಾಧೇ  ಶ್ಯಾಮ್ ।ಶಕಟ  ಸಂಹಾರಿ ಮೇಘ ಶ್ಯಾಮ್ ।೨।\nಮಾತುಳ ಧ್ವಂಸಿ ರಾಧೇ  ಶ್ಯಾಮ್ ।ಅನಾಥ ರಕ್ಷಕ ಮೇಘ ಶ್ಯಾಮ್ ।।ರಾಧೇ।।\n\nಮುರಳಿ ಮನೋಹರ ರಾಧೇ  ಶ್ಯಾಮ್ । ನರಕಾಂತಕ  ಹರಿ ಮೇಘ ಶ್ಯಾಮ್ ।೨।\nಕರುಣಾಕರ ಹರಿ ರಾಧೇ  ಶ್ಯಾಮ್ । ಕರುಣಿಸಿ ಪೊರೆ ಹರಿ ಮೇಘ ಶ್ಯಾಮ್ ।।ರಾಧೇ।।\n\nನಂದ ಕುಮಾರ ರಾಧೇ  ಶ್ಯಾಮ್ ।ನವನೀತ ಚೋರ ಮೇಘ ಶ್ಯಾಮ್ ।೨।\nಪಾಂಡವ ಪ್ರಾಣನೇ  ರಾಧೇ  ಶ್ಯಾಮ್ ।ಪಾಂಡವ ತ್ರಾಣನೇ  ಮೇಘ ಶ್ಯಾಮ್ ।।ರಾಧೇ।।\n\nಗೋಪಿ ಜನ ಪ್ರಿಯ ರಾಧೇ  ಶ್ಯಾಮ್ ।ಗೋವರ್ಧನೋದ್ಧಾರ  ಮೇಘ ಶ್ಯಾಮ್ ।೨।\nಗೋಕುಲ ಕೃಷ್ಣ ರಾಧೇ  ಶ್ಯಾಮ್ ।  ನಂದ ಗೋಕುಲ ಮೇಘ ಶ್ಯಾಮ್ ।।ರಾಧೇ।।\n\nಯಶೋದ ಬಾಲ ರಾಧೇ  ಶ್ಯಾಮ್ । ಮುರಳಿ ಕೃಷ್ಣ ಮೇಘ ಶ್ಯಾಮ್ ।೨।\nಕೌಸ್ತುಭ ಆಭರಣ ರಾಧೇ  ಶ್ಯಾಮ್ ।ಯಾದವ ನಂದನ ಮೇಘ ಶ್ಯಾಮ್ ।।ರಾಧೇ।।\n\n",english:"Radhe shyaam radhe shyaam | radha madhava megha shyaam ||radhe||\n\nAdi narayana radhe shyaam | anadi purusha megha shyaam |vasudeva haei radhe shyaam | vasukitanayane megha shyaam||radhe||\n\nDevaki tanaya radhe shyaam| deva deva hari megha shyaam | sarasija nayana radhe shyaam | govugala priya hari megha shyaam||radhe||\n\nPootani mardhana radhe shyaam| shakata samhari megha shyaam| maatula dhwamsi radhe shyaam| anaatha rakshaka megha shyaam||radhe||\n\nmurali manohara radhe shyaam| narakaantaka hari megha shyaam| karunaakara hari radhe shyaam| karunisi pore hari megha shyaam||radhe||\n\nNandakumara radhe shyaam |navaneeta chora megha shyaam| paandava pranane radhe shyaam|paandava tranane megha shyaam||radhe||\n\nGopi jana priya radhe shyaam| govardhanodhara megha shyaam| gokulakrishna radhe shyaam| nandagokula megha shyaam||radhe||\n\nGopi jana priya radhe shyaam| govardhanodhara megha shyaam| gokulakrishna radhe shyaam| nandagokula megha shyaam||radhe||\n\nYashoda bala radhe shyaam| muralikrishna megha shyaam| koustubha abharana radhe shyaam| yaadava nandana megha shyaam||radhe||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=WUmtfyrECA8"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ರಾಧೇ-ಶ್ಯಾಮ್-ರಾಧೇ-ಶ್ಯಾಮ್.json",
	rawData: "",
};

export { _internal, collection, data, id };
