const id = "ರಂಗನಾಥನೆ-ನಿಮ್ಮ-ಕಾಣದೆ";
const collection = "bhajan";
const data = {kannada_title:"ರಂಗನಾಥನೆ ನಿಮ್ಮ ಕಾಣದೆ",english_title:" Ranganaathane nimma kaanade",kannada:"ರಂಗನಾಥನೆ ನಿಮ್ಮ ಕಾಣದೆ ಭಂಗ ಪಟ್ಟೆನು ಬಹುದಿನಾ…||ರಂಗ||\nಮಂಗಳಾಂಗ ನಿಮ್ಮ ಪಾದವ ಎನ್ನ ಕಂಗಳಿಗೇ ತೋರೋ…||ಮಂಗಳಾಂಗ||\n||ರಂಗನಾಥನೆ||\n\nಕರಿಯ ಮೊರೆ ಲಾಲಿಸಿದಿ ಬೇಗನೆ ನೆರೆದ ಸಭೆಯಲಿ ದ್ರೌಪದಿಗೆ ಅಭಯವನಿತ್ತೇ |\nಅಡವಿಯಲಿ ಅಹಲ್ಯೆಯ ಸಲಹಿದಿ ಮುಚುಕುಂದನ ರಕ್ಷಿಸಿದೀ ||\nಮುಚುಕುಂದನ ರಕ್ಷಿಸಿದೀ…. ||ರಂಗನಾಥನೆ||\nಭಂಗ ಪಟ್ಟೆನು ಬಹುದಿನ. ….\n\nಪುಟ್ಟ ಪ್ರಹ್ಲಾದನ ಸಲಹಿದಿ ಪಟ್ಟವನು ವಿಭೀಷಣನಿಗೆ ಸಲ್ಲಿಸಿದಿ|\nದಟ್ಟ ಅಡವಿಲಿ ಬಂದ ಧ್ರುವನ ಆದರಿಸಿ ಕಾಯ್ದ ರಂಗನಾಥ |\nಆದರಿಸಿ ಕಾಯ್ದ ರಂಗನಾಥ…. ||ರಂಗನಾಥನೆ||\nಭಂಗ ಪಟ್ಟೆನು ಬಹುದಿನ. …\n\nಎಷ್ಟು ಹೇಳಲಿ ನಿಮ್ಮ ಮಹಿಮೆಯ ಸ್ರಿಷ್ಠಿ ಸ್ಥಿತಿ ಲಯವನ್ನು ಅಳೆದೆ, ರಂಗನಾಥಾ |\nಈ ಪುಟ್ಟ ಪಾದವ ಎನ್ನ ಮನದಲಿ ಇಟ್ಟು ದಯಮಾಡೊ ಕ್ರಷ್ಣಾ. …|\nಇಟ್ಟು ದಯಮಾಡೊ ಕ್ರಷ್ಣಾ. …. ||ರಂಗನಾಥನೆ||\nಭಂಗ ಪಟ್ಟೆನು ಬಹುದಿನ. …\n\nದಕ್ಷಿಣ ಮುಖವಾಗಿ ಪವಡಿಸಿದಿ ನೀ ದೇವಶಿಖಾಮಣೀ ಏಳೈ… ದೇವಶಿಖಾಮಣೀ ಏಳೈ…|\nಬಂದ ಭಕ್ತರಿಗೆಲ್ಲಾ ಅಭಯ ಹಸ್ತವ ಕೊಡುವಿ ರಾಜೀವನೇತ್ರ ಹಯವದನ||ಅಭಯ||\nರಾಜೀವನೇತ್ರ ಹಯವದನಾ…. ||ರಂಗನಾಥನೆ||\n\n",english:"Ranganaathane nimma kaanade bhanga pattenu bahudinaa …. ||\n\nMangalaanga nimma paadava enna kangalige toro …. || ranganaathane ||\n\nKariya more laalisida begane | nereda sabheyali droupadige abhayavanitte || adaviyali ahalyeya salahida muchukundana rakshiside | muchukundana rakshisidi …. || ranganaathane ||\n\nPutta prahladana salahidi pattavanu vibhishananige sallisidi | datta adavili banda dhruvana adarisis kaayda ranganaatha | adarisi kaayda ranganaatha ….. || ranganaathane ||\n\nEshtu helali nimma mahimeya srishti stiti layavannu alede ranganaatha | e putta paadava enna manadali ittu dayamaado krishna …. | ittu dayamado krishna …… || ranganaathane ||\n\nDakshina mukhavaagi pavadisidi nee deva shikhaamani alai … || banda bhaktarigella abhaya hastava koduvi raajivanetra hayavadana || raajivanetra hayavadana ….. || ranganaathane ||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=y16A8J_w2JU"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ರಂಗನಾಥನೆ-ನಿಮ್ಮ-ಕಾಣದೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
