const id = "ರಂಗನಾಯಕ-ರಾಜೀವಲೋಚನ";
const collection = "bhajan";
const data = {kannada_title:"ರಂಗನಾಯಕ ರಾಜೀವಲೋಚನ",english_title:" Ranganaayaka raajivalochana",kannada:"ರಂಗನಾಯಕ ರಾಜೀವ ಲೋಚನ\nರಮಣನೇ ಬೆಳಗಾಯಿತು ಏಳೆನ್ನುತಾ ।ಪ।\n\nಅಂಗನೇ  ಲಕುಮಿ ತಾ ಪತಿಯನೆಬ್ಬಿಸಿದಳು\nಶೃಂಗಾರದ ನಿದ್ರೆ ಸಾಕೆನ್ನುತಾ ।।ಪ।।\n\nಪಕ್ಷರಾಜನು ಬಂದು ಬಾಗಿಲಲ್ಲಿ ನಿಂದು\nಅಕ್ಷಿ ತೆರೆದು ಬೇಗ ಈಕ್ಷೀಸೆಂದು\nಪಕ್ಷಿ ಜಾತಿಗಳೆಲ್ಲಾ ಚಿಲಿಪಿಲಿಗುಟ್ಟುತಾ\nಸೂಕ್ಷ್ಮದಲ್ಲಿ ನಿನ್ನ ಸ್ಮರಿಸುವವೋ ಕೃಷ್ಣ ।।ಪ।।\n\nಸನಕ ಸನಂದನ  ಸನತ್ಸುಜಾತರು ಬಂದು\nವಿನಯದಿಂ ಕರ ಮುಗಿದು ಓಲೈಪರು\nಘನಶುಕ  ಶೌನಕ ವ್ಯಾಸ ವಾಲ್ಮೀಕರು\nನೆನೆದು ನೆನೆದು ಕೊಂಡಾಡುವರು  ಹರಿಯೇ ।।ಪ।।\n\nಸುರರು ಕಿನ್ನರರು ಕಿಂಪುರುಷರು ಉರಗುರು\nಪರಿಪರಿಯಲಿ  ನಿನ್ನ ಸ್ಮರಿಸುವರು\nಅರುಣನು ಬಂದು ಉದಯಾಚಲದಲಿ ನಿಂದು\nಕಿರಣ ತೋರುವನು  ಭಾಸ್ಕರನು ಶ್ರೀಹರಿಯೇ ।।ಪ।।\n\nಪದುಮನಾಭನೇ  ನಿನ್ನ ನಾಮಾಮೃತವನ್ನು\nಪದುಮಾಕ್ಷಿಯರು ತಮ್ಮ ಗೃಹದೊಳಗೆ\nಉದಯದೊಳೆದ್ದು ಸವಿದಾಡುತ್ತಾ  ಪಾಡುತ್ತಾ\nದಧಿಯ ಕಡೆವರೇಳೋ  ಮಧುಸೂಧನ ಕೃಷ್ಣಾ।।ಪ।।\n\nಮುರಮಥನನೇ  ನಿನ್ನ ಚರಣದ  ಸೇವೆಯ\nಕರುಣಿಸಬೇಕೆಂದು ತರುಣಿಯರು\nಪರಿಪರಿಯಿಂದಲೇ  ಸ್ಮರಿಸಿ ಹಾರೈಪರು\nಪುರಂದರ ವಿಠಲ\nನೀನೇಳೋ  ಶ್ರೀ ಹರಿಯೇ।।ಪ।।\n\n",english:"Ranganayaka  rajeeva lochana\nramanane belagayitu elennutaa||pa||\nangane lakumi taa patiyanebbisidalu\nshrungarada nidre sakennutaa||pa||\n\nPakshirajanu bandu bagilalli nindu\nakshi teredu bega eekshisendu\npakshi jatigalella chilipiliguttutaa (2)\nsookshmadali ninna smarisuvavo krushna||pa||\n\nSanaka sanandana sanatsujataru bandu\nvinayadim kara mugidu olaiparu\nghanashuka shounaka vyaasa valmikaru\nnenedu nenedu kondaduvaru hariye||pa||\n\nSuraru kinnararu kimpurusharu uraguru\nparipariyali ninna smarisuvaru\narunanu bandu udayachaladali nindu\nkirana toruvanu bhaskaranu srihariye||pa||\n\nPadumanabhane ninna naamamrutavannu\npadumaakshyari tamma gruhadolage\nudayadoleddu savidaadutta paadutta\ndadhiya kadevarelommadhudoodhana krishna||pa||\n\nMuramathanane ninna charanada seveya\nkarunisabekendu taruniyaru\nparipariyindale smarisi haraiparu\npurandaravithala\nneenelo srihariye||pa||\n\nListen to the song in below given link by Vidyabhushana Theertha Swamiji\nhttps://youtu.be/bsI30qItJvk\n\nBy Putturu Narasimha Nayak\nhttps://youtu.be/eVBV46-SI1c\n\n",meta:"",tags:["narayana","dasara padagalu","kannada devotional song","kannada lyrics","narayana song"],media:"https://www.youtube.com/watch?v=bsI30qItJvk"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ರಂಗನಾಯಕ-ರಾಜೀವಲೋಚನ.json",
	rawData: "",
};

export { _internal, collection, data, id };
