const id = "ರಾ-ಎಂದ-ಮಾತ್ರದೊಳು";
const collection = "bhajan";
const data = {kannada_title:"ರಾ ಎಂದ ಮಾತ್ರದೊಳು",english_title:" Raa enda matradolu rakta",kannada:"ರಾ ಎಂದ ಮಾತ್ರದೊಳು ರಕ್ತ ಮಾಂಸದೊಳಿದ್ದಾ\nಆಯಸ್ತವಾದ ಅತಿ ಪಾಪವನೂ ಮಾಯ ಮಾಡಿ, ಮತ್ತೆ ಮಾ ಎಂದೆನಲು\nಹೊರಬಿದ್ದ ಪಾಪಗಳು ಒತ್ತಿ ಒಳ ಪೋಗದಂತೇ…ಏ…\nಕವಾಟವಾಗಿ ಕಾಯ್ವ ಮಂತ್ರಾ…..ಆ…\n\nಶ್ರೀ ರಾಮ ಜಯ ರಾಮ ರಮಣೀಯ ನಾಮ ರಘುರಾಮ ||2||\nರಾಮ ಮಂತ್ರವ ಜಪಿಸೀ ಪಾಪವ ಕಳೆಯೋಣ ||\nರಘುಕುಲತಿಲಕನ ಚರಣಕ್ಕೆರಗಿ ಪುನೀತರಾಗೋಣ\n\nಅಗಣಿತ ಗುಣ ಗಣ ಶ್ರೀ ರಾಮ ಆಶ್ರೀತ ವತ್ಸಲ ಶ್ರೀ ರಾಮ\nದೀನದಯಾಳು ಶ್ರೀ ರಾಮ ಹರಿ ಸರ್ವೋತ್ತಮ ಶ್ರೀ ರಾಮ\nದಶಮುಖ ಮರ್ದನ,  ದಶರಥ ರಾಮ ಮಾರುತಿ ಸೇವಿತ ಶ್ರೀ ರಾಮ\nರಾಮಚಂದ್ರ ಪ್ರಭು ‌ ||ರಾಮ ಮಂತ್ರವ||\n\nಜಾನಕಿ ಮನೋಹರ  ಜ್ಞಾನಧಾತ ಕರುಣಾಸಾಗರ ಕೋದಂಡರಾಮಾ..\nಭಕ್ತಿಪ್ರಿಯನಿಧಿ ,ಮುಕ್ತಿದಾಯಕ ಭಕ್ತಜನ ಶ್ರೀ ಮಂದಾರನೇ\nರಾಮ ಎಂಬುವ ಎರಡು ಅಕ್ಷರದ ಮಹಿಮೆಯ |\nಪಾಮರರು ನಾವು ಬಲ್ಲೆವೇನು ||\n\nರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ\nರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ\nರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ\nರಾಮಚಂದ್ರ ಪ್ರಭು         ||ರಾಮ ಮಂತ್ರವ||\n\nಧರೆಯೊಲಿ ನಾಮಕೆ ಸರಿಸಾಟಿ ಇಲ್ಲವೆಂದು\nಪರಮ ವೇದಗಳೆಲ್ಲ ಪೊಗಳುತಿವೆ\nಚಿತ್ತ ಕಾಯಗಳ ಪವಿತ್ರ ಪಾದೋದಕವ ಭಕ್ತವರ ಹನುಮಂತನೊಬ್ಬ ತಾ ಬಲ್ಲ\nರಾಮ ಗೋವಿಂದ ಹರೇ ಕ್ರಷ್ಣ ಗೋವಿಂದ\nರಾಮ ಗೋವಿಂದ ಹರೇ ಕ್ರಷ್ಣ ಗೋವಿಂದ\nಶಂಖಚಕ್ರ ಧರಾ ವಿಷ್ಣು ಮುಕುಂದ ||\n\nರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ\nರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ\nರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ ರಾಮ\nರಾಮಚಂದ್ರ ಪ್ರಭು        ||ರಾಮ ಮಂತ್ರವ||\n\n",english:"Raa enda matradolu rakta mamsadoliddaa\nayastavada ati papavanoo maya madi, matte maa endenalu\nhobidda paapagalu otti ola pogadante …\nkavaatavagi kayva mantra …….\n\nSri rama jaya rama ramaneeya nama raghurama\nrama mantrava japisi paapava kaleyona ||\nraghukulatilakana charanakkeragi puneetaragona\n\nAganita gunagana sri rama ashrita vatsala sri rama\ndeenadayalu sri rama hari sarvottama sri rama\ndashamukha mardhana, dasharatha rama maruti sevita sri rama\nramachandra prabhu || rama mantrava ||\n\nJanaki manohara jnanadaata karunasagara kodandarama\nbhaktipriyanidhi muktidayaka bhaktajana sri mandarane\nrama embuva eradu aksharada mahimeya|\npamararu navu ballevenu ||\n\nRama rama rama rama rama rama rama\nrama rama rama rama rama rama rama\nrama rama rama rama rama rama rama\nramachandra prabhu || rama mantrava ||\n\nDhareyoli namake sarisati illavendu\nparama vedagalella pogalutive\nchitta kayagala pavitra paadodakava\nbhaktavara hanumantanobba taa balla\nrama govinda hare krishna govinda hare\nrama govinda hare krishna govinda hare\nshankhachakradhara vishnu mukunda ||\n\nRama rama rama rama rama rama rama\nrama rama rama rama rama rama rama\nrama rama rama rama rama rama rama\nramachandra prabhu || rama mantrava ||\n\n**********************\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=2A5DyQj8DGo"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ರಾ-ಎಂದ-ಮಾತ್ರದೊಳು.json",
	rawData: "",
};

export { _internal, collection, data, id };
