const id = "ರಾಘವೇಂದ್ರ ಯತಿ-ಸಾರ್ವಭೌಮ";
const collection = "bhajan";
const data = {kannada_title:"ರಾಘವೇಂದ್ರ ಯತಿ ಸಾರ್ವಭೌಮ",english_title:"  Raghavendra yati sarvabhauma",kannada:"ರಾಘವೇಂದ್ರ  ಯತಿ  ಸಾರ್ವಭೌಮ  ದುರಿತೌಘ ದೂರ  ತೇ ನಮೋ ನಮೋ |\nಮಾಗಧರೀಪು ಮತ  ಸಾಗರ  ಮೀನ  ಮಹಾಘ  ವಿನಾಶನ ನಮೋ ನಮೋ ||\n\nಶ್ಲಾಘಿತ ಗುಣ ಗಣ  ಸೂರಿ  ಪ್ರಸಂಗ  ಸದಾಗಮಜ್ಞ  ತೇ ನಮೋ ನಮೋ |\nಮೇಘ  ಶ್ಯಾಮಲ  ರಾಮಾರಾಧಕ ಅಮೋಘ ಬೋಧತೇ ನಮೋ ನಮೋ ||\n\nತುಂಗಭದ್ರ  ಸುತರಂಗಿಣಿ ತೀರಗ  ಮಂಗಳ  ಚರಿತ  ಶುಭಾಂಗ ನಮೋ |\nಇಂಗಿತಜ್ಞ ಕಾಳಿಂಗ  ಮರ್ಧನ  ಯದು ಪುಂಗವ  ಹೃದಯ  ತುರಂಗ ನಮೋ ||\n\nಸಂಗಿರ  ಚಿಹ್ನಿತ ಶೃ0ಗಾರಾನನ ತಿಂಗಳ  ಕರುಣಾಪಾಂಗ ನಮೋ |\nಗಾಂಗೇಯ ಸಮಭಾಂಗ ಕುಮತ  ಮಾತಂಗ  ಸಂಘ ಶಿತಪಿಂಗ ನಮೋ ||\n\nಶ್ರೀ  ಸುಧೀಂದ್ರ  ಕರಜಾತ ನವೋ ನಮೋ  ಭೂಸುರ  ವಿನುತ  ವಿಖ್ಯಾತ ನಮೋ ನಮೋ |\nದೇಶಿಕ  ವರ  ಸಂಸೇವ್ಯ ನಮೋ ನಮೋ    ದೋಷ  ವಿವರ್ಜಿತ  ಕಾವ್ಯ ನಮೋ ||\n\nಕ್ಲೇಶಿತ  ಜನ  ಪರಿಪಾಲ ನಮೋ ನಮೋ        ಭಾಸಿತ ಕರುಣಾಶೀಲ ನಮೋ |\nವ್ಯಾಸರಾಯ  ಪದ  ಭಕ್ತ ನಮೋ ನಮೋ      ಶಾಶ್ವತ ಧರ್ಮಾಸಕ್ತ ನಮೋ ||\n\nಕೋವಿದ  ಮಸ್ತಕ  ಶೋಭಿತ  ಮಣಿ  ಸಂಭಾವಿತ  ಮಹಿಮಾ  ಪಾಲಯಮಾಮ್ |\nಸೇವಾಪರ  ಸರ್ವಾರ್ಥಪ್ರದ  ಬೃಂದಾವನ  ಮಂದಿರ  ಪಾಲಯಮಾಮ್ ||\n\nಭಾವಜ  ಮಾರ್ಗಣ  ಭುಜಗವಿನಾಯಕ  ಭಾವಜ್ಞ  ಪ್ರಿಯ  ಪಾಲಯಮಾಮ್ |\nಕೇವಲ  ನುತಜನ  ಪಾವನ ರೂಪಿ  ಸದಾ  ವಿನೋದಿ  ಹೇ  ಪಾಲಯಮಾಮ್||\n\nಸನ್ನುತ ಮಹಿಮ  ಶ್ರೀ  ಜಗನ್ನಾಥ  ವಿಠಲ  ಸಹ್ನಿತ  ಮಾನಸ  ಜಯ  ಜಯ  ಭೋ |\nಚಿಹ್ನಿತ  ದಂಡ  ಕಮಂಡಲ  ಪುಂಡರ  ಪ್ರಪನ್ನ  ಭಯಾಪಹ  ಜಯ  ಜಯ  ಭೋ ||\n\nಮಾನ್ಯ  ಮಹಾತ್ಮ  ಪ್ರಸನ್ನ ವದನ ಕಾರುಣ್ಯಪಯೋನಿಧಿ  ಜಯ  ಜಯ  ಭೋ |\nಧನ್ಯ ಕ್ಷಮ ಸಂಪನ್ನ ಧರಾಮರ ಶರಣ್ಯ ಶಾಶ್ವತ ಜಯ  ಜಯ  ಭೋ ||\n\n",english:"Raghavendra yati sarvabhauma duritaugha dura te namo namo|\nmagadharipu mata sagara mina mahagha vinashana namo namo||\n\nShlagita guna gana suri prasanga sadaga majna te namo namo |\nmegha shyamala ramaaraadaka amogha bodha te namo namo ||\n\nTungabhadra sutarangini tiraga mangala charita shubhanga namo|\ningitajna kalinga mardhana yadupungava hridaya turanga namo|\n\nSangira chihnita shringaranana tingala karunapanga namo |\ngangeya sama bhanga kumata matanga sangha shitapinga namo||\n\nShri sudhindra karajata namo namo bhusura vinuta vikhyata namo namo\ndeshika vara samsevya namo namo dosa vivarjita kavya namo ||\n\nKleshita jana paripala namo namo bhashita karuna shila namo |\nvyasaraya pada bhakta namo namo shashvata dharmasakta namo ||\n\nKovida mastaka shobhita mani sambhavita mahima palayamam\nsevapara sarvarthaprada brindavana mandira palayamam ||\n\nBhavaja margana bhujagavinayaka bhavajna priya palayamam\nkevala nutajana pavana rupi sada vinodi he palayamam ||\n\nSannuta mahima shri jagannatha vithala sannita manasa jaya jaya bho\nchihnita danda kamandala pundra prapanna bhayapaha jaya jaya bho||\n\nManya mahatma prasanna vadana karunyapayonidhi jaya jaya bho |\ndhanya kshama sampana dharamara sharanya shashwatha jaya jaya bho||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=AVWOSlEDGZ4"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ರಾಘವೇಂದ್ರ ಯತಿ-ಸಾರ್ವಭೌಮ.json",
	rawData: "",
};

export { _internal, collection, data, id };
