const id = "ರಾಜಬೀದಿಯೊಳಗಿಂದ-ಕಸ್ತೂರಿರಂಗ";
const collection = "bhajan";
const data = {kannada_title:"ರಾಜಬೀದಿಯೊಳಗಿಂದ ಕಸ್ತೂರಿರಂಗ",english_title:" Rajabeediyolaginda kasturiranga",kannada:"ರಾಜ ಬೀದಿಯೊಳಗಿಂದ ಕಸ್ತೂರಿ ರಂಗ\nತೇಜನೇರಿ ಮೆರೆದು ಬಂದಾ | ಪ |\nಸುತ್ತಮುತ್ತಲು ಸಾವಿರಾರು ಸಾಲು ದೀವಿಗೆ\nಹತ್ತು ದಿಕ್ಕಲಿ ಬೆಳಗುತ್ತಿದ್ದ ಹಗಲು ಬತ್ತಿಯು\nವಿಸ್ತಾರದಿ ಭೂಸುರರು ಸುತ್ತುಗಟ್ಟಿ ನಿಂತಿರಲು\nಮತ್ತೆ ನಮ್ಮೊಳೆಂತೊ ತೇಜ ಮೆಲ್ಲನೆ ನಡೆಸುತ ಜಾಣ | ೧ |\nತಾಳ ಶಂಖ ಭೇರಿ ತಂಬೂರಿ ಮೊದಲಾದ\nಮೇಲು ಪಂಚಾಗಗಳೆಲ್ಲ ಹೊಗಳಿ ಹೊಗಳಲು\nಗಾಳಿಗೋಪುರದ ಮುಂದೆ ಧಾಳಿಯಾಡುತ ಸುತ್ತ\nಧೂಳಿಯನ್ನೆಬ್ಬಿಸಿ ವೈಯಾಳಿಸಿ ನಿಕ್ಕುತ ಜಾಣ | ೨ |\nವೇದಶಾಸ್ತ್ರ ಪುರಾಣಗಳು ವಂದಿಸಿ ಪೊಗಳಲು\nಮೋದದಿಂದ ಗಾಯಕರು ಮೌರಿ ಪಾಡಲು\nಹಾದಿ ಬೀದಿಯಲ್ಲಿ ನಿಂತು ಭೂಸುರ ಜನರಿಗೆಲ್ಲಾ\nಅದರಿಂದ ಅಷ್ಟಮೃತಾನ್ನವ ನಿಕ್ಕುತ ಜಾಣ | ೩ |\nರಂಭಾ ಮೊದಲಾದ ಸುರರಮಣಿಯರು\nತುಂಬಿದಾರುತಿಯ ಪಿಡಿದು ಕೂಡಿ ಪಾಡಲು\nಶಂಭು ಮುಖ ನಿರ್ಜರನೇ ಪರಾಕೆನುತಲಿ\nಅಂಬುದಿ ಭವಾದ್ಬಿಗಳ ಆಳಿದ ಶ್ರೀರಂಗನಾಥ | ೪ |\nಹಚ್ಚನಗೆ ಸಾರು ಬೇಳೆ ಹಾಲು ಕೆನೆಗಳು\nಮುಚ್ಚಿ ತಂದ ಕೆನೆ ಮೊಸರು ವೀಸಲು ಬೆಣ್ಣೆಯು\nಹಚ್ಚಿ ತುಪ್ಪ ಪಕ್ವವಾದ ಅತಿರಸ ಹುಗ್ಗಿಯನ್ನು\nಮೆಚ್ಚಿ ಉಂಡು ಪಾನಕ ನೀರ್ ಮಜ್ಜಿಗೆಗಳಸವಿದು ಬೇಗ | ೫ |\nಮುತ್ತಿನ ತುರಾಯಿ ಮುಂಡಾಸನದಿ ತತ್ತಳಿಪ\nತಾಳಿ ವಜ್ರ ತಾಳಿ ಚೌಕಳಿ ಮುತ್ತಿನ ಕುಂಡಲನಿಟ್ಟು\nಮೋಹಿಸುತ್ತ ಬೀದಿಯಲ್ಲಿ ಕತ್ತಿಯ\nಕೈಯಲ್ಲಿ ಪಿಡಿದು ಮತ್ತಿಲ್ಲೆ ವಿರಾಜಿಸುತ್ತ | ೬ |\nಸಣ್ಣ ಮುತ್ತು ಕೆತ್ತಿಸಿದ ಸಕಲಾಧಿಗಳು\nಹೊನ್ನಹೊಸ ಜಾನ ಜಂಗುಳಿ ಹೊಳೆವಸೊಬಗಿನ\nಉನ್ನತ ಪಾರಾಯಣ ಉತ್ತಮರಾ ಜಶ್ವವೇರಿ\nಎನ್ನ\nಹಯವದನ\nರಂಗ ಎಲ್ಲರಿಗಷ್ಟಾರ್ಥಕೊಡುತ | ೭ |\n\n",english:"Raajbeediyolaginda kasturi ranga\ntejaneri meredu banda || pa ||\n\nSutta muttalu saaviraaru saalu deevige\nhattu dikkalu belaguttidda hagalu batthiyu\nvistaaradi bhoosuraru suttugatti nintiralu\nmatte nammolento teja mellane nadesuta jaana || 1 ||\n\nThaala shankha bheri tamboori modalaada\nmelu panchangagalella hogali hogalalu\ngaali gopurada munde dhaaliyaaduta sutta\ndhooliyannebbisi vaiyaarisi nikkuta jaana || 2 ||\n\nVedashaastra puraanagalu vandisi pogalalu\nmodadinda gaayakaru mauri paadalu\nhaadi beediyali nintu bhoosura janarigella\naadaradinda ashta amrataannava nikkuta jaana || 3 ||\n\nRambhaa modalaada surara maniyaru\ntumbidaarutiya pididu koodi paadalu\nshambhu mukha nirjarane paraakenutali\nambudi bhaavbdigala aalida Shree Ranganaatha || 4 ||\n\nHacchanage saaru bele haalu kenegalu\nmucchi tanda kene mosaru veesalu benneyu\nhacchi tuppa pakvavaada atirasa huggiyannu\nmecchi undu paanaka neer majjigegalasavidu bega || 5 ||\n\nSanna muttu kettisida sakalaadhigalu\nhonnahosa jaana janguli holeva sobagina\nunnata paarayana uttamaraajshvaveri\nenna\nHayavadana\nranga ellarigishtaartha koduta || 6 ||\n\nYoutube link\n:\nhttps://youtu.be/bSB7Z7D-CAA\nby Sri Putturu Narasimha Nayak\n\n",meta:"",tags:["krishna","dasara padagalu","kannada devotional lyrics","krishna song"],media:"https://www.youtube.com/watch?v=bSB7Z7D-CAA"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ರಾಜಬೀದಿಯೊಳಗಿಂದ-ಕಸ್ತೂರಿರಂಗ.json",
	rawData: "",
};

export { _internal, collection, data, id };
