const id = "ವೃಷಭನೇರಿದ-ವಿಷಧರನ್ಯಾರೆ";
const collection = "bhajan";
const data = {kannada_title:"ವೃಷಭನೇರಿದ ವಿಷಧರನ್ಯಾರೆ",english_title:"Vrushabhanerida vishadharanyare",kannada:"ವೃಷಭನೇರಿದ ವಿಷಧರನ್ಯಾರೆ ಪೇಳಮ್ಮಯ್ಯ || ಪ ||\n\nಹಸುಳೆ ಪಾರ್ವತಿಯ ತಪಸಿಗೆ ಮೆಚ್ಚಿದ\nಜಟಾಕುಂಡಲಧಾರಿ ಕಾಣಮ್ಮ || ಅ.ಪ ||\n\nಕೈಲಾಸಗಿರಿಯ ದೊರೆಯಿವನಮ್ಮ – ಅದು ಅಲ್ಲದೆ ಕೇಳೆ\nಬೈಲು ಸ್ಮಶಾನದಿ ಮನೆಯಿವಗಮ್ಮ – ಸಂಕರ್ಷಣನೆಂದು\nಕೇಳೆ ಮಹಿಯೊಳು ಜನಪೊಗಳುವರಮ್ಮ – ಇದು ನೈಜವಮ್ಮ\nನಾಲಿಗೆ ಸಾಸಿರ ಫಣಿಭೂಷಣನಮ್ಮ\nರಮೆಯರಸಗೆ ಇವ ಮೊಮ್ಮಗನಮ್ಮ || ೧ ||\n\nಬಾಲೆ ದಾಕ್ಷಾಯಣಿ ಪತಿ ಇವನಮ್ಮ – ಮಾನವ ಯಾಗದಲಿ\nಬ್ಹಾಳ ಕೃತ್ಯಗಳನು ನಡೆಸಿದನಮ್ಮ – ಸಾಗರದಲಿ ಹುಟ್ಟಿದ\nಕಾಳಕೂಟವ ಭಕ್ಷಿಸಿದನಮ್ಮ – ರಾಮನ ದಯವಮ್ಮ\nಮೇಲೆ ಉಳಿಯಲು ಶೇಷಗರಳವು\nನೀಲಕಂಠನೆಂದೆನಿಸಿದನಮ್ಮ || ೨ ||\n\nಹರನೊಂದಿಗೆ ವೈಕುಂಠಕೆ ಬರಲು – ತಾತಗೆ ವಂದಿಸುತ\nತರಣೀ ರೂಪವ ನೋಡೇನೆನೆಲು – ಹರಿ ತಾ ನಸುನಗುತ\nಕರೆದು ಸೈರಿಸಲಾರೆ ನೀ ಎನಲು – ಹಠದಿ ಕುಳ್ಳಿರಲು\nಕರುಣಿಗಳರಸನು ಹರನ ಮೊಗದ ನೋಡಿ\nಅರುಣೋದಯಕೆ ಬಾರೆಂದು ಕಳುಹಿದ || ೩ ||\n\nಅರುಣೋದಯಕೆ ಗಂಗಾಧರ ಬರಲು – ಹದಿನಾರು ವರುಷದ\nತರುಣೀ ರೂಪದಿ ಹರಿ ಮನದೊಳಗಿರಲು – ಚರಣನಖಾಗ್ರದಿ\nಧರಣೀ ಬರೆಯುತ್ತ ನಿಂತಿರಲು – ಸೆರಗ ಪಿಡಿಯೆ ಬರಲು\nಕರದಿ ಶಂಖ ಗದೆ ಚಕ್ರವ ತೋರಲು\nಹರನು ನಾಚಿ ತಲೆ ತಗ್ಗಿಸಿ ನಿಂತ || ೪ ||\n\nಮಂಗಳಾಂಗನೆ ಮಾರಜನಕ – ನಾ ಮಾಡಿದ ತಪ್ಪ\nಹಿಂಗದೆ ಕ್ಷಮಿಸೊ ಯದುಕುಲ ತಿಲಕ – ವಕ್ಷದಲ್ಲೊಪ್ಪುವ ನಿ\nನ್ನಂಗನೆ ಅರಿಯಳೊ ನಖಮಹಿಮಾಂಕ – ಹೀಗೆನುತಲಿ ತವಕ\nರಂಗವಿಠಲನ ಪದಂಗಳ ಹಿಡಿದು ಸಾ\nಷ್ಟಾಂಗವೆರಗಿ ಕೈಲಾಸಕೆ ನಡೆದ || ೫ ||\n\n",english:"Vrushabanerida vishadharanyare pelammayya || pa ||\n\nHasule parvatiya tapasige mecchida\nJatakundaladhari kanamm || a.pa ||\n\nKailasagiriya doreyivanamma – adu allade kele\nBailu smashanadi maneyivagamma – shankarshananendu\nKele mahiyolu janapogaluvaramma – idu nijavamma\nNalige sasira panibushananamma\nRameyarasa iva mommaganamma || 1 ||\n\nBale dakshayani pati ivanamma – manava yagadali\nBahala krutyagalanu nadesidanamma – sagaradali huttida\nKalakutava bakshisidanamma – ramana dayavamma\nMele uliyalu sheshagaralavu\nNilakanthanendenisida namma || 2 ||\n\nHaranondige vaikunthake baralu – taatage vandisuta\nTaruni rupava nodenenelu – hari ta nasunaguta\nKaredu sairisalare ni enalu – hathadi kulliralu\nKarunigalarasanu harana mogada nodi\nArunodayake barendu kaluhida || 3 ||\n\nArunodayake gangadhara baralu – hadinaru varushada\nTaruni rupadi hari manadolagiralu – charananakagradi\nDharani bareyutta nintiralu – seraga pidiye baralu\nKaradi sanka gade chakrava toralu\nHaranu naci tale taggisi ninta || 4 ||\n\nMangalangane marajanaka – na madida tappa\nHingade kshamiso yadukula tilaka – vakshadalloppuva ni\nNnangane ariyalo nakamahimanka – higenutali tavaka\nRangavithalana padangala hididu sa\nShtangaveragi kailasake nadeda || 5 ||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=Szt_Qray7Aw"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ವೃಷಭನೇರಿದ-ವಿಷಧರನ್ಯಾರೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
