const id = "ವರವ-ಕೊಡೆ-ಚಾಮುಂಡಿ";
const collection = "bhajan";
const data = {kannada_title:"ವರವ ಕೊಡೆ ಚಾಮುಂಡಿ",english_title:"Varava kode chamundi",kannada:"ಗಾಯನ : ಬಿ. ಕೆ. ಸುಮಿತ್ರ\n\nಚಾಮುಂಡಿ ದೇವಿ ಚಾಮುಂಡಿ||2||\n\nವರವ ಕೊಡೆ ಚಾಮುಂಡಿ ವರವ ಕೊಡೆ ||2||\nಸೆರಗೊಡ್ಡಿ ಬೇಡುವೆನೂ ವರವ ಕೊಡೆ\nವರವ ಕೊಡೆ\nಒಲವಿಂದ ನೀನೆನಗೆ ,ವರ ನೀಡಿ ಸಲಹದಿರೆ||2||\nನಿನ್ನಾಣೆ ನಾ ನಿನ್ನ‌ ಪಾದ ಬಿಡೆ\nನಿನ್ನ ಪಾದ ಬಿಡೆ  ||ವರವ||\n\nಕುಂಕುಮವು ಅರಸಿನವು\nಹೊಳೆವಂತ ಕರಿಮಣಿಯು||ಕುಂಕುಮ||\nಸ್ಥಿರವಾಗಿ ಇರುವಂತೆ ವರವ ತೊಡೆ\nಸೆರಗೊಡ್ಡಿ ಬೇಡುವೆನು ವರವ ಕೊಡೆ\nವರವ ಕೊಡೆ  ||ವರವ||\n\nಬಾಗಿಲಲಿ ತೋರಣ\nಮದುವೆ ಮುಂಜಿ ನಾಮಕರಣ||ಬಾಗಿಲಲಿ||\nಯಾವಾಗಲು ಆಗುವಂತೆ ವರವ ಕೊಡೆ\nನಿನ್ನಾಣೆ ನಾ ನಿನ್ನ ಪಾದ ಬಿಡೆ\nನಿನ್ನ ಪಾದ ಬಿಡೆ  ||ವರವ||\n\nಹೆಸರುಳ್ಳ ಮನೆ ಕಟ್ಟಿ\nಹಸು ಕರುಗಳ ಸಾಲು ಕಟ್ಟಿ||ಹೆಸರು||\nವಂಶವ್ರಧ್ಧಿ ಆಗುವಂತೆ ವರವ ಕೊಡೆ\nಸೆರಗೊಡ್ಡಿ ಬೇಡುವೆನು ವರವ ಕೊಡೆ\nವರವ ಕೊಡೆ  ||ವರವ||\n\nಮನೆಯಲ್ಲಿ ಹರುಷ ಕೊಟ್ಟು\nಮನದಲ್ಲಿ ಶಾಂತಿ ಕೊಟ್ಟು||ಮನೆಯ||\nಭಕ್ತಿ ಹ್ರದಯ ತುಂಬುವಂತೆ ವರವ ಕೊಡೆ\nನಿನ್ನಾಣೆ ನಾ ನಿನ್ನ ಪಾದ ಬಿಡೆ\nನಿನ್ನ ಪಾದ ಬಿಡೆ  ||ವರವ||\n\n",english:"Singer : B.K. Sumitra\n\nChamundi Devi Chamundi\nChamundi Devi Chamundi\n\nVarava Kode Chamundi Varava Kode..\nVarava Kode Chamundi Varava Kode..\nSeragoddi Beduvenu Varava Kode Varava Kode\nVarava Kode Chaamundi Varava Kode\n\nOlavinda Neenanege Vara Needi Salahidare\nOlavinda Neenanege Vara Needi Salahidare\nNinnaane Naa Ninna Paada Bide..\nNinna Paada Bide.. || varava ||\n\nKumkumavu Arishinavu Holevantha Karimaniyu\nKumkumavu Arishinavu Holevantha Karimaniyu\nSthiravaagi Iruvanthe Varava Kode\nSeragoddi Beduvenu Varava Kode Varava Kode ||varava||\n\nBaagilali Thorana Maduve Munji Naamakarana\nBaagilali Thorana Maduve Munji Naamakarana\nYaavagalu Aaguvanthe Varava Kode\nNinnaane Naa Ninna Paada Bide Ninna Paada Bide.. || varava||\n\nHesarulla Mane katti Hasu Karuva Saalu Katti\nHesarulla Mane katti Hasu Karuva Saalu Katti\nVamsha Vruddi Aaguvanthe Varava Kode ||varava||\n\nManeyalli Harusha Kottu Manadalli Shanthi Kottu\nManeyalli Harusha Kottu Manadalli Shanthi Kottu\nBhakthi Hrudaya Thumbuvanthe Varava Kode\nNinnaane Naa Ninna Paada Bide Ninna Paada Bide|| varava ||\n\n",meta:"",tags:["durga","kannada devotional song"],media:"https://www.youtube.com/watch?v=TigFofP5ZWc"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ವರವ-ಕೊಡೆ-ಚಾಮುಂಡಿ.json",
	rawData: "",
};

export { _internal, collection, data, id };
