const id = "ವಾರಿಜನಯಪತೆ-ವಾರಿಜನಾಭನೆ";
const collection = "bhajan";
const data = {kannada_title:"ವಾರಿಜನಯಪತೆ ವಾರಿಜನಾಭನೆ",english_title:"Varijalayapate varijanabhane",kannada:"ವಾರಿಜಲಯಪತೆ ವಾರಿಜನಾಭನೆ\nವಾರಿಜಭವಪಿತ ವಾರಿಜನೇತ್ರನೆ\nವಾರಿಜಮಿತ್ರ ಅಪಾರಪ್ರ ಭಾವನೆ\nವಾರಿಜ ಝಾಂಡದ ಕಾರಣ ದೊರೆಯೆ\nಬಾರೈಯ್ಯ ಬಾ ಬಾ ಭಕುತರ ಪ್ರಿಯ ಶ್ರೀನಿವಾಸ ರಾಯ ||ಪ||\n\nಮಾರ ಜನಕ ಮುಕುತರೋಡೆಯ ದೇವೈಯ್ಯ ಜೀಯ ಶ್ರೀನಿವಾಸ ರಾಯ ||ಅಪ||\n\nಸ್ಯಂದನವೇರಿಬಪ್ಪ ರಂಗ ದೇವೋತ್ತುಂಗ\nನಂದ ನಂದನ ಅರಿಮದ ಭಂಗ ಕರೂಣಾ ಪಾಂಗ\nಸಿಂಧು ಶಯನ ಸುಂದರಾಂಗ ಹೇ ನಾರಸಿಂಹ\nಕಂದ ವಿರಿಂಚಿಯು ನಂದಿವಾಹನ ಅಮರೇಂದ್ರ\nಸನಕನ ಸನಂದನಾದಿ ಮುನಿ\nವೃಂದ ಬಂದು ನಿಂದು ಧಿಂ ಧಿಂ ಧಿಮಿಕೆಂದು\nನಿಂದಾಡಲು ಆನಂದದಿ ಮನಕೆ ||೧||\n\nಜಗತ್ ಜನ್ಮಾದಿ ಕರ್ತ ಗೋವಿಂದ ಉದರದಿ ಲೋಕವ\nಲಘುವಾಗಿ ಧರಿಸಿದ ಮುಕುಂದ ಭಕ್ತರ ಮನಕೆ\nಝಗ ಝಗಿಸುವ ಪೊಳೆವಾನಂದ ನಿಗಮಾವಳಿಯಿಂದ\nಅಗಣಿತ ಮುನಿಗಣ ನಗ ಖಗ ಮೃಗ ಶಶಿ\nಗಗನ ಮಣ್ಯಾದ್ಯರು ಸೊಗಸಾಗಿ ಬಗೆ ಬಗೆ\nಪೊಗಳುತಲಿ ಬೇಗ ಜಿಗಿಜಿಗಿದಾಡಲು\nಮುಗುಳುನಗೆಯು ಮಹೋ ಉರಗಗಿರಿವಾಸ ||೨||\n\nತಡಮಾಡ ಬ್ಯಾಡವೊ ಹೇ ನಲ್ಲ ವಾಕು ಲಾಲಿಸು ಎನ್ನೊಡೆಯ\nಗೋಪಾಲ ವಿಠ್ಠಲ ದೇವ ಪರಾಖು\nಅಡಿ ಇಡು ಭಕ್ತವತ್ಸಲ ಶ್ರೀ ಲಕುಮಿನಲ್ಲ\nಮಡುವಿನೊಳಗೆ ಗಜ ಮೊರೆಯಿಡಲಾಕ್ಷನೆ\nಮಡದಿಗೆ ಹೇಳದೆ ದುಡುದುಡುನೆ ಬಂದು\nಹಿಡಿದು ನಕ್ರನ ಬಾಯ ಕಡಿದು ಬಿಡಿಸಿದನೆ\nಸಡಗರದಲಿ ರಮೆಪೊಡವಿಲೊಡಗೂಡಿ ಬೇಗ ||೩||\n\n",english:"Varijalayapati varijanabhane\nvarijabhavapita varijanetrane\nvarijamitra aparaprabhavane\nvarija jhandada karana doreye ||pa||\n\nBaraiyya ba ba bakutara priya Srinivasa raya |\nmara janaka mukutharodeya devaiyya jiya baraiyya ba ba ba ba ba||\n\nSyandana veribappa ranga devotunga\nnandanadanarimada bhanga karuna panga |\nsindhu shayana sundaranga he Narasingha|\nkanda virinchiyu nandivahana amarendra|\nsanakana sanandanadi munivrindanidu|\nbandu nindu dim dim dimikendu\nnindadalu Anadadi manake||\n\nBaraiyya ba ba ba ba ba ba ba ba ba bakutara priya Srinivasa raya ||\n\nJagat janmmadi karta govinda udaradi lokava|\nlaguvagi darisida mukunda bhaktara manake|\njaga jagaisuta polevananda nigamavaliyinda||\n\nAganita munigalu naga kaga mriga shashi|\ngagana manyAdyaru sogasagi bhage bhage|\npogalutali bega chigichigidadalu|\nmugulunageyu maha uragagirivasa||\n\nBaraiyya ba ba ba ba ba bakutara priya Srinivasa raya||\n\nTadamada byadavo he nalla vaku lalisuennodeya|\nGopala vittalaa deva paraku\nadi idu bhaktavatsala shri lakuminalla|\nmaduvinolage gaja moreyidalakshane\nmadadige hellade dudududune bandu\nhididu nakrana baya kadidu bidisidane|\nsadagaradali ramepodaveyodagude||\n\nBaraiyya ba ba ba ba ba bakutara priya Srinivasa raya||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=xP5ujruQzBc"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ವಾರಿಜನಯಪತೆ-ವಾರಿಜನಾಭನೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
