const id = "ವಾರ-ಬಂತಮ್ಮ-ಗುರುವಾರ";
const collection = "bhajan";
const data = {kannada_title:"ವಾರ ಬಂತಮ್ಮ ಗುರುವಾರ",english_title:" Vaara bantamma guruvaara",kannada:"ಪೂಜ್ಯಾಯ ರಾಘವೇಂದ್ರಯ ಸತ್ಯ ಧರ್ಮರತಾಯಚ\nಭಜತಾಂ ಕಲ್ಪವೃಕ್ಷಾಯ ನಮತಾಂ ಕಾಮಧೇನವೇ ||\n\nಗುರುವಾರ ಬಂತಮ್ಮ ಗುರುರಾಯರ ನೆನೆಯಮ್ಮ\nಗುರುವಾರ ಬಂತಮ್ಮ ಗುರುರಾಯರ ನೆನೆಯಮ್ಮ\nಸ್ಮರಣೆ ಮಾತ್ರದಲಿ ಕ್ಲೇಶ ಕಳೆದು ಸದ್ಗತಿಯ ಕೊಡುವನಮ್ಮ\n\nವಾರ ಬಂತಮ್ಮ ಗುರುವಾರ ಬಂತಮ್ಮ\nರಾಯರ ನೆನೆಯಮ್ಮ ಗುರುರಾಯರ ನೆನೆಯಮ್ಮ\n\nಯೋಗಿ ಬರುವನಮ್ಮ ಶುಭ ಯೋಗ ಬರುವುದಮ್ಮ\nರಾಘವೇಂದ್ರ ಗುರುರಾಯ ಬಂದು ಭವ ರೋಗ ಕಳೆವನಮ್ಮ ||ವಾರ ಬಂತಮ್ಮ||\n\nಮನವ ತೊಳೆಯಿರಮ್ಮ ಭಕ್ತಿಯ ಮನೆಯ ಹಾಕಿರಮ್ಮ\nಧ್ಯಾನದಿಂದ ಕರೆದಾಗ ಬಂದು ಒಳಗಣ ಬೆರೆವನಮ್ಮ  ||ವಾರ ಬಂತಮ್ಮ||\n\nಕೋಪ ಅರಿಯನಮ್ಮ ಯಾರನು ದೂರ ತಳ್ಳನಮ್ಮ\nಪ್ರೀತಿ ಮಾತಿಗೆ ಸೋತು ಬರುವ ಮಗುವಂಥೆ ಕಾಣಿರಮ್ಮ ||ವಾರ ಬಂತಮ್ಮ||\n\nಹಿಂದೆ ಬರುವನಮ್ಮ ರಾಯರ ನೆರಳಿನಂತೆ ಹನುಮ\nಹನುಮನಿದ್ದೆಡೆ ರಾಮನಿದ್ದು ನಿಜ ಮುಕ್ತಿ ಕೊಡುವನಮ್ಮ ||ವಾರ ಬಂತಮ್ಮ||\n\n",english:"|Poojyaya Raaghavendraaya\nSathya Dharma Rathayacha\nBhajathaam Kalpavrukshyaa\nNamatham Kaamadhenave |\n\nGuruvaara Banthamma Guru Raayara Neneyamma\nGuruvaara Banthamma Guru Raayara Neneyamma\nSmarane Mathradali Klesha Kaledu Sadgathiya Koduvanamma\nVaara Banthamma Guruvara Banthamma\n\nYogi Baruvanamma Shubhayoga Baruvudamma\nYogi Baruvanamma Shubhayoga Baruvudamma\nRaghavendra Gururaaya Bandu Bhavaroga Kalevanamma\nVaara Banthamma Guruvara Banthamma\n\nManava Tholeyiramma Bhakthiya Maneya Haakiramma\nManava Tholeyiramma Bhakthiya Maneya Haakiramma\nDhyanadinda Karedaaga Bandu Olaganna Berevanamma\nVaara Banthamma Guruvara Banthamma\n\nKopa Ariyanamma Yaranu Doora Thallanamma\nKopa Ariyanamma Yaranu Doora Thallanamma\nPrethi Maathige Sothu Baruva Maguvanthe Kaaniramma\nVaara Banthamma Guruvara Banthamma\n\nHinde Baruvanamma Raayara Neralinanthe Hanuma\nHanumaniddede Raamaniddu Nija Mukthi Koduvanamma\nVaara Banthamma Guruvara Banthamma\n\nGuruvaara Banthamma Guru Raayara Neneyamma\nGuruvaara Banthamma Guru Raayara Neneyamma\nSmarane Mathradali Klesha Kaledu Sadgathiya Koduvanamma\nVaara Banthamma Guruvara Banthamma ….\n\nClick the link to listen song\n\n",meta:"",tags:["raghavendra","kannada devotional song"],media:"https://www.youtube.com/watch?v=6gQ7PpVDGkI"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ವಾರ-ಬಂತಮ್ಮ-ಗುರುವಾರ.json",
	rawData: "",
};

export { _internal, collection, data, id };
