const id = "ವಾಮದೇವ-ವಿರಂಚಿತನಯ";
const collection = "bhajan";
const data = {kannada_title:"ವಾಮದೇವ ವಿರಂಚಿತನಯ",english_title:"Vasudeva viranchintanayaVasudeva",kannada:"ವಾಮದೇವ ವಿರಂಚಿತನಯ ಉಮಾಮನೋಹರ ಉಘ್ರದುರ್ಜಟಿ | ಸಾಮಜಾಜಿನ ವಸನ ಭೂಷಣ\nಸುಮನ ಸೂಪ್ತಂಸಾ |ಕಾಮಹರ ಕೈಲಾಸ ಮಂದಿರ ಸೋಮಸೂರ್ಯ ನಳ ವಿಲೋಚನ |\nಕಾಮಿತಪ್ರದ ಕರುಣಿಸೆಮಗೆ ಸದಾ ಸುಮಂಗಳವಾ….ಆಆ.. |  ಸದಾ ಸುಮಂಗಳವಾ. … ಸದಾ ಸುಮಂಗಳವಾ. …\n\nಅಂಭರಪುರ ಹರ ಶಂಭ ತ್ರಿಯಂಬಕ ಶಂಭಾರಾರಿ ರಿಪು ಗಂಭೀರ ಕರುಣೆ | ಶಂಭೋ ಸ್ವಯಂಭೋ ಸಂಭವಾ ಆ…ಆ…| ನಂಬಿದೆ ಕಾಯೋ ಜಂಭಾರಿನುತ ಭವಾ |\n\nಹಸಿತ ಭೂಷಿತ ಶರೀರ ಭಕ್ತರುಧ್ಧಾರ ವಿಷಕಂಠ ದುರಿತ ಹರ |\nಪಶುಪತಿ ಫಣಿಪಹಾರ ಪಾವನಕಾರ ತ್ರಿಶೂಲ ಢಮರುಗಧರ |\nವಸನಲಯನ ವಿಕಸಿತಾಂಭುಜಮುಖ ಶಶಿಧರ ಮಕರಕ್ಕಸ ಮದಮರ್ದನ | ಗಸನೆಗೊಳಿಪ ತಾಮಸವ ಕಳೆದು ಮಾನಸದಲಿ ರಂಗನ ಬಿಸಜ ಪದವ ತೋರೊ ||\nಶಂಭೋ ಸ್ವಯಂಭೋ ಸಂಭವಾ ನಂಬಿದ ಕಾಯೊ ಜಂಭಾರಿನುತ ಭವಾ. .. ಜಂಭಾರಿನುತ ಭವಾ. …\n\nರಜತ ಪರ್ವತ ನಿವಾಸ …ಆಆಆ..…  ರಜತ ಪರ್ವತ ನಿವಾಸ ನಿರ್ಮಲ ಭಾಸ | ಗಜದೈತ ನಾಶ ಗಿರೀಶ | ಸುಜನರ ಮನೋವಿಲಾಸ ವ್ಯೋಮಕೇಶ | ತ್ರಿಜಗ ತಲ್ಲಣ ಗೌರೀಶ ಅಜಸುತನದ್ವಾರ ಭಜನೆಯ ಕೆಡಿಸಿದೆ | ಅಜಗರ ಮಂದಿರ ಗಜಮುಖ ಜನಕನೆ | ಗಜಗಮನೆ ಮುನಿ ತನುಜನ ಕಾಯ್ದನೆ ಸ್ರಜಮುನಿ ವಂದಿತ ಭಜಿಸುವೆ ನಿನ್ನನು ||\nಶಂಭೋ ಸ್ವಯಂಭೋ ಸಂಭವಾ ನಂಬಿದೆ ಕಾಯೋ ಜಂಭಾರಿನುತ ಭವಾ….  ಜಂಭಾರಿನುತ ಭವಾ. …\n\nಮಧುರಾಪುರಿ ನಿಲಯ….ಆ….ಆ…ಆ… ಮಧುರಾಪುರಿ ನಿಲಯ  ಮ್ರತ್ಯುಂಜಯ | ಸದಮಲ ಸುಮನಗೆಯ | ಸದಾನಮಿಪರ ಹ್ರದಯ ದೊಳಗುಲ್ಲ | ಭಯ ಸದೆಯುತ್ತ ಕೊಡು ಅಭಯ ಸದಾಶಿವ ಜಾಹ್ನವಿ ಧರಕ್ರತ ಮಾಲ\nನದಿತೀರದಿ ವಾಸವಾಗಿರ್ಪ ಸೌಂದರ್ಯ | ಮಧುರಿಪು ವಿಜಯವಿಠ್ಠಲನ ಪಾದಾಭ್ಜಕೆ ಮಧುಪನೆಂಬ ಪಂಚ ವದನ ಕೈಲಾಸದ ||\nಶಂಭೋ ಸ್ವಯಂಭೋ ಸಂಭವಾ ನಂಬಿದೆ ಕಾಯೋ ಜಂಭಾರಿನುತ ಭವಾ. …. ಜಂಭಾರಿನುತ ಭವಾ. .. |\n\nಶಂಭೋ ಸ್ವಯಂಭೋ ಸಂಭವಾ. .. ಶಂಭೋ ಸ್ವಯಂಭೋ ಸಂಭವಾ… ಶಂಭೋ ಸ್ವಯಂಭೋ ಸಂಭವಾ….\n\n",english:"Shambho swayambho sambhava nambide kayo jambharinuta bhava ….. Jambharinuta ….\n\nVasudeva viranchintanaya umamanohara ughradurjati | samajaajina vasanabhushana sumana suptansaa |kamahara kailasa mandira somasurya nala vilochana | kamitaprada karunisemage sada sumangalava … sada sumangalava …… sada sumangalava …..\n\nAmbharapura hara shambha triyambaka shambharari ripu gambhira karune | shambho swayambho sambhava ..a… a…. | nambide kayo jambharinuta bhava ||\n\nHasita bhushita sharira bhaktaruddhara vishakanta durita hara |pashupati phanipahara pavanakara trishula dhamarugadhara | vasanalayana vikasitaambhujamukha shashidhara makarakkasa madamardhana | gasanegolipa tamasava kaledu manasadali rangana bisaja padava toro | shambho swayambho sambhava nambida kayo jambharinuta bhava …. jambharinuta bhava ….\n\nRajata parvata nivasa … a…. a ….. rajata parvata nivasa, nirmalabhasa, gajadaita nasha girisha | sujanara manovilasa vyomakesha trijaga tallana gowrisha, ajasutanadwara bhajaneya kediside ajagara mandira gajamukha janakane | gajagamane muni tanujana kaydane srujamuni vandita bhajisuve ninnanu | shambho swayambho sambhava nambide kayo jambharinuta bhava ….. Jambharinuta ….\n\nMadhurapuri nilaya ….. A….. A…….a…… madhurapuri nilaya mrutyunjaya sadamala sumanageya | sadanamipara hrudayadolagulla | bhaya sadeyutta kodu abhaya sadashiva jahnavi dharakrutamala | naditeeradi vasavagirpa soundarya | madhuripu vijayavittalana padabjake madhupanemba pancha vadana kailasada | shambho swayambho sambhava nambide kayo jambharinuta bhava ….. Jambharinuta ….\n\n",meta:"",tags:["kannada devotional song"],media:""};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ವಾಮದೇವ-ವಿರಂಚಿತನಯ.json",
	rawData: "",
};

export { _internal, collection, data, id };
