const id = "ವಂದೇ-ವಂದ್ಯಂ-ಸದಾನಂದಂ";
const collection = "bhajan";
const data = {kannada_title:"ವಂದೇ ವಂದ್ಯಂ ಸದಾನಂದಂ",english_title:" Vande vandyam sadanandam",kannada:"ವಂದೇ ವಂದ್ಯಂ ಸದಾನಂದಂ ವಾಸುದೇವಂ ನಿರಂಜನಂ ಇಂದಿರಾಪತಿಮಾದ್ಯಾದಿ ವರದೇಶ ವರಪ್ರದಮ್ || ೧||\n\nನಮಾಮಿ ನಿಖಿಲಾಧೀಶ ಕಿರೀಟಾಘೃಷ್ಟಪೀಠವತ್ |ಹೃತ್ತಮಃ ಶಮನೇsರ್ಕಾಭಂ ಶ್ರೀಪತೇಃ ಪಾದಪಂಕಜಮ್    || ೨ ||\n\nಜಾಂಬೂನದಾಂಬರಾಧಾರಂ ನಿತಂಬಂ ಚಿಂತ್ಯಮೀಶಿತುಃಸ್ವರ್ಣಮಂಜೀರಸಂವೀತಂ ಆರೂಢಂ ಜಗದಂಬಯಾ || ೩ ||\n\nಉದರಂ ಚಿಂತ್ಯಂ ಈಶಸ್ಯ ತನುತ್ವೇsಪಿ ಅಖಿಲಂಬರಮ್ವಲಿತ್ರಯಾಂಕಿತಂ ನಿತ್ಯಂ ಆರೂಢಂ ಶ್ರಿಯೈಕಯಾ || ೪ ||\n\nಸ್ಮರಣೀಯಮುರೋ ವಿಷ್ಣೋಃ ಇಂದಿರಾವಾಸಮುತ್ತಮಮ್ ಅನಂತಂ ಅಂತವದಿವ ಭುಜಯೋರಂತರಂಗತಮ್   || ೫ ||\n\nಶಂಖಚಕ್ರಗದಾಪದ್ಮ ಧರಾಶ್ಚಿಂತ್ಯಾ ಹರೇರ್ಭುಜಾಃ |ಪೀನವೃತ್ತಾ ಜಗದ್ರಕ್ಷಾ ಕೇವಲೋದ್ಯೋಗಿನೋsನಿಶಮ್  || ೬ ||\n\nಸಂತತಂ ಚಿಂತಯೇತ್ಕಂಠಂ ಭಾಸ್ವತ್ಕೌಸ್ತುಭಭಾಸಕಮ್ವೈಕುಂಠಸ್ಯಾಖಿಲಾ ವೇದಾ ಉದ್ಗೀರ್ಯಂತೇsನಿಶಂ ಯತಃ     || ೭ ||\n\nಸ್ಮರೇತ ಯಾಮಿನೀನಾಥ ಸಹಸ್ರಾಮಿತ ಕಾಂತಿಮತ್ |ಭವತಾಪಾಪನೋದೀಡ್ಯಂ ಶ್ರೀಪತೇಃ ಮುಖಪಂಕಜಮ್    || ೮ ||\n\nಪೂರ್ಣಾನನ್ಯಸುಖೋದ್ಭಾಸಿಂ ಅಂದಸ್ಮಿತಮಧೀಶಿತುಃ |ಗೋವಿಂದಸ್ಯ ಸದಾ ಚಿಂತ್ಯಂ ನಿತ್ಯಾನಂದಪದಪ್ರದಮ್         || ೯ ||\n\nಸ್ಮರಾಮಿ ಭವಸಂತಾಪ ಹಾನಿದಾಮೃತಸಾಗರಮ್ಪೂರ್ಣಾನಂದಸ್ಯ ರಾಮಸ್ಯ ಸಾನುರಾಗಾವಲೋಕನಮ್     || ೧೦ ||\n\nಧ್ಯಾಯೇದಜಸ್ರಮೀಶಸ್ಯ ಪದ್ಮಜಾದಿಪ್ರತೀಕ್ಷಿತಮ್ |ಭ್ರೂಭಂಗಂ ಪಾರಮೇಷ್ಠಯಾದಿ ಪದದಾಯಿ ವಿಮುಕ್ತಿದಮ್      || ೧೧ ||\n\nಸಂತತಂ ಚಿಂತಯೇsನಂತಂ ಅಂತಕಾಲೇ ವಿಶೇಷತಃನೈವೋದಾಪುಃ ಗೃಣಂತೋಂತಂ ಯದ್ಗುಣಾನಾಂ ಅಜಾದಯಃ  || ೧೨ ||\n\nಇತಿ ಶ್ರೀಮದಾನಂದತೀರ್ಥ ಭಗವತ್ಪಾದಾಚಾರ್ಯ ವಿರಚಿತ ದ್ವಾದಶ ಸ್ತೋತ್ರೇಷು ಪ್ರಥಮ ಸ್ತೋತ್ರಂ ಸಂಪೂರ್ಣಮ್\n\n",english:"Vande vandyam sadanandam vasudevam nirajanam |\nindirapatimadyadi varadesha varapradam || 1||\n\nNamami nikhiladhisha kiritaghrishhtapithavath |\nhrittamah shamanearkabham shripateh paadapankajam || 2||\n\nJambunadambaradharam nitambam chintyamishituh |\nsvarnamaJnjirasamvitam arudham jagadambaya || 3||\n\nUdaram chintyam ishasya tanutveapi akhilambharam |\nvalitrayankitam nityam arudham shriyaikaya || 4||\n\nSmaraniyamuro vishhnoh indiravasamuttamaih |\nanantam antavadiva bhujayorantarangatamh || 5||\n\nShankhachakragadapadmadharashch-intya harerbhujah |\npinavritta jagadraksha kevalodyoginonishamh || 6||\n\nSantatam chintayetkantham bhasvatkaustubhabhasakamh |\nvaikunthasyakhila veda udgiryanteanisham yatah || 7||\n\nSmareta yamininatha sahasramitakantimath |\nbhavatapapanodidhyam shripateh mukhapankajamh || 8||\n\nPurnananyasukhodbhasim andasmitamadhishituh |\ngovindasya sada chintyam nityanandapadapradamh || 9||\n\nSmarami bhavasantapa hanidamritasagaramh |\npurnanandasya ramasya sanuragavalokanamh || 10||\n\nDhyayedajasramishasya padmajadipratixitamh |\nbhrubhangam parameshhthhyadi padadayi vimuktidamh || 11||\n\nSantatam chintayeanantam antakale visheshhatah |\nnaivodapuh grinantoantam yadgunanam ajadayah || 12||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=kbs26gRbZyw"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ವಂದೇ-ವಂದ್ಯಂ-ಸದಾನಂದಂ.json",
	rawData: "",
};

export { _internal, collection, data, id };
