const id = "ವೃಂದಾವನವೆ-ಮಂದಿರವಾಗಿದೆ";
const collection = "bhajan";
const data = {kannada_title:"ವೃಂದಾವನವೆ ಮಂದಿರವಾಗಿದೆ",english_title:" Vrundaavanave mandiravaagide",kannada:"ದಯೆ ತೋರಮ್ಮ ಶ್ರೀ ತುಳಸಿ ವರನೀಡಮ್ಮ ಶ್ರೀ ತುಳಸಿ\nದಯಮಾಡಮ್ಮ ಶ್ರೀ ತುಳಸಿ ನಿತ್ಯವು ಪೂಜಿಪೆ ವರ ತುಳಸಿ\nಇಂದಿರೆ ಸುಂದರಿ ವಂದಿಪೆ ಮಾಧವಿ ಶುಭವನು ಮಾಡೆ ಜಯ ತುಳಸಿ ||ಇಂದಿರೆ||\n\nವೃಂದಾವನವೆ ಮಂದಿರವಾಗಿದೆ ನಿಂದಿರೆ ಶ್ರೀತುಳಸಿ||ವ್ರಂದಾವನವೇ|| ನಂದನಂದನ ಮುಕುಂದಗೆ ಪ್ರಿಯಳಾದ ||2|| ಚೆಂದದ ಶ್ರೀ ತುಳಸೀ…. || ವೃಂದಾವನವೆ||\n\nತುಳಸಿಯ ವನದಲಿ ಹರಿ ಇಹನೆಂಬುದ ಶ್ರತಿಸಾರುತಿದೆ ಕೇಳಿ\nತುಳಸಿ ದರ್ಶನದಿಂದ ದುರಿತಗಳೆಲ್ಲವು ದೂರವಾಗುವುದು ಕೇಳಿ|\nತುಳಸಿ ಸ್ಪರ್ಶವ ಮಾಡೆ,ದೇಹ ಪಾವನವೆಂದು |\nತಿಳಿದುದಿಲ್ಲವೆ ಕೇಳಿ ತುಳಸಿ ಸ್ಮರಣೆ ಮಾಡಿ ,ಸಕಲ ಇಷ್ಟವ ಪಡೆದು | ಸುಖದಲಿ ನೀವು ಬಾಳಿ ||ವೃಂದಾವನವೆ||\n\nಮೂಲ ಮ್ರತ್ತಿಕೆಯನು ಮುಖದಲಿ ಧರಿಸಲು ಮೂರ್ಲೋಕ ವಶವಹುದು\nಮಾಲೆ ಕೊರಳಲಿಟ್ಟ ,ಮುನುಜಗೆ ಮುಕುತಿಯ ಮಾರ್ಗವ ತೋರುವುದು |\nಕಾಲ ಕಾಲಗಳಲಿ ,ಮಾಡುವ ದುಷ್ಕರ್ಮ | ಕಳೆದು ಬಿಸಾಡುವುದು\nಕಾಲನ ದೂತರ ಕಳಚಿ ಕೈವಲ್ಯದ | ಲೀಲೆಯ ತೋರುವುದು\n||ವೃಂದಾವನವೆ||\n\nಧರೆಯೊಳು ಸುಜನರ ಮರೆಯದೆ ಸಲಹುವ ,ವರಲಕ್ಷ್ಮಿ ಶ್ರೀ ತುಳಸಿ\nಪರಮ ಭಕ್ತರ ಘೋರ ಪಾಪಗಳ ತರಿದು ಪಾವನ ಮಾಡುವ ತುಳಸಿ |\nಸಿರಿ, ಆಯು, ಪುತ್ರಾದಿ ಸಂಪದಗಳನ್ನಿತ್ತು| ಹರುಷಗೊಳಿಪ ತುಳಸೀ…\nಪುರಂದರವಿಠ್ಠಲನ ಚರಣ ಕಮಲಗಳ | ಪುರಂದರವಿಠ್ಠಲನಾ……ಆ…ಆ… |\nಪುರಂದರವಿಠ್ಠಲನ ಚರಣ ಕಮಲಗಳ | ಸ್ಮರಣೆ ಕೊಡುವ ತುಳಸಿ\n||ವೃಂದಾವನವೆ||\n\n",english:"Daye toramma sri tulasi vara needamma sri tulasi daya maadamma, sri  tulasi nityavu poojipe vara tulasi indire sundari vandipe madhavi shubhavanu maade jaya tulasi || indire ||\n\nVrundaavanave mandiravaagide nindire sri tulasi ||vrundaavanave || nandanandana mukundage priyalaada chendada sri tulasi ||vrundaavanave ||\n\nTulasiya vanadali hari ehanembudu shruti saarutide keli | tulasi darshanadinda duritagalellavu dooravaaguvudu keli | tulasi sparshava maade deha paavanavendu || tilidudillave keli tulasi smarane maadi, sakala eshtava padedu | sukhadali neevu baali || vrundaavanave ||\n\nMoola mruttikeyanu mukhadali dharisalu moorloka vashavahudu | maale koralalitta manujage mukutiya maargava toruvudu | kaala kaalagalali maaduva dushkarma | kaledu bisaaduvudu kaalana dootara kalachi kaivalyada | leeleya toruvudu || vrundaavanave ||\n\nDhareyolu sujanara mareyade salahuva varalakshmi sri tulasi | parama bhaktara ghora paapagala taridu paavana maaduva tulasi | siri, aayu putraadi sampadagalannittu | harushagolipa tulasi …. | purandara vittalana charana kamalagala | purandara vittalanaa …. a….. a…. | purandara vittalana charana kamalagala | smarane koduva tulasi | vrundaavanave ||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=vPdn0l2QDAU"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ವೃಂದಾವನವೆ-ಮಂದಿರವಾಗಿದೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
