const id = "ವಿಠ್ಠಲ-ಪಾಂಡುರಂಗ";
const collection = "bhajan";
const data = {kannada_title:"ವಿಠ್ಠಲ ಪಾಂಡುರಂಗ",english_title:" vittala panduranga",kannada:"ವಿಠ್ಠಲ ಪಾಂಡುರಂಗ  ||\n\nಶಂಖಚಕ್ರಧರ ವೈಜಯಂತಿಧರ\nಪೀತಾಂಬರಧರ ಗೋವರ್ಧನೋದ್ಧರ\nತುಲಸಿ ಮಾಲಾ ಶೋಭಿತ ಗಳಲಾ\nಗರುಡ ಗಮನ ಹರಿ ಪಂಕಜನಾಭಾ\nಹೊ ವಿಠಲಾ ಯೇರೆ ಪಂಢರಿರಾಯ ವಿಠಲಾ ಯೇರೆ ಪಂಢರಿರಾಯ\nವಿಠಲ ಪಾಂಡುರಂಗ ವಿಠಲ ಪಾಂಡುರಂಗ\nವಿಠಲ ಪಾಂಡುರಂಗ ವಿಠಲ ಪಾಂಡುರಂಗ\n\nಮಸ್ತಕ ಲಿಂಗ ಸ್ವರೂಪ ಲಿಂಗ\nರೂಪ ಬಂಗ ಸಜ್ಜನ ಸಂಗ\nಯದುಕುಲ ತಿಲಕ ಮನ್ಮಥ ಜನಕ\nಪತಿತ ಪಾವನ ದೀನ ದಯಾಳಾ\nಹೊ ವಿಠಲಾ ಯೇರೆ ಪಂಢರಿರಾಯ ವಿಠಲಾ ಯೇರೆ ಪಂಢರಿರಾಯ\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಜೈಜೈ ವಿಠ್ಠಲ ||2||\nವಿಠ್ಠಲ ವಿಠ್ಠಲ ಶ್ರೀಹರಿ ವಿಠ್ಠಲ ||2||\n\nತ್ರಿಭುವನ ರೂಪ ವಿಶ್ವಸ್ವರೂಪ\nಭವಭಯ ತಾಪ ಹರತಿ ಪಾಪ\nರುಕ್ಮಿಣಿ ಕಾಂತ ರೂಪ ಅನಂತಾ\nಜನನಿ ಜನಕ ತುಝ ಮಾವಕಲೇನ\nಹೊ ವಿಠಲಾ ಯೇರೆ ಪಂಢರಿರಾಯ ವಿಠಲಾ ಯೇರೆ ಪಂಢರಿರಾಯ\nವಿಠಲ ಪಾಂಡುರಂಗ ವಿಠಲ ಪಾಂಡುರಂಗ\nವಿಠಲ ಪಾಂಡುರಂಗ ವಿಠಲ ಪಾಂಡುರಂಗ\n\nಚಂದ್ರಭಾಗೆ ತೀರಿ ಉಭಾವಿಠೇವರಿ\nಕರಕಟಾವರಿ ರಂಗ ಶಿಲೆವರಿ\nಜಗದೋದ್ಧಾರಾ ವೇದೋದ್ಧಾರ\nಭಕ್ತಸಾಗರ ಪಂಢರಪುರಾ\nಹೊ ವಿಠಲಾ ಯೇರೆ ಪಂಢರಿರಾಯ ವಿಠಲಾ ಯೇರೆ ಪಂಢರಿರಾಯ\nವಿಠಲ ಪಾಂಡುರಂಗ ವಿಠಲ ಪಾಂಡುರಂಗ\nವಿಠಲ ಪಾಂಡುರಂಗ ವಿಠಲ ಪಾಂಡುರಂಗ\n\n",english:"Vittala panduranga ||\n\nShankhachakradhara vaijayanti dhara\npitambharadhara govardhanoddhara\ntulasimale shobhitagala\ngarudagamana hari pankajanabha\nho vittalayere pandariraya vittala yere pandariraya ||vittala||\n\nMastakalinga swaroopa linga\nroopabhanga sajjana Sangha\nyadukula tilaka manmatajanaka\npatitapavana deenadayalu\nvittalayere pandariraya vittala yere pandariraya ||vittala||\nvittala vittala jaijai vittala\nvittala vittala srihari vittala\n\nTribhuvana roopa vishwa swaroopa\nbhavabhaya tapa harisi papa\nrukmini kanta roopa ananta\njanani janaka tuja màvakalena\nvittalayere pandariraya vittala yere pandariraya ||\nVittala vittala jai jai vittala\nvittala vittala sri hari vittala\n\nChandrabhage teeri ubhavitevari\nkarakataavari ranga shilevari\njagadodhaara vedoddhara\nbhaktasagara pandarapura\nho vittala yere pandariraya vittala yere pandariraya||\nvittala panduranga vittala panduranga\nvittala panduranga vittala panduranga\n\nhttps://youtu.be/8djSxyebyWE\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:""};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ವಿಠ್ಠಲ-ಪಾಂಡುರಂಗ.json",
	rawData: "",
};

export { _internal, collection, data, id };
