const id = "ಶರಣು-ಮೃತ್ಯುಂಜಯ-ಶರಣ್ಯ";
const collection = "bhajan";
const data = {kannada_title:"ಶರಣು ಮೃತ್ಯುಂಜಯ ಶರಣ್ಯ",english_title:" Sharanu mrutyunjaya sharanya",kannada:"ರಚನೆ : ಶ್ರೀ ಜಗನ್ನಾಥ ದಾಸರು\n\nಶರಣು ಮೃತ್ಯುಂಜಯ ಶರಣ್ಯ ಸಜ್ಜನರ ಭಯ |\nಪರಿಹರಿಪೆ ಕರುಣಾಳು ಬಿನ್ನಪವ ಕೇಳು || ಪ ||\n\nವಾಸವಾದ್ಯಮರನುತ ವನಜ ಸಂಭವನ ಸುತ |\nನೀ ಸಲಹು ಕೈಲಾಸವಾಸ ಈಶ |\nಕ್ಲೇಶ ಮೋದಗಳು ಸಮಾ ತಿಳಿಸೊ ಅಶ್ವತ್ಥಾಮ |\nಶ್ರೀ ಶುಕನೆ ದುರ್ವಾಸ ಸ್ಫಟಿಕ ಸಮಭಾಸಾ || 1 ||\n\nವೈಕಾರಿಕಾದಿತ್ಯರೂಪ ನಿನ್ನಯ ಕೋಪ |\nಶೋಕ ಕೊಡುವದು ದೈತ್ಯಜನಕೆ ನಿತ್ಯಾ |\nಲೌಕಿಕಗಳೆಲ್ಲ ವೈದಿಕವಾಗಲ್ಯೆನಗೆ\nಮೈನಾಕಿ ಹೃತ್ಕುಮುದೇಂದು ಭಕ್ತಜನ ಬಂಧು || 2 ||\n\nಪವಮಾನತನಯ ನಿನ್ನವರಲ್ಲಿ ಕೊಡು ವಿನಯ |\nದಿವಸ ಸವನಗಳಲ್ಲಿ ಎನ್ನಿರವ ಬಲ್ಲಿ |\nಸವನ ದ್ವಿತೀಯ ರೂಪ ಸತತ ಎನ್ನಯ ಪಾಪ |\nಅವಲೋಕಿಸದಲೆ ಎನ್ನ ಸಲಹೊ ಸುರಮಾನ್ಯ || 3 ||\n\nಶೇಷನಂದನ ಶೇಷಭೂಷಣ ನಿಶ್ಶೇಷ |\nದೋಷರಹಿತನ ತೋರೊ ಕರುಣವನೆ ಬೀರೊ |\nಶ್ರೀ ಷಣ್ಮುಖನ ತಂದೆ ಸತತ ನೀ ಗತಿಯೆಂಬೆ |\nಶೋಷಿಸೋ ಭವಾಮಯವ ಬೇಡುವೆನೊ ದಯವ || 4 ||\n\nಗರ್ಗಮುನಿ ಕರಕಮಲ ಪೂಜ್ಯ ಚರಣಾಬ್ಜ ಮಮ |\nದುರ್ಗುಣಗಳೆಣಿಸದಲೆ ಜಗದಿ ಮ್ಯಾಲೆ|\nನಿರ್ಗತಾಶನ\nಜಗನ್ನಾಥವಿಟ್ಠಲ\nನ\nಸನ್ಮಾರ್ಗವನೆ ತೋರು ಈ ದೇಹ ನಿನತೇರು || 5 ||\n\n",english:"Composer : Sri Jagannatha dasaru\n\nSharanu mrutyunjaya sharanya sajjanara bhaya |\npariharipe karunaalu binnapava kelu ||pa||\n\nVaasavadyamaranuta vanaja sambhavana suta |\nnee salahu kailasavaasa eesha |\nklesha modagalu samaa tiliso ashwatthama |\nsri shukane durvaasa spatika samabhaasa || 1||\n\nVaikaarikaaditya roopa ninnaya kopa |\nshoka koduvadu daityajanake nitya |\nloukikagalella vaidikavaagalyanage |\nmainaaki hrutyumudendu bhaktajana bandhu |\n\nPavamaana tanaya ninnavaralli kodu vinaya |\ndivasa savanagalalli ennirava balli |\nsavana dwiteeya roopa satata ennaya paapa |\navalokisadale enna salaho suramaanya ||3||\n\nSheshananadana sheshabhushana nisheysha |\ndosharahitana toro karunavane beero |\nsri shanmukhana tande satata nee gatiyembe |\nshoshiso bhavaamayava beduveno dayava ||4||\n\nGargamuni karakamala poojya charanaabja mama |\ndurgunagalenisadale jagadi myaale |\nnirgataashana\njagannaata vittala\nna\nsanmargavane toro e deha ninateru ||5||\n\n",meta:"",tags:["shiva","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=46QNd6cf6Og"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶರಣು-ಮೃತ್ಯುಂಜಯ-ಶರಣ್ಯ.json",
	rawData: "",
};

export { _internal, collection, data, id };
