const id = "ಶ್ರೀ-ಮಹಾಲಕ್ಷ್ಮಿ-ಅಷ್ಟಕಮ್";
const collection = "bhajan";
const data = {kannada_title:"ಶ್ರೀ ಮಹಾಲಕ್ಷ್ಮಿ ಅಷ್ಟಕಮ್",english_title:"  SRI MAHALAKSHMI ASHTAKAM",kannada:"ನಮಸ್ತೇಸ್ತು ಮಹಾಮಾಯೇ ಶ್ರೀಪೀಠೇ ಸುರಪೂಜಿತೇ |\nಶಂಖಚಕ್ರ ಗದಾಹಸ್ತೇ ಮಹಾಲಕ್ಷ್ಮಿ ನಮೋಸ್ತುತೇ || 1 ||\n\nನಮಸ್ತೇ ಗರುಡಾರೂಢೇ ಕೋಲಾಸುರ ಭಯಂಕರಿ |\nಸರ್ವಪಾಪಹರೇ ದೇವಿ ಮಹಾಲಕ್ಷ್ಮಿ ನಮೋಸ್ತುತೇ || 2 ||\n\nಸರ್ವಜ್ಞೇ ಸರ್ವವರದೇ ಸರ್ವ ದುಷ್ಟ ಭಯಂಕರಿ |\nಸರ್ವದುಃಖ ಹರೇ ದೇವಿ ಮಹಾಲಕ್ಷ್ಮಿ ನಮೋಸ್ತುತೇ || 3 ||\n\nಸಿದ್ಧಿ ಬುದ್ಧಿ ಪ್ರದೇ ದೇವಿ ಭುಕ್ತಿ ಮುಕ್ತಿ ಪ್ರದಾಯಿನಿ |\nಮಂತ್ರ ಮೂರ್ತೇ ಸದಾ ದೇವಿ ಮಹಾಲಕ್ಷ್ಮಿ ನಮೋಸ್ತುತೇ || 4 ||\n\nಆದ್ಯಂತ ರಹಿತೇ ದೇವಿ ಆದಿಶಕ್ತಿ ಮಹೇಶ್ವರಿ |\nಯೋಗಜ್ಞೇ ಯೋಗ ಸಂಭೂತೇ ಮಹಾಲಕ್ಷ್ಮಿ ನಮೋಸ್ತುತೇ || 5 ||\n\nಸ್ಥೂಲ ಸೂಕ್ಷ್ಮ ಮಹಾರೌದ್ರೇ ಮಹಾಶಕ್ತಿ ಮಹೋದರೇ |\nಮಹಾ ಪಾಪ ಹರೇ ದೇವಿ ಮಹಾಲಕ್ಷ್ಮಿ ನಮೋಸ್ತುತೇ || 6 ||\n\nಪದ್ಮಾಸನ ಸ್ಥಿತೇ ದೇವಿ ಪರಬ್ರಹ್ಮ ಸ್ವರೂಪಿಣಿ |\nಪರಮೇಶಿ ಜಗನ್ಮಾತಃ ಮಹಾಲಕ್ಷ್ಮಿ ನಮೋಸ್ತುತೇ || 7 ||\n\nಶ್ವೇತಾಂಬರಧರೇ ದೇವಿ ನಾನಾಲಂಕಾರ ಭೂಷಿತೇ |\nಜಗಸ್ಥಿತೇ ಜಗನ್ಮಾತಃ ಮಹಾಲಕ್ಷ್ಮಿ ನಮೋಸ್ತುತೇ || 8 ||\n\nಮಹಾಲಕ್ಷ್ಮಷ್ಟಕಂ ಸ್ತೋತ್ರಂ ಯಃ ಪಠೇದ್ ಭಕ್ತಿಮಾನ್ ನರಃ |\nಸರ್ವ ಸಿದ್ಧಿ ಮವಾಪ್ನೋತಿ ರಾಜ್ಯಂ ಪ್ರಾಪ್ನೋತಿ ಸರ್ವದಾ || 9 ||\n\nಏಕಕಾಲೇ ಪಠೇನ್ನಿತ್ಯಂ ಮಹಾಪಾಪ ವಿನಾಶನಮ್ |\nದ್ವಿಕಾಲಂ ಯಃ ಪಠೇನ್ನಿತ್ಯಂ ಧನ ಧಾನ್ಯ ಸಮನ್ವಿತಃ || 10 ||\n\nತ್ರಿಕಾಲಂ ಯಃ ಪಠೇನ್ನಿತ್ಯಂ ಮಹಾಶತ್ರು ವಿನಾಶನಮ್ |\nಮಹಾಲಕ್ಷ್ಮೀರ್ಭವೇನ್-ನಿತ್ಯಂ ಪ್ರಸನ್ನಾ ವರದಾ ಶುಭಾ || 11 ||\n\n",english:"MAHALAKSHMI ASHTAKAM\n\nNamastestu Mahamaye\nShree Pithe Sura Poojite |\nShanka Chakra Gadha Haste\nMaha Lakshmi Namostute ||1||\n\nNamaste Garudarudhe\nKolasura Bhayankari |\nSarva Papa Hare Devi\nMaha Lakshmi Namostute ||2||\n\nSarvajne Sarva Varade\nSarva Dushta Bhayankari |\nSarva Duhkha Hare Devi\nMaha Lakshmi Namostute ||3||\n\nSiddhi Buddhi Prade Devi\nBhakti Mukti Pradayini\nMantra Moorte Sada Devi\nMaha Lakshmi Namostute ||4||\n\nAdyanta Rahite Devi\nAdi Shakti Maheshwari |\nYogaje Yoga Sambhute\nMaha Lakshmi Namostute ||5||\n\nSthula Sukshme Maha Raudre\nMaha Shakti Mahodari |\nMaha Papa Hare Devi\nMaha Lakshmi Namostute ||6||\n\nPadmasana Sthithe Devi\nParabrahma Swaroopini ||\nParameshi Jagan Mata\nMaha Lakshmi Namostute||7||\n\nShwetambara Dhare Devi\nNanalankara Shobhite|\nJagasthithe Jaganmata\nMaha Lakshmi Namoostute ||8||\n\nMaha Lakshmyashtakam Stotram\nYah Patheth Bhakti Man Narah\nSarva Siddhi Mavapnoti\nRajyam Prapnoti Sarvada ||9||\n\nEka Kalam Pathennityam\nMaha Papa Vinashanam\nDwikalam Yah Pathennityam\nDhana Dhanya Samanvitah ||10||\n\nTrikalam Yah Pathennityam\nMaha Shatru Vinashanam\nMaha Lakshmi Bhavennityam\nPrasanna Varada Shubhah||11||\n\nYoutube link\n:\nhttps://youtu.be/0L_hiErVcyE\nby Bombay sisters\n\n",meta:"",tags:["lakshmi","kannada devotional song","lakshmi stotra"],media:"https://www.youtube.com/watch?v=0L_hiErVcyE"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶ್ರೀ-ಮಹಾಲಕ್ಷ್ಮಿ-ಅಷ್ಟಕಮ್.json",
	rawData: "",
};

export { _internal, collection, data, id };
