const id = "ಶೇಷಾದ್ರಿವಾಸ-ಶ್ರೀ-ವೆಂಕಟೇಶ";
const collection = "bhajan";
const data = {kannada_title:"ಶೇಷಾದ್ರಿವಾಸ ಶ್ರೀ ವೆಂಕಟೇಶ",english_title:" Sheshaadrivaasa shri venkatesh",kannada:"ಹಾಡಿದವರು: ಎಸ್.ಪಿ. ಬಾಲಸುಬ್ರಹ್ಮಣ್ಯಂ\n\nಪ್ರಭುಜೀ.. ಬಾಲಾಜಿ..\nತಿರುಪತಿ ವಾಸ, ನಮೋ ಶ್ರೀನಿವಾಸ\nಪೊರೆಯೋ ಪಾಪ ವಿನಾಶ, ಶ್ರೀಶ\nಜಯ ಜಯ ಜಗದೀಶ ಜಯ ಗೋವಿಂದ\nಜಪಿಸಲು ನಿನ್ನ ನಾಮ ಪರಮಾನಂದ\nಅಂಜನಾದ್ರಿ ವಾಸ, ಆನಂದಾದ್ರಿ ವಾಸ\nಪೊರೆಯೋ ಪಾಪ ವಿನಾಶ, ಶ್ರೀಶ\nಜಯ ಜಯ ಜಗದೀಶ ಜಯ ಗೋವಿಂದ\nಜಪಿಸಲು ನಿನ್ನ ನಾಮ ಪರಮಾನಂದ\nಶೇಷಾದ್ರಿ ವಾಸ, ಗೋವಿಂದಾ ಗೋವಿಂದ\nಗರುಡಾದ್ರಿ ವಾಸ, ಗೋವಿಂದಾ ಗೋವಿಂದ\nಬಾಲಾಜಿ, ಗೋವಿಂದಾ ಗೋವಿಂದ, ಬಾಲಾಜಿ\n\nತಂದೆಯು ನೀನೆ, ತಾಯಿಯು ನೀನೆ\nನಂಬಿದ ಭಕುತರ ಬಂಧುವು ನೀನೆ\nತಂದೆಯು ನೀನೆ, ತಾಯಿಯು ನೀನೆ\nನಂಬಿದ ಭಕುತರ ಬಂಧುವು ನೀನೆ\nಸುಂದರ ನಯನ ಚಂದಿರ ವದನ\nಸಲಹೋ ವೆಂಕಟರಮಣ\nಸುಂದರ ನಯನ ಚಂದಿರ ವದನ\nಸಲಹೋ ವೆಂಕಟರಮಣ\nತೋರೋ ಪಾವನ ಚರಣ ಸ್ವಾಮೀ\n\nಜಯ ಜಯ ಜಗದೀಶ ಜಯ ಗೋವಿಂದ\nಜಪಿಸಲು ನಿನ್ನ ನಾಮ ಪರಮಾನಂದ\nನೀಲಾದ್ರಿ ವಾಸ, ಗೋವಿಂದಾ ಗೋವಿಂದ\nವೆಂಕಟಾದ್ರಿ ವಾಸ, ಗೋವಿಂದಾ ಗೋವಿಂದ\nಬಾಲಾಜಿ, ಗೋವಿಂದಾ ಗೋವಿಂದ, ಬಾಲಾಜಿ\n\nದಾಸನ ಮೇಲೆ ಏನೀ ಕೋಪ\nಕರಗದೆ ಇನ್ನೂ ನಾ ಮಾಡಿದ ಪಾಪ\nದಾಸನ ಮೇಲೆ ಏನೀ ಕೋಪ\nಕರಗದೆ ಇನ್ನೂ ನಾ ಮಾಡಿದ ಪಾಪ\nನಿನ್ನನು ಕಾಣದ ಕಣ್ಣುಗಳೇಕೆ\nಪೂಜಿಸದ ಕೈಗಳೇಕೆ\nಶೋಕದ ಬಾಳಿನ್ನೇಕೆ\nವ್ಯರ್ಥದ ಜನುಮವಿದೇಕೆ, ಸ್ವಾಮೀ\nಸೇರುವೆ ನಾನಿನ್ನ ಪಾದಾರವಿಂದ\nಕರೆದುಕೊ ಕರುಣಾಳು ಹೇ ಗೋವಿಂದ\nಬಾಲಾಜಿ, ಬಾಲಾಜಿ, ಪ್ರಭೋ…\n\n",english:"Prabhuji… balaji..\ntirupati vasa\nnamo srinivasa\nporeyo papa vinasha shrisha\njaya jaya jagadisha jaya govinda\njapisalu ninna nama paramananda\n\nAnjanadri vasa\nanandadri vasa\nporeyo papa vinasha shrisha\njaya jaya jagadisha jaya govinda\njapisalu ninna nama paramananda\nsheshadri vasa (govinda govinda)\ngarudadri vasa (govinda govinda)\nbalaji…(govinda govinda)\n\nTandeyu neene tayiyu neene\nnambida bhakutara bhaddhuvu neene\ntandeyu neene.. tayiyu neene\nnambida bhakutara bhaddhuvu neene\nsundara nayana chandira vadana\nsalaho venkataramana..\nsundara nayana chandira vadana\nsalaho venkataramana..\nthoro pavana charana swami..\n\njaya jaya jagadisha jaya govinda\njapisalu ninna nama paramananda\nneeladri vasa (govinda govinda)\nvenktadri vasa (govinda govinda)\nbalaji..(govinda govinda)\nbalaji..\n\nDaasana mele enee kopa\nkaragade innu naa madidha papa\ndaasana mele enee kopa\nkaragade innu naa.. madidha papa\nninnanu kaanada kannugaleke\npoojisada kaigale..ke\nshokada baa..linneke\nvyarthada janumavideke swami…\nseruve naa ninna padaravinda\nkareduko karunalu he govinda\nbalaji..balaji..prabho..o…\n\n",meta:"",tags:["venkateshwara srinivasa","kannada devotional song"],media:"https://www.youtube.com/watch?v=RW2qOzM8wkY"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶೇಷಾದ್ರಿವಾಸ-ಶ್ರೀ-ವೆಂಕಟೇಶ.json",
	rawData: "",
};

export { _internal, collection, data, id };
