const id = "ಶಿವ-ಲಿಂಗಾಷ್ಟಕಮ್";
const collection = "bhajan";
const data = {kannada_title:"ಶಿವ ಲಿಂಗಾಷ್ಟಕಮ್",english_title:" Shiva Lingaashtakam",kannada:"ಬ್ರಹ್ಮ ಮುರಾರಿ ಸುರಾರ್ಚಿತ ಲಿಂಗಂ, ನಿರ್ಮಲಭಾಷಿತ ಶೋಭಿತ ಲಿಂಗಂ | ಜನ್ಮಜದುಃಖ ವಿನಾಶಕ ಲಿಂಗಂ, ತತ್ಪ್ರಣಮಾಮಿ ಸದಾಶಿವಲಿಂಗಂ || ೧ ||\n\nದೇವಮುನಿ ಪ್ರವರಾರ್ಚಿತ ಲಿಂಗಂ, ಕಾಮದಹನ ಕರುಣಾಕರ ಲಿಂಗಂ | ರಾವಣದರ್ಪ ವಿನಾಶಕ ಲಿಂಗಂ, ತತ್ಪ್ರಣಮಾಮಿ ಸದಾಶಿವಲಿಂಗಂ || ೨ ||\n\nಸರ್ವಸುಗಂಧ ಸುಲೇಪಿತ ಲಿಂಗಂ, ಬುದ್ಧಿವಿವರ್ಧನ ಕಾರಣ ಲಿಂಗಂ | ಸಿದ್ಧಸುರಾಸುರ ವಂದಿತ ಲಿಂಗಂ, ತತ್ಪ್ರಣಮಾಮಿ ಸದಾಶಿವಲಿಂಗಂ || ೩ ||\n\nಕನಕಮಹಾಮಣಿ ಭೂಷಿತ ಲಿಂಗಂ, ಫಣಿಪತಿವೇಷ್ಟಿತ ಶೋಭಿತ ಲಿಂಗಂ | ದಕ್ಷಸುಯಜ್ಞ ವಿನಾಶಕ ಲಿಂಗಂ, ತತ್ಪ್ರಣಮಾಮಿ ಸದಾಶಿವಲಿಂಗಂ || ೪ ||\n\nಕುಂಕುಮ ಚಂದನಲೇಪಿತ ಲಿಂಗಂ, ಪಂಕಜಹಾರ ಸುಶೋಭಿತ ಲಿಂಗಂ | ಸಂಚಿತಪಾಪ ವಿನಾಶನ ಲಿಂಗಂ | ತತ್ಪ್ರಣಮಾಮಿ ಸದಾಶಿವಲಿಂಗಂ || ೫ ||\n\nದೇವಗಣಾರ್ಚಿತ ಸೇವಿತ ಲಿಂಗಂ,  ಭಾವೈರ್ಭಕ್ತಿ ಭಿರೇವ ಚ ಲಿಂಗಂ | ದಿನಕರಕೋಟಿ ಪ್ರಭಾಕರ ಲಿಂಗಂ, ತತ್ಪ್ರಣಮಾಮಿ ಸದಾಶಿವಲಿಂಗಂ || ೬ ||\n\nಅಷ್ಟದಳೋ ಪರಿವೇಷ್ಟಿತ ಲಿಂಗಂ, ಸರ್ವಸಮುದ್ಭವ ಕಾರಣ ಲಿಂಗಂ | ಅಷ್ಟದರಿದ್ರ ವಿನಾಶಕ ಲಿಂಗಂ |ತತ್ಪ್ರಣಮಾಮಿ ಸದಾಶಿವಲಿಂಗಂ |೭ ||\n\nಸುರವರ ಸುರಗುರು ಪೂಜಿತ ಲಿಂಗಂ | ಸುರವನಪುಷ್ಪ ಸದಾರ್ಚಿತ ಲಿಂಗಂ | ಪರಾತ್ಪರಂ ಪರಮಾತ್ಮಕ ಲಿಂಗಂ |ತತ್ಪ್ರಣಮಾಮಿ ಸದಾ ಶಿವಲಿಂಗಂ || ೮ ||\n\nಲಿಂಗಾಷ್ಟಕಮಿದಂ ಪುಣ್ಯಂ ಯಃ ಪಠೆಚ್ಚಿವಸನ್ನಿಧೌ | ಶಿವಲೋಕ ಮವಾಪ್ನೋತಿ ಶಿವೇನ ಸಹ ಮೋದತೆ ||\n\n",english:"Brahma muraari surarchita lingam\nNirmala bhaashita shobhitha lingam\nJanmaja dhukha vinaashaka lingam\nTatpranamaami sadaashiva lingam ||1||\nDevamuni pravaraarchita lingam\nKaama dahana karunaakara lingam\nRavana darpa vinaashka lingam\nTatpranamaami sadaashiva lingam ||2||\nSarva sugandha sulepitha lingam\nBuddhi vivaardhana kaarana lingam\nSiddha suraasura vandhitha lingam\nTatpranamaami sadaashiva lingam ||3||\nKanaka mahaamani bhooshitha lingam\nPanipati veshthitha shobitha lingam\nDaksha suyajna vinaashana lingam\nTatpranamaami sadaashiva lingam ||4||\nKunkuma chandhana lehpitha lingam\nPankaja haara sushobhitha lingam\nSanchitha paapa vinaashana lingam\nTatpranamaami sadaashiva lingam ||5||\nDeva ganaarchita sevitha lingam\nBhavair bhakhi bhirevacha lingam\nDinakara koti prabhaakara lingam\nTatpranamaami Sadaashiva Lingam ||6||\nAhshta dalopari veshthitha lingam\nSarva samudbhava kaarana lingam\nAhshta daridra vinaashana lingam\nTatpranamaami sadaashiva lingam ||7||\nSuraguru suravara poojitha lingam\nSuravana pushpa sadarchitha lingam\nParaath param paramatmaka lingam\nTatpranamaami sadaashiva lingam ||8||\nLingashtaka midam punyam\nYah pathet shivasannidhau\nSivaloka mavaapnoti\nSivehna saha modatheh ||\n\n",meta:"",tags:[],media:"https://www.youtube.com/watch?v=gvDm-ESDhls"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶಿವ-ಲಿಂಗಾಷ್ಟಕಮ್.json",
	rawData: "",
};

export { _internal, collection, data, id };
