const id = "ಶ್ರೀ-ಚಕ್ರ-ಧಾರಿಗೆ-ಶಿರಬಾಗಿ";
const collection = "bhajan";
const data = {kannada_title:"ಶ್ರೀ ಚಕ್ರ ಧಾರಿಗೆ ಶಿರಬಾಗಿ",english_title:" Shri Chakradhaarege",kannada:"ಲಾಲಿ ಲಾಲಿ ಲಾಲಿ ಲಾಲಿ ಲಾಲಿ ಲಾಲಿ ಲಾಲಿ ಲಾಲಿ\n\nಶ್ರೀ ಚಕ್ರ ಧಾರಿಗೆ ಶಿರಬಾಗಿ ಲಾಲಿ\nರಾಜೀವನೇತ್ರನಿಗೆ ರಾಮಣೀಯ ಲಾಲಿ\nಹಾಲ್ಗೆನ್ನೆ ಕೃಷ್ಣನಿಗೆ.. ಹಾಲ್ಗೆನ್ನೆ ಕೃಷ್ಣನಿಗೆ ಹಾಲ್ಜೆನ ಲಾಲಿ\nಜಗವಾಳೋ ಸ್ವಾಮಿಗೆ ಪದಮಾಲೆ ಲಾಲಿ.. ಶ್ರೀ ಚಕ್ರಧಾರಿಗೆ…\n\nಕಲ್ಯಾಣರಾಮನಿಗೆ ಕೌಸಲ್ಯಾ ಲಾಲಿ..\nಕಲ್ಯಾಣರಾಮನಿಗೆ ಕೌಸಲ್ಯಾ ಲಾಲಿ..\nಯದುವಂಶ ವಿಭುವಿಗೆ ಯಶೋದೆ ಲಾಲಿ..\nಯದುವಂಶ ವಿಭುವಿಗೆ ಯಶೋದೆ ಲಾಲಿ..\nಪರಮೇಶ ಸುತನಿಗೆ …. ಪರಮೇಶ ಸುತನಿಗೆ ಪಾರ್ವತಿಯ ಲಾಲಿ..\nಧರೆಯಾಳೋ ವರ್ಧನಿಗೆ ಶರನೆಂದೆ ಲಾಲಿ…\n\nಶ್ರೀ ಚಕ್ರಧಾರಿಗೆ…\n\nಜೋ ಜೋ ಜೋ ಜೋ ಜೋ….\nಜೋ ಜೋ ಜೋ ಜೋ ಜೋ….\n\nಶ್ರೀ ಕನಕದಾಸರದು ಕೃಷ್ಣನಿಗೆ ಲಾಲಿ\nಶ್ರೀ ಕನಕದಾಸರದು ಕೃಷ್ಣನಿಗೆ ಲಾಲಿ\nಲಿಂಗಕೆ ಜಂಗಮರ ವಚನಗಳ ಲಾಲಿ\nಲಿಂಗಕೆ ಜಂಗಮರ ವಚನಗಳ ಲಾಲಿ\nವೇದ ವೇದ್ಯರಿಗೆ ವೇದಾಂತ ಲಾಲಿ\nಆಗಮ ನಿಗಮವೇ ಲಾಲಿಗೇ.. ಲಾಲಿ..\n\nಶ್ರೀ ಚಕ್ರಧಾರಿಗೆ ಶಿರಬಾಗಿ ಲಾಲಿ\nರಾಜೀವನೇತ್ರನಿಗೆ ರಮಣೀಯ ಲಾಲಿ\nಹಾಲ್ಗೆನ್ನೆ ಕೃಷ್ಣನಿಗೆ ಹಾಲ್ಜೆನ ಲಾಲಿ\nಜಗವಾಳೋ ಸ್ವಾಮಿಗೆ ಪದಮಾಲೆ ಲಾಲಿ..\n\nಶ್ರೀ ಚಕ್ರಧಾರಿಗೆ……\n\n",english:"Laali Laali Laali Laali (2)\n\nShri Chakradhaarege Shirabaagi Laali\nRaajeeva Nethranige Ramaneeya Laali\nHaalgenne Krishnanige,\n\nHaalgenne Krishnanige Haaljena Laali.. |Jagavaalo Swaamige Padamaale Laali.. ||\n\nShri Chakradhaarege Shirabaagi Laali\nRaajeeva Nethranige Ramaneeya Laali\n\nLaali Laali Laali Laali |2 times|\n\nKalyaanaraamanige Kousalya Laali  2\nYaduvamsha Vibhuvige Yashode Laali 2 times\nParamesha Sutanige.. Paramesha Sutanige Parvatiya Laali..  2 times\nDhareyaalo Vaardhanige Sharanende Laali.. ||1||\n\nJo Jo Jo Jo Joooo..\nJo Jo Jo Jo Joooo..\n\nShri Kanakadaasaradu Krishnanige Laali | 2 times|\nLingakke Jangamara Vachanagala Laali || 2 times||\nVeda Vedyarige Vedaantha Laali || 2\nAagama Nigamave Laali.. Laali.. ||2||\n\nShri Chakradhaarege Shirabaagi Laali\nRaajeeva Nethranige Ramaneeya Laali\nHaalgenne Krishnanige\nHaalgenne Krishnanige Haaljena Laali..\nJagavaalo Swaamige Padamaale Laali..\n\n***************************************\n\n",meta:"",tags:["krishna","kannada devotional song","kannada lyrics","krishna song","lulluby"],media:"https://www.youtube.com/watch?v=sus8KCBC6fE"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶ್ರೀ-ಚಕ್ರ-ಧಾರಿಗೆ-ಶಿರಬಾಗಿ.json",
	rawData: "",
};

export { _internal, collection, data, id };
