const id = "ಶಂಭೋ-ಪಾಲಿಸು-ನೀ";
const collection = "bhajan";
const data = {kannada_title:"ಶಂಭೋ ಪಾಲಿಸು ನೀ",english_title:"Shambho paaliso nee",kannada:"ಶಂಭೋ ಪಾಲಿಸು ನೀ ಎನ್ನಾ||2||\nಜಗದಂಬಾ ರಮಣ ಮುಕ್ಕಣ್ಣಾ ||ಶಂಭೋ||\nಕುಂಭಿನಿಕ್ರತ ರಥ, ಜಂಭಾರಿನುತ ಪಾದ\nಅಂಬುಜ ಮನ್ಮನೋ,ಅಂಬುಜದಲಿ ತೋರೋ||ಕುಂಭಿನಿಕ್ರತ||                ||ಶಂಭೋ||\n\nನಂದಿವಾಹನ ತ್ರಿಶೂಲಿ ಶತಾನಂದಾನಂದನ ಕಪಾಲಿ\nವಂದಿಪಜನರಘ ಚಿಂದಿಸಿ | ಸುಜ್ಞಾನಾನಂದಸಲಿಸುವ ಎಂದು ನಿನ್ನನು ಭಜಿಪೆ                                                   ಸಿಂಧೂಜಾತಾರ್ಥಮೌರಿಯೆ ಕಂದು ಕಂದರ ನಿನ್ನ ಪಾದ ದ್ವಂದ್ವದಲ್ಲಿ ಮನಸ್ಸು ನಿಲ್ಲಿಸಿ ಇಂದಿರೇಶನ ತೋರಿಸಯ್ಯ ||ಸಿಂಧು||  ||ಶಂಭೋ||\n\nಮನೋ ಮಾನಿಯೆ ಮಾರಾರಿ ದುರ್ಮನಸ್ಸು ಬಿಡಿಸು ತ್ರಿಪುರಾರಿ |ಕನಕಗರ್ಭನ ಬ್ರುಗುಟ\nಜನುಮ ನಿನ್ನಯ ಪಾದ ವನಜಯುಗ್ಮದಿ ಎನ್ನ ತನುವು ನೀಡುವೆ ದೇವ ||\n\nಇನ ಶಶಾಂಕಾಗ್ನಿ ನಯನನೆ ಕನಕಗಿರಿಕ್ರತ‌ ಅಂಬುಪಾಣಿಯೆ ಜನುಮ ಜನುಮಕೆ ಹರಿಯ ಭಜಿಸುವ ಮನಸ್ಸು ಪಾಲಿಸು ಪವನ ತನಯನೆ ||ಇನಶಶಾಂಕ||.              ||ಶಂಭೋ||\n\nನಿಟಿಲಾಕ್ಷ ಸುರ ಗಂಗಾಧರನೆ ಪಂಪಾತಟ ನಿಲಯನೆ ನಿಸ್ಸಂಘ |ಕಟುಜನ ಅವಿಕುಲ ಕಟಸಮ ಹರಿಪಾದ\nಭಟಜನರೊಲು ನೀನು ತುಂಟನೆನೆಸಿದೆ ದೇವ ||\n\nದಿಟನೆ ಎನಭವ ಹಠ ದವಾನಲ ಕುಟಿಲ ಕಟುಮತಿ ತಟನೆ ನೀಗುವ | ನಿಜಗುರು ಜಗನ್ನಾಥವಿಠಲನ\nಬಡಜನಾಗ್ರನಿ ತಟನೆ ಪಾಲಿಸೋ ||ಶಂಭೋ||\n\n",english:"Shambho paalisu nee ennaa ||2||jagadambaa ramana mukkanna ||shambho|| kumbhinikrata ratha, jambharinuta paada ambuja manmano, ambujadali toro|2times| shambho||\n\nNandivahana trishuli shatananda nandana kapali vandipa janaragha chindisi sujnanaanandasalisuva endu ninnanu bhajipe ||\n\nSindhujaartamouriye kandu kandara ninna paada dwandadalli manassu nillisi indireshana toriseyya|2times||shambho||\n\nMano maniye marari durmanassu bidisu tripuraari| kanakagarbhana bruguta | januma ninnaya paada vanajayugmadi enna tanuvu needuve deva ||\n\nEna shashaankaagni nayanane kanakagirikrata ambupaaniye januma janumake hariya bhajisuva manassu paalisu pavana tanayane||2times||.    Shambho||\n\nNitilaaksha sura gangaadharane pampa tata nilayane nissangha| katujana avikula katasama haripaada bhata janarolu neenu tuntaneneside deva ||\n\nDitane enabhava hata davaanala kutila katumati tatane neeguve| nijaguru janannaatha vithalana badajanaagrani tatane paaliso||shambho||\n\n",meta:"",tags:[],media:"https://www.youtube.com/watch?v=07xSO-WIu4A"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶಂಭೋ-ಪಾಲಿಸು-ನೀ.json",
	rawData: "",
};

export { _internal, collection, data, id };
