const id = "ಶ್ರೀ-ಮಹಾಲಕುಮಿ-ದೇವಿಯೇ";
const collection = "bhajan";
const data = {kannada_title:"ಶ್ರೀ ಮಹಾಲಕುಮಿ ದೇವಿಯೇ",english_title:"  Sri maha lakumi deviye",kannada:"ಶ್ರೀ ಮಹಾಲಕುಮಿ ದೇವಿಯೆ ಕೋಮಲಾಂಗಿಯೆ ಸಾಮಗಾಯನ ಪ್ರಿಯಳೇ\nಹೇಮಗರ್ಭ ಕಾಮಾರಿ ಶಕ್ರಸುರ ಸ್ತೋಮ ವಂದಿತೆ ಸೋಮಸೋದರಿಯೇ ||\n\nಸಕಲ ಶುಭಗುಣ ಭರಿತಳೆ ಏಕ ದೇವಿಯೆ ವಾಕು ಲಾಲಿಸಿ ನೀ ಕೇಳೆ\nಲೋಕನಾಥನ ಗುಣ ಲೀಲೇ ಕೊಂಡಾಡುವಂಥ ಏಕಮನವ ಕೊಡು ಶುಭಶೀಲೆ\nಬೇಕುಬೇಕು ನಿನ್ನ ಪತಿಪಾದಾಬ್ಜವ ಏಕಾಂತದಲಿ ಭಜಿಪರ ಸಂಗವ ಕೊಡು\nಲೋಕದ ಜನರಿಗೆ ನಾ ಕರವೊಡ್ಡದಂತೆ ತಾಯೆ ಕರುಣಿಸು ರಾಕೆಂದುವದನೆ  || ೧ ||\n\nಬಟ್ಟಕುಂಕುಮ ನೊಸಲೊಳೆ ಮುತ್ತಿನ ಹೊಸ ಕಠ್ಠಾಣಿ ತ್ರಿವಳಿ ಕೊರಳೊಳು\nಇಟ್ಟ ಪೊನ್ನೋಲೆ ಕಿವಿಯೊಳೆ ಪವಳದ ಕಯ್ಯ ಕಟ್ಟು ಕಂಕಣ ಕೈ ಬಳೆ\nತೊಟ್ಟ ಕುಬುಸ ಬಿಗಿದುಟ್ಟ ಪೀತಾಂಬರ ಘಟ್ಟಿ ವಡ್ಯಾಣ ಕಾಲಂದುಗೆ ರುಳಿಗೆಜ್ಜೆ\nಬೆಟ್ಟಿಲಿ ಪೊಳೆವುದು ಮೇಂಟಕೆ ಕುರುಪಿಲ್ಲಿ ಇಟ್ಟು ಶೋಭಿಸುವ ಅಷ್ಟ ಸಂಪನ್ನೆ  || ೨ ||\n\nಮಂದರಧರನರಸಿಯೆ ಇಂದಿರೆ ಎನ್ನ ಕುಂದುದೋಷಗಳನೀ ತರಿಯೆ\nಅಂದುಳ್ಳ ಸೌಭಾಗ್ಯದಸಿರಿಯೇ ನಿನ್ನ ಕಂದನೆಂದು ಮುಂದಕ್ಕೆ ಕರೆಯೇ\nಸಿಂಧುಸುತಳೇ ನಿತ್ಯಸಿಂಧೂರ ಗಮನೇ ಸಿಂಧುಶಯನ\nಸಿರಿ\nವಿಜಯವಿಠಲ\nನ ಎಂದೆಂದಿಗು ಮನದಿಂದ ಅಗಲದಂತೆ  || ೩ ||\n\n",english:"Composer : Sri Vijaya dasaru\n\nShree mahaalakumi deviye komalaangiye saamagaayana priyale\nhemagarbha kaamaari shakrasura stoma vandite somasodariye ||\n\nSakala shubhaguna bharitale Eka deviye vaaku laalisi nee kele\nlokansthana guna leele kondaaduvamtha Ekamanava kodu shubhasheele\nbekubeku ninna patipaadaabjava Ekaantadali bhajipara sangava kodu\nlokada janarige naa karavoddadante taye karunisu raakenduvadane  || 1 ||\n\nbattakumkuma nosalole muttina hosa kaththaani trivali koralolu\nitta ponnole kiviyole pavalada kayya kattu kankaNa kai bale\ntotta kubusa bigidutta peetaambara ghatti vadyaana kaalanduge ruligejje\nbettili polevudu memtake kurupilli ittu shobhisuva ashta sampanne  || 2 ||\n\nmandaradharanarasiye indire enna kundudoshagalanee tariye\nandulla soubhaagyadasiriye ninna kandanendu mundakke kareye\nsindhusutale nityasindhura gamane sindhushayana\nsiri vijayavithalana endendigu manadinda agaladante  || 3 ||\n\nClick the link below to listen the song\n\n",meta:"",tags:["lakshmi","dasara padagalu","kannada devotional songs"],media:"https://www.youtube.com/watch?v=eNzT9Xy_fxo"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶ್ರೀ-ಮಹಾಲಕುಮಿ-ದೇವಿಯೇ.json",
	rawData: "",
};

export { _internal, collection, data, id };
