const id = "ಶರಧಿ-ಮರ್ದನದಲ್ಲಿ-ಸಿರಿದೇವಿ-ಜನಿಸಿದಳು";
const collection = "bhajan";
const data = {kannada_title:"ಶರಧಿ ಮರ್ದನದಲ್ಲಿ ಸಿರಿದೇವಿ ಜನಿಸಿದಳು",english_title:" Sharadhi mardanadalli siridevi janisidalu",kannada:"ಸಾಹಿತ್ಯ :- ಪುರಂದರ ದಾಸರು\n\nಶರಧಿ ಮಥನದಲ್ಲಿ ಸಿರಿದೇವಿ ಜನಿಸಿದಳು\nಕಮಲದ ವನಮಾಲೆ ಕರದಿ ಪಿಡಿದಿಹಳು||\n\nಗರುಡನ್ನ ಒಲ್ಲೆನಮ್ಮ ಗಗನಕ್ಹಾರುವನ\nಉರಗನ್ನ ಒಲ್ಲೆನಮ್ಮ ಧರೆಯ ಪೊತ್ತವನ\nಕಾಲ ಯಮನನ ಒಲ್ಲೆ ಕೋಣನೇರ್ದವನ\nಜ್ವಾಲಾಗ್ನಿಯ ಒಲ್ಲೆ ವಹ್ನಿ ಸುಡುವವನ ||\n\nಸೂರ್ಯನ್ನ ಒಲ್ಲೆನಮ್ಮ ಸುತ್ತ ಸುಡುವವನ\nವಾಯುದೇವರನೊಲ್ಲೆ ಗಾಳಿ ಬೀಸುವನ\nಇಂದ್ರನ್ನ ಒಲ್ಲೆನಮ್ಮ ಮೈಯೆಲ್ಲಾ ಕಣ್ಣವನ\nಚಂದ್ರನ್ನ ಒಲ್ಲೆನಮ್ಮ ಕಳೆಗುಂದಿದವನ ||\n\nಮತ್ಸ್ಯನ್ನ ಒಲ್ಲೆನಮ್ಮ ಜಲದೊಳಗಡಗಿಹನ\nಕೂರ್ಮನ್ನ ಒಲ್ಲೆನಮ್ಮ ಗಿರಿಯ ಪೊತ್ತವನ\nವರಹನ್ನ ಒಲ್ಲೆನಮ್ಮ ನೆಲವ ಬಗೆದವನ\nನರಹರಿಯ ಒಲ್ಲೆನಮ್ಮ ಕರುಳ ಬಗೆದವನ ||\n\nವಾಮನನ್ನ ಒಲ್ಲೆನಮ್ಮ ದಾನ ಬೇಡ್ದವನ\nಪರಶುರಾಮನ್ನ ಒಲ್ಲೆನಮ್ಮ ತಾಯ ಕೊಂದವನ\nರಾಮನ್ನ ಒಲ್ಲೆನಮ್ಮ ಶಬರಿ ಎಂಜಲುಂಡವನ\nಕೃಷ್ಣನ್ನ ಒಲ್ಲೆನಮ್ಮ ಬೆಣ್ಣೆ ಕದ್ದವನ ||\n\nಬೌದ್ಧನ್ನ ಒಲ್ಲೆನಮ್ಮ ಬೆತ್ತಲೆ ನಿಂತವನ\nಕಲ್ಕೀನ ಒಲ್ಲೆನಮ್ಮ ತೇಜಿಗೇರ್ದವನ\nವಾಸುಕಿ ಶಯನ\nಶ್ರೀ ಪುರಂದವಿಠಲ\nನಿಗೆ\nಮಂದಾರ ಹೂವಿನ ಮಾಲೆ ಹಾಕಿದಳು ||\n\nಶರಧಿ ಮಥನದಲ್ಲಿ ಸಿರಿದೇವಿ ಜನಿಸಿದಳು\nಕಮಲದ ವನಮಾಲೆ ಕರದಿ ಪಿಡಿದಿಹಳು ||\n\n",english:"Sharadhi mathanadalli siridevi janisidalu\nkamalada vanamaale karadi pidihalu ||\n\nGarudanna ollenamma gaganakahruvana\nuraganna ollenamma dhareya pottavana\nkaala yamanana olle konanerdavana\njwalaagniya olle vahni suduvavana ||\n\nSuryanna ollenamma sutta suduvavana\nvayudevara olle gaali beesuvana\nindranna ollenamma maiyella kannavana\nchandranna ollenamma kalegundidavana ||\n\nMatsyanna ollenamma jaladolagadagihana\nkoormanna ollenamma giriya pottavana\nvarahanna ollenamma nelava bagedavana\nnarahariya ollenamma karula bagedavana ||\n\nVamananna ollenamma daana beddavana\nparashuramanna ollenamma taaya kondavana\nramanna ollenamma shabari enjalundavana\nkrishnanna ollenamma benne kaddavana ||\n\nBouddanna ollenamma bettale nintavana\nkalkina ollenamma tejigerdavana\nvaasuki shayana\nsri purandara vittala\nnige\nmandara hoovina maale hakidalu ||\n\nSharadhi mathanadalli siridevi janisidalu\nkamalada vanamaale karadi pididihalu ||\n\n",meta:"",tags:["lakshmi","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=3h3jNZ9nW90"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶರಧಿ-ಮರ್ದನದಲ್ಲಿ-ಸಿರಿದೇವಿ-ಜನಿಸಿದಳು.json",
	rawData: "",
};

export { _internal, collection, data, id };
