const id = "ಶ್ರೀ-ಮಹಾಲಕ್ಷ್ಮಿಯ-ಅಲಂಕರಿಸಿ";
const collection = "bhajan";
const data = {kannada_title:"ಶ್ರೀ ಮಹಾಲಕ್ಷ್ಮಿಯ ಅಲಂಕರಿಸಿ",english_title:"Shri mahalakshmiya alankarisi",kannada:"ಶ್ರೀ ಮಹಾಲಕ್ಷ್ಮಿಯ ಅಲಂಕರಿಸಿ ಕರೆದರು ||\n\nಕೇಶವ ನಿಮ್ಮ ನಾಮ ಮಾಂಗಲ್ಯಸೂತ್ರ ತಾಳಿ\nನಾರಾಯಣ ನಿಮ್ಮ ನಾಮ ತಾಳಿ ಪದಕವು\nಮಾಧ್ವ ನಿಮ್ಮ ನಾಮ ಸುರಗೆ ಸಂಪಿಗೆ ಮೊಗ್ಗು\nಗೋವಿಂದ ನಿಮ್ಮ ನಾಮ ಗೋಧಿಯ ಸರವು ||೧||\n\nವಿಷ್ಣುವೆ ನಿಮ್ಮ ನಾಮ ರತ್ನ ಕುಂಡಲಗಳು\nಮಧುಸೂದನ ನಿಮ್ಮ ನಾಮ ಮಾಣಿಕ್ಯದ ಹರಳು\nತ್ರಿವಿಕ್ರಮ ನಿಮ್ಮ ನಾಮ ವಂಕಿ ನಾಗಮುರುಗಿಯು\nವಾಮನ ನಿಮ್ಮ ನಾಮ ಓಲೆ ಏಕಾವಳಿಯು ||೨||\n\nಶ್ರೀಧರ ನಿಮ್ಮ ನಾಮ ಒಳ್ಳೆ ಮುತ್ತಿನ ಹಾರ\nಹೃಷಿಕೇಶ ನಿಮ್ಮ ನಾಮ ಕಡಗ ಗೆಜ್ಜೆಯು\nಪದ್ಮನಾಭ ನಿಮ್ಮ ನಾಮ ಮುತ್ತಿನಡ್ಡಿಕೆಯು\nದಾಮೋದರ ನಿಮ್ಮ ನಾಮ ರತ್ನದ ಪದಕವು ||೩||\n\nಸಂಕರ್ಷಣ ನಿಮ್ಮ ನಾಮ ವಂಕಿ ತೋಳಾಯಿತು\nವಾಸುದೇವ ನಿಮ್ಮ ನಾಮ ಒಲಿದ ತೋಡೆ\nಪ್ರದ್ಯುಮ್ನ ನಿಮ್ಮ ನಾಮ ಹಸ್ತಕಂಕಣ ಬಳೆ\nಅನಿರುದ್ಧ ನಿಮ್ಮ ನಾಮ ಮುಕುರ ಬುಲಾಕು ||೪||\n\nಪುರುಷೋತ್ತಮ ನಿಮ್ಮ ನಾಮ ಹೊಸ ಮುತ್ತಿನ ಮೂಗುತಿ\nಅಧೋಕ್ಷಜ ನಿಮ್ಮ ನಾಮ ಚಂದ್ರ ಸೂರ್ಯ\nನಾರಸಿಂಹ ನಿಮ್ಮ ನಾಮ ಚೌರಿ ರಾಗಟಿ ಗೊಂಡ್ಯ\nಅಚ್ಯುತ ನಿಮ್ಮ ನಾಮ ಮುತ್ತಿನ ಬೊಟ್ಟು ||೫||\n\nಜನಾರ್ದನ ನಿಮ್ಮ ನಾಮ ಜರಿಯ ಪೀತಾಂಬರ\nಉಪೇಂದ್ರ ನಿಮ್ಮ ನಾಮ ಕಡಗ ಗೆಜ್ಜೆಯು\nಶ್ರೀಹರಿ ನಿಮ್ಮ ನಾಮ ಕಂಚು ಅಂಕಿಯ ತುಳಸಿ\nಶ್ರೀಕೃಷ್ಣ ನಿಮ್ಮ ನಾಮ ನಡುವಿನೊಡ್ಯಾಣವು ||೬||\n\nಸರಸಿಜಾಕ್ಷ ನಿಮ್ಮ ನಾಮ ಅರಸಿನ ಎಣ್ಣೆ ಹಚ್ಚಿ\nಪಂಕಜಾಕ್ಷ ನಿಮ್ಮ ನಾಮ ಕುಂಕುಮ ಕಾಡಿಗೆಯು\nಪುರಂದರ ವಿಠಲ ನಿಮ್ಮ ನಾಮ ಸರ್ವಾಭರಣವು\nನಿಲುವುಗನ್ನಡಿಯಲಿ ಲಲನೆಯ ತೋರಿಸುತ ||೭||\n\n",english:"Shri mahalakshmiya alankarisi karedaru||\n\nKeshava nimma nama mangalyasutra tali\nnarayana nimma nama tali padakavu|\nmadhva nimma nama surage sampige moggu\ngovinda nimma nama godhiya saravu ||1||\n\nVishnuve nimma nama ratna kundalagalu\nmadhusudana nimma nama manikyada haralu|\ntrivikrama nimma nama vanki nagamurugiyu\nvamana nimma nama ole ekavaliyu ||2||\n\nShridhara nimma nama olle muttina hara\nhrushikesha nimma nama kadaga gejjeyu|\npadmanabha nimma nama muttinaddikeyu\ndamodara nimma nama ratnada padakavu ||3||\n\nSankarshana nimma nama vanki tolayitu\nvasudeva nimma nama olida tode|\npradyumna nimma nama hastakankana bale\naniruddha nimma nama mukura bulaku ||4||\n\nPurushottama nimma nama hosa muttina muguti\nadhokshaja nimma nama chandra surya|\nnarasimha nimma nama chouri ragati gondya\nachyuta nimma nama muttina bottu ||5||\n\nJanardana nimma nama jariya pitambara\nupendra nimma nama kadaga gejjeyu|\nshrihari nimma nama kanchu ankiya tulasi\nshrikrushna nimma nama naduvinodyanavu ||6||\n\nSarasijaksha nimma nama arasina enne hachchi\npankajaksha nimma nama kunkuma kadigeyu|\npurandara vithala nimma nama sarvabharanavu\nniluvugannadiyali lalaneya torisuta ||7||\n\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=XkXk8NzeQ7Q"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶ್ರೀ-ಮಹಾಲಕ್ಷ್ಮಿಯ-ಅಲಂಕರಿಸಿ.json",
	rawData: "",
};

export { _internal, collection, data, id };
