const id = "ಶೃಂಗಾರವಾಗಿಹುದು-ಶ್ರೀಹರಿಯ-ಮಂಚ";
const collection = "bhajan";
const data = {kannada_title:"ಶೃಂಗಾರವಾಗಿಹುದು ಶ್ರೀಹರಿಯ ಮಂಚ",english_title:" Shrungaravagihudu srihariya mancha",kannada:"ಶೃಂಗಾರವಾಗಿಹುದು | ಶ್ರೀಹರಿಯ ಮಂಚ | ಅಂಗನೆ ರುಕ್ಮಿಣಿಯರಸ | ಪವಡಿಸುವ ಮಂಚ || ಪ ||\n\nಬಡಗಿ ಮಟ್ಟದ ಮಂಚ | ಕಡಲಿನೊಳಗಿಹ ಮಂಚ || ಮೃಡನ ತೋಳಿನಲಿ |ಅಡಗಿರುವ ಮಂಚ | ಹೆಡೆಯುಳ್ಳ ಹೊಸ ಮಂಚ | ಪೊಡವಿ ಪೊತ್ತಿಹ ಮಂಚ | ಕಡಲ ಶಯನ ಶ್ರೀ|ರಂಗನಾ ಮಂಚ    || ಶೃಂಗಾರವಾಗಿಹುದು ||\n\nಕಾಲಿಲ್ಲದಿಹ ಮಂಚ | ಗಾಳಿನುಂಗುವ ಮಂಚ || ತೋಳು ಬಿಳುಪಿನ ಮಂಚ | ವಿಷದ ಮಂಚ | ಕಾಳಗದೊಳರ್ಜುನನ | ಮುಕುಟ ಕೆಡಹಿದ ಮಂಚ | ಕೇಳು ಪರೀಕ್ಷಿತನ | ಕೊಂದುದೀ ಮಂಚ      || ಶೃಂಗಾರವಾಗಿಹುದು ||\n\nಕಣ್ಣು ಕಿವಿಯಾದ ಮಂಚ|ಬೆನ್ನು ಬಾಗಿದ ಮಂಚ || ಹುಣ್ಣಿಮೆಯ ಚಂದ್ರಮನ | ಅಡ್ಡಗಟ್ಟುವ ಮಂಚ | ಬಣ್ಣ ಬಿಳುಪಿನ ಮಂಚ || ಹೊನ್ನಕಾದಿಹ ಮಂಚ|ಕನ್ನೆ ಮಹಲಕ್ಷ್ಮಿಯರಸನಾ ಮಂಚ || ಶೃಂಗಾರವಾಗಿಹುದು ||\n\nಹಕ್ಕಿಗೆ ಹಗೆ ಮಂಚ | ರೊಕ್ಕ ಮಟ್ಟದ ಮಂಚ || ರಕ್ಕಸರೆದೆಯನ್ನು | ನಡುಗಿಸುವ ಮಂಚ | ಸೊಕ್ಕು ಪಿಡಿದಿಹ ಮಂಚ || ಫಕ್ಕನೆ ನುಂಗುವ ಮಂಚ|ಲಕ್ಕುಮಿ ರಮಣ ಶ್ರೀಹರಿಯ ಮಂಚ || ಶೃಂಗಾರವಾಗಿಹುದು ||\n\nಅಂಕುಡೊಂಕಿನ ಮಂಚ|ಅಕಲಂಕ ಮಹಿಮ ಮಂಚ || ಸಂಕರುಷಣಾನೆಂಬೊ | ಸುಖದ ಮಂಚ | ಶಂಕರನ ಕೊರಳಿಗೆ ಪದಕವಾಗಿಹ ಮಂಚ || ವೆಂಕಟ ಪುರಂದರ | ವಿಠಲರಾಯನ ಮಂಚ || ಶೃಂಗಾರವಾಗಿಹುದು ||\n\n",english:"Shrungaravagihudu srihariya mancha angane rukminiyarasa pavadisuva mancha || pa ||\n\nBadagi muttada mancha | kadalinolagiha mancha | mrudana tolinali | adagiruva mancha | hedeyulla hosa mancha | podavi pottiha mancha | kadala shayana sri rangana mancha || shrugaravagihudu ||\n\nkaalilladiha mancha|  gaali nunguva mancha| tolu bilupina mancha | vishada mancha | kaalagadolarjunana mukuta kedahida mancha | kelu pareekshitana | kondudee mancha ||shrungaravagihudu||\n\nKannu kiviyada mancha | bennu bagida mancha | hunnimeya chandrama addagattuva mancha | Banna bilupina mancha | honnakadiha mancha | kanne mahalakshmiyarasana mancha |shrungaravagihudu||\n\nHakkige hage mancha | rokka mattada mancha | rakkasaredeyannu nadugisuva mancha | sokku pididiha mancha | phakkane nunguva mancha | lakkumi Ramana srihariya mancha ||shrungaravagihudu||\n\nAnkudonkina mancha| akalanka mahima mancha | sankarushananembo sukhada mancha | shankarana koralige padakavagiha mancha | venkata purandara vittalarayana mancha ||shrungaravagihudu||\n\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=WrqclhiOVk8"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶೃಂಗಾರವಾಗಿಹುದು-ಶ್ರೀಹರಿಯ-ಮಂಚ.json",
	rawData: "",
};

export { _internal, collection, data, id };
