const id = "ಶ್ರೀದೇವಿ-ವಾಗ್ದೇವಿ-ಜಯಗೌರಿ";
const collection = "bhajan";
const data = {kannada_title:"ಶ್ರೀದೇವಿ ವಾಗ್ದೇವಿ ಜಯಗೌರಿ",english_title:"Sridevi vagdevi jayagowri",kannada:"",english:"ಶ್ರೀದೇವಿ ವಾಗ್ದೇವಿ ಜಯಗೌರಿ । [ಪ]\nಸರಿಸಾಟಿ ನಿನಗಿಲ್ಲ ದೈವಗಳದೈವ ಶ್ರೀದೇವಿ ….।। [ಅ. ಪ]\nಪಾಲ್ಗಡಲ ಶ್ರೀನಿಧಿಯೇ ಹೃತ್ಕಮಲ ವಾಸಿ\nಫಲಬಗೆಯ ಸಿರಿತನಕ್ಕೆ ಸಿರಿಯೇ ನೀನಮ್ಮ ।\nಕುಲದೇವಿ ನೀನೆಂದು …..ಅ…… ಅ…. ಬೇಡುವೆ ನಿನ್ನ\nಕುಲಕ್ಕಾಗಿ ಐಸಿರಿಯ ವರನೀಡು ತಾಯಿ ।।\n[ಶ್ರೀದೇವಿ]\nಶೃತಿಯಾಗಿ ವೀಣೆಯಲಿ ಗತಿಯಾಗಿ ಬಾಳಲ್ಲಿ\nಸತಿಯಾಗಿ ಪೊರೆಯುತಿಹ ಬ್ರಹ್ಮನರಸಿ ।\nಹಿತವಾದ ನುಡಿ ಕಲಿಸಿ ಮತಿವಂತಳಾಗಿಸುತ\nಪತಿ ಸೇವೆ ಕರುಣಿಸು ಉಸಿರಿರುವತನಕ ।।\n[ಶ್ರೀದೇವಿ ]\nಪರಶಿವನ ಅರ್ಧಾಂಗಿ ಪತಿತ ಪಾವನೆ ಗೌರಿ\nಅರಿತವರ ಬಾಳಿನಲಿ ನೀನೆ ಪಾವನ ಗಂಗೆ ।\nಕರಗುವುದು ನೀನೊಲಿಯೇ ದುರಿತಗಳೆಲ್ಲಾ\nಪರಿಹರಿಸಿ ದುಗುಡವನು ಮುತೈದೆತನ ನೀಡು।।\n[ಶ್ರೀದೇವಿ]\nLyrics in English\nSridevi vagdevi jaya gowri ||pa|| sarisaati ninagilla daivagala daiva sridevi ….||a.pa||\nPaalgadala srinidhiye  hrutkamalavaasi  |phalabageya siritanakke siriye neenamma | kuladevi neenendu ….a…a….beduve ninna, kulakkaagi  isiriya varaneedu taayi ||sridevi||\nShrtiyaagi veeneyali gatiyaagi baalalli satiyaagi poreyutiha brahmanarasi|hitavaada nudi kalasi mativantalaagisuta pati seve karunisu usiriruvatanaka ||sridevi||\nParashivana ardhaangi patita paavane gowri |aritavara baalinali neene paavana gange | karaguvudu neenoliye duritagalella | pariharisi dugudavanu muttaidetana needu ||sridevi||\n\nಪಾಲ್ಗಡಲ ಶ್ರೀನಿಧಿಯೇ ಹೃತ್ಕಮಲ ವಾಸಿ\nಫಲಬಗೆಯ ಸಿರಿತನಕ್ಕೆ ಸಿರಿಯೇ ನೀನಮ್ಮ ।\nಕುಲದೇವಿ ನೀನೆಂದು …..ಅ…… ಅ…. ಬೇಡುವೆ ನಿನ್ನ\nಕುಲಕ್ಕಾಗಿ ಐಸಿರಿಯ ವರನೀಡು ತಾಯಿ ।।\n[ಶ್ರೀದೇವಿ]\n\nಶೃತಿಯಾಗಿ ವೀಣೆಯಲಿ ಗತಿಯಾಗಿ ಬಾಳಲ್ಲಿ\nಸತಿಯಾಗಿ ಪೊರೆಯುತಿಹ ಬ್ರಹ್ಮನರಸಿ ।\nಹಿತವಾದ ನುಡಿ ಕಲಿಸಿ ಮತಿವಂತಳಾಗಿಸುತ\nಪತಿ ಸೇವೆ ಕರುಣಿಸು ಉಸಿರಿರುವತನಕ ।।\n[ಶ್ರೀದೇವಿ ]\n\nಪರಶಿವನ ಅರ್ಧಾಂಗಿ ಪತಿತ ಪಾವನೆ ಗೌರಿ\nಅರಿತವರ ಬಾಳಿನಲಿ ನೀನೆ ಪಾವನ ಗಂಗೆ ।\nಕರಗುವುದು ನೀನೊಲಿಯೇ ದುರಿತಗಳೆಲ್ಲಾ\nಪರಿಹರಿಸಿ ದುಗುಡವನು ಮುತೈದೆತನ ನೀಡು।।\n[ಶ್ರೀದೇವಿ]\n\nLyrics in English\n\nSridevi vagdevi jaya gowri ||pa|| sarisaati ninagilla daivagala daiva sridevi ….||a.pa||\n\nPaalgadala srinidhiye  hrutkamalavaasi  |phalabageya siritanakke siriye neenamma | kuladevi neenendu ….a…a….beduve ninna, kulakkaagi  isiriya varaneedu taayi ||sridevi||\n\nShrtiyaagi veeneyali gatiyaagi baalalli satiyaagi poreyutiha brahmanarasi|hitavaada nudi kalasi mativantalaagisuta pati seve karunisu usiriruvatanaka ||sridevi||\n\nParashivana ardhaangi patita paavane gowri |aritavara baalinali neene paavana gange | karaguvudu neenoliye duritagalella | pariharisi dugudavanu muttaidetana needu ||sridevi||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=3HorHezTBPo"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶ್ರೀದೇವಿ-ವಾಗ್ದೇವಿ-ಜಯಗೌರಿ.json",
	rawData: "",
};

export { _internal, collection, data, id };
