const id = "ಶ್ರೀ-ಗಣೇಶ-ಪಂಚರತ್ನ-ಸ್ತೋತ್ರಂ";
const collection = "bhajan";
const data = {kannada_title:"ಶ್ರೀ ಗಣೇಶ ಪಂಚರತ್ನ ಸ್ತೋತ್ರಂ",english_title:" Shri Ganesh pancharatna stotram",kannada:"ರಚನೆ : ಶ್ರೀ ಶಂಕರಾಚಾರ್ಯರು\n\nಮುದಾಕರಾತ್ತ ಮೋದಕಂ ಸದಾ ವಿಮುಕ್ತಿ ಸಾಧಕಮ್ |\nಕಲಾಧರಾವತಂಸಕಂ ವಿಲಾಸಿಲೋಕ ರಕ್ಷಕಮ್ |\nಅನಾಯಕೈಕ ನಾಯಕಂ ವಿನಾಶಿತೇಭ ದೈತ್ಯಕಮ್ |\nನತಾಶುಭಾಶು ನಾಶಕಂ ನಮಾಮಿ ತಂ ವಿನಾಯಕಮ್ ||೧||\n\nನತೇತರಾತಿ ಭೀಕರಂ ನವೋದಿತಾರ್ಕ ಭಾಸ್ವರಮ್ |\nನಮತ್ಸುರಾರಿ ನಿರ್ಜರಂ ನತಾಧಿಕಾಪದುದ್ಧರಮ್ |\nಸುರೇಶ್ವರಂ ನಿಧೀಶ್ವರಂ ಗಜೇಶ್ವರಂ ಗಣೇಶ್ವರಮ್ |\nಮಹೇಶ್ವರಂ ತಮಾಶ್ರಯೆ ಪರಾತ್ಪರಂ ನಿರಂತರಮ್ ||೨||\n\nಸಮಸ್ತ ಲೋಕ ಶಂಕರಂ ನಿರಸ್ತ ದೈತ್ಯ ಕುಂಜರಮ್ |\nದರೇತರೋದರಂ ವರಂ ವರೇಭ ವಕ್ತ್ರಮಕ್ಷರಮ್ |\nಕೃಪಾಕರಂ ಕ್ಷಮಾಕರಂ ಮುದಾಕರಂ ಯಶಸ್ಕರಮ್ |\nಮನಸ್ಕರಂ ನಮಸ್ಕೃತಾಂ ನಮಸ್ಕರೋಮಿ ಭಾಸ್ವರಮ್ ||೩||\n\nಅಕಿಂಚನಾರ್ತಿ ಮಾರ್ಜನಂ ಚಿರಂತನೋಕ್ತಿ ಭಾಜನಮ್ |\nಪುರಾರಿ ಪೂರ್ವ ನಂದನಂ ಸುರಾರಿ ಗರ್ವ ಚರ್ವಣಮ್ |\nಪ್ರಪಂಚನಾಶ ಭೀಷಣಂ ಧನಂಜಯಾದಿ ಭೂಷಣಮ್ |\nಕಪೋಲ ದಾನವಾರಣಂ ಭಜೇ ಪುರಾಣ ವಾರಣಮ್ ||೪||\n\nನಿತಾಂತಕಾಂತ ದಂತಕಾಂತಿಮಂತಕಾಂತಕಾತ್ಮಜಮ್ |\nಅಚಿಂತ್ಯ ರೂಪಮಂತಹೀನ ಮಂತರಾಯ ಕೃಂತನಮ್ |\nಹೃದಂತರೆ ನಿರಂತರಂ ವಸಂತಮೇವ ಯೋಗಿನಾಮ್ |\nತಮೇಕದಂತಮೇವ ತಂ ವಿಚಿಂತಯಾಮಿ ಸಂತತಮ್ ||೫||\n\nಮಹಾಗಣೇಶ ಪಂಚರತ್ನಮಾದರೇಣ ಯೋನ್ವಹಮ್ |\nಪ್ರಜಲ್ಪತಿ ಪ್ರಭಾತಕೆ ಹೃದಿ ಸ್ಮರನ್ ಗಣೇಶ್ವರಮ್ |\nಅರೋಗತಾಮದೋಷತಾಂ ಸುಸಾಹಿತೀಂ ಸುಪುತ್ರತಾಮ್ |\nಸಮಾಹಿತಾಯು ರಷ್ಟಭೂತಿಮಭ್ಯುಪೈತಿ ಸೋಚಿರಾತ್ ||\n\n**************************\n\n",english:"Shri Ganesha Pancharatna Stotra written by Shree Adi Shankaracharya and sung by M.S. Subbalaxmi\n\nMudakaratta modakam sada vimukti sadhakam |\nkaladharavatamsakam vilasiloka rakshakam |\nanayakaika nayakam vinasiteba daityakam |\nnatasubasu nasakam namami tam vinyakam ||1||\n\nNatetarati bikaram navoditarka basvaram |\nnamatsurari nirjaram natadhikapaduddharam |\nsuresvaram nidhisvaram gajesvaram ganesvaram |\nmahesvaram tamasraye paratparam nirantaram ||2||\n\nSamasta loka Shakaram nirasta daitya kunjaram |\ndaretarodaram varam vareba vaktramakSharam |\nkrupakaram kshamakaram mudakaram yashaskaram |\nmanaskaram namaskrutam namaskaromi bssvaram ||3||\n\nakinchanarti marjanam chirantanokti bajanam |\npurari purva nandanam surari garva charvanam |\nprapanchanasha bishanam dhananjayadi bushamam |\nkapola danavaranam Baje purana varanam ||4||\n\nnitantakanta dantakantimantakantakatmajam |\nachintya rupamantahina mantaraya kruntanam |\nhrudantare nirantaram vasantameva yoginam |\ntamekadantameva tam vichintayami santatam ||5||\n\nMahaganesha pancharatnamadarena yonvaham |\nprajalpati prabatake hrudi smaran ganesvaram |\narogatamadoshatam susahitim suputratam |\nsamahitayu rashtabutimabyupaiti sochirat ||\n\nClick the link to listen song by M.S.Subbalaxmi\n\n",meta:"",tags:["ganapati"],media:"https://www.youtube.com/watch?v=FRXp9VUAhsw"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶ್ರೀ-ಗಣೇಶ-ಪಂಚರತ್ನ-ಸ್ತೋತ್ರಂ.json",
	rawData: "",
};

export { _internal, collection, data, id };
