const id = "ಶ್ರೀಶ-ಕೊಳಲನೂದಿದನಿಂದು";
const collection = "bhajan";
const data = {kannada_title:"ಶ್ರೀಶ ಕೊಳಲನೂದಿದನಿಂದು",english_title:"Sreesha kolalanoodidanindu",kannada:"ಶ್ರೀಶ ಕೊಳಲನೂದಿದನಿಂದು  ಶ್ರೀಧರನಿಂದು\nಶ್ರೀಶ ಕೊಳಲನೂದಿದನಿಂದು\nವಾಸವ ವಂದಿತ ವಾಸಜ ಸೇವಿತ\nವಾಸುಕಿ ಶಯನನು ವಾರೆ ಸುನೋಟದಿ\nಶ್ರೀಶ ಕೊಳಲನೂದಿದನಿಂದು\nಶ್ರೀಧರನಿಂದು ಶ್ರೀಶ ಕೊಳಲನೂದಿದನಿಂದು   || ೧ ||\n\nಬೆರಳ ಸಂದಿಲಿ ಮುರಳಿ ಪಿಡಿದು\nಮುರಾರಿ ತಾನು ಹರುಷದಿಂದಲಿ ಸ್ವರಗಳ ನುಡಿದು\nವಾರಿಜ  ನೇತ್ರ ಅರಳು ಮಲ್ಲಿಗೆ ಸ್ವರಗಳ ಮುಡಿದು\nಕೊರಳ ಪದಕ ಹಾರ ಕೌಸ್ತುಭ ಶೋಭಿತ\nಮರಳು ಮಾಡುತ ಮಡದಿಯರೆಲ್ಲರ\nಶ್ರೀಶ  ಕೊಳಲನೂದಿದನಿಂದು ಶ್ರೀಧರನಿಂದು\nಶ್ರೀಶ  ಕೊಳಲನೂದಿದನಿಂದು   || ೨ ||\n\nಗೌರಿ ಗಾಂಧಾರಿ ಗೌಳಿ ಪಂತು ಗೌರೀಶ ಭೂಷಣ\nಚೌರಿ ಸಾರಂಗ ಮೋಹನನಿಂತು ಕಾವೇರಿ ಶೃತಿ\nಭೈರವಿ ವ್ಯಾಗಡೆ ಊದುತ ನಿಂತು\nಮಾರಜನಕ ತಾನಾನಂದದಿಂದಲಿ\nವೀರ ಶ್ರೀ ಕೃಷ್ಣನು ವಿಧ ವಿಧ ರಾಗದಿ\nಶ್ರೀಶ  ಕೊಳಲನೂದಿದನಿಂದು ಶ್ರೀಧರನಿಂದು\nಶ್ರೀಶ ಕೊಳಲನೂದಿದನಿಂದು  || ೩ ||\n\nನಾರದ ತುಂಬುರು ನಾಟ್ಯವನಾಡಿ ನಳಿನ ನಾಭನ\nಗಿರಿಜಾ ಪತಿಯು ವಂದಿಸಿ ಬೇಡಿ\nಗೋಪಾಲ ಕೃಷ್ಣನ ಭಾರತಿ ಪತಿ ತಾ ಕೊಂಡಾಡಿ\nವರಗುರು ವಂದಿತ ವಿಜಯವಿಠಲರೇಯ\nಹರುಷವ ಪಡಿಸುತ ವನಿತೆಯರೆಲ್ಲರ\nಶ್ರೀಶ  ಕೊಳಲನೂದಿದನಿಂದು ಶ್ರೀಧರನಿಂದು\nಶ್ರೀಶ ಕೊಳಲನೂದಿದನಿಂದು\nವಾಸವ ವಂದಿತ ವಾಸಜ ಸೇವಿತ\nವಾಸುಕಿ ಶಯನನು ವಾರೆ ಸುನೋಟದಿ\nಶ್ರೀಶ ಕೊಳಲನೂದಿದನಿಂದು ಶ್ರೀಧರನಿಂದು\nಶ್ರೀಶ ಕೊಳಲನೂದಿದನಿಂದು  ಕೊಳಲನೂದಿದನಿಂದು ಕೊಳಲನೂದಿದನಿಂದು || ೪ ||\n\n",english:"Sreesha kolalanoodidanindu sridharanindu Sreesha kolalanoodidanindu | vaasava vandita vaasaja sevita vasuki shayananu vaare sunotadi Sreesha kolalanoodidanindu sridharanindu   Sreesha kolalanoodidanindu ||\n\nBerala sandili murali pididu murari taanu harushadindali swaragala nudidu | varija netra aralu mallige swaragala mudidu | korala padaka haara koustubha shobhita | maralu maduta madadiyarellara  |Sreesha kolalanoodidanindu sridharanindu   Sreesha kolalanoodidanindu ||\n\nGowri gandhari gowli pantu gowreesha bhushana |chouri saranga mohana nintu kaveri shruti | bhairavi vyagade uduta nintu | marajanaka taanaanandadindali | veera sri krishnanu vidha vidha raagadi |Sreesha kolalanoodidanindu sridharanindu   Sreesha kolalanoodidanindu ||\n\nNarada tumburu natyavanadi nalinanaabhana girija patiyu vandhisi bedi | gopalakrishnana bharati pati taa kondadi varaguru vandita vijayavittalaraaya | harushava padisuta vaniteyarellara| Sreesha kolalanoodidanindu sridharanindu   Sreesha kolalanoodidanindu ||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=Bbx4LN1vGLc"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶ್ರೀಶ-ಕೊಳಲನೂದಿದನಿಂದು.json",
	rawData: "",
};

export { _internal, collection, data, id };
