const id = "ಶ್ರೀ-ಲಲಿತಾ-ಪಂಚರತ್ನ -ಸ್ತೋತ್ರಂ";
const collection = "bhajan";
const data = {kannada_title:"ಶ್ರೀ ಲಲಿತಾ ಪಂಚರತ್ನ  ಸ್ತೋತ್ರಂ",english_title:"Shri Lalita Pancha Ratna Stotram",kannada:"ಪ್ರಾತಃ ಸ್ಮರಾಮಿ ಲಲಿತಾವದನಾರವಿಂದಂ\nಬಿಂಬಾಧರಂ ಪೃಥುಲಮೌಕ್ತಿಕಶೋಭಿನಾಸಮ್ |\nಆಕರ್ಣದೀರ್ಘನಯನಂ ಮಣಿಕುಂಡಲಾಢ್ಯಂ\nಮಂದಸ್ಮಿತಂ ಮೃಗಮದೋಜ್ಜ್ವಲಫಾಲದೇಶಮ್ || 1 ||\n\nಪ್ರಾತರ್ಭಜಾಮಿ ಲಲಿತಾಭುಜಕಲ್ಪವಲ್ಲೀಂ\nರಕ್ತಾಂಗುಳೀಯಲಸದಂಗುಳಿಪಲ್ಲವಾಢ್ಯಾಮ್ |\nಮಾಣಿಕ್ಯಹೇಮವಲಯಾಂಗದಶೋಭಮಾನಾಂ\nಪುಂಡ್ರೇಕ್ಷುಚಾಪಕುಸುಮೇಷುಸೃಣೀರ್ದಧಾನಾಮ್ || 2 ||\n\nಪ್ರಾತರ್ನಮಾಮಿ ಲಲಿತಾಚರಣಾರವಿಂದಂ\nಭಕ್ತೇಷ್ಟದಾನನಿರತಂ ಭವಸಿಂಧುಪೋತಮ್ |\nಪದ್ಮಾಸನಾದಿಸುರನಾಯಕಪೂಜನೀಯಂ\nಪದ್ಮಾಂಕುಶಧ್ವಜಸುದರ್ಶನಲಾಂಛನಾಢ್ಯಮ್ || 3 ||\n\nಪ್ರಾತಃ ಸ್ತುವೇ ಪರಶಿವಾಂ ಲಲಿತಾಂ ಭವಾನೀಂ\nತ್ರಯ್ಯಂತವೇದ್ಯವಿಭವಾಂ ಕರುಣಾನವದ್ಯಾಮ್ |\nವಿಶ್ವಸ್ಯ ಸೃಷ್ಟವಿಲಯಸ್ಥಿತಿಹೇತುಭೂತಾಂ\nವಿದ್ಯೇಶ್ವರೀಂ ನಿಗಮವಾಙ್ಮಮನಸಾತಿದೂರಾಮ್ || 4 ||\n\nಪ್ರಾತರ್ವದಾಮಿ ಲಲಿತೇ ತವ ಪುಣ್ಯನಾಮ\nಕಾಮೇಶ್ವರೀತಿ ಕಮಲೇತಿ ಮಹೇಶ್ವರೀತಿ |\nಶ್ರೀಶಾಂಭವೀತಿ ಜಗತಾಂ ಜನನೀ ಪರೇತಿ\nವಾಗ್ದೇವತೇತಿ ವಚಸಾ ತ್ರಿಪುರೇಶ್ವರೀತಿ || 5 ||\n\nಯಃ ಶ್ಲೋಕಪಂಚಕಮಿದಂ ಲಲಿತಾಂಬಿಕಾಯಾಃ\nಸೌಭಾಗ್ಯದಂ ಸುಲಲಿತಂ ಪಠತಿ ಪ್ರಭಾತೇ |\nತಸ್ಮೈ ದದಾತಿ ಲಲಿತಾ ಝಟಿತಿ ಪ್ರಸನ್ನಾ\nವಿದ್ಯಾಂ ಶ್ರಿಯಂ ವಿಮಲಸೌಖ್ಯಮನಂತಕೀರ್ತಿಮ್ ||\n\n",english:"Pratha smarami Lalitha vadanaravindam,\nBimbadaram pradhula maukthika shobhi nasam,\nAakarna deerga nayanam mani kundaladyam,\nMandasmitham mruga madojjwala phala desam. || 1 ||\n\nPrathar Bhajami Lalitha Bhuja kalpa vallim,\nRathnanguleeya lasathanguli pallavadyam,\nManikhya hema valayangadha Shobha maanam,\nPundreshu Chapa kusumeshu sruneen dadhanam. || 2 ||\n\nPrathar namami lalitha charanaravindam,\nBhakteshta dana niratham bhava sindhu potham,\nPadmasanadhi sura nayaka poojaneeyam,\nPadmangusa dwaja sudarsana lanchanadyam. || 3 ||\n\nPratha sthuthave parasivaam lalithaam bhvaneem,\nTrayyanha vedhya vibhavam karunanan vadhyam,\nViswasya srushti vilaya sthithi hethu bhootham,\nVisweswareem nigama vang mana sathi dhooram. || 4 ||\n\nPrathar vadami lalithe thava punya nama,\nKameswarethi, kamalethi Maheswareethi,\nSri shambhaveethi jagatham janani parethi,\nVag deva thethi vachasa tripureswareethi. || 5 ||\n\nYa sloka panchakam idham, Lalithambikya,\nSoubhagyuam, sulalitham patathi prabhathe,\nThasmai dadathi lalitha jadithi prasanna,\nVidhyaam sriyam vimala soukha manantha keerthim||\n\n",meta:"",tags:["kannada devotional song","kannada lyrics"],media:"https://www.youtube.com/watch?v=H-VgQP5f-RQ"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಶ್ರೀ-ಲಲಿತಾ-ಪಂಚರತ್ನ -ಸ್ತೋತ್ರಂ.json",
	rawData: "",
};

export { _internal, collection, data, id };
