const id = "ಸಂಕಟ-ನಾಶನ-ಶ್ರೀ-ಗಣಪತಿ-ಸ್ತೋತ್ರ";
const collection = "bhajan";
const data = {kannada_title:"ಸಂಕಟ ನಾಶನ ಶ್ರೀ ಗಣಪತಿ ಸ್ತೋತ್ರ",english_title:" Sankata Naashana Shri Ganapati Stotra",kannada:"|| #ಸಂಕಟನಾಶನ ಶ್ರೀ #ಗಣಪತೀ ಸ್ತೋತ್ರ ||\n\nಪ್ರಣಮ್ಯ ಶಿರಸಾ ದೇವಂ ಗೌರೀಪುತ್ರಂ ವಿನಾಯಕಮ್\nಭಕ್ತಾವಾಸಂ ಸ್ಮರೇನಿತ್ಯಮ ಆಯುಷ್ಕಾಮಾರ್ಥ ಸಿಧ್ದಯೇ\n\nಪ್ರಥಮಂ ವಕ್ರತುಂಡಂ ಚ ಏಕದಂತಂ ದ್ವಿತೀಯಕಂ\nತ್ರತೀಯಂ ಕ್ರುಷ್ಣಪಿನ್ಗಾಕ್ಷಂ ಗಜವಕ್ತ್ರಂ ಚತುರ್ಥಕಂ\n\nಲಂಬೋದರಂ ಪಂಚಕಂ ಚ ಷಷ್ಠಂ ವಿಕಟಮೇವ ಚ\nಸಪ್ತಮಂ ವಿಘ್ನರಾಜೇಂದ್ರಂ ಧುಮ್ರವರ್ನಂ ತಥಾಷ್ಟಮಂ\n\nನವಮಂ ಭಾಲಚಂದ್ರಂ ಚ ದಶಮಂ ತು ವಿನಾಯಕಂ\nಏಕಾದಶಂ ಗಣಪತಿಂ ದ್ವಾದಶಂ ತು ಗಜಾನನಂ\n\nದ್ವಾದಶೈತಾನಿ ನಾಮಾನಿ ತ್ರಿಸಂಧ್ಯಂ ಯಃ ಪಠೇನ್ನರಃ\nನ ಚ ವಿಘ್ನಭಯಂ ತಸ್ಯ ಸರ್ವಸಿದ್ಧೀಕರ ಪ್ರಭೋ\n\nವಿದ್ಯಾರ್ಥೀ ಲಭತೇ ವಿದ್ಯಾಂ ಧನಾರ್ಥೀ ಲಭತೇ ಧನಂ\nಪುತ್ರಾರ್ಥೀ ಲಭತೇ ಪುತ್ರಾನ್ಮೋಕ್ಷಾರ್ಥೀ ಲಭತೇ ಗತಿಂ\n\nಜಪೆದ್ಗಣಪತಿಸ್ತೋತ್ರಂ ಷಡಭಿರ್ಮಾಸೇ ಫಲಂಲಭೇತ್\nಸಂವತ್ಸರೇಣ ಸಿಧ್ದೀಂಚ ಲಭತೇ ನಾತ್ರಸಂಶಯಃ\n\nಅಷ್ಟೇಭ್ಯೋ ಬ್ರಾಹ್ಮಣೇಭ್ಯಸ್ಚ ಲಿಖಿತ್ವಾ ಯಃ ಸಮರ್ಪಯೇತತಸ್ಯ ವಿದ್ಯಾ ಭಾವೇತ್ಸರ್ವಾ\nಗಣೇಶಸ್ಯ ಪ್ರಸಾದತಃ\n\n|| ಇತಿ ಶ್ರೀನಾರದಪುರಾಣೇ ಸಂಕಟನಾಶನಂ ನಾಮ ಶ್ರೀ ಗಣಪತಿಸ್ತೋತ್ರಂ ಸಂಪೂರ್ಣಂ ||\n\n",english:"Pranamya Sirasa devam Gauri Puthram Vinayakam\nBhaktavasam Smarennithyam Ayuh Kamartha Siddaye (1)\n\nPrathamam Vakrathundam cha Ekadantham Dvithiyakam\nThrithiyam Krishna Pingaaksham Gajavakthram Chathurthakam (2)\n\nLambodaram Panchamam cha Shashtam Vikatameva cha\nSaptamam Vighna Rajam cha Dhoomravarnam thathashtakam (3)\n\nNavamam Phala Chandram cha Dasamam thu Vinayakam\nEkadasam Ganapathim Dwadasam thu Gajananam (4)\n\nDwadasaithani Namaani Thri Sandhyam Yah Pathennarah\nNa cha Vighna Bhayam thasya Sarva Siddhi karim Prabho! (5)\n\nVidyarthi Labhate Vidyam Dhanarthi Labhate Dhanam\nPuthrarthi Labhate Putraam Mokshaarthi Labhate Gatim (6)\n\nJapeth Ganapthi Stotram Shadbhirmaasai Phalam Labheth\n,Samvatsarena Siddhim cha Labhate Naathra Samsayaha !\n\nAshtabhyo Brahmanebhyash cha Likhitwa yah Samarpayeth\nThasya Vidya bhavetsarva Ganeshasya Prasadathaha !! (8)\n\n|| Ithi Sri Narada Purane Sankashta Nashana Ganapathi Sthothram Sampoornam||\n\n",meta:"",tags:["ganapati","kannada devotional song"],media:"https://www.youtube.com/watch?v=vEuV3U3BFfQ"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಸಂಕಟ-ನಾಶನ-ಶ್ರೀ-ಗಣಪತಿ-ಸ್ತೋತ್ರ.json",
	rawData: "",
};

export { _internal, collection, data, id };
