const id = "ಸತ್ಯ-ಜಗತಿದು-ಪಂಚ-ಭೇದವು-ನಿತ್ಯ-ಶ್ರೀ-ಗೋವಿಂದನ";
const collection = "bhajan";
const data = {kannada_title:"ಸತ್ಯ ಜಗತಿದು ಪಂಚ ಭೇದವು ನಿತ್ಯ ಶ್ರೀ ಗೋವಿಂದನ",english_title:" Satya jagatidu pancha bhedhavu",kannada:"ಸತ್ಯ ಜಗತಿದು ಪಂಚ ಭೇದವು , ನಿತ್ಯ ಶ್ರೀ ಗೋವಿಂದನ\nಕೃತ್ಯ ತಿಳಿದು ತಾರತಮ್ಯದಿ ಕೃಷ್ಣನಧಿಕೆಂದು ಸಾರಿರೈ ||\n\nಜೀವ ಈಶಗೆ ಭೇದ ಸರ್ವತ್ರ ಜೀವ ಜೀವಕೆ ಭೇದವು\nಜೀವ ಜಡಕೆ ಜಡ ಜಡಕೆ ಭೇದ ಜೀವ ಜಡ ಪರಮಾತ್ಮಗೆ ||\n\nಮಾನುಷೋತ್ತಮರಧಿಕ ಕ್ಷಿತಿಪರು ಮನುಜ ದೇವ ಗಂಧರ್ವರು\nಪಿತೃ ಅಜಾನಜ ಕರ್ಮಜರು ಉಕ್ತ ಶೇಷ ಶತಸ್ಥರು ||\n\nಗಣಪ ಮಿತ್ರರು ಸಪ್ತಋಷಿಗಳು ವಹ್ನಿ ನಾರದ ವರುಣನು\nಇನಜಗೆ ಸಮ ಚಂದ್ರ ಸೂರ್ಯರು ಮನುಸುತೆಯು ಹೆಚ್ಚು ಪ್ರವಹನು ||\n\nದಕ್ಷ ಸಮ ಅನಿರುದ್ಧ ಶಚಿ ಗುರು ರತಿ ಸ್ವಾಯಂಭುವರಾರ್ವರು\nಪಕ್ಷ ಪ್ರಾಣನಿಗಿಂತ ಕಾಮನು ಕಿಂಚಿದಧಿಕನು ಇಂದ್ರನು ||\n\nದೇವೇಂದ್ರನಿಂದಧಿಕ ಮಹರುದ್ರ ರುದ್ರ ಸಮ ಶೇಷಗರುಡರು\nಗರುಡ ಶೇಷರಿಗಥಿಕರೆನಿಪರು ದೇವಿ ಭಾರತಿ ಸರಸ್ವತಿ ||\n\nವಾಯುವಿಗೆ ಸಮರಿಲ್ಲ ಜಗದೊಳು ವಾಯು ದೇವರೆ ಬ್ರಹ್ಮರು\nವಾಯು ಬ್ರಹ್ಮಗೆ ಕೋಟಿ ಗುಣದಿಂದ ಅಧಿಕ ಶಕ್ತಳು ಶ್ರೀ ರಮಾ ||\n\nಅನಂತ ಗುಣದಿಂದ ಲಕುಮಿಗಿಂತ ಅಧಿಕ\nಪುರಂದರವಿಠಲ\nನು\nಘನ ಸಮರು ಇವಗಿಲ್ಲ ಜಗದೊಳು ಹನುಮ ಹೃತ್ಪದ್ಮ ವಾಸಿಗೆ ||\n\n",english:"Satya jagatidu pancha bhedhavu nitya sri govindana\nkrutya tilidu taaratamyadi krishnanadhikendu sarirai ||\n\nJeeva eeshage bhedha sarvartra jeeva jeevake bhedhavu\njeeva jadake jada jadake bhedha jeeva jada paramatmage ||\n\nMaanushottamaradhika kshitiparu manuja deva gandharvaru\npitru ajanaka karmajaru ukta shesha shatastaru ||\n\nGanapa mitraru saptarushigalu vahni narada varunanu\nenajage sama chandra suryaru manusuteya hecchu pravahanu ||\n\nDaksha sama aniruddha shachi guru rati swaayambhuvaraarvaru\npaksha prananiginta kaamanu kinchidadhikanu indranu ||\n\nDevendranindadhika maharudra rudra sama sheshagarudaru\ngaruda shesharigathikareniparu devi bharati saraswati ||\n\nVayuvige samarilla jagadolu vayu devare brahmaru\nvayu brahmage koti gunadinda adhika shaktalu sri rama ||\n\nAnanta gunadinda lakumiginta adhika\npurandaravittala\nnu\nghana samaru ivagilla jagadolu hanuma hrutpadma vaasige ||\n\n",meta:"",tags:["krishna","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=3P68L39Fpz0"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಸತ್ಯ-ಜಗತಿದು-ಪಂಚ-ಭೇದವು-ನಿತ್ಯ-ಶ್ರೀ-ಗೋವಿಂದನ.json",
	rawData: "",
};

export { _internal, collection, data, id };
