const id = "ಸುಂದರಿ-ರಂಗನ-ತಂದು-ತೋರ";
const collection = "bhajan";
const data = {kannada_title:"ಸುಂದರಿ ರಂಗನ ತಂದು ತೋರ",english_title:" Sundari rangana tandu tora",kannada:"ಸುಂದರಿ ರಂಗನ ತಂದು ತೋರ | ಒಂದರಘಳಿಗ್ಯಾಗೆ || ಪ ||\n\nಮತ್ಸ್ಯನಾಗಿ ಮೊದಲಿನಲ್ಲಿ | ಕೂರ್ಮನಾಗಿ ಕೊರೆನು ಕಾಯ್ದ |\nದೈತ್ಯರ ಕೊಂದ ಬಹು ಕ್ರೋಧದಿಂದ ದುರುಳ ಹಿರಣ್ಯಕನ ಕರುಳು ಬಗೆದು ತೋಡಿ\nಕೊರಳೊಳಗೆ ಧರಿಸಿದನು ಸರಗಳನ್ನೇ ಮಾಡಿ |\nಕೊರಳು ಕೊಯ್ದ ಎಲ್ಲಮ್ಮನ ಪುತ್ರನಾಗಿ ಕಾಯ್ದಿ ಸರಳ ಬಾಣವನ್ನೇ ಹೂಡಿ\nಲಂಕಾದ್ರಿ ಮಥನ ಮಾಡಿ ಎರಳ ಗಂಗೆಯರ ಪತಿವೃತೆಯರ ಕೆಡಿಸಿದನು ಕೂಡಿ |\nಮರಳು ತನದಿಂದ ಸೆಗೆದ ಹಯವನೇರಿ ಓಡಿ ||೧||\n\nನೀರೊಳು ಮೀನನಾಗಿ ಅಲೆವ | ಧರೆ ಭಾರವನ್ನು ಹೊರುವ |\nವರಹನಾಗಿ ನರಕಾಸುರನನು ತರೆವ ಕೋರೇಲಿ ಮಣ್ಣು ಬಗೆವ |\nಒಡೆ ಮುಡಿ ಕಂಬದಿಂದ ಘುಡಘುಡಿಸುತ ಬಂದ ಧೃಢವುಳ್ಳ ಬಲಿಚಕ್ರವರ್ತಿ\nಪಾಲಿಸಿದ ವರವಾ | ಕೊಡಲಿ ಪಿಡಿದು ಹಡೆದ ತಾಯಿ ಶಿರವಾ ಕಡಿದಾ |\nಮಡದಿ ಒಯ್ದ ರಾವಣನ ಕಡೆದು ಶಿರವಾ ದಾಡಿ ಬಿಟ್ಟು ತಿರುಗುವಂಥ\nತ್ರಿಪುರರರಂಥಪುರವಾ ಏರಿಸಿದ ಅಶ್ವಮೇಧ ಅರ್ಥಿಯಿಂದ ಮೆರೆವಾ ||೨||\n\nಬ್ರಹ್ಮಗೆ ಒಲಿದು ವೇದವ ತರುವ ಬ್ರಹ್ಮಾಂಡವನ್ಹೊರುವ |\nಗಮ್ಮೀಲಿ ಕಾಯ್ದವ- ನಾಗಿರುವ ಸುಮ್ಮನೆ ಹೋಗಿ ಬರುವಾ |\nಸಿಟ್ಟಿನಿಂದ ನಾರಸಿಂಹ ರೂಪನಾಗಿ ಬಂದ |\nಸೃಷ್ಟಿಯೊಳು ಪರಶುರಾಮ ರೇಣುಕೆಯ ಕಂದ |\nಕಷ್ಟವನ್ನಾಚರಿಸಿದನು ರಾಮ ವನವಾಸದಿಂದ |\nಕೃಷ್ಣಾವತಾರ ಬೌದ್ಧ ಕಲ್ಕಿ ರೂಪ ಒಂದೊಂದಾ |\nಇಷ್ಟುಪರಿ ವರ್ಣಿಸುತ ಹತ್ತಾವತಾರ ಚೆಂದ |\nಸೃಷ್ಠಿಯೋಳು ಕಾಗಿನೆಲೆ ಆದಿಕೇಶವನಿಂದಾ ||\n\n",english:"Sundari rangana tandu tora | ondaraghaligyaage ||pa||\n\nMatsyanaagi modalinalli | koormanaagi korenu kaayda |daityara konda bahu krodhadinda durula hiranyakana karulu bagedu todi koralolage dharisidanu saragalanne maadi|koralu koyda ellammana putranaagi kaydi sarala baanavanne hoodi lankaadri mathana maadi erala gangeyara pativruteyara kedisidanu koodi | maralu tanadinda segeda hayavaneri odi||1||\n\nNeerolu meenanaagi aleva | dhare bhaaravannu horuva | varahanaagi narakaasurananu tareva koreli mannu bageva | ode mudi kambadinda ghudaghudisuta banda dhrudhavulla bali chakravarti| paalisida varavaa | kodali pididu hadeda tayi shirava kadidaa | madadi oyda raavanana kadedu shiravaa daadi bittu tiruguvanta | tripurara antapuravaa arisida ashwamedha arthiyinda merevaa ||2||\n\nBrahmage olidu vedava taruva brahmaandavanohruva |gammeeli kaaydavanaagiruva summane hogi baruvaa | sittininda naarasimha roopanaagi banda | srushtiyolu parashuraama renukeya kanda| kashtavannaacharisidanu raama vanavaasadinda | krishnaavataara boudha kalki roopa ondondaa | eshtu pari varnisuta hattaavataara chanda| srushtiyolu kaaginele adikeshavanindaa||3||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=h_yqgFqQyok"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಸುಂದರಿ-ರಂಗನ-ತಂದು-ತೋರ.json",
	rawData: "",
};

export { _internal, collection, data, id };
