const id = "ಸಂಗಸುಖವ-ಬಯಸಿ-ಬದುಕಿರೋ";
const collection = "bhajan";
const data = {kannada_title:"ಸಂಗಸುಖವ ಬಯಸಿ ಬದುಕಿರೋ",english_title:" sangasukhava bayasi badukiro",kannada:"ಸಂಗಸುಖವ ಬಯಸಿ ಬದುಕಿರೋ\nರಂಗವಲಿದ ಭಾಗವತರ || ಪ||\nಸಂಗಸುಖವ ಬಯಸಿ ಬದುಕಿ\nಭಂಗಪಡಿಪ ಭವವ ನೂಕಿ\nಹಿಂಗದೇ ನರಸಿಂಗನನ್ನು\nಕಂಗಳಿಂದ ಕಾಣುತಿಹರ ||ಅ.ಪ.||\nಪುಟ್ಟಿದಾರಭ್ಯ ಪರಮ ವೈಷ್ಣವಾಧ್ಯಕ್ಷರೆನಿಸಿ\nಶಿಷ್ಟ ಸದಾಚಾರದಲ್ಲಿ ನಿಷ್ಠರಾಗಿ ನಿತ್ಯ ಮುದ್ದು\nಕೃಷ್ಣ ಕೀರ್ತನೆಯನು ಪಾಡುತ ಕಾವ್ಯಕರ್ಮ\nಬಿಟ್ಟು ಭಕ್ತಿಯನೆ ಮಾಡುತ ಮಧ್ವಮತವ\nಪುಷ್ಟಿಗೈಸಿ ಖಳರ ಕಾಡುತ ಬಂದ ಲಾಭ\nನಷ್ಟ ತುಷ್ಟಿಗಳಿಗೆ ಒಡಂಬಟ್ಟ ಬಗೆಯ ಪೇಳಲೆಷ್ಟು ||1||\nಭೂತದಯಾಶೀಲರಾದ ನೀತ ಗುರು ಜಗ-\nನ್ನಾಥ ವಿಠಲಾಂಕಿತವನು ಪಡೆದು ಸಂಗೀತ\nವೃತ್ತ ಪದ ಸುಳಾದಿಯ ಪೇಳಿ ಪ್ರೇ-\nಮಾತಿಶಯದಿ ಒಲಿಸಿಕೊಂಡು ಮಧುವಿರೋಧಿಯ ಒಲಿಸಿಕೊಂಡ\nಜಾತರಾಗಿ ಜವನಬಾಧೆಯ ಬಯಲು ಮಾಡಿ\nಖ್ಯಾತರಾಗಿಹರು ಪುಸಿಯ ಮಾತಿದಲ್ಲ ಮರೆಯಸಲ್ಲ ||2||\nಮೇದಿನಿಯೊಳಗುಳ್ಳ ಗಂಗಾದಿತೀರ್ಥ ಸತಿಗಳಿವರ\nಕಾದುಕೊಂಡಿಹರು ಬಿಡದೆ ಸ್ವಾದಿರಾಜೇಂದ್ರರ ಪ್ರ-\nಸಾದದಿಂದ ಹರಿಕಾಥಾಮೃತ ಸಾರತತ್ವ\nಸಾಧುಜನರಿಗಾಗಿ ಪ್ರಾಕೃತ ಪದ್ಧತಿಯಲಿ\nಸಾದರದಲಿ ಪೇಳಿ ದುಷ್ಕoತ ದೂರಮಾಡಿ\nಮೋದಿಸುವರಿಗೆಣೆಗಾಣೆ ಶ್ರೀದ ವಿಠಲನಾಣೆ ||3||\n\n",english:"Sangasukhava bayasi badukiro\nrangavalida bhagavatara || pa||\nsangasukhava bayasi baduki\nbhangapadipa bhavava nuki\nhingade narasinganannu\nkangalinda kanutihara ||a.Pa.||\nPuttidarabhya parama vaisnavadhyaksarenisi\nShishta sadacharadalli nishtaragi nitya muddu\nkrishna kirtaneyanu paduta kavyakarma\nbittu bhaktiyane maduta madhvamatava\npushtigaisi khalara kaduta banda labha\nnashta tushtigalige odambatta bageya pelaleshtu ||1||\nBhutadayasheelarada nita guru jaga-\nnnatha viṭhalankitavanu paḍedu sangita\nvrutta pada suladiya peli pre-\nmatishayadi olisikondu madhuvirodhiya olisikonda\njataragi javanabadheya bayalu madi\nkhyataragiharu pusiya matidalla mareyasalla ||2||\nMediniyolagulla gangaditirtha satigalivara\nkadukondiharu bidade svadirajendrara pra-\nsadadinda harikathamruta saratatva\nsadhujanarigagi prakruta paddhatiyali\nsadaradali peli dushkanta duramadi\nmodisuvarigenegane sridavithalanane ||3||\n\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=BgQFDK2mjkQ"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಸಂಗಸುಖವ-ಬಯಸಿ-ಬದುಕಿರೋ.json",
	rawData: "",
};

export { _internal, collection, data, id };
