const id = "ಸಾಗಿಬಾರೈಯ-ಭವರೋಗದ-ವೈದ್ಯನೆ";
const collection = "bhajan";
const data = {kannada_title:"ಸಾಗಿಬಾರೈಯ ಭವರೋಗದ ವೈದ್ಯನೆ",english_title:" Sagi barayya bavarogada vaidyane",kannada:"ಸಾಗಿಬಾರೈಯ ಭವರೋಗದ ವೈದ್ಯನೆ\nಬಾಗಿ ನಿನಗೆ ಚೆನ್ನಾಗಿ ಸ್ತುತಿಪೆ ನಿಂದು\nಭಾಗೀರಥಿ ಪಿತ ಭಾಗವತರ ಸಂಯೋಗ ರಂಗ ಉರಗಗಿರಿ ವೆಂಕಟ ||pa||\n\nರಥದ ಮಧ್ಯದಲಿಪ್ಪನೆ ರಥಾಂಡಜ ವಾಹನನೆ\nರಥಾಂಗಪಾಣಿಯೆ ದಶರಥ ನೃಪಬಾಲ\nಪಾರ್ಥಗೆ ಒಲಿದವನ ರಥವ ನಡಿಸಿ ಅತಿರಥ ಮಹರಥರ ವಿರಥರ ಮಾಡಿ ಗೆಲಿಸಿದೆ\nಪ್ರಥಮ ದೈವವೆ ಮನ್ಮಥಪಿತ ದೈತ್ಯರ-\nಮಥನ ಭಕ್ತರ ಮನೋರಥನೆ ತಾರಾ-\nಪಥವರ್ಣನೆ ತವ ಕಥಾಶ್ರವಣದಲಿ ಸುಪಥವನು ತೋರಿಸು ಪ್ರಥಮಾಂಗದೊಡೆಯ ||1||\n\nನಿಲ್ಲದೆ ಬರುವುದು ಪುಲ್ಲಲೋಚನೆ ಸಿರಿವಲ್ಲಭ ಸರ್ವರಿಗು ಬಲ್ಲಿದನೆ ಅಪ್ರತಿಮಲ್ಲ ಮುರವಿರೋಧಿ ಮೆಲ್ಲಮೆಲ್ಲನೆ ಪಾದ\nಪಲ್ಲವ ತೋರುತ್ತ ಎಲ್ಲಾ ಕಾಲದಿ ನಮ್ಮ-\nನೆಲ್ಲರುದ್ಧರಿಪುದು ಎಲ್ಲಿ ನಿನಗೆ ಸರಿಯಿಲ್ಲವೊ ನೋಡಲು ಸಲ್ಲುವುದೋ ಬಿರುದಲ್ಲಿಗಲ್ಲಿಗೆ ಗುಣಬಲ್ಲವರಾರಿನ್ನು\nನೆಲ್ಲಕಟ್ಟು ಕೊನೆಯಲ್ಲಿಪ್ಪ ವಿಶ್ವ ||2||\n\nಬೊಮ್ಮ ಮೊದಲು ಮನುಜೋತ್ತಮರು ಕಡೆಯಾಗಿ\nನಿಮ್ಮ ದಾಸರು ಅವರ ಸಮ್ಮಂಧಿಗಳ ಪಾದ-\nನೆಮ್ಮಿಕೊಂಡಿಪ್ಪಂಥ ಧಮ್ಮನು ನಾ ಸರ್ವೋ-\nತ್ತುಮ್ಮಾನೇಕ ಗುಣಮಹಿಮ ವಿಭೂಷಿತ\nರಮ್ಮೆಧರಣಿದೇವಿ ಇಮ್ಮಹಿಷೇರ ಕೂಡಿ\nಸಮುಖನಾಗುತ ಸುಮ್ಮನೆ ಬಾ ಬಾ\nಹಿಮ್ಮೆಟ್ಟಿದೆ ಸಿರಿ ವಿಜಯವಿಠ್ಠಲ ಅನು-\nಪಮ್ಮಚರಿತ ಪರಬೊಮ್ಮ ತಿರುಮಲೇಶ ||3||\n\n",english:"Sagi barayya bavarogada vaidyane\nBaguve ninage chennagi stutisi indu |\nBagiratipita bagavatara samyoga\nRanga uragagiri venkata |\n\nRathada madhyadallippane rathaganujavahana\nRathangapaniye dasarathanrupati pala |\nParthage sarathiyagi rathava nadesi |\nAthirathamaharathara virathara madi geliside |\nPrathamadaivave manmathapitadaityara\nMathana Baktara manoratha paripurnane\nPathamanivarnane kathasravanadali\nSupathava torisutippa prathamanganodeya | 1 |\n\nNillade baruvudu pullalochana siri-\nvallaba sarvarige ballidane aprati-\nmalla muravirodhiye mella mellane\npada pallava torisutta illa kaladi namma\nNella uddharisuvudu elli ninage sari-\nyillavo nodalu salluvudo birudalli\ngallige guna ballavararinnu –\nnella koti koneyalippa vishva || 2 ||\n\nBomma modalu manujottamaru kadeyagi\nnimma dasaru avara sambandhigala pada\nnammikondippa adhama na sarvottamane\naneka mahima sarvabushita iremme\nmahishare gudi sammoga-\nvaguta gammane ba ba |\nhimmettide sirivijayavithala anupamma-\ncharita parabomma tirumalesa ||3||\n\n",meta:"",tags:["dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=wb7asSAgQ9Y"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಸಾಗಿಬಾರೈಯ-ಭವರೋಗದ-ವೈದ್ಯನೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
