const id = "ಹೇಳುವೆ-ಕಥೆ-ಹೇಳುವೆ";
const collection = "bhajan";
const data = {kannada_title:"ಹೇಳುವೆ ಕಥೆ ಹೇಳುವೆ",english_title:" Heluve kathe heluve keliri kathe heluve ",kannada:"ಹೇಳುವೆ ಕಥೆ ಹೇಳುವೆ ಕೇಳಿರಿ ಕಥೆ ಹೇಳುವೆ\nಗೌರಿ ಪುತ್ರ ವಿನಾಯಕನಿಗೆ ಆನೆ ಮುಖವು ಬಂದ ಕಥೆಯ\n||ಹೇಳುವೆ||\n\nಒಂದು ದಿನಾ ಪಾರ್ವತಿಯು ಸ್ನಾನ ಗ್ರಹಕೆ ಹೊರಟಲು\nಮಣ್ಣಿನಿಂದ ಮೂರ್ತಿಯ ಮಾಡಿ ಜೀವ ಅದಕ್ಕೆ ಇತ್ತಳು |\nಅಮ್ಮಾ ನಿನ್ನ ಆಜ್ಞೆಯೇನು ಎಂದು ಕೇಳಿ ಗಣಪನು |\nಕಾವಳಿರು ಎಂದಳು ಗೌರಿ ಒಲವಿಂದ ||\n||ಹೇಳುವೆ||\n\nಕಂದ ಕಾವಲಿರುವ ವೇಳೆ ಶಿವನು ಅಲ್ಲಿ ಬಂದ\nಶಿವನು ಯಾರೆಂದರಿಯದೆ ನಿಲ್ಲಿಸಿದನು ಕಂದಾ\nಒಳಗೆ ಬಿಡೆನು ಇಲ್ಲೆ ನಿಲ್ಲಿ ಕಂದ ಎನಲು\nಹರಗೆ ಉಕ್ಕಿ ಬಂತು ಆಗ ಕೋಪದ ಹೊನಲು\nಕೋಪದಾ…..ಹೊನಲೂ…….\n\nಕೋಪದಿಂದ ಶೂಲ ತೆಗೆದು ನಿಂತನು ತ್ರಿಪುರಾರಿ\nಕಂದನ ತಲೆ ಕತ್ತರಿಸಿದ ,ಕಾಮ ಸಂಹಾರಿ\nಶಬ್ದ ಕೇಳಿ ಒಳಗಿನಿಂದ ಓಡಿ ಬಂದಳು ಗೌರಿ\nಸತ್ತ ಮಗನ ಕಂಡು\nಅತ್ತು ಗೋಳಾಡಿದಳು ನಾರೀ||ಸತ್ತ||\n\nಸತ್ತ ಹುಡುಗ ತನ್ನ ಮಗನು ಎಂದು ಅರಿತ ನೊಂದ ಶಿವನು\nಒಂದು ತಲೆಯ ಅರಸಿ ತನ್ನಿ ಎಂದು ಆಜ್ಞೆ ತಂದನು\nಅರಸಿ ಹೊರಟರು ಗಣಗಳು, ಧಿಕ್ಕು ಧಿಕ್ಕಿಗೆ\nಆನೆಯೊಂದು ಮಲಗಿತ್ತು ಉತ್ತರ ಧಿಕ್ಕಿಗೆ\n\nಆನೆ ತಲೆಯ ಕತ್ತರಿಸಿ ಶಿವನ ಬಳಿಗೆ ತಂದರು\nಅದನ್ನು ಮಗನ ದೇಹಕಿಟ್ಟು ಜೀವ ತಂದನು ದೇವನು\nಜೀವ ತುಂಬಿದ ಕಂದ ತಂದೆಗೆ ವಂದನೆ ಗೈದನು ,\nಸಂತಸದಿ ಮಗನ ತಬ್ಬಿ ,ಅವಗೆ ವರವ ಇತ್ತನು||2||\n\nಇಂದಿನಿಂದ ಮೊದಲ ಪೂಜೆ ಎಂದು ನಿನಗೆ ಎಂದನು\nಗಣಗಳಿಗೆ ನಾಯಕನು ಎಂದು ಶಿವನು ನುಡಿದನು\nಅಂದಿನಿಂದ ಕಂದನಾದ ದೈವಗಳ ನಾಯಕ\nಭಕ್ತರ ವಿಘ್ನಗಳನು ಹರಿಸುವ ವಿನಾಯಕ||3||\n\n",english:"Heluve kathe heluve keliri kathe heluve |\ngouri putra vinayakanige ane mukhavu banda katheya || heluve||\n\nOndu dina parvatiyu snana grahake horatalu\nmannininda moortiya madi jeeva adake ettalu |\namma ninna ajne enu andu keli ganapanu\nkavaliru endalu gouri olavinda || heluve||\n\nKanda kavaliruva vele shivanu alli ban\nshivanu yarendariyade nillisidanu kanda\nolage bidenu elle nilli kanda enalu\nharage ukki bantu kopada honalu ||\nkopada …. honalu ….\n\nKopadinda shoola tegedu nintanu tripurari\nkandana tale kattarisida kama samhari\nshabda keli olagininda odi bandalu gouri\nsatta magana kandu\nattu goladidalu naari ||\n\nSatta huduga tanna maganu endu arita nonda shivanu\nondu taleya arasi tanni endu ajne tandanu\narasi horataru ganagalu dhikku dhikkige\naneyondu malagittu uttara dikkige\n\nAne taleya kattarisi shivana balige tandaru\nadannu magana dehakittu jeeva tandanu devanu\njeeva tumbida kanda tandege vandane gaidanu\nsantasadi magana tabbi avage varava ettanu ||\n\nIndininda modalu pooje endu ninage endanu\nganagalige nayakanu endu shivanu nudidanu\nandininda kandanada daivagala nayaka\nbhaktara vighnagalanu harisuva vinayaka ||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=1QL_rLmFF8w"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಹೇಳುವೆ-ಕಥೆ-ಹೇಳುವೆ.json",
	rawData: "",
};

export { _internal, collection, data, id };
