const id = "ಹರಿ-ನಿನ್ನೊಲುಮೆ-ಆಗುವ-ತನಕ-ಅರಿತು";
const collection = "bhajan";
const data = {kannada_title:"ಹರಿ ನಿನ್ನೊಲುಮೆ ಆಗುವ ತನಕ ಅರಿತು",english_title:" Hari ninnolumeyu aguva tanaka",kannada:"ರಚನೆ : ಶ್ರೀ ಪುರಂದರ ವಿಠ್ಠಲ\n\nಹರಿ ನಿನ್ನೊಲುಮೆ ಆಗುವ ತನಕ\nಅರಿತು ಸುಮ್ಮನಿರುವುದೇ ಲೇಸು ||ಪ||\n\nಮರಳಿ ಮರಳಿ ತಾ ಪಡೆಯದ ಭಾಗ್ಯಕೆ\nಹೊರಳಿ ಹೊರಳಿ ಅತ್ತರೆ ಬಂದೀತೆ ||ಅ.ಪ||\n\nದೂರು ಬರುವ ತೆರ ನಂಬಿಕೆ ಕೊಟ್ಟರೆ |\nದುರ್ಜನ ಬರುವುದು ತಪ್ಪಿತೆ |\nದೂರದಿ ನಿಂತು ಮೊರೆಯಿಟ್ಟು ಕೂಗಲು|\nಚೋರರಿಗೆ ದಯ ಪುಟ್ಟಿತೆ||೧||\n\nಬಾರಿ ಬಾರಿಗೆ ಪತಿವೃತತನ ಬೋಧಿಸೆ |\nಜಾರೆಗದರ ನಿಜ ಸೊಗಸೀತೆ |\nಊರು ಬಿಟ್ಟು ಪರ ಊರಿಗೆ ಹೋದರೆ |\nಪ್ರಾರಬ್ದವು ಬೇರಾದೀತೆ||೨||\n\nಪಟ್ಟೆ ಮಂಚ ತಿರುವಿಟ್ಟರೆ ಫಣೆಯೊಳು |\nಹುಟ್ಟಿದ ಭ್ರಮೆಯ ಬಿಟ್ಟೀತೆ|\nಹೊಟ್ಟೆಲಿ ಸುತರಿಲ್ಲೆಂದತ್ತು ಕರೆದರೆ |\nಹುಟ್ಟು ಬಂಜೆಗೆ ಮಕ್ಕಳಾದೀತೆ||೩||\n\nಬೆಟ್ಟದ ನವಿಲಿಗೆ ಕಣ್ಣೀರು ಬಂದರೆ |\nಬೇಟೆಗಾರನಿಗೆ ದಯ ಪುಟ್ಟೀತೆ |\nಕೆಟ್ಟ ಹಾವು ಕಚ್ಚಿದ ಗಾಯಕ್ಕೆ ಹಳೆ |\nಬತ್ತೆಯೊರಸೆ ವಿಷ ಹೋದೀತೆ||೪||\n\nಧನಿಕರ ಕಂಡು ದೈನ್ಯವ ಪಟ್ಟರೆ |\nತನ್ನ ದ್ರಾರಿದ್ರ್ಯವು ಹಿಂಗೀತೆ|\nಎಣಿಸಿಕೊಂಡೇಳಹಂಜಿಯ ನೂತರೆ |\nಮಣಿಯದ ಸಾಲವು ತೀರೀತೆ ||೫||\n\nಮುನಿಸಿಂದ ಬೈದಾಡುತಲಿದ್ದರೆ |\nಮುರಹರ ಭಜನೆಯು ಆದೀತೇ|\nಅನುದಿನ ನಮ್ಮ\nಪುರಂದರ ವಿಠ್ಠಲ\nನ |\nನೆನೆದಲ್ಲದೆ ಭವ ಹಿಂಗೀತೇ||೬||\n\n",english:"Composer : Sri purandara vittala\n\nHari ninnolumeyu aguva tanaka\naritu summaniruvude lesu || pa ||\n\nMarali marali taa padeyada bhagyake\nhorali horali attare bandeete ||a.pa||\n\nDooru baruva tera nambike kottare |\ndurjana baruvudu tappite |\ndooradi nintu moreyittu koogalu |\nchorarige daya putteete || 1 ||\n\nBaari baarige pativrutatana bhodhise |\njaaregadara nija sogasite |\nooru bittu para oorige hodare |\npraarbdavu beraadite || 2||\n\nPatti mancha tiruvittare phaniyolu |\nhuttida bhrameya bitteete |\nhotteli sutarillendattu karedare |\nhuttu banjege makkalaadite ||3||\n\nBettada navilige kanneeru bandare |\nbetegaranige daya putteete |\nketta haavu kacchida gaayakke hale |\nbatteyorase visha hodite ||4||\n\nDhanikara kandu dainyava pattare |\ntanna daaridryavu hingite |\nenisikondelahanjiya nootare |\nmaniyada saalavu teerite ||5||\n\nMunisinda baidaadutaliddare |\nmurahara bhajaneyu adeete |\nanudina namma\npurandara vittala\nna |\nnenedallade bhava hingeete ||6||\n\n",meta:"",tags:["narayana","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=Yl5H39bN_mU"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಹರಿ-ನಿನ್ನೊಲುಮೆ-ಆಗುವ-ತನಕ-ಅರಿತು.json",
	rawData: "",
};

export { _internal, collection, data, id };
