const id = "ಹರಿವರಾಸನಂ-ವಿಶ್ವಮೋಹನಂ";
const collection = "bhajan";
const data = {kannada_title:"ಹರಿವರಾಸನಂ ವಿಶ್ವಮೋಹನಂ",english_title:"Harivaraasanam vishwamohanam",kannada:"ಹರಿವರಾಸನಂ ವಿಶ್ವಮೋಹನಂ ಹರಿದಧೀಶ್ವರಂ  ಆರಾಧ್ಯಪಾದುಕಂ|ಅರಿವಿಮರ್ದನಂ ನಿತ್ಯನರ್ತನಂ ಹರಿಹರಾತ್ಮಜಂ ದೇವಮಾಶ್ರಯೇ|\n\nಶರಣಂ ಅಯ್ಯಪ್ಪ ಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪ|ಶರಣಂ ಅಯ್ಯಪ್ಪ ಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪ||2 ಸಲ||\n\nಶರಣ ಕೀರ್ತನಂ ಭಕ್ತ ಮಾನಸಂ ಭರಣ ಲೋಲುಪಮ್  ನರ್ತನಾಲಸಂ|ಅರುಣ ಭಾಸುರಂ ಭೂತನಾಯಕಂ  ಹರಿಹರಾತ್ಮಜಂ ದೇವಮಾಶ್ರಯೇ||\n\nಪ್ರಣಯ ಸತ್ಯಕಂ ಪ್ರಾಣ ನಾಯಕಂ ಪ್ರಣತ ಕಲ್ಪಕಂ ಸುಪ್ರಭಾಂಜಿತಂ|ಪ್ರಣವ ಮಂದಿರಂ ಕೀರ್ತನ ಪ್ರಿಯಂ  ಹರಿಹರಾತ್ಮಜಂ ದೇವಮಾಶ್ರಯೇ||\n\nಶರಣಂ ಅಯ್ಯಪ್ಪ ಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪ ಶರಣಂ ಅಯ್ಯಪ್ಪ ಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪ||2 ಸಲ||\n\nತುರಗವಾಹನಂ ಸುಂದರಾನನಂ ವರಗದಾಯುಧಂ ವೇದವರ್ಣಿತಂ| ಗುರುಕೃಪಾಕರಂ ಕೀರ್ತನಪ್ರಿಯಂ ಹರಿಹರಾತ್ಮಜಂ ದೇವಮಾಶ್ರಯೇ||\n\nತ್ರಿಭುವನಾರ್ಚಿತಂ ದೇವತಾತ್ಮಕಂ ತ್ರಿನಯನಂ ಪ್ರಭುಂ ದಿವ್ಯದೇಶಿಕಂ |ತ್ರಿದಶ ಪೂಜಿತಂ ಚಿಂತಿತಪ್ರದಂ ಹರಿಹರಾತ್ಮಜಂ ದೇವಮಾಶ್ರಯೇ||\n\nಶರಣಂ ಅಯ್ಯಪ್ಪ ಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪ ಶರಣಂ ಅಯ್ಯಪ್ಪ ಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪ||2 ಸಲ||\n\nಭವಭಯಾಪಹಂ ಭಾವುಕಾವಹಂ ಭುವನ ಮೋಹನಂ ಭೂತಿಭೂಷಣಂ |  ಧವಳ ವಾಹನಂ ದಿವ್ಯ ವಾರಣಂ ಹರಿಹರಾತ್ಮಜಂ ದೇವಮಾಶ್ರಯೇ||\n\nಕಳಮೃದು ಸ್ಮಿತಂ ಸುಂದರಾನನಂ ಕಳಭ ಕೋಮಲಂ ಗಾತ್ರ ಮೋಹನಂ | ಕಳಭ ಕೇಸರಿ ವಾಜಿ ವಾಹನಂ ಹರಿಹರಾತ್ಮಜಂ ದೇವಮಾಶ್ರಯೇ||\n\nಶರಣಂ ಅಯ್ಯಪ್ಪ ಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪ ಶರಣಂ ಅಯ್ಯಪ್ಪ ಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪ||2 ಸಲ||\n\nಶ್ರಿತ ಜನ ಪ್ರಿಯಂ ಚಿಂತಿತಪ್ರದಂ ಶ್ರುತಿ ವಿಭೂಷಣಂ ಸಾಧು ಜೀವನಂ | ಶ್ರುತಿ ಮನೋಹರಂ ಗೀತ ಲಾಲಸಂ ಹರಿಹರಾತ್ಮಜಂ ದೇವಮಾಶ್ರಯೇ||\n\nಶರಣಂ ಅಯ್ಯಪ್ಪ ಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪ ಶರಣಂ ಅಯ್ಯಪ್ಪ ಸ್ವಾಮಿ ಶರಣಂ ಅಯ್ಯಪ್ಪ||2 ಸಲ||\n\n",english:"Harivaraasanam vishwamohanam | haridadhishwaram aradhyapaadukam |arivimardhanan nityanartanam| harharaatmajam devamaashraye||\n\nSharanam ayyappa swami sharanam ayyappa|Sharanam ayyappa swami sharanam ayyappa|2 times|\n\nSharana keertanam bhakta maanasam bharana lolupam nartanaalasam| aruna bhasuram bhutanayajam hariharaatmajam devamaashraye||\n\nPranaya satyakam prana nayakam pranata  kalpakam suprabhaanjitam| pranava mandiram keertanam priyam hariharaatmajam devamaashraye||\n\nSharanam ayyappa swami sharanam ayyappa|Sharanam ayyappa swami sharanam ayyappa|2 times|\n\nTuragavaahanam sundaraananam varagadayudham vedavarnitam| gurukrupaakaram keertanapriyam hariharaatmajam devamaashraye||\n\nTribhuvanaarchitam devataatmakam trinayanam prabhum divyadeshikam| tridash poojitam chintitapradam hariharaatmajam devamaashrye ||\n\nSharanam ayyappa swami sharanam ayyappa|Sharanam ayyappa swami sharanam ayyappa|2 times|\n\nBhavabhayaapaham bhavukaavaham bhuvana mohanam bhutibhushanam| dhavala vahanam divya vaaranam hariharaatmajam devamaashraye||\n\nKalamrudusmitam sundaraananam kalabha komalam gatra mohanam|kalabha kesari vaaji vahanam hariharaatmajam devanashraye||\n\nSharanam ayyappa swami sharanam ayyappa|Sharanam ayyappa swami sharanam ayyappa|2 times|\n\nShritajanapriyam chintitapradam| shruti vibhuashanam sadhu jeevanam|shruti manoharam geetalaalasam| haruharaatmajam devamaashraye||\n\nSharanam ayyappa swami sharanam ayyappa|Sharanam ayyappa swami sharanam ayyappa|2 times|\n\n",meta:"",tags:["kannada devotional song"],media:""};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಹರಿವರಾಸನಂ-ವಿಶ್ವಮೋಹನಂ.json",
	rawData: "",
};

export { _internal, collection, data, id };
