const id = "ಹಾಲು-ಮಾರಲು-ಪೋದೇವಮ್ಮ";
const collection = "bhajan";
const data = {kannada_title:"ಹಾಲು ಮಾರಲು ಪೋದೇವಮ್ಮ",english_title:"Halu maralu podevamma",kannada:"ಹಾಲು ಮಾರಲು ಪೋದೇವಮ್ಮ\nಗೋಕುಲದೊಳಗ್ಹಾಲು ಮಾರಲು ಪೋದೆವಮ್ಮ||2||\n\nಹಾಲು ಮಾರುವ ಧ್ವನಿ ಆಲಿಸಿ ಕೇಳುತ\nಬಾಲಕೃಷ್ಣ ಬಹು ಲೀಲೆ ಮಾಡುತ ಬಂದ\n||ಹಾಲು||\n\nಹಸಿರು ಜರದ ಸೀರೆಯನುಟ್ಟು ಕುಸುರಿ ಕಂಕಣ\nಎಸೆವೊ ಹವಳದ ಹಿಂಬಳೆ ಕಟ್ಟು ಮೊಸರಿನ ಕುಂಭ\nಕುಸುಮ ಮಲ್ಲಿಗೆಯ ಮುಡಿಯಲ್ಲಿಟ್ಟು |\nಶಶಿವದನೆಯರೆಲ್ಲ ಚೆಂದದಿ ಬರುತಿರೆ\nಕುಸುಮನಾಭ ಮುಸುಗೆಳೆದು ಮೊಸರು ಸುರಿದ\n||ಹಾಲು||\n\nಬಣ್ಣ ಬಣ್ಣದ ಸೀರೆಯನುಟ್ಟು ಮುತ್ತಿನ ಬಟ್ಟು\nಹೊಳೆವೊ ಕಸ್ತೂರಿ ತಿಲಕವನಿಟ್ಟು ಹಾಲಿನ ಕುಂಭ\nಸಣ್ಣ ಮಲ್ಲಿಗೆ ಮುಡಿಯಲಿಟ್ಟು |\nಚೆನ್ನಾರ ಚೆಲುವೇರು ಚೆಂದದಿ ಬರುತಿರೆ\nಕಣ್ಣು ಸನ್ನೆ ಮಾಡಿ ಕರೆದು ಮುದ್ದಿಡುವ ||ಹಾಲು||\n\nಮುಂದೆ ಮುಂದಾಗಿ ಹೋಗುತಲಿರಲು ಹಿಂದ್ಹಾಲಿನ್ಹರವಿ\nಒಂದೊಂದ್ಹರಳು ಮೀಟುತಿರಲು ಧಾರೆಗೆ ಬಾಯಾ\nಆನಂದದಿಂದೊಡ್ಡಿ ಕುಡಿಯುತಿರಲು |\nಸಂದಣಿಯೊಳು ನಾವು ಒಂದರಿಯದಲೆ\nಬಂದಿಳುಹಲು ಬರೀ ಗಡಿಗೆ ಕಾಣಮ್ಮ ||ಹಾಲು||\n\nಕಡಗೋಲಿಂದೊಡೆದು ಗಡಿಗೆಯನು ಬಡವರ ಬೆಣ್ಣೆ\nಒಡಲಿಗೆ ಕದ್ದು ತಿಂಬುವುದೇನು ಕಂಡರೆನಗಂಡ\nಬಡಿದರಿನ್ನೇನು ಮಾಡುವೆ ನೀನು |\nಗಡಿಬಿಡಿ ಮಾಡುತ ಕತ್ತಲ ಮನೆಯೊಳು\nತುಡುಗನಂತೆ ತಿರುಗಾಡುವ ತಾನು||ಹಾಲು||\n\nಸಿಟ್ಟು ಮಾಡುವುದ್ಯಾತಕಮ್ಮ ಶ್ರೀ ರಮಣನ\nಬಿಟ್ಟು ಬಾಹುವುದೆ ಲೇಸಮ್ಮ ಭೀಮೇಶಕೃಷ್ಣನ\nಕಟ್ಟಿ ಹಾಕುವುದೆ ಲೇಸಮ್ಮ |\nಪಟ್ಟುಮಾಡಿ ಪರಹೆಂಗಳೇರೊಳು\nಕಣ್ಣಿಟ್ಟ ಮ್ಯಾಲೆ ಒಂದಿಷ್ಟಾದರು ಬಿಡ ||ಹಾಲು||\n\n",english:"Haalu maralu podevamma gokuladolagahgalu maralu podevamma||\n\nHaalu maaruva dhwani aalisi keluta |balakrishna bahu leele maaduta banda ||haalu||\n\nHasiru jarada seereyanuttu kusuri kankana | asevo havalada himbale kattu mosarina kumbha kusuma malligeya mudiyalittu shashivadaneyarella chendadi barutire kusumanaabha musugeledu mosaru surida ||haalu||\n\nBanna bannada seereyanuttu muttina battu | holeva kasturi tilakavanittu haalinakumbha | sanna mallige mudiyalittu chennaara cheluveru chendadi barutire | kannu sanne maadi karedu muddiduva ||haalu||\n\nMunde mundaagi hogutaliralu hindaahlinahravi | ondondahralu meetutiralu dhaarege baaya anandadindoddi kudiyutiralu sandaniyolu naavu ondariyadale bandiluhalu bari gadige kaanamma ||haalu||\n\nKadagolindodedu gadigeyanu badavara benne| odalige kaddu timbuvudenu kandarenaganda | badidarinnenu maduve neenu | gadibidi maduta kattala maneyolu | tuduganante tirugaduva taanu||haalu||\n\nSittu maduvudyaatakamma sri ramanana | bittu baahuvude lesamma bheemesha krishnana | katti haakuvude lesamma pattumadi parahengalerolu| kannitta myaale ondishtaadaru bida||haalu||\n\n",meta:"",tags:["kannada devotional song"],media:"https://www.youtube.com/watch?v=VOs_Es-yFhA"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಹಾಲು-ಮಾರಲು-ಪೋದೇವಮ್ಮ.json",
	rawData: "",
};

export { _internal, collection, data, id };
