const id = "ಹ್ಯಾಂಗೆ-ಮಾಡಲಯ್ಯಾ-ಕೃಷ್ಣ";
const collection = "bhajan";
const data = {kannada_title:"ಹ್ಯಾಂಗೆ ಮಾಡಲಯ್ಯಾ ಕೃಷ್ಣ",english_title:" Hyaange maadalayya Krishna",kannada:"ಹ್ಯಾಂಗೆ ಮಾಡಲಯ್ಯಾ ಕೃಷ್ಣ ಪೋಗುತಿದೆ ಆಯುಷ್ಯ || ಪ ||\n\nಮಂಗಳಾಂಗ ಭವಭಂಗ ಬಿಡಿಸಿ\nನಿನ್ನ ಡಿಂಗರಿಗನ ಮಾಡೋ ಅನಂಗ ಜನಕ || ಅ.ಪ ||\n\nಏಸು ಜನುಮದ ಸುಕೃತದ ಫಲವೋ ತಾನು ಜನಿಸಲಾಗಿ\nಭೂಸುರ ದೇಹದ ಜನುಮವು ಎನಗೆ ಸಂಭವಿಸಿದೆಯಾಗಿ\nಮೋದತೀರ್ಥ ಮತ ಚಿಹ್ನಿತನಾಗದೆ ದೋಷಕೆ ಒಳಗಾಗಿ\nಲೇಶ ಸಾಧನವ ಕಾಣದೆ ದುಸ್ಸಹವಾಸದಿಂದಲೇ ದಿನದಿನ ಕಳೆದೆ || 1 ||\n\nಶಶಿಮುಖಿ ಕನಕದ ಆಸೆಗೆ ಬೆರೆತು ವಸುಪತಿ ನಿನ್ನಡಿಯ\nಹಸನಾಗಿ ನಿನ್ನ ನೆನೆಯದೆ ಕೃಪೆಯಗಳಿಸದೆ ಕೆಟ್ಟೆನಯ್ಯ\nನಿಶಿಹಗಲು ಸ್ಥಿರವೆಂದು ತನುವನು ಪೋಷಿಸಲಾಶಿಸಿ ಜೀಯ\nಉಸುರಿದೆ ನೆಲವೋ ಸರ್ವಕಾಲ ನಿನ್ನೊಡೆತನವೆಂಬುವ ಬಗೆಯನು ಅರಿಯದೆ || 2 ||\n\nನೆರೆನಂಬಿದ ಪಾವಟಿಗಳು ಎಲ್ಲಾ ಸರಿದು ಹೋದವಲ್ಲ\nಮರಳಿ ಈ ಪರಿ ಜನುಮವು ಬರುವ ಭರವಸೆಯಂತೂ ಇಲ್ಲ\nಪರಿಪರಿ ವಿಷಯದ ಆಸೆಯು ಯನಗೆ ಪಿರಿದು ಆಯಿತಲ್ಲ\nಹರಿಯೇ ಜಗದಿ ನೀನೊಬ್ಬನಲ್ಲದೆ ಪೊರೆವರಿನ್ನಾರು ಇಲ್ಲವಲ್ಲ || 3 ||\n\nಅವನಿಯೊಳಗೆ ಪುಣ್ಯಕ್ಷೇತ್ರ ಚರಿಸುವ ಹವಣಿಕೆ ಎನಗಿಲ್ಲ\nಪವನಾತ್ಮಕ ಗುರು ಮಧ್ವಶಾಸ್ತ್ರದ ಪ್ರವಚನ ಕೇಳಲಿಲ್ಲ\nತವಕದಿಂದ ಗುರುಹಿರಿಯರ ಸೇವಿಸಿ ಅವರ ಒಲಿಸಲಿಲ್ಲ\nರವಿನಂದನ ಕೇಳಿದರುತ್ತರ ಕೊಡೆ ವಿವರ ಸರಕು ಒಂದಾದರಿಲ್ಲ || 4 ||\n\nಭಾಗವತರೊಡಗೂಡಿ ಉಪವಾಸ ಜಾಗರ ಒಂದಿನ ಮಾಡಲಿಲ್ಲ\nರಾಗದಿ ಶುಕಮುನಿ ಪೇಳ್ದ ಹರಿಕಥೆ ಸಂಯೋಗವೆಂಬೋದಿಲ್ಲ\nನೀಗುವಂಥ ಭವಭಯವ ಭಕುತಿ ವೈರಾಗ್ಯವೆಂಬೋದಿಲ್ಲ\nಯೋಗಿವಂದ್ಯ\nಗೋಪಾಲವಿಠ್ಠಲ\nತಲೆಬಾಗಿ ನಿನ್ನನೇ ಬೇಡಿಕೊಂಬೆ || 5 ||\n\n",english:"Composer : Sri Gopala dasaru\n\nHyaange maadalayya Krishna hogutide aayushya || pa ||\n\nMangalaanga bhava bhanga bidisi\nninna dingarigana maado ananga janaka || a.pa ||\n\nYesu janmada sukratada phalavo taanu janisalaagi\nbhoosura dehada janumavu enage sambhavisideyaagi\nModa teertha matha chinhita naagade doshake olagaagi\nlesha saadhanava kaanade dussaha vaasadindale dina dina kalede || 1 ||\n\nShashimukha kanakada aasege beretu vasupati ninnadiya\nhasanaagi ninna neneyade krupeya galisade kettenayya\nnishi hagalu stiravendu tanuvanu poshisalaashisi jeeya\nusuride nelavo sarvakaala ninnodetanavembuva bageyanu ariyade || 2 ||\n\nNere nambida paavatigalu ella saridu hodavalla\nmarali ee pari janumavu baruva bharavaseyantu illa\npari pari vishayada aaseyu yanage piridu aayitalla\nHariye jagadi neenobba nallade porevarinnaaru illavayya || 3 ||\n\nAvaniyolage punya kshetra charisuva havanike yanagilla\nPavanaatmaka guru Madhwa shaastrada pravachana kelalilla\ntavakadinda guri hiriyara sevisi avara olisalilla\nRavi nandana kelidaruttara kode vivara saraku ondaadarilla || 4 ||\n\nBhaagavata rodagoodi upavaasa jaagara ondina maadalilla\nraagadi Shuka muni pelda Harikathe samyogavembodilla\nneegu vantha bhava bhayava bhakuti vairaagya vembodilla\nyogi vandya\nGopaala Vittala\ntalebaagi ninnane bedi kombe || 5 ||\n\n————————\n\n",meta:"",tags:["krishna","dasara padagalu","kannada devotional song"],media:"https://www.youtube.com/watch?v=_7hnnG5wGnU"};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಹ್ಯಾಂಗೆ-ಮಾಡಲಯ್ಯಾ-ಕೃಷ್ಣ.json",
	rawData: "",
};

export { _internal, collection, data, id };
