const id = "ಹರಿ-ಕೃಪೆಯಲಿ-ತಾನೊಲಿದದ್ದಾದರೆ-ಉರುತರ";
const collection = "bhajan";
const data = {kannada_title:"ಹರಿ ಕೃಪೆಯಲಿ ತಾನೊಲಿದದ್ದಾದರೆ ಉರುತರ",english_title:" Hari krupeyali tanolidaddaadare urutara",kannada:"ಹರಿ ಕೃಪೆಯಲಿ ತಾನೊಲಿದದ್ದಾದರೆ ಉರುತರ ಮೋಕ್ಷವೆ ಸಾಕ್ಷಿ ||ಪ||\n\nಹರಿ ಶರಣರ ಸೇವಿಸುವ ನರರಿಗೆ ಧರೆಯ ಸೌಖ್ಯವೆ ಸಾಕ್ಷಿ ||ಅ. ಪ||\n\nಮಡದಿ ಮಕ್ಕಳ ಸಾಕದೆ ಬಿಡುವಗೆ ಕಡು ದಾರಿದ್ರ್ಯವೆ ಸಾಕ್ಷಿ\nಕಡು ಬಡವಗೆ ಧರ್ಮವ ಕೊಡದಿರೆ ಬಾಯಿ ಬಿಡುವದೆ ಪರರಿಗೆ ಸಾಕ್ಷಿ\nಅನ್ನ ದಾನವ ಮಾಡಿದವಗೆ ದಿವ್ಯ ಅನ್ನ ಉಂಬುವದೆ ಸಾಕ್ಷಿ\nಹೊನ್ನು ದಾನವ ಮಾಡದವಗೆ ಪರ ದೈನ್ಯಬಡುವುದೆ ಸಾಕ್ಷಿ\n\nಕನ್ಯಾ ದಾನವ ಮಾಡಿದವಗೆ ದಿವ್ಯ ಹೆಣ್ಣಿನ ಭೋಗವೇ ಸಾಕ್ಷಿ\nಕನ್ಯಾ ದಾನವ ಮಾಡದವಗೆ ಹೆಣ್ಣಿನ ಹೋರಾಟವೆ ಸಾಕ್ಷಿ\nಕಂಡ ಪುರುಷಗೆ ಕಣ್ಣಿಕ್ಕುವಳಿಗೆ ಗಂಡನ ಕಳೆವುದೆ ಸಾಕ್ಷಿ\nಬಂಡತನದಿ ಪರ ಸ್ತ್ರೀಯರ ಮೆಚ್ಚುವಗೆ ಹೆಂಡಿರ ಕಳೆವುದೆ ಸಾಕ್ಷಿ\n\nಕ್ಷೇತ್ರ ದಾನವ ಮಾಡಿದವಗೆ, ಏಕ- ಛತ್ರ ರಾಜ್ಯವೆ ಸಾಕ್ಷಿ\nಪಾತ್ರಾಪಾತ್ರವನರಿತು ದಾನ ಮಾಡಿದವಗೆ ಪುತ್ರರ ಪಡೆವುದೆ ಸಾಕ್ಷಿ\nಪರಿಪರಿ ತಾನುಂಡು ಪರರಿಗೊಂದಿಕ್ಕದ ನರಗೆ ಗುಲ್ಮರೋಗವೆ ಸಾಕ್ಷಿ\nಪರಿಪರಿಯಿಂದಲಿ ಹಿರಿಯರ ದೂಷಿಸೆ ತಿರಿದುಂಬೋದೆ ಬಲು ಸಾಕ್ಷಿ\n\nಭಕ್ತಿಯಿಲ್ಲದ ಅಧಮರಿಗೊಂದು ಕತ್ತಲೆ ಮನೆಯೆ ಸಾಕ್ಷಿ\nಮುಕ್ತಿ ಪಡೆವುದಕೆ ಶ್ರೀ\nಪುರಂದರವಿಠಲ\nನ ಭಕ್ತನಾಗಿ ಇರುವುದೆ ಸಾಕ್ಷಿ ||\n\n",english:"Hari kr̥peyali tānolidaddādare urutara mōkṣave sākṣhi ||pa||\n\nhari śharaṇara sēvisuva nararige dhareya saukhyave sākṣhi ||a. Pa||\n\nMaḍadi makkaḷa sākade biḍuvage kaḍu dāridryave sākṣhi\nkaḍu baḍavage dharmava koḍadire bāyi biḍuvade pararige sākṣhi\nanna dānava māḍidavage divya anna umbuvade sākṣhi\nhonnu dānava māḍadavage para dainyabaḍuvude sākṣhi ||\n\nKanyā dānava māḍidavage divya heṇṇina bhōgavē sākṣhi\nkan’yā dānava māḍadavage heṇṇina hōrāṭave sākṣhi\nkaṇḍa puruṣhage kaṇṇikkuvaḷige gaṇḍana kaḷevude sākṣhi\nbaṇḍatanadi para strīyara mecchuvage heṇḍira kaḷevude sākṣhi ||\n\nkṣhētra dānava māḍidavage, ēkachatra rājyave sākṣhi\npātrāpātravanaritu dāna māḍidavage putrara paḍevude sākṣhi\nparipari tānuṇḍu pararigondikkada narage gulmarōgave sākṣhi\nparipariyindali hiriyara dūṣise tiridumbōde balu sākṣhi ||\n\nbhaktiyillada adhamarigondu kattale maneye sākṣhi\nmukti paḍevudake śrī\npurandaraviṭhala\nna bhaktanāgi iruvude sākṣhi ||\n\n",meta:"",tags:["narayana","dasara padagalu","kannada devotional song"],media:""};
const _internal = {
	type: 'data',
	filePath: "C:/Users/karth/Documents/Web Projects/Bhajanamrutha/src/content/bhajan/ಹರಿ-ಕೃಪೆಯಲಿ-ತಾನೊಲಿದದ್ದಾದರೆ-ಉರುತರ.json",
	rawData: "",
};

export { _internal, collection, data, id };
