backend:
  name: git-gateway
  branch: main
  publish_mode: editorial_workflow

  collections:
  - name: "bhajan" # Used in routes, e.g., /admin/collections/blog
    label: "bhajan" # Used in the UI
    folder: "src/content/bhajan" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "kannada_title", name: "kannada_title", widget: "string"}
      - {label: "english_title", name: "english_title", widget: "string", default: ""}
      - {label: "kannada", name: "kannada", widget: "string"}
      - {label: "english", name: "english", widget: "string", default: ""}
      - {label: "meta", name: "meta", widget: "string", default: ""}
      - {label: "media", name: "media", widget: "string", default: ""}
      - {label: "tags", name: "tags", widget: "list", default: []}